### PR TITLE
&benshamza, fkiraly [BUG] Fix `numba` errors when calling `tslearn` `lcss`

### LINKED ISSUE #5367: [BUG] `numba` related failures on main from `tslearn` `lcss`
On main, it seems we have the following `numba` related failures:

```
During: resolving callee type: type(CPUDispatcher(<function _local_squared_dist at 0x14fc267a0>))
During: typing of call at /Users/runner/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/tslearn/metrics/dtw_variants.py (1421)
```

This is not related to the recent newer `numba` release as we did not upgrade yet.

For test runs with the failures, see here: https://github.com/sktime/sktime/actions/runs/6424459407/job/17445296470?pr=5083

### PR DESCRIPTION
**Pull request by benHeid**
#### Reference Issues/PRs
Fixes #5367

#### What does this implement/fix? Explain your changes.
updated by @fkiraly after discussion in #5367
This restores the vectorization patch we had a while ago for lcss.

@fkiraly update:
I think this was introduced in order to cope with interface non-compliance of lcss in the first place.

#### TODOs
* [ ] Figure out if this leads to results that are still valid.
* [x] Make this safer, by using reshape instead of selecting elements.
* [ ] Check if this works with the full test suite

### CODE REVIEW

**Comment by benHeid** [comment]
Still requires the full test suite run to ensure that the error is fixed. 

Needs verification that this fix leads to valid results since I am very unsure about the impact of the fix. Would really appreciate it if someone could check this.

**Review by fkiraly — CHANGES_REQUESTED** [review]
This seems like it will likely render `tslearn` calls incorrect in multivariate cases, as the last dimension will be larger than 1.

The docstring for `lcss` states "Compute the Longest Common Subsequence (LCSS) similarity measure between (possibly multidimensional) time series and return the similarity."

Unfortunately, it does not specify the expected format for time series, but from other locations in `tslearn` it is 3D numpy array, (instance, time point, variable) - so dimensions 1 and 2 (starting the count at 0) switched when compared to`numpy3D` mtype in sktime.

**Comment by fkiraly** [comment]
started a PR with full tests here to check if this works: https://github.com/sktime/sktime/pull/5369

**Comment by fkiraly** [comment]
this fix gets the other `tslearn` distances failling, it seems. I will try to except lcss from the tests and see if it we can isolate it this way.

**Comment by fkiraly** [comment]
It seems it is indeed isolated to https://github.com/sktime/sktime/pull/5371 - I'll try to move your fix to the LCSS distance trafo to see whether that solves the issue.

**Comment by fkiraly** [comment]
@benHeid, I think the fix does not work - see the errors.

**Review by fkiraly — APPROVED** [review]
Bringing the `tslearn` bug patch back fixes this.

**Pull request merged**
