### PR TITLE
[BUG] Fix `nested_univ` converter inconsistent handling of index level names

### LINKED ISSUE #7025: [BUG] `nested_univ` to `pd.multtiindex` conversion returns wrong index names
**Describe the bug**
while converting `nested_univ` to `pd.multiindex` the time index is hardcoded to be `timepoints` 

```python
    if isinstance(store, dict) and "index_names" in store.keys():
        instance_index = store["index_names"][0]
        time_index = store["index_names"][1]
    else:
        instance_index = obj.index.names[0]
        time_index = "timepoints"
```

**Expected behavior**
It should return `None` if name doesn't exist, or actual name if the nested series index has a name

### PR DESCRIPTION
**Pull request by pranavvp16**
This PR fixes the `nested_univ` converter, to return the index name of series nested in the dataframe. 
Fixes #7025

### CODE REVIEW

**Comment by pranavvp16** [comment]
@fkiraly The failure in run notebooks is caused by this change, as we no longer return `timepoints` as name in last level. I tried checking it, what is returned now is the actual index name of the series which is `level_1`, instead of timepoints. I think somehow `nested_univ` converter is being used while going from `df_panel` to `pd-multiindex`

**Comment by fkiraly** [comment]
that seems like a reasonable fix - btw, I think the loader should just use the `return_type` argument here instead of attempting explicit conversion.

This highlights that this might break user code, although only under very brittle circumstances, so we may consider shipping it only with the full minor version.

**Comment by fkiraly** [comment]
yes, that's what I meant - the notebook should of course run with this.

**Review by fkiraly — CHANGES_REQUESTED** [review]
see above, the notebook ought to run

**Comment by pranavvp16** [comment]
> see above, the notebook ought to run

made changes in the notebook

**Pull request merged**
