### PR TITLE
[ENH] Add scoring direction to ForecastingOptunaSearchCV 

### PR DESCRIPTION
**Pull request by gareth-brown-86**
#### What does this implement/fix? Explain your changes.

Currently the optuna study assumes that we are trying to minimise our metric.
We have changed it so it uses the get_tag("lower_is_better") from the passed scorer.
So if the scoring metric should be maximised, the study will  do that.
#### Does your contribution introduce a new dependency? If yes, which one?
No

#### Did you add any tests for the change?
No tests were added for this.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [x] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

### CODE REVIEW

**Comment by gareth-brown-86** [comment]
@fkiraly here is a small change to allow maximising as well as minimising a scoring metric.
I am sure this will have conflicts once the other PR (#6823) is merged.

**Comment by fkiraly** [comment]
also, I notice, there are a lot of commits, since you seem to be branching off an old state of the fork. I would advise to update `main` on your fork, and then merge `main` into the branch.

Further, it is not advised to use `main` on the fork for developing features, see recent discussion here: https://github.com/sktime/sktime/pull/6827

**Comment by gareth-brown-86** [comment]
> also, I notice, there are a lot of commits, since you seem to be branching off an old state of the fork. I would advise to update `main` on your fork, and then merge `main` into the branch.
> 
> Further, it is not advised to use `main` on the fork for developing features, see recent discussion here: #6827

I will do that (and create a new PR from that branch)

**Comment by gareth-brown-86** [comment]
> I would add a new parameter that lets the user choose - `"auto"`, `"minimize"`, "`maximize`". With `"auto"` looking for the tag, and if not found, minimize.
> 
> The reason is, I think the user can pass metrics that are not classes, in which case the tag will not exist.
> 
> I would also be defensive and do if `hasattr("get_tag")` and if the tag is boolean. Otherwise, under the `"auto"` setting, you would minimise.

How does it currently work (in the BaseGridSearch) if the tag doesn't exist? Does `ascending=scoring.get_tag("lower_is_better")` return none and so default to  `ascending=True` ? 

Adding in a new parameter I think would be good as it is explicit, but would we the add it for all the different Search types? As I think this is used in all of them:
        ```
results[f"rank_{scoring_name}"] = results.loc[:, f"mean_{scoring_name}"].rank(
            ascending=scoring.get_tag("lower_is_better")
        )
```

**Comment by fkiraly** [comment]
> How does it currently work (in the BaseGridSearch) if the tag doesn't exist?

My understanding:

* `check_scoring`, as @yarnabrina pointed out, coerces to an instance of a child of `BaseForecastingErrorMetric`, namely `_DynamicForecastingErrorMetric`
* the base class has default tags, among others, `"lower_is_better" = True`

Therefore, after running `check_scoring`, `get_tag("lower_is_better")` will exist, as a method, and return `True`

**Comment by fkiraly** [comment]
> Adding in a new parameter I think would be good as it is explicit, but would we the add it for all the different Search types?

Perhaps, *but* since it would have to be done in multiple locations to be consistent, I would consider it out of scope and orthogonal for this PR. I would also recommend to open a new issue.

I.e., progress this PR to cover parity with other tuners; discuss and potentially implement separately a new argument to all the tuners. Just to keep changes modular and avoid feature creep in PR that could otherwise be merged quickly.

**Comment by fkiraly** [comment]
closed as superseded by https://github.com/sktime/sktime/pull/6846

**Pull request closed without merging**
