### PR TITLE
[ENH] Add ForecastingBayesianSearchCV using Skopt 

### LINKED ISSUE #4188: [ENH] advanced hyper-parameter tuning for forecasting
We should add a module in `sktime` that is to `ForecastingGridSearchCV` as `tune-sklearn` is to `sklearn`.

This should not be too hard if we inherit from `BaseGridSearch` and exchange the tuning engine.

Optimization methods:

- [ ] `hyperopt` native
- [ ] `optuna` native
- [ ] `skopt` native
- [ ] `tune-sklearn` (ray back-end for the above)

### PR DESCRIPTION
**Pull request by hazrulakmal**
Fixes #4188. 
See also #3390 #3359 

#### What does this implement/fix? Explain your changes.

This PR aims to integrate BayesianCV optimization method using skopt under the hood into sktime ecosystem 

#### Does your contribution introduce a new dependency? If yes, which one?

Yes, scikit-optimize

#### What should a reviewer concentrate their feedback on?

Under development. Will mention someone when the code is ready for review. 

#### Did you add any tests for the change?

Will do it soon. 

#### Any other comments?

Under Active development.

##### Note to self
- [ ] Look through BaseGridSearch, ForecastingGridSearch etc works
- [ ] Look through how to use skopt
- [ ] think of the best way to integrate skopt, inherit from `BaseGridSearch` or from `_DelegatedForecaster`
##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by fkiraly** [comment]
Thanks for the contribution, looks nice!

Info to get started, we're using some code formatting conventions and pre-commits at `sktime`, here's the guide how go get set up:
https://www.sktime.net/en/stable/developer_guide/coding_standards.html
let us know if you have any questions!

**Comment by hazrulakmal** [comment]
Ok noted. Will do that in the next commits. Thanks!

Anyway, small thing from me, my IDE flags a syntax error in  [_split.py](sktime/forecasting/model_selection/_split.py), more specifically in this line of code

```
FORECASTING_HORIZON_TYPES = Union[
    Union[VALID_FORECASTING_HORIZON_TYPES], ForecastingHorizon 
```

is it supposed to be Union[VALID_FORECASTING_HORIZON_TYPES, ForecastingHorizon]? rather than the nested union?

**Comment by fkiraly** [comment]
> is it supposed to be `Union[VALID_FORECASTING_HORIZON_TYPES, ForecastingHorizon]`? rather than the nested union?

I think `VALID_FORECASTING_HORIZON_TYPES` is an iterable, so it should probably be `Union[
    Union[*VALID_FORECASTING_HORIZON_TYPES], ForecastingHorizon ]`? Anyway, I didn't add the type hint, so maybe we can ask the person who did (@khrapovs)

**Comment by fkiraly** [comment]
@hazrulakmal, I just noticed, some merge or rebase accident must have happened, as this PR modifies 409 files.
You may like to check whether you are up to date with the `main` branch?

**Comment by hazrulakmal** [comment]
I believe I followed the wrong steps to update my dev branch. The developer guide only teaches how to sync the "main" branch in my local machine, but not the dev branch. To resolve this, I plan to close this pull request and delete the current branch since there haven't been many changes in the codebase in this draft pull request. I'll create a new pull request later.  imo, this seems like the cleanest solution

Also just to verify about git workflow just to make sure something like this wont happen again. Firstly, I synch the main branch with the main repo (upstream) as follows.

To prevent issues like this in the future, could you review my git workflow. I've looked over the internet and there seem to be many ways to do it. I just wanna make sure I'm following the right one. 

First, sync the main branch with the main repository (upstream) by following these steps:
```
git checkout main
git fetch upstream
git merge upstream/main
```
Once the main branch is updated locally, I do the following to my dev-branch so that it gets all the changes made from the main repo
```
git checkout dev-branch
git rebase main
```
Thanks in advance for helping!

**Comment by fkiraly** [comment]
> To resolve this, I plan to close this pull request and delete the current branch since there haven't been many changes in the codebase in this draft pull request. I'll create a new pull request later. imo, this seems like the cleanest solution

Makes sense - please link to this PR as related in the description.

> but not the dev branch

Hm, why would that be necessary? That would be necessary only if someone else works on the branch upstream. In the default workflow that does not happen?

See https://www.sktime.net/en/latest/developer_guide/git_workflow.html
is this the document you are using?

**Comment by hazrulakmal** [comment]
I see. I thought I have to keep updating the dev branch in sync with the main all the time.

**Pull request closed without merging**
