### PR TITLE
[DOC] docstring usage examples for `AlignerDTW` and `AlignerDTWfromDist`

### PR DESCRIPTION
**Pull request by Adarsh2345**
### Pull Request Description ( See issue_number #4264 )

**Title**: Added usage examples to `AlignerDTW` and `AlignerDTWfromDist` class docstrings

**What’s Changed**:
- I’ve added simple and advanced usage examples to the docstrings for both `AlignerDTW` and `AlignerDTWfromDist`.
- The examples show how to initialize the aligners, fit them with some example data, and get the alignment, distance, and distance matrix.
- This update will make it easier for users to understand how to use these classes for time series alignment using DTW (Dynamic Time Warping).

**Why It Matters**:
- There were no usage examples in the original docstring, which could make it harder for new users to get started. These examples will now provide quick guidance.

**How It Was Tested**:
- No functionality was changed, so there’s no need for extra testing—just a docstring update!

**Other Notes**:
- The examples I’ve included cover both basic use (default settings) and more complex scenarios (custom alignment parameters).
- This should help make the classes more user-friendly and easier to implement for anyone looking to do time series alignment with DTW.

---

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
This is great, thanks!

We sohuld ensure though that the code is formatted according to the guidelines, e..g, maximum line length etc.
Here is the developer guide for that:
https://www.sktime.net/en/latest/developer_guide/coding_standards.html

Please let us know if you have any questions!

**Comment by Adarsh2345** [comment]
Ok @fkiraly, will look into it!
Thanks a ton!!

**Comment by Adarsh2345** [comment]
I've formatted it now. Pls see if there are any more issues to be resolved

**Comment by Adarsh2345** [comment]
Thanks a ton, @fkiraly

**Pull request merged**
