### PR TITLE
[ENH] interface to `statsforecast` ARCH family estimators

### PR DESCRIPTION
**Pull request by eyjo**
#### Reference Issues/PRs
Towards issue #4643.

#### What does this implement/fix? Explain your changes.
direct interfaces to the ARCH family of models from Nixtla: ARCH and GARCH

#### Does your contribution introduce a new dependency? If yes, which one?
No new dependency. It relies on statsforecast

#### What should a reviewer concentrate their feedback on?

This is my first attempt at implementing a forecast module for sktime. 

#### Did you add any tests for the change?
No

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [x] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
uh-oh, there are some linter/precommit failures!

But don't worry, this is only a small issue, I'll fix them so we can wrap up today with a geat success!

**Comment by fkiraly** [comment]
additional note: there are a lot more parameters in `forecast` - let's deal with these in a separate PR.

@yarnabrina, does the generalized adapter class cover parameters in the `statsforecast` `forecast` method?

**Comment by yarnabrina** [comment]
> does the generalized adapter class cover parameters in the `statsforecast` `forecast` method?

It does not. It uses `predict` and not `forecast`, and the two function signatures are quite different (only prediction vs train and prediction).

```python
    def predict(
        self,
        h: int,
        X_df: Optional[Union[pd.DataFrame, pl.DataFrame]] = None,
        level: Optional[List[int]] = None,
    ):
```

vs

```python
    def forecast(
        self,
        h: int,
        df: Optional[Union[pd.DataFrame, pl.DataFrame]] = None,
        X_df: Optional[Union[pd.DataFrame, pl.DataFrame]] = None,
        level: Optional[List[int]] = None,
        fitted: bool = False,
        sort_df: bool = True,
        prediction_intervals: Optional[ConformalIntervals] = None,
    ):
```

Ref. https://github.com/Nixtla/statsforecast/blob/main/statsforecast/core.py

**Comment by fkiraly** [comment]
@eyjo, looks like this almost works, but you are passing an `approximation` param in the `get_test_params`, which the `__init__`-s don't have?

Should the inits have that parameter, or is this coming from sth else?

**Review by fkiraly — APPROVED** [review]
Thanks for fixing!

Looks all green now, we should be able to merge soon!

**Comment by yarnabrina** [comment]
It's already merged, but I do have a small feedback here: I'd have suggested to have this in `statsforecast.py` instead of a new module. @fkiraly What do you think?

Or, if too big module is an issue, we can create a `statsforecast` directory, have a `__init__` and then have separate modules for separate set of estimators grouped together. Grouping logic can be same as the way Nixtla groups theire algorithms. This way, all `statsforecast` models can be imported easily in a single import.

(I just realised that this is different from how `statsmodels` forecasters are listed, and this PR follows that, but dependency wise grouping seemed like a nice idea to me.)

**Comment by fkiraly** [comment]
> (I just realised that this is different from how statsmodels forecasters are listed, and this PR follows that, but dependency wise grouping seemed like a nice idea to me.)

That's a good point, @yarnabrina, although I don't know what the best ordering system is. I'm opening a new issue on the general point.

Regarding this specific estimator's location, we can move it anytime efore the next release.

**Pull request merged**
