### PR TITLE
[ENH] `DummyRegressor` for time series regression

### LINKED ISSUE #3899: [ENH] DummyRegressor for straw man comparison when benchmarking
**Is your feature request related to a problem? Please describe.**

There is a DummyClassifier in the classification package. It would be useful to have an equivalent straw man in the Regression package for those who think they are a sensible benchmark. 

**Describe the solution you'd like**

A class DummyRegressor that extends BaseRegressor using the template that predicts the mean of the response variable in the train file. Other dummy settings could be possible. 

**Describe alternatives you've considered**
We can just work out the mean and use it as a benchmark, as we could with class distribution, but since there is a DummyClassifier, seems there should be a DummyRegressor.

### PR DESCRIPTION
**Pull request by badrmarani**
#### Reference Issues/PRs

Fixes #3899.

#### What does this implement/fix? Explain your changes.

Adds a DummyRegressor that wraps over a sklearn DummyRegressor and inherits from BaseRegressor.

#### Does your contribution introduce a new dependency? If yes, which one?

No.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [x] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] I've added unit tests and made sure they pass locally.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

### CODE REVIEW

**Comment by fkiraly** [comment]
Nice! I've started the CI.

**Comment by fkiraly** [comment]
linting is failing, kindly ensure you format your code correctly.
Guideline here: https://www.sktime.org/en/stable/developer_guide/coding_standards.html

**Review by fkiraly — CHANGES_REQUESTED** [review]
(see above)

**Comment by badrmarani** [comment]
Hi,

I've gone ahead and fixed the linting issues on my last pull request. I believe everything should be good to go now.

Thank you!

**Comment by badrmarani** [comment]
Hi,

I've gone ahead and fixed the linting issues on my last pull request. I believe everything should be good to go now.

Thank you!

**Comment by fkiraly** [comment]
Tests are now genuinely failing. I think this may be one or both fo the following reasons:

* regressors should return floats in `predict`, and expect float `y` in `fit` - not strings
* when you compare equality with `np.all`, you might be missing a list comprehension

**Review by fkiraly — CHANGES_REQUESTED** [review]
thanks a lot, useful!

there are some small fiddly issues to sort out, see the failing tests

**Comment by badrmarani** [comment]
I've gone ahead and fixed the unit test related errors. Code should now be able to pass the tests.

**Comment by fkiraly** [comment]
Nice, they pass now! Thank you!

**Review by fkiraly — APPROVED** [review]
Great!

I made a minor change: put the docs section in alphabetical order

**Pull request merged**
