### PR TITLE
[GOV] provisions for treasurer role

### PR DESCRIPTION
**Pull request by fkiraly**
Following on an action on me and @marrov from the last CC meetings - draft provisions for the treasurer role.

I am aware that the action was on @marrov primarily - now I thought it would be good to get started as some expenditures are on the horizon, within 1 month time frame. @marrov, feel free to replace or discard.

### CODE REVIEW

**Comment by fkiraly** [comment]
I asked chatGPT to review this version https://github.com/sktime/sktime/pull/4798/commits/f8af15c391f6b79794f61101e0a1dac51b5df214, prompt:

"the following are draft provisions for eligibility, appointment, and end of tenure of a treasurer, appointed by a committee called CC (community council). Can you comment on the provisions, with the aim of improving clarity, avoiding loopholes, and minimizing the potential for corruption?"

ChatGPT:

Appointment:

* Define the term "simple majority" to specify the required percentage of votes needed for an appointment. For example, it could be defined as more than 50% of the CC votes.
* Clarify the process for conducting the appointment vote, including the timeline, method of voting, and how votes will be counted to ensure transparency and fairness.

End of Tenure:

* Consider adding a provision that allows for the removal of a treasurer in case of proven misconduct or ethical violations to further safeguard against corruption. This could include provisions for investigating and addressing any reported instances of misconduct.
* Specify the process for reappointment, including whether there is a limit on the number of consecutive terms a treasurer can serve and any requirements for reapplying or going through the appointment process again.

Inactivity and Removal:

* Clarify the definition of "inactivity" to specify the expectations and responsibilities of the treasurer, such as the frequency and content of financial reports or any other duties relevant to the position.
* Clearly outline the steps and process for removing a treasurer due to inactivity, including the role of the CC and the requirements for initiating the removal process.
* Consider incorporating safeguards to prevent any misuse of the removal process by requiring a thorough evaluation and proper documentation before initiating removal proceedings.

CoC Violations:

* Specify the procedures for handling violations of the CoC provisions on resource allocation and fiscal transparency, including the role of the CoC committee, the steps involved in investigating and addressing violations, and any disciplinary actions or consequences for such violations.

Overall, it is essential to ensure that the provisions are clear, transparent, and provide checks and balances to prevent corruption and misuse of power. Regular reviews and updates of these provisions may also be necessary to adapt to changing circumstances and emerging best practices.

**Comment by fkiraly** [comment]
This resulted in version https://github.com/sktime/sktime/pull/4798/commits/2bf41d882ba0beb08af65f943ecad1cf97ba9510. After asking to re-review:

Thank you for providing the updated provisions. Here are my comments:

Eligibility:

* The addition of provisions stating that individuals previously removed from the role of treasurer due to inactivity or code of conduct violations are not eligible for reappointment within a calendar year is a good safeguard to prevent potential issues from recurring.

Appointment:

* The requirement for a proposer and a seconder (both core developers) for a core developer to register as a candidate adds a layer of validation to the nomination process.

* It's positive that you clarified that the CC will appoint the treasurer among the candidates with a simple relative majority. This provides a clearer understanding of the decision-making process.

End of Tenure:

* The inclusion of a provision allowing the treasurer to resign voluntarily at any point in time, by informing the CC in writing, ensures a straightforward process for resignation.

* The specified conditions for removal due to inactivity, such as failing to compile a budget or statement within the required timeframe and at least one member of the CC requesting removal, are clear and provide a basis for making the decision.

* The addition of requirements for at least two members of the CC to request or complain before the CoC committee can initiate an investigation into potential removal due to a violation of CoC provisions adds an additional layer of checks and balances to prevent misuse of the process.

Overall, the updated provisions address the points raised in my previous response. They provide more clarity, avoid potential loopholes, and minimize the potential for corruption. However, it's important to note that the final effectiveness of these provisions will depend on the context and implementation within the specific organization.

**Comment by fkiraly** [comment]
FYI @marrov, I made minor changes to the approved, can you kindly have a look?

* CC should refer to the actual name (not core committee, community council)
* "first order of business" -> translated to responsibility, to clarify it is not just a "one time thing"
* clarified the appointment process along the lines we discussed in the Sep 5 meeting

**Comment by marrov** [comment]
@fkiraly - I'm ok with the changes. I also made a minor format fix.

**Review by fkiraly — COMMENTED** [review]
Alright, thanks! Let's merge then.

**Pull request merged**
