### PR TITLE
[ENH] logger transformer for logging pipeline inputs and outputs

### PR DESCRIPTION
**Pull request by fkiraly**
This PR adds a `Logger` transformer which can be pipelined with anything to write inputs or outputs to `logging` log targets, and optionally to `self` to retrieve by `get_fitted_params`.

Inputs pass the `Logger` unchanged, so apart from the logging it behaves like the `Id` transformer.

Depends on https://github.com/sktime/sktime/pull/7075 as in the API reference the logger is sorted into a new pipeline building category.

### CODE REVIEW

**Comment by Lenaklsk** [comment]
This PR aligns perfectly with the functionality I need for my project.

What I essentially require is the following:
1. Set up the logger 
3. Create a logger before each transformation step 
3. Retrieve X and y after each transformation (in dataframe format) to analyze the results of the transformation steps. 

Here's an example of how this would be done:   

``` logger = logging.getLogger("sktime")
logger_sk = Logger(
    logger=logger,
    log_methods=["fit", "transform"],
    level=logging.DEBUG,
    log_fitted_params=True 
)transform_piperline = TransformerPipeline(
    steps=[
        ("logger_1", logger_sk),
        ("scaler", TabularToSeriesAdaptor(StandardScaler())),
        ("logger_2", logger_sk),
        ("deseason", Deseasonalizer(sp=12)),  # ConditionalDeseasonalizer(sp=12)), ...
    ]
)
fitted_pipeline = transform_piperline.fit(X_train, y_train) 
fitted_pipeline.get_fitted_params()["logger_1"].X_

**Comment by Lenaklsk** [comment]
- For our use case at the moment it is enough to get the inputs at fit time
- right now I don't now a way

**Comment by fkiraly** [comment]
> right now I don't now a way

I think I found one - I've just written a very simple multiton logger which stores the data in a list. As long as nothing gets mutated, this should work fine.

**Comment by Lenaklsk** [comment]
This Logger looks really good for my project. I'd really like to see it included in the main package so that I can use it. 

Thank you for your work!

**Comment by fkiraly** [comment]
great, thanks for the review! Would appreciate if you could try it out from a developer install already before the release to see whether it fits the use case.
Otherwise it should be in the late Sep release.

**Pull request merged**
