### PR TITLE
[MNT] Add score function test to classifiers

### PR DESCRIPTION
**Pull request by Cyril-Meyer**
#### Reference Issues/PRs
* Details on the original problem and discussion in #6018 
* Same as #6019 for classifier

#### What does this implement/fix? Explain your changes.
Add a test for classifier score function.

#### Does your contribution introduce a new dependency? If yes, which one?
No.

#### What should a reviewer concentrate their feedback on?
Using `pytest -k TestAllClassifiers`

Before (branch main) :
```
===================================== 6 skipped, 11 warnings in 161.67s (0:02:41) ======================================
```

After (my branch) : 
```
===================================== 146 passed, 42 warnings in 173.86s (0:02:53) =====================================
```

#### Did you add any tests for the change?
Yes.
* `pytest -k TestAllClassifiers`
* `make test`

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

### CODE REVIEW

**Comment by Cyril-Meyer** [comment]
As some tests are failed, I am interested in some opinions.

The `score` function we call is not happy with **NaN**.
The `score` function use `sklearn.metrics.accuracy_score` which is in definitive the one who call the error.

Solutions : 
1. Remove test from test_multioutput.
2. Return NaN "error value" instead of raising an error in `score`.

Example of test fail :
```
FAILED sktime/classification/tests/test_all_classifiers.py::TestAllClassifiers::test_multioutput[TSCGridSearchCV-0] - ValueError: Input y_pred contains NaN.
FAILED sktime/classification/tests/test_all_classifiers.py::TestAllClassifiers::test_multioutput[TSCGridSearchCV-1] - ValueError: Input y_pred contains NaN.
```

**Comment by fkiraly** [comment]
well, that's odd - I don't see why the classifier would produce `nan` - possibly this is an issue with the classifier?

**Comment by Cyril-Meyer** [comment]
> well, that's odd - I don't see why the classifier would produce `nan` - possibly this is an issue with the classifier?

For now, I don't know at all, I need to reproduce the error without the test environment.

What I know : 
-> `y_pred` = `self.predict(X)`
* `sklearn.metrics.accuracy_score(y_true, y_pred, ...)`
* `accuracy_score(y, self.predict(X), normalize=True)`
-> error may be linked to some of those methods, but I haven't checked them yet :
* `predict`
* `_check_convert_X_for_predict`
* `_convert_output_y`

**Comment by fkiraly** [comment]
Ouch. Sometimes this happens - you fix a bug, and you discovered a bug one layer down.

While it might be tempting to dig, the metaphorical risk is that of a cave-in, i.e., at the end your multi-fix gets unfixably broken.

The "clean" way is: open a bug report, reproducible code can be the unique string identifier of the test; add an exception to the failing tests (here: in `tests/_config.py`, in the dictionary), add a comment that refers to the issue number. Merge the fix for the "first layer".

Of course, in the interest of full honest disclosure, I should also admit that in similar situations I have disregarded this advice more often than not; and sometimes I have really really regretted it. But it's good to know the theory, I suppose...

**Comment by Cyril-Meyer** [comment]
I created issue #6061 to document the error.

> The "clean" way is: open a bug report for the "layer 2 bug" (or, layer 1 bug in python counting convention), reproducible code can be the unique string identifier of the test; add an exception to the failing tests in the initial bugfix (here: in `tests/_config.py`, in the dictionary), add a comment that refers to the issue number. Merge the fix for the "first layer".

Maybe I didn't understand what you meant but, as the `score` test is included in a current working test (checking outputs), I don't think that adding an exception for this function is a good idea as we may stop check things that were checked before.

**Comment by fkiraly** [comment]
> I don't think that adding an exception for this function is a good idea as we may stop check things that were checked before.

Yes, I see the point - we should not reduce test coverage.

Then I see the following two - painful - ways to keep test coverage intact:

* make a copy of the excepted test `test_multioutput` as it was before testing `score`, and add it in the tests for the grid search; add an exception for `test_multioutput`. Does not reduce coverage, because we add coverage in the "loose" test
* split the suit test into two, leaving the `test_multioutput` as it was, and add a new test `test_multioutput_score`. Add an exception for `test_multioutput_score`.

None of these are really great, solution 1 duplicates code, solution 2 multiplies test runtime (due to repeated calls to computational bottleneck `fit`).

**Comment by fkiraly** [comment]
@Cyril-Meyer, this still would be useful - I was thinking we would just skip the rid search?

**Pull request closed without merging**
