### PR TITLE
[BUG] fix `BaseRegressor.score` method failing with `sklearn.metrics r2_score got an unexpected keyword argument 'normalize'`

### LINKED ISSUE #6018: [BUG] sklearn.metrics r2_score got an unexpected keyword argument 'normalize'
**Describe the bug**
When using ResNetRegressor score (also tested with FCNRegressor and same bug) you got a sklearn.metrics error.

TypeError: got an unexpected keyword argument 'normalize'

**To Reproduce**
```python
import sktime
from sktime.regression.deep_learning.resnet import ResNetRegressor
from sktime.datasets import load_UCR_UEA_dataset

data = 'BIDMC32HR'
train_x, train_y = load_UCR_UEA_dataset(name=data, split="train")
test_x,  test_y  = load_UCR_UEA_dataset(name=data, split="test")

model = ResNetRegressor(n_epochs=1, batch_size=1)
model.fit(train_x, train_y)
model.score(test_x, test_y)
```

**Expected behavior**
Not an error but score

**Additional context**

ResNetRegressor::score
<details>

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[7], line 1
----> 1 model.score(test_x, test_y)

File [~/Development/sktime-dev/sktime/sktime/regression/base.py:302](http://localhost:18888/lab/tree/sktime/sktime/sktime/regression/base.py#line=301), in BaseRegressor.score(self, X, y, multioutput)
    298 from sklearn.metrics import r2_score
    300 self.check_is_fitted()
--> 302 return r2_score(y, self.predict(X), normalize=True, multioutput=multioutput)

File [~/Development/sktime-dev/venv/lib/python3.10/site-packages/sklearn/utils/_param_validation.py:191](http://localhost:18888/lab/tree/sktime/venv/lib/python3.10/site-packages/sklearn/utils/_param_validation.py#line=190), in validate_params.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    188 func_sig = signature(func)
    190 # Map *args/**kwargs to the function signature
--> 191 params = func_sig.bind(*args, **kwargs)
    192 params.apply_defaults()
    194 # ignore self/cls and positional/keyword markers

File /usr/lib/python3.10/inspect.py:3186, in Signature.bind(self, *args, **kwargs)
   3181 def bind(self, /, *args, **kwargs):
   3182     """Get a BoundArguments object, that maps the passed `args`
   3183     and `kwargs` to the function's signature.  Raises `TypeError`
   3184     if the passed arguments can not be bound.
   3185     """
-> 3186     return self._bind(args, kwargs)

File /usr/lib/python3.10/inspect.py:3175, in Signature._bind(self, args, kwargs, partial)
   3173         arguments[kwargs_param.name] = kwargs
   3174     else:
-> 3175         raise TypeError(
   3176             'got an unexpected keyword argument {arg!r}'.format(
   3177                 arg=next(iter(kwargs))))
   3179 return self._bound_arguments_cls(self, arguments)

TypeError: got an unexpected keyword argument 'normalize'
```
</details>

FCNRegressor::model
<details>

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[8], line 4
      2 model = FCNRegressor(n_epochs=1, batch_size=1)
      3 model.fit(train_x, train_y)
----> 4 model.score(test_x, test_y)

File [~/Development/sktime-dev/sktime/sktime/regression/base.py:302](http://localhost:18888/lab/tree/sktime/sktime/sktime/regression/base.py#line=301), in BaseRegressor.score(self, X, y, multioutput)
    298 from sklearn.metrics import r2_score
    300 self.check_is_fitted()
--> 302 return r2_score(y, self.predict(X), normalize=True, multioutput=multioutput)

File [~/Development/sktime-dev/venv/lib/python3.10/site-packages/sklearn/utils/_param_validation.py:191](http://localhost:18888/lab/tree/sktime/venv/lib/python3.10/site-packages/sklearn/utils/_param_validation.py#line=190), in validate_params.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    188 func_sig = signature(func)
    190 # Map *args/**kwargs to the function signature
--> 191 params = func_sig.bind(*args, **kwargs)
    192 params.apply_defaults()
    194 # ignore self/cls and positional/keyword markers

File /usr/lib/python3.10/inspect.py:3186, in Signature.bind(self, *args, **kwargs)
   3181 def bind(self, /, *args, **kwargs):
   3182     """Get a BoundArguments object, that maps the passed `args`
   3183     and `kwargs` to the function's signature.  Raises `TypeError`
   3184     if the passed arguments can not be bound.
   3185     """
-> 3186     return self._bind(args, kwargs)

File /usr/lib/python3.10/inspect.py:3175, in Signature._bind(self, args, kwargs, partial)
   3173         arguments[kwargs_param.name] = kwargs
   3174     else:
-> 3175         raise TypeError(
   3176             'got an unexpected keyword argument {arg!r}'.format(
   3177                 arg=next(iter(kwargs))))
   3179 return self._bound_arguments_cls(self, arguments)

TypeError: got an unexpected keyword argument 'normalize'
```
</details>

**Versions**
<details>

```
/home/cyril/Development/sktime-dev/venv/lib/python3.10/site-packages/_distutils_hack/__init__.py:26: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
/home/cyril/Development/sktime-dev/venv/lib/python3.10/site-packages/statsforecast/core.py:26: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm
```
System:
    python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
executable: /home/cyril/Development/sktime-dev/venv/bin/python
   machine: Linux-6.5.0-14-generic-x86_64-with-glibc2.35

Python dependencies:
          pip: 24.0
       sktime: 0.26.1
      sklearn: 1.4.1.post1
       skbase: 0.7.2
        numpy: 1.26.4
        scipy: 1.12.0
       pandas: 2.1.4
   matplotlib: 3.8.3
       joblib: 1.3.2
        numba: 0.58.1
  statsmodels: 0.14.1
     pmdarima: 2.0.4
statsforecast: 1.7.3
      tsfresh: 0.20.2
      tslearn: 0.6.3
        torch: None
   tensorflow: 2.15.0
tensorflow_probability: None
</details>

### PR DESCRIPTION
**Pull request by Cyril-Meyer**
#### Reference Issues/PRs
Fixes #6018

#### What does this implement/fix? Explain your changes.
Remove non-existing `normalize` parameter for `r2_score` in `sktime.regression.base` class : `BaseRegressor` method : `score`.

#### Does your contribution introduce a new dependency? If yes, which one?
No.

#### What should a reviewer concentrate their feedback on?
This PR does not solve another issue which is not directly linked, but should be noted.

With `test_x,  test_y  = load_UCR_UEA_dataset(name=data, split="test")`
```
model.score(test_x, test_y)
```
Will throw error :
<details>

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[6], line 1
----> 1 model.score(test_x, test_y)

File [~/Development/sktime-dev/sktime/sktime/regression/base.py:302](http://localhost:18888/lab/tree/sktime/sktime/sktime/regression/base.py#line=301), in BaseRegressor.score(self, X, y, multioutput)
    298 from sklearn.metrics import r2_score
    300 self.check_is_fitted()
--> 302 return r2_score(y, self.predict(X), multioutput=multioutput)

File [~/Development/sktime-dev/venv/lib/python3.10/site-packages/sklearn/utils/_param_validation.py:213](http://localhost:18888/lab/tree/sktime/venv/lib/python3.10/site-packages/sklearn/utils/_param_validation.py#line=212), in validate_params.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    207 try:
    208     with config_context(
    209         skip_parameter_validation=(
    210             prefer_skip_nested_validation or global_skip_validation
    211         )
    212     ):
--> 213         return func(*args, **kwargs)
    214 except InvalidParameterError as e:
    215     # When the function is just a wrapper around an estimator, we allow
    216     # the function to delegate validation to the estimator, but we replace
    217     # the name of the estimator by the name of the function in the error
    218     # message to avoid confusion.
    219     msg = re.sub(
    220         r"parameter of \w+ must be",
    221         f"parameter of {func.__qualname__} must be",
    222         str(e),
    223     )

File [~/Development/sktime-dev/venv/lib/python3.10/site-packages/sklearn/metrics/_regression.py:1180](http://localhost:18888/lab/tree/sktime/venv/lib/python3.10/site-packages/sklearn/metrics/_regression.py#line=1179), in r2_score(y_true, y_pred, sample_weight, multioutput, force_finite)
   1039 @validate_params(
   1040     {
   1041         "y_true": ["array-like"],
   (...)
   1059     force_finite=True,
   1060 ):
   1061     """:math:`R^2` (coefficient of determination) regression score function.
   1062 
   1063     Best possible score is 1.0 and it can be negative (because the
   (...)
   1178     -inf
   1179     """
-> 1180     y_type, y_true, y_pred, multioutput = _check_reg_targets(
   1181         y_true, y_pred, multioutput
   1182     )
   1183     check_consistent_length(y_true, y_pred, sample_weight)
   1185     if _num_samples(y_pred) < 2:

File [~/Development/sktime-dev/venv/lib/python3.10/site-packages/sklearn/metrics/_regression.py:103](http://localhost:18888/lab/tree/sktime/venv/lib/python3.10/site-packages/sklearn/metrics/_regression.py#line=102), in _check_reg_targets(y_true, y_pred, multioutput, dtype)
     69 """Check that y_true and y_pred belong to the same regression task.
     70 
     71 Parameters
   (...)
    100     correct keyword.
    101 """
    102 check_consistent_length(y_true, y_pred)
--> 103 y_true = check_array(y_true, ensure_2d=False, dtype=dtype)
    104 y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
    106 if y_true.ndim == 1:

File [~/Development/sktime-dev/venv/lib/python3.10/site-packages/sklearn/utils/validation.py:1038](http://localhost:18888/lab/tree/sktime/venv/lib/python3.10/site-packages/sklearn/utils/validation.py#line=1037), in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator, input_name)
   1035         raise ValueError(msg)
   1037 if dtype_numeric and hasattr(array.dtype, "kind") and array.dtype.kind in "USV":
-> 1038     raise ValueError(
   1039         "dtype='numeric' is not compatible with arrays of bytes/strings."
   1040         "Convert your data to numeric values explicitly instead."
   1041     )
   1042 if not allow_nd and array.ndim >= 3:
   1043     raise ValueError(
   1044         "Found array with dim %d. %s expected <= 2."
   1045         % (array.ndim, estimator_name)
   1046     )

ValueError: dtype='numeric' is not compatible with arrays of bytes/strings.Convert your data to numeric values explicitly instead.
```
</details>

The solution is to do something like : 
```
model.score(test_x, test_y.astype(np.float64))
```

#### Did you add any tests for the change?
Change is straightforward and working on dev setup, but I didn't run coverrage test.

```
check for added large files..............................................Passed
check for case conflicts.................................................Passed
check for merge conflicts................................................Passed
check for broken symlinks............................(no files to check)Skipped
check yaml...........................................(no files to check)Skipped
debug statements (python)................................................Passed
fix end of files.........................................................Passed
fix python encoding pragma...............................................Passed
fix requirements.txt.................................(no files to check)Skipped
trim trailing whitespace.................................................Passed
pyupgrade................................................................Passed
isort....................................................................Passed
black....................................................................Passed
flake8...................................................................Passed
nbqa-black...........................................(no files to check)Skipped
nbqa-isort...........................................(no files to check)Skipped
nbqa-flake8..........................................(no files to check)Skipped
pydocstyle...............................................................Passed
shellcheck...........................................(no files to check)Skipped
```

#### Any other comments?
1. This error can probably be detected in tests.
2. `r2_score` choice is debatable, `mean_squared_error` can also be an option.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Yes, that fixes the issue.

We should also add a test to ensure this doesn't break again in the future, suggestions are discussed in the original issue https://github.com/sktime/sktime/issues/6018

**Comment by Cyril-Meyer** [comment]
> Yes, that fixes the issue.
> 
> We should also add a test to ensure this doesn't break again in the future, suggestions are discussed in the original issue #6018

As said in #6018 I think that we should create a new issue / pull request pair for the test part.

**Comment by Cyril-Meyer** [comment]
Tests are run using `pytest -k TestAllRegressors`.

Test without fix :

```
=============================================== short test summary info ================================================
FAILED sktime/regression/tests/test_all_regressors.py::TestAllRegressors::test_multioutput[DummyRegressor] - TypeError: got an unexpected keyword argument 'normalize'
FAILED sktime/regression/tests/test_all_regressors.py::TestAllRegressors::test_multioutput[ComposableTimeSeriesForestRegressor] - TypeError: got an unexpected keyword argument 'normalize'
FAILED sktime/regression/tests/test_all_regressors.py::TestAllRegressors::test_multioutput[RocketRegressor] - TypeError: got an unexpected keyword argument 'normalize'
================================= 3 failed, 9 passed, 12 warnings in 164.61s (0:02:44) =================================
```

Test with fix :
```
===================================== 12 passed, 12 warnings in 155.03s (0:02:35) ======================================
```

**Review by fkiraly — CHANGES_REQUESTED** [review]
Great!

Could you also add to `test_regressor_output`?

It would be `estimator_instance.score(X_new, y_pred)` if I'm not mistaken.

**Comment by Cyril-Meyer** [comment]
> Could you also add to `test_regressor_output`?

Yes, no problem.

Test without fix :
```
=============================================== short test summary info ================================================
FAILED sktime/regression/tests/test_all_regressors.py::TestAllRegressors::test_multioutput[DummyRegressor] - TypeError: got an unexpected keyword argument 'normalize'
FAILED sktime/regression/tests/test_all_regressors.py::TestAllRegressors::test_regressor_output[DummyRegressor-ClassifierFitPredictUnequalLength] - TypeError: got an unexpected keyword argument 'normalize'
FAILED sktime/regression/tests/test_all_regressors.py::TestAllRegressors::test_multioutput[ComposableTimeSeriesForestRegressor] - TypeError: got an unexpected keyword argument 'normalize'
FAILED sktime/regression/tests/test_all_regressors.py::TestAllRegressors::test_multioutput[RocketRegressor] - TypeError: got an unexpected keyword argument 'normalize'
FAILED sktime/regression/tests/test_all_regressors.py::TestAllRegressors::test_regressor_output[RocketRegressor-ClassifierFitPredict] - TypeError: got an unexpected keyword argument 'normalize'
FAILED sktime/regression/tests/test_all_regressors.py::TestAllRegressors::test_regressor_output[ComposableTimeSeriesForestRegressor-ClassifierFitPredict] - TypeError: got an unexpected keyword argument 'normalize'
FAILED sktime/regression/tests/test_all_regressors.py::TestAllRegressors::test_regressor_output[DummyRegressor-ClassifierFitPredictMultivariate] - TypeError: got an unexpected keyword argument 'normalize'
FAILED sktime/regression/tests/test_all_regressors.py::TestAllRegressors::test_regressor_output[RocketRegressor-ClassifierFitPredictMultivariate] - TypeError: got an unexpected keyword argument 'normalize'
FAILED sktime/regression/tests/test_all_regressors.py::TestAllRegressors::test_regressor_output[DummyRegressor-ClassifierFitPredict] - TypeError: got an unexpected keyword argument 'normalize'
================================= 9 failed, 3 passed, 12 warnings in 156.24s (0:02:36) =================================
```

Test with fix :
```
===================================== 12 passed, 12 warnings in 154.89s (0:02:34) ======================================
```

**Comment by Cyril-Meyer** [comment]
> Nice!
> On to classification then? (in a separate PR and if you don't mind applying the same fix)
> I suppose it suffices to add the tests there, and `score` will not fail (hopefully)

Yes, I will prepare another PR for classification, should be coming soon.
As you may notice, I used my fork main branch for this PR, so I need to clean things for multiple PR handling.

**Comment by fkiraly** [comment]
I see - using `main` on fork is not advised, one reason is that it makes resolving merge conflicts very unpleasant. Tends not to be a problem for smaller PR, but can turn into nightmares for larger ones...

**Comment by Cyril-Meyer** [comment]
> I see - using `main` on fork is not advised, one reason is that it makes resolving merge conflicts very unpleasant. Tends not to be a problem for smaller PR, but can turn into nightmares for larger ones...

Yes, Iesson learned, it's my last time using main for PR 😄

**Pull request merged**
