### PR TITLE
[ENH] pykan based forecaster

### PR DESCRIPTION
**Pull request by benHeid**
Towards #6390 

```python

from sktime.forecasting.pykan_forecaster import PyKANForecaster
from sktime.datasets import load_airline
forecaster = PyKANForecaster()
forecaster.fit(load_airline(), fh=range(12))
prediction = forecaster.predict()
import matplotlib.pyplot as plt
plt.plot(prediction.detach().numpy().flatten(), label="Prediction")
plt.plot(test_target[0].detach().numpy().flatten(), label="True")
plt.show()

```

#### Reference Issues/PRs
#6390 

#### What does this implement/fix? Explain your changes.
Add a simple PyKAN based forecaster

#### Does your contribution introduce a new dependency? If yes, which one?
pykan

#### Did you add any tests for the change?

add get_test_params

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [x] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [x] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Comment by benHeid** [comment]
## TODOs
* [ ] Try to expose all available parameters of the KAN and the train methods using dicts.

**Comment by narencastellon** [comment]
How do I install from sktime.forecasting.pykan_forecaster import PyKANForecaster, what is the dependency to install?

**Comment by benHeid** [comment]
Hey, it is not on the main branch yet. You need to install the feature branch. E.g. by cloning the repo check out the feature branch and install this branch. 

Hopefully, this feature is included in the next sktime release. 
@fkiraly fyi.

**Comment by fkiraly** [comment]
let me know when it's ready to review - currently there is one unchecked todo

**Comment by benHeid** [comment]
> let me know when it's ready to review - currently there is one unchecked todo

Sorry, I forgot to tick the open todo. I enabled the parameter using two dicts: model_params and fit_params

**Review by fkiraly — APPROVED** [review]
Seems done, then.

Have you solved the test time issue?

**Comment by narencastellon** [comment]
Thank you very much @fkiraly Franz Király excellent work,, I'm going to try it. a query to perform some tests I must clone the repository, and then I can call the function like this: from sktime.forecasting.pykan_forecaster import PyKANForecaster

**Comment by fkiraly** [comment]
@narencastellon, this is actually almost entirely @benHeid's work!

To use this, you can simply wait for the release 0.29.1 in a few days, I would assume it is by then merged.

**Comment by benHeid** [comment]
> Seems done, then.
> 
> 
> 
> Have you solved the test time issue?

Not checked it directly, but due to the set test params and rather small test time series I haven't experienced any long test runs. Furthermore, also the CI forecasting runs are not reporting this forecaster as slowest. 
However, I can check tomorrow locally.

**Comment by benHeid** [comment]
I compared it with the cINNForecaster. After reducing the network size of the test network it is now a bit faster than the cINNForecaster.

**Comment by narencastellon** [comment]
I have updated and cloned sktime with 0.29.1, and I want to apply the pykan_forecaster example:

from sktime.forecasting.pykan_forecaster import PyKANForecaster
forecaster = PyKANForecaster()
forecaster.fit(df, fh = 12)

but it sends me the following error

"TypeError: 'NoneType' object is not subscriptable"

**Comment by benHeid** [comment]
The issue is that the grid param is not set and that I haven't set sensible defaults... So the following code should work:

```python
from sktime.forecasting.pykan_forecaster import PyKANForecaster
forecaster = PyKANForecaster(grids=[5,5])
forecaster.fit(df, fh = 12)
```

regarding the problem you identified. Might you open an issue, so that this can be tracked and fixed?

**Pull request merged**
