### PR TITLE
[MNT] new CI workflow to test extras

### PR DESCRIPTION
**Pull request by yarnabrina**
new CI workflow that tris to install `sktime` each extra to see if the specified packages (with specified versions or versions bounds) are compatible with one another.

when does it run:

1. runs first of every month at 00:00
2. runs for a PR into `main`that modifies `pyproject.toml`
3. runs when triggered manually

what does it do:

1. runs for all supported operating system
2. runs for all supported python version
3. runs for all supported extras
4. creates a new python environment of specific python version on a specific operating system with a specific python version and installs `sktime` with a specific extra

what does it not do:

1. installation multiple extras simultaneously - too many combinations
2. automated resolution if installation fails with conflicts - probably impossible

other changes

1. formatted of `pyproject.toml` with `pyproject-fmt` as needed to test workflow
2. skipped `mrsqm` from `classification` extra as it was failing to be built in most combinations
3. added python version bound for relevant packages

### CODE REVIEW

**Comment by yarnabrina** [comment]
I'm not sure if we are still in feature freeze or not, but is this ready to be merged? It does not affect any existing CI or functionality to the best of my knowledge.

Summary of changes:

1. adds an action to install an extra to see if dependencies are compatible with one another
2. adds an workflow based on above action to auto-trigger in case of change in pyproject.toml, and in a schedule
3. formats pyproject.toml using https://pypi.org/project/pyproject-fmt/

CC: @fkiraly, @benHeid, @achieveordie

(Reason for this bump/reminder is that with every new change in `main` branch's `pyproject.toml`, Github decides it's a conflict and I've to solve manually. If I skip the changes in `pyproject.toml`, no more conflict problem but I can't test the workflow in this PR anymore.)

**Comment by fkiraly** [comment]
not a review yet, but some questions:

* there are 160 CI (matrix) elements here - can you explain how these arise?
* the title of the CI element is quite long, so one can't see the total runtime or status string. Perhaps we should shorten it?

**Comment by yarnabrina** [comment]
> the title of the CI element is quite long, so one can't see the total runtime or status string

Not following this question. Can it be the case that it depends on screen size or anything? I'm not sure what can't be seen. I shortened th strings nevertheless.

> there are 160 CI (matrix) elements here - can you explain how these arise?

As part of #5136, I introduced 9 new extras. This workflow tries to test each of these on each supported python version (3.8 to 3.12 - so 5 each) on each supported operating system (so 3 each) - leading to 135 jobs. The rest of the CI jobs are from existing workflows, as those are completely unchanged so far.

**Comment by fkiraly** [comment]
> Can it be the case that it depends on screen size or anything? I'm not sure what can't be seen. I shortened th strings nevertheless.

Yes, of course - we need to think of people with normal scree sizes, too...

Also I think the names of the workflow elements should be self-descriptive to any new contributor:
image
I think "extras" is too contextual, although I have no good alternative suggestion.

**Comment by fkiraly** [comment]
> This workflow tries to test each of these on each supported python version (3.8 to 3.12 - so 5 each) on each supported operating system (so 3 each) - leading to 135 jobs

That's 160 minutes CI time - are you saying, these run even if there is no change to the modules?

**Comment by fkiraly** [comment]
> when does it run:

Oh, I see, it does not run for the average PR, right?

**Comment by yarnabrina** [comment]
> Oh, I see, it does not run for the average PR, right?

Yes, it does not. Only for PR's modifying the pyproject.toml.

---

Is it okay to merge this PR now? I think the timeout/connection errors are out of scope of this PR?

**Comment by fkiraly** [comment]
>Is it okay to merge this PR now? I think the timeout/connection errors are out of scope of this PR?

I won't block it or approve it until I fully understand it, so you are fine to merge it as there is no change request.

**Comment by yarnabrina** [comment]
> so you are fine to merge

I don't have sufficient rights to merge without approval. So, adding a depends clause in the PR description for #5304.

**Review by fkiraly — APPROVED** [review]
Thanks, reviewed and approved.

Number 1 in the sequence of merges.

**Pull request merged**
