### PR TITLE
[DOC] fix typo: Transforemd → Transformed

### PR DESCRIPTION
**Pull request by kgeis**
#### Reference Issues/PRs
n/a

#### What does this implement/fix? Explain your changes.
a typo in the documentation

#### Does your contribution introduce a new dependency? If yes, which one?
no

#### What should a reviewer concentrate their feedback on?
the ordering of the letters m and e

#### Did you add any tests for the change?
no

#### Any other comments?
no

##### For all contributions
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Much appreciated!
Typos like this also drive me crazy, thanks for fixing.

Unfortunately, the diff for the notebook is substantial (possibly due to re-execution on a different system) - can you make sure that you really only change the typos that you fix?

You can ensure that is the case by cloning and then editing as a text file, sometimes notebook readers reset and rewrite the metadata.

**Comment by kgeis** [comment]
Yeah, I noticed that +/-. I edited it in the GitHub editor. Shame on them! 😁

I'll see if I can get around to editing this more precisely, but I won't be offended if you make the change and close the PR.

**Review by fkiraly — APPROVED** [review]
It was just easier to do a search/replace.

The culprit is the general interaction between git and jupyter, this is still not that great.
(pointers appreciated what makes that less annoying)

Thanks!

**Comment by fkiraly** [comment]
Also, this:

> What should a reviewer concentrate their feedback on?
> the ordering of the letters m and e

Extremely funny and appreciated if intended.
Or shall I say: extrmeely funny?

**Pull request merged**
