### PR TITLE
[ENH] Add peak hour and working hour as two new features to DateTimeFeatures transformer

### PR DESCRIPTION
**Pull request by ali-parizad**
#### What does this implement/fix? Explain your changes.
It adds two new features i.e., peak hour and working hour to in the "comprehensive" argument in the "DateTimeFeatures" transformer. These features can be useful when we know about peak hours, e.g., in energy forecasting. As an example, a commercial building may have peak hours of energy consumption from 5 pm to 9 pm. On the other hand, a university building may have peak hours of energy consumption from 12 pm to 5 pm.

#### Does your contribution introduce a new dependency? If yes, which one?
No

#### What should a reviewer concentrate their feedback on?
Reviewers can check the functionality of

[] is_peak_hour (check new column in df)
[] is_working_hour (check new column in df)
[] is_peak_hour_range
[] is_working_hour_range
[] _check_is_peak_hour_range function (use negative value and getting error, or use peak_hour_start greater than peak_hour_end)
[] _check_is_working_hour_range function (use negative value and getting error, or use working_hour_start greater than working_hour_end)

#### Did you add any tests for the change?

```python
from sktime.transformations.series.date import DateTimeFeatures
from sktime.datasets import load_solar
y =  load_solar(start='2022-05-01', return_full_df=True, end='2022-06-18', api_version="v4")
y = y.tz_localize(None)
y = y.asfreq("H")
transformer = DateTimeFeatures(ts_freq="H", feature_scope="comprehensive", is_peak_hour_range = [12, 17], is_working_hour_range = [8,16])
y_hat = transformer.fit_transform(y)
y_hat
```

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Comment by fkiraly** [comment]
Great addition, @ali-parizad!

Few questions re design:

* aren't peak hours dependent on things like the country/region/state, working hour laws, type of industry or building, etc? That is, putting hard-coded "peak hours" is maybe too restrictive for covering a good range of use cases?
* following this train of thought, would it be worth thinking about a dedicated `PeakHourFeatures` transformer, i.e., a separate transformer, where you can specify when peak hours start and end? Possibly having multiple classes - non-working hours, core working hours, flex working hours? Similar could be useful for production schedules, factories might have peak production hours which differ from peak working hours, but the same transformer would be useful there!
* you can of course start off a `PeakHourFeatures` transformer by copy-pasting `DateTimeFeatures` and stripping it down to a template, if you found it helpful.

I could imagine sth like `PeakHourFeatures(schema="nine-to-five")` for a couple hard-coded schemas, and it would also work with sth like `PeakHourFeatures({"start_peak": 10, "end_peak": 3})` or `PeakHourFeatures({"start_peak1": 6, "end_peak1": 9, "start_peak2": 16, "end_peak2": 19})` for custom ranges (the examples are: core working hours under partial flex time; traffic/transport rush hour)

**Comment by fkiraly** [comment]
FYI @KishManani, @VyomkeshVyas, if you have any opinions?

**Comment by VyomkeshVyas** [comment]
> FYI @danbartl, @KishManani, @VyomkeshVyas, if you have any opinions?

I think its better to keep these features separately from the DateTimeFeatures as "PeakTimeFeatures" since it has scope to extend further to something like "peak week" or "peak quarter", etc.

**Comment by ali-parizad** [comment]
Great Suggestions @fkiraly and comments @VyomkeshVyas . I am working on it to create a separate PeakHourFeatures.

**Comment by fkiraly** [comment]
obsolete, replaced by https://github.com/sktime/sktime/pull/5191

**Pull request closed without merging**
