### PR TITLE
[ENH] Examples for `YtoX` transformer docstring

### PR DESCRIPTION
**Pull request by geetu040**
#### Reference Issues/PRs

Continuation to this PR: #6028

#### What does this implement/fix? Explain your changes.

- In the mentioned PR, examples were added for `YtoX`. I have made minor fixes in import and pipeline initialization.
- Added `load_airline` dataset in both examples.
- Replaced `ARMIAX` with `Prophet` which made the forecast resutls better for this particular use-case.
- Completed the missing lines to make sure examples can be copied and pasted without any error.

#### What should a reviewer concentrate their feedback on?

I have considered `pydocstyle` documentation for examples and put `# doctest: +SKIP` for soft-dependencies. I hope I don't miss any line.

##### For all contributions
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [x] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks for the fixes!

Only one major comment: `Prophet` already has built-in fourier features, so changing the example makes it less "useful" in the sense of adding something above the base use.

How about adding two more use cases? (non-blocking)

* adding the lags to exogenous data that is already there? That should work with `Id` and `FeatureUnion` (via `+` dunder).
* construction of reduction, using `YfromX` with `Lags`

**Comment by fkiraly** [comment]
FYI, since this PR contains https://github.com/sktime/sktime/pull/6028 and builds on it, I am planning to close https://github.com/sktime/sktime/pull/6028.

**Comment by geetu040** [comment]
I have added another example that uses `WindowSummarizer`.

Although I have not been able to generate these examples, yet if you answer these queries I'll try again. We already have 3 examples, we can either stop with examples here or make changes to the newly added example of `WindowSummarizer`.

> * adding the lags to exogenous data that is already there? That should work with `Id` and `FeatureUnion` (via `+` dunder).

did you mean to apply lags to exogenous data and combine them with `YtoX` converted exogenous data.

> * construction of reduction, using `YfromX` with `Lags`

How is it going to use `YtoX` transformer

---

**Review by fkiraly — APPROVED** [review]
Thanks! I think this is now good to go, there's enough examples to make the pattern clear?

**Comment by geetu040** [comment]
> Thanks! I think this is now good to go, there's enough examples to make the pattern clear?

Agreed, we already have 3 examples. I believe we are good to go.

**Comment by geetu040** [comment]
fixed this failing test because of docstring examples
https://github.com/sktime/sktime/actions/runs/8241729902/job/22539629663

**Review by fkiraly — APPROVED** [review]

**Pull request merged**
