### PR TITLE
[MNT] rename variables in base

### PR DESCRIPTION
**Pull request by yarnabrina**
Diagnosing #5498

Depends #5498

### CODE REVIEW

**Comment by yarnabrina** [comment]
@fkiraly I rebased this from `main` now that #5498 is merged. This was mainly for diagnostics, but removing the probably unnecessary typo is probably good. Please let me know if it's good to be merged, or should I close this PR.

---

There's a numpy installation failure due to sha mismatch, not sure what to do about it.

**Review by fkiraly — APPROVED** [review]
Behaves as expected, and the code change makes the naming clearer.

Btw, this code is a duplicate of a parallel location in `skbase`, at some point we want to deduplicate. Until then, it might be nice if you change it there as well?

**Comment by fkiraly** [comment]
> There's a numpy installation failure due to sha mismatch, not sure what to do about it.

No idea. Sporadic?

**Comment by yarnabrina** [comment]
Ok, ignoring sporadic stuff for now and merging. 

Will take a look at skbase and create a PR there.

**Pull request merged**
