### PR TITLE
[ENH] Adding support for GluonTS' PandasDataset object

### LINKED ISSUE #6658: [ENH] Adding PandasDataset from GluonTS support in Sktime
**Is your feature request related to a problem? Please describe.**
I am currently working on implementing an interface for LagLlama - [link here](https://github.com/sktime/sktime/issues/6142#event-12924676868) - and one of the accepted input types for LagLlama is GluonTS' PandasDataset.

**Describe the solution you'd like**
I wish to add support for the `PandasDataset` object type in sktime. I have already worked on GluonTS in sktime, and am quite familiar with both frameworks.

**Describe alternatives you've considered**
An alternate solution would be using `CSV` files, but since `PandasDataset` offer easy conversions from `pd.DataFrame`, I think this implementation will be really helpful.

**Additional context**
Nothing additional to add for now.

### PR DESCRIPTION
**Pull request by shlok191**
#### Reference Issues/PRs
Fixes #6658 

#### What does this implement/fix? Explain your changes.
This implementation adds conversion functions to easily deal with `pd.DataFrame` of the `long` and `long` varieties in addition to lists and dictionaries of the same to `gluonTS PandasDataset` objects. This also includes the conversion of `pd.Series` to `gluonTS PandasDataset` objects.

#### Does your contribution introduce a new dependency? If yes, which one?
Nope! Since GluonTS is a pre-existing dependency added in from a different PR.

#### What should a reviewer concentrate their feedback on?
A reviewer should concentrate on the `sktime/datasets/_adapter/gluonts.py` file.

#### Did you add any tests for the change?
Not yet, but I am planning on doing so

#### Any other comments?
I was really hoping to add the `gluonTS PandasDataset` as a proper mtype, but I could not find any way to convert a PandasDataset to a pd.DataFrame. I'll discuss this more in a comment!

##### For all contributions
- [X] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [X] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

### CODE REVIEW

**Comment by shlok191** [comment]
@fkiraly, I have added conversion functions to convert pandas DataFrames to the GluonTS PandasDataset that is utilized by LagLlama! I was hoping to make the new data format an sktime mtype, but unfortunately there is no way that I can find which converts a PandasDataset back to pd.DataFrame.

Could we have it possibly reference the use of the adapter functions we have defined in the LagLlama documentation and the written examples? That way, I think we could make the conversion functions known easily to end users. If there is a better way to proceed, do let me know and I'll update the PR!

**Comment by shlok191** [comment]
@fkiraly, Hello Franz! I have added support for the `PandasDataset` type along with `pd-multiindex`. I hope that the PR is okay, and I'm moving on to the LagLlama work now! :)

**Comment by fkiraly** [comment]
@shlok191, after merging #6530, there are a lot of conflicts with this PR, can you kindly resolve?

**Comment by shlok191** [comment]
@fkiraly, I think the conflicts have been fixed. Thank you for pointing them out!

**Review by fkiraly — APPROVED** [review]
Great, thanks!

**Comment by shlok191** [comment]
@fkiraly, no problem! Thanks a lot for merging it in! :)

**Pull request merged**
