### PR TITLE
[MNT] Add codecov token to coverage uploads

### LINKED ISSUE #5922: [MNT] add codecov token in Github secrets and use in CI
Recently codecov got an update, and after that our CI seems unable to push the coverage reports. This was first noted in #5896.

Ref. https://github.com/sktime/sktime/pull/5891/checks

image

Ref. https://github.com/sktime/sktime/actions/runs/7806282782

image

Ref. https://github.com/sktime/sktime/actions/runs/7806282782/job/21292552170#step:11:34

image

The possible solution is likely to add a token in CI.

Ref. https://about.codecov.io/blog/january-product-update-updating-the-codecov-ci-uploaders-to-the-codecov-cli/

image

### PR DESCRIPTION
**Pull request by yarnabrina**
Closes #5922

### CODE REVIEW

**Comment by yarnabrina** [comment]
I've added the token now, name is `CODECOV_TOKEN`

_Originally posted by @fkiraly in https://github.com/sktime/sktime/issues/5922#issuecomment-1937026258_

Can you please tell where have you added it? Is it in secrets or variables, and whether for the whole repository or for a specific environment?

My changes expect something like this, screenshot being from my personal repository.

image

**Comment by fkiraly** [comment]
as a repo secret:
image

**Comment by fkiraly** [comment]
@yarnabrina, is this working, or not working? How would we check?

**Comment by yarnabrina** [comment]
It is not working as I hoped. The logs are showing token is missing.

However something happened which I can not explain, and it managed to upload few coverage reports.

image

**Comment by yarnabrina** [comment]
#5949 suggests passing token is working, but only if PR is created from a branch in this repository.

Can we take that as an acceptable (though possibly imperfect) solution, as PR's from non-main branches/forks are going to be incomplete anyways?

**Comment by fkiraly** [comment]
> but only if PR is created from a branch in this repository. 

hm, could you make precise the exact condition you have diagnosed? As in, does the condition depend on the branch (name), the source repository, or both?

**Comment by yarnabrina** [comment]
As far as I can see, source repository of the branch from which the PR is created targeting `main`. Now if you/Benedikt/Sagar tried to create a PR from your forks and their token gets shown, my hypothesis and so far collected empirical evidence will be disproved.

**Comment by fkiraly** [comment]
still a bit confused, could you fill in your knowledge please? And please let me know if my categories don't make sense.

CI on PR from `sktime` repo, any branch -> works/doesn't/don't know
CI after merge to `main` of PR from `sktime` repo, branch -> works/doesn't/don't know
CI on PR from fork, branch not `main` -> works/doesn't/don't know
CI on PR from fork, branch is `main` -> works/doesn't/don't know
CI after merge to `main` of PR from fork, branch not `main`-> works/doesn't/don't know
CI after merge to `main` of PR from fork, branch is `main`-> works/doesn't/don't know

**Comment by yarnabrina** [comment]
@fkiraly here are my understandings which has changes from this branch.

- CI in PR targeting `sktime:main`
    - from `<fork>:<branch>` -> works tokenless (verified in #5949)
    - from `sktime:<non-main-branch>` -> works with token (verified in #5950 and other PR's)
- CI after merge of PR targeting `sktime:main` -> should work with token, but can not check unless this PR is merged 
- CI in PR targeting `sktime:<non-main-branch>` -> CI should not be triggered based on current conditions
- CI after merge of PR targeting `sktime:<non-main-branch>` -> CI should not be triggered based on current conditions

Here are definitions of my terms in case of usual naming confusions:

- CI: `test.yml` workflow and its jobs (including other workflows and their jobs that are called recursively)
- `<fork>`: repository in Github outside sktime namespace where `sktime/sktime` is forked
- `<branch>`: name of a branch in `<fork>`
- `sktime:main`: `main` branch in `sktime/sktime`
- `<non-main-branch>`: name of a branch in `sktime/sktime` which is not `main`

---

I am considering that debugging is complete. My suggestion is we merge this PR (#5930) into sktime:main and the two other PR's as well. Then we should trigger `test_all` manually from `Actions` page for triggering all tests and see what all works and what is the actuall code coverage.

**Comment by fkiraly** [comment]
@yarnabrina, apologies, I think there is a misunderstanding and I have not been clear.

The target branch in all of the above is `main` on `sktime`, i.e., `sktime:main`.

The requests are to merge into `sktime:main` any of:

* `sktime:<non-main>`
* `<fork>:main`
* `<fork>:<non-main>`

and there are two run conditions:

* on the PR
* after merge to `sktime:main`

This gives rise to the six conditions by cartesian product.

**Comment by yarnabrina** [comment]
Very sorry, we are going into terminology barrier once again. I don't understand which of the case I have not commented. From my perspective, I make 5 comments and one mentions pre/post merge are same in that, so all 6 are covered.

**Comment by yarnabrina** [comment]
image

Does it help?

**Comment by fkiraly** [comment]
Ah, thanks for clarifying! So you were covering multiple situations with individual lines in your answer, and I was just unsure whether the ambiguity explicitly meant to cover multiple cases (the "merged cells" in your table). So you were not ambiguous, but just meaning to cover multiple cases.

The table explains it clearly - thanks a lot! Apologies for triggering the work to make the table.

**Review by fkiraly — APPROVED** [review]
Let's merge then for testing.

**Comment by yarnabrina** [comment]
@fkiraly please take a look here https://github.com/sktime/sktime/actions/runs/7932291556

All steps completed so far have successful coverage upload without warning, and logs show token was detected successfully.

**Pull request merged**
