### PR TITLE
@ericjb [ENH], [BUG] utils/plotting.py: change plot_series() to use matplotlib conventions; enhance plot_interval()

### PR DESCRIPTION
**Pull request by fkiraly**
By @ericjb, copy of https://github.com/sktime/sktime/pull/6416 after reverting.

1. sktime.utils.plot_series() now handles xticks following matplotlib defaults. (Fixes https://github.com/sktime/sktime/issues/5895) As a result fig,ax objects returned by plot_series() can be used correctly by matplotlib. See accompanying pdf for details including some before and after plot comparisons. (section 3 in the pdf)

2. Fixed (or enhanced) sktime.utils.plot_series() so that it can plot multiple coverage levels if present in the pred_interval multiindex. (section 5 in the pdf)

[PullRequestNotes.pdf](https://github.com/sktime/sktime/files/15298401/PullRequestNotes.pdf)

### CODE REVIEW

**Comment by fkiraly** [comment]
@ericjb, I merged Pr #6416, and it seems it is failing the notebook tests on `main`.

It is a bit odd that we did not notice in the tests previously.

Here is the full traceback, from the notebook `03_transformers.ipynb`, failing CI job is here: https://github.com/sktime/sktime/actions/runs/9289021565/job/25566235977


```
[NbConvertApp] Converting notebook examples/03_transformers.ipynb to notebook
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jupyter_core/application.py", line 283, in launch_instance
    super().launch_instance(argv=argv, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 420, in start
    self.convert_notebooks()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 597, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 563, in convert_single_notebook
    output, resources = self.export_single_notebook(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 487, in export_single_notebook
    output, resources = self.exporter.from_filename(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 201, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 220, in from_file
-> 1473         return func(
   1474             ax,
   1475             *map(sanitize_sequence, args),
   1476             **{k: sanitize_sequence(v) for k, v in kwargs.items()})
   1478     bound = new_sig.bind(ax, *args, **kwargs)
   1479     auto_label = (bound.arguments.get(label_namer)
   1480                   or bound.kwargs.get(label_namer))

File /opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/matplotlib/axes/_axes.py:4901, in Axes.scatter(self, x, y, s, c, marker, cmap, norm, vmin, vmax, alpha, linewidths, edgecolors, plotnonfinite, **kwargs)
   4897         keys_str = ", ".join(f"'{k}'" for k in extra_keys)
   4898         _api.warn_external(
   4899             "No data for colormapping provided via 'c'. "
   4900             f"Parameters {keys_str} will be ignored")
-> 4901 collection._internal_update(kwargs)
   4903 # Classic mode only:
   4904 # ensure there are margins to allow for the
   4905 # finite size of the symbols.  In v2.x, margins
   4906 # are present by default, so we disable this
   4907 # scatter-specific override.
   4908 if mpl.rcParams['_internal.classic_mode']:

File /opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/matplotlib/artist.py:1216, in Artist._internal_update(self, kwargs)
   1209 def _internal_update(self, kwargs):
   1210     """
   1211     Update artist properties without prenormalizing them, but generating
   1212     errors as if calling `set`.
   1213 
   1214     The lack of prenormalization is to maintain backcompatibility.
   1215     """
-> 1216     return self._update_props(
   1217         kwargs, "{cls.__name__}.set() got an unexpected keyword argument "
   1218         "{prop_name!r}")

File /opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/matplotlib/artist.py:1190, in Artist._update_props(self, props, errfmt)
   1188             func = getattr(self, f"set_{k}", None)
   1189             if not callable(func):
-> 1190                 raise AttributeError(
   1191                     errfmt.format(cls=type(self), prop_name=k))
   1192             ret.append(func(v))
   1193 if ret:

AttributeError: PathCollection.set() got an unexpected keyword argument 'markersize'
```

**Comment by ericjb** [comment]
My local environment has matplotlib 3.8.4 and markersize is a valid argument for both plot() and scatter(). What version of matplotlib is being used for the test?

**Comment by fkiraly** [comment]
according to the logs, 3.9.0

**Comment by fkiraly** [comment]
(also, this PR also has code formatting issues 😁 )

**Comment by fkiraly** [comment]
> according to the logs, 3.9.0

Sorry, I also can't explain it - but we should try to resolve the formatting issues and rerun the CI to see what is going on.

**Comment by ericjb** [comment]
I plugged the error message into GitHub Copilot and it said to make the following change in utils.plotting.py:
In the statement
ax.scatter(y.index, y.values, marker=marker, label=label, color=color, markersize=4)

change 'markersize=4' to 's=4'

I will try to make the change myself but I am quite unclear which branch I should be working on after all your changes and how to check it out. I will try. If I don't figure it out quickly you might want to make the change recommended by Copilot.

**Comment by fkiraly** [comment]
superseded by https://github.com/sktime/sktime/pull/6501

**Pull request closed without merging**
