### PR TITLE
&vectornd [ENH] Added Spatio-Temporal DBSCAN

### PR DESCRIPTION
**Pull request by vagechirkov**
#### Reference Issues/PRs
#7054. See also #7106

#### What does this implement/fix? Explain your changes.
Re-implementation of the spatio-temporal DBSCAN algorithm from @eren-ck (see the original implementation [here](https://github.com/eren-ck/st_dbscan))

#### Does your contribution introduce a new dependency? If yes, which one?
No

#### What should a reviewer concentrate their feedback on?
This is a work in progress, here is the list of features:
- [x] Implementation of fitting methods for dense and sparse distance matrices
- [x] Test that the dense and sparse versions of the algorithm produce identical results
- [x] Add a toy example (e.g. spatially moving Gaussian blobs)
- [x] Add the [`fit_frame_split`](https://github.com/eren-ck/st_dbscan/blob/ace025a684edca57fd1fc765e7bda14cd0fb3c6a/src/st_dbscan/st_dbscan.py#L149) method (fit data in batches and then merge cluster labels) 
- [x] Test that the `fit_frame_split` method returns the same results as the default `fit`

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [x] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [x] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [x] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [x] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Comment by fkiraly** [comment]
Hm, it looks like the newly added test `test_st_dbsacan_frame_split` is failing. (also, typo - sacan vs scan?)

**Review by fkiraly — CHANGES_REQUESTED** [review]
LGTM now, interface-wise.

Regarding the logic, in `_fit` you write that the *first column represents time as a float*.

This will not be the case in `sktime` data formats! If you want a time index which is not consecutive integers, you will have to use one of the `pd.DataFrame` based types, e.g., `X_inner_mtype="pd.DataFrame"`. Here, time is stored in the `index`.

**Comment by vagechirkov** [comment]
> Regarding the logic, in `_fit` you write that the _first column represents time as a float_.
> 
> This will not be the case in `sktime` data formats! If you want a time index which is not consecutive integers, you will have to use one of the `pd.DataFrame` based types, e.g., `X_inner_mtype="pd.DataFrame"`. Here, time is stored in the `index`.

Oh, right, I had not thought of that, thanks @fkiraly! I am not quite sure in which category of `scitype` the data format for st-clustering falls. For each time point there is the number of locations in space (each location corresponds to an instance, but the instance column is not needed for clustering). Between time points, the number of instances can differ. 

Here is an example (columns: `time, x, y`):

```
[[1, 5.0, 3.4],
 [1, 2.2, 3.2],
 [1, 0.2, 0.2],
 [2, 1.2, 4.6],
 [2, 2.4, 3.6],
 [3, 2.5, 3.6],
...]
```

**Review by fkiraly — CHANGES_REQUESTED** [review]
Great! I think this is almost done.

One thing, in the internal docstring you say that index level 0 is time, level 1 is object ID.

However, in the `pd-multiindex` specification, it is the other way round:
https://www.sktime.net/en/latest/api_reference/auto_generated/sktime.datatypes._panel._check.PanelPdMultiIndex.html#sktime.datatypes._panel._check.PanelPdMultiIndex

Could you check which way it is assumed in your code?

**Review by fkiraly — APPROVED** [review]
Looks good now. To be merged if tests pass.

**Pull request merged**
