### PR TITLE
[DOC] Fix rendering issues in `ColumnEnsembleForecaster` docstring

### LINKED ISSUE #5200: [DOC] ColumnEnsembleForecaster example not correctly formatted
#### Describe the issue linked to the documentation

The examples in the documentation of the `ColumnEnsembleForecaster` are not well formatted.
[Documentation](https://www.sktime.net/en/v0.17.0/api_reference/auto_generated/sktime.forecasting.compose.ColumnEnsembleForecaster.html)

### PR DESCRIPTION
**Pull request by benHeid**
#### Reference Issues/PRs
Fixes #5200 

#### What does this implement/fix? Explain your changes.
I added the directive `..doctest::` and enabled it by adding `sphinx.ext.doctest`.  Now it seems that the rendering works correctly. 
https://sktime--5201.org.readthedocs.build/en/5201/api_reference/auto_generated/sktime.forecasting.compose.ColumnEnsembleForecaster.html

#### Does your contribution introduce a new dependency? If yes, which one?
No

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Comment by fkiraly** [comment]
FYI, these lines are actually needed as information for `doctest` what to expect as an output. I think (but am not sure) that they are unrelated to the formatting problem. It *could* relate to the formatting issue though. @hazrulakmal has worked on similar issues before.

Re the `ColumnEnsembleForecaster(...)`, it's like in the basic example for doctest:
https://docs.python.org/3/library/doctest.html
where 120 is the expected output for `factorial(6)`.

The `...` is the python ellipsis, it is matched to any string that could appear in the output, e.g., the print of various args and kwargs.

**Comment by fkiraly** [comment]
> [Use explicit ..doctest:: directives](https://github.com/sktime/sktime/pull/5201/commits/33881c57293aa8fb2110d50def2123ee4a397b08)

Interesting! I did not know you could do that!

**Comment by benHeid** [comment]
> > [Use explicit ..doctest:: directives](https://github.com/sktime/sktime/pull/5201/commits/33881c57293aa8fb2110d50def2123ee4a397b08)
> 
> Interesting! I did not know you could do that!

Yes, it is possible if you are using `sphinx.ext.doctest`. I also added this in the conf.py.

**Comment by benHeid** [comment]
I added again the skips to the doctest of the classifier since it fails due to missing soft dependencies. We could add a conditional skipping using https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html#skipping-tests-conditionally

**Comment by fkiraly** [comment]
> We could add a conditional skipping using https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html#skipping-tests-conditionally

That is very useful!
I was looking for sth like this, but didn't find it in `doctest`. I see, you need the `sphinx` extension.

**Comment by benHeid** [comment]
It seems that I looked at the wrong version of the docs. At the latest, it is fixed.

**Comment by benHeid** [comment]
Just realised the Examples of ColumnEnsembleTransformer would be useful. Thus, blocking todo:

* [ ] Remove all stuff that is not related to ColumnEnsembleTransformer doc improvement, since it is not necessary..
# TODOs

**Comment by fkiraly** [comment]
The `ColumnEnsembleTransformer` examples are extremely helpful - I assume you are not implying that we should remove them, but just the remaining things.

I think the nice example also fulfils a request by @MCRE-BE for such an example, see here: https://github.com/sktime/sktime/issues/4983#issuecomment-1672689904

**Review by fkiraly — APPROVED** [review]

**Comment by MCRE-BE** [comment]
thanks for the example !

**Pull request merged**
