### PR TITLE
[MNT] unpin `sphinx` and plugins, with defensive upper bounds

### PR DESCRIPTION
**Pull request by fkiraly**
This PR replaces all the pins from `sphinx` and plugins with defensive upper bounds - next MAJOR release if the package is post-0, next MINOR release if the package is on zero-point.

---

original post: Diagnostic PR to see what happens if we remove all the pins from sphinx and plugins.

### CODE REVIEW

**Comment by yarnabrina** [comment]
Read the docs workflow seems to be working fine, so we can remove pins?

(Assuming other workflows are all independent of `docs` dependency, and hence don't matter.)

**Comment by fkiraly** [comment]
> Assuming other workflows are all independent of `docs` dependency, and hence don't matter.

Afaik this assumption is correct, I just checked the `yml`-s and could not find a `docs` set.

> Read the docs workflow seems to be working fine, so we can remove pins?

Maybe upper bound to next major (or minor if zero-point), for safety?

**Comment by yarnabrina** [comment]
I doubt it'll have changes that'll break `sktime`, but as you said, it makes sense for safety. Let's do in this PR only.

(You can commit with [skip ci] in commit message I think, it'll skip all Github workflows, but read-the-docs one will still run. )

**Comment by fkiraly** [comment]
> You can commit with [skip ci] in commit message I think, it'll skip all Github workflows

Thanks for the reminder and learning moment!

Although in this specific case, I think it's worth to check carefully whether it has any interactions with the other dependencies by a way we don't foresee.

**Review by yarnabrina — APPROVED** [review]
As long as read the docs workflow passes, I'm happy.

One minor non-blocking suggestion: use `sphinx-issues` instead of `sphinx_issues` as hyphen one is the [PyPI name](https://pypi.org/project/sphinx-issues/).

**Comment by fkiraly** [comment]
> One minor non-blocking suggestion: use `sphinx-issues` instead of `sphinx_issues` as hyphen one is the [PyPI name](https://pypi.org/project/sphinx-issues/).
> Similarly, `Sphinx` instead of `sphinx`. I don't think these differences matter though, as `pip` checks only for sanitised versions.

Updated. I did not know that `pip` did some kind of closest name resolution.

I knew it doesn't allow package names which are too close, e.g., only dashes or capitalization away.

**Review by yarnabrina — APPROVED** [review]

**Pull request merged**
