### PR TITLE
[ENH] "typical length" constant in transformer scenarios

### PR DESCRIPTION
**Pull request by fkiraly**
update: the PR no longer makes the example series longer. It only adds the "typical length" constant which can be used to change length of all examples, but does not change the length.

---

This extends the length of time series in the base interface compliance tests for `sktime` transformers.

It also exposes the "typical length" of the time series as a config parameter in the transformer scenarios file.

Should help with this PR: https://github.com/sktime/sktime/issues/3712

### CODE REVIEW

**Comment by fkiraly** [comment]
@chillerobscuro, is this still needed for the `tsfeatures` trafo, or have you found a workaround?

**Comment by chillerobscuro** [comment]
> @chillerobscuro, is this still needed for the `tsfeatures` trafo, or have you found a workaround?

The author of the repo put in a [fix](https://github.com/sktime/sktime/issues/3712#issuecomment-1354037097) in the new version, so this change is not necessary for me, as long as anything using `tsfeatures` is `>=0.4.0`.

**Comment by fkiraly** [comment]
Ok, so I'll close this, and you ensure to have a lower version bound in the soft dependency then?

**Comment by chillerobscuro** [comment]
> Ok, so I'll close this

That works for me

> and you ensure to have a lower version bound in the soft dependency then?

In `pyproject.toml` I have `"tsfeatures>=0.4.0"`, since as we discussed `_check_soft_dependencies` doesn't support versions.

**Comment by fkiraly** [comment]
> since as we discussed `_check_soft_dependencies` doesn't support versions.

The newest version of `_check_soft_dependencies` now does!

**Comment by fkiraly** [comment]
actually, I think it still makes sense to merge this since it exposes the length in all the scenarios as a parameter that is easy to change. I'll simply change it to 10 (what it currently is) instead of 14 (the longer version).

**Pull request merged**
