### PR TITLE
[MNT] Update pre commit hooks post dropping python 3.8 support

### PR DESCRIPTION
**Pull request by yarnabrina**
Depends on #6330

### CODE REVIEW

**Comment by yarnabrina** [comment]
@fkiraly shall we skip #6330 and #6331 from this release, and merge post this? We need not wait till next release though.

Without some code changes in `skbase`, this seems very difficult to be able to fix this and will be difficult to fix quickly with a release deadline.

**Comment by fkiraly** [comment]
> Without some code changes in `skbase`, this seems very difficult to be able to fix this and will be difficult to fix quickly with a release deadline.

I am of course happy to make changes, the main question we need to answer: *will this PR, if merged, together with `skbase 0.7.8`, cause user exceptions in `all_estimators`*?

**Comment by yarnabrina** [comment]
Not tested with `0.7.8`, but fails locally with `0.8.0` conditionally (haven't determined the exact condition, mostly presence of base early classifier and base deep network is noticed).

**Comment by yarnabrina** [comment]
@fkiraly similar request as #6330 - if you add more commit, please recreate your local branch as commit history is changed with rebasing.

**Comment by yarnabrina** [comment]
@fkiraly / @benHeid : similar comment to #6330, all failure seem to be from timeout so it's likely this PR changes are not introducing any new issues. Given that most changes are from `black` adding new lines (other than pyupgrade changes coming from the dependency of #6330), it seems safe to merge currently to me.

**Comment by fkiraly** [comment]
for 0.31.0

**Comment by yarnabrina** [comment]
@fkiraly after you updated the branch with `main` and prophet changes, the PR was failing in CI due to code quality issues. I rebased from main and fixed the issues and force pushed. This branch is now up to date with `main`, including #6721 and #6729 .

If you wish to update this PR, requesting to delete your existing local branch first. I think it has few old attempted changes (change from `typing.Callable` to `collections.abc.Callable`) which were causing serious problems earlier (even before `abc` issues). These will probably be better addressed by @fnhirwa's `ruff` PR.

**Pull request merged**
