### PR TITLE
[ENH] `TimeSeriesForestClassifier` feature importance and optimized interval generation

### PR DESCRIPTION
**Pull request by YHallouard**
Enable to force interval to not overlap between different columns after a ColumnContatenator.

#### What does this implement/fix? Explain your changes.

Full explanation can be found: 
- [Sktime — Feature Importance on TimeSeriesForestClassifier](https://medium.com/totalenergies-digital-factory/sktime-feature-importance-on-timeseriesforestclassifier-7cbf3d44e939)
- [Sktime — TimeSeriesForestClassifier Improving features comprehension](https://medium.com/p/f7ecd9ae39c6)

The main changes are: 
- Adding feature importances to TimeseriesForestClassifier
- Change _get_interval to force intervals to be contained in columns of previous ColumnsConcatenator (In multivariate case)

#### What should a reviewer concentrate their feedback on?

I think that the major changes are in _get_intervals, the changes in feature_importances were already implemented before I think are at least they were in draw.

##### For all contributions
- [X] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [X] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks, this is very nice!

* could you add a reference in the docstring to - preferably - the original source of the feature importance  generation?
* if you are changing the `_get_intervals` function, could you add a docstring, given that you seem to know what the arguments do?
* I did not notive there was some duplication between `tsf` in the `series_as_features` module and the one in the classificaiton module. Can you explain the difference? I feel the latter should also be in the classification module, no?

**Comment by YHallouard** [comment]
> Thanks, this is very nice!
> 
> * could you add a reference in the docstring to - preferably - the original source of the feature importance  generation?
> * if you are changing the `_get_intervals` function, could you add a docstring, given that you seem to know what the arguments do?
> * I did not notive there was some duplication between `tsf` in the `series_as_features` module and the one in the classificaiton module. Can you explain the difference? I feel the latter should also be in the classification module, no?

Hi @fkiraly, thank you for your review :)

- (ON HOLD)  I added it to the docstring you're right - Maybe there is an optim to avoid duplication (even if it is not implemented the same way)
- (ON HOLD) I added some documentation in docstring
- I think that tsf in series_as_feature is a Base (BaseTimeSeriesForest) for TimeSeriesForestRegressor and TimeSeriesForestClassifier. 
image
But you're right, I found a duplication of that base in sktime.series_as_features.base.estimators._ensemble.py -> BaseTimeSeriesForest(BaseForest) and this class is implementing the feature_importances_
It seems that RandomIntervalFeatureExtractor use RandomIntervalSegmenter to extract intervals the same way that I wanted to do. So I think that the TimeSeriesForestRegressor and TimeSeriesForestClassifier used with ColumnConcatenator are deprecated no ?

**Comment by YHallouard** [comment]
If I go to the end of this PR it will implement some features to maintain [TimeSeriesForestRegressor](https://github.com/sktime/sktime/blob/0f477b0a10fa7bc51848f7f3b21a9a874b495fca/sktime/regression/interval_based/_tsf.py#L18) and [TimeSeriesForestClassifier](https://github.com/sktime/sktime/blob/0f477b0a10fa7bc51848f7f3b21a9a874b495fca/sktime/classification/interval_based/_tsf.py#L21) but I don't know if it is really useful with the thing I mentioned above. You tell me :)

**Comment by fkiraly** [comment]
RIFE and RISE are transformers, not classifiers - as you say this may be redundant though. I still think we should maintain the classifier/regressors for now, as they are reference implementations used in historical benchmarks, and they are not transformers.

Long-term though, we may want to move content from `series_as_features` to other modules. Do you have a good suggestion?

**Comment by YHallouard** [comment]
> RIFE and RISE are transformers, not classifiers - as you say this may be redundant though. I still think we should maintain the classifier/regressors for now, as they are reference implementations used in historical benchmarks, and they are not transformers.
> 
> Long-term though, we may want to move content from `series_as_features` to other modules. Do you have a good suggestion?

Hello @fkiraly,

I implemented the change you required :) 

> Long-term though, we may want to move content from series_as_features to other modules. Do you have a good suggestion?
I think that we can imagine that ether: 
- TimeSeriesForestClassifier no longer creates its own feature space (because currently it transforms X in the fit) and use [RandomIntervalFeatureExtractor](https://github.com/sktime/sktime/blob/0f477b0a10fa7bc51848f7f3b21a9a874b495fca/sktime/transformations/panel/summarize/_extract.py#L161) in a pipeline before
- Convert the [BaseTimeSeriesForest(BaseForest)](https://github.com/sktime/sktime/blob/main/sktime/series_as_features/base/estimators/_ensemble.py#L74) to support multivariate time series and heritate from it (as ComposableTimeSeriesForestClassifier) if TimeSeriesForestClassifier

I can try it in an other PR

**Comment by YHallouard** [comment]
Hi @fkiraly how are you ?  

Is it good for you or is there any new requirements ? Feel free to ask :)

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks a lot!

I would be happy with this in-principle.

Blocking:

* the docstring of the class(es) should describe the `inner_series_length` parameter
* the docstring of the class(es) should describe the feature importance method

Non-blocking:

* the two classes, in `classification` and in `series_as_features`, look very similar. As you have looked at them, what do you think how similar they are? I would like to hear your impression.
* If they are very similar, we should refactor and aim to remove or reduce the footprint of the one in `series_as_features`, although that can be done in a separate PR. We should avoid copy-paste and duplications.

**Comment by fkiraly** [comment]
@YHallouard, are you still working on this?

Great contribution, just minimal remaining work to do.

**Comment by YHallouard** [comment]
> * docstring of the class(es) should describe the `inner_series_length` parameter
> * the docstring of the class(es) should describe the feature importance method

Hi @fkiraly !

Yes sorry, i'm still working on it, I've been quite busy this week, I will work on the blocking points the weekend ;) 
And create a new PR for the non blocking points

Have a good day

**Comment by YHallouard** [comment]
Hi @fkiraly 

I added the docstrings for inner_series_length and feature importance :)

**Review by fkiraly — APPROVED** [review]
Thanks!

I'll merge this now for the release, what would be nice if you could help in another PR with de-duplicating the TSF in `classification` and `series_as_features`, given that you have now looked into both in detail.

I have added more explanation in this issue: https://github.com/sktime/sktime/issues/5520

**Pull request merged**
