### PR TITLE
[BUG] TinyTimeMixerForecaster: fix truncating index and update test_params

### PR DESCRIPTION
**Pull request by geetu040**
**Fix Truncating Index**
from `data[:, :seq_len, :]` -> to `data[:, -seq_len:, :]`
use the latest history instead

**Update Test Params**
set `report_to="none"` for `training_args` - as it may use `W&B Integration` which requires token verification - blocking the tests.
Although this has not happened before and till now the test cases run without any restriction but for some specific environments it may block the tests, as it did today on my system unexpectedly.
So using `report_to="none"` ensures safety from future bugs

### CODE REVIEW

**Review by fkiraly — APPROVED** [review]
lgtm.

not blocking since out of scope, but there should be a second set of test params, too, no?

**Comment by geetu040** [comment]
> not blocking since out of scope, but there should be a second set of test params, too, no?

there is already a second set that tests broadcasting. Apart from that I don't think any other test set is needed that would add more logical coverage

**Comment by geetu040** [comment]
- added another test set that does not add coverage but tests the default config
- reduced the train parameter size for efficient testing as macOS worker may get crashed as in [workflows](https://github.com/sktime/sktime/actions/runs/10374995002/job/28723798247)

**Comment by fkiraly** [comment]
tests seem to be failing - is that caused by this PR?

**Comment by geetu040** [comment]
> tests seem to be failing - is that caused by this PR?

yes it the PR but I am not really sure about the cause
- one failure is because of timeout after 5 hours - not mentioning any estimator
- second failure is also because of crashing job after 5 hours and this points out to the `train` function of `TinyTimeMixer` during the test `TestAllForecasters.test_predict_interval` - which should have raised exception instead as `"capability:pred_int": False` for `TinyTimeMixer`

I see there are some changes in `test_all_forecasters.py`, so I'll sync with the main branch and see if it continues.
There has been no change in the logical however since the last successful runs.

**Comment by geetu040** [comment]
Again the tests are failing, with the same logs https://github.com/sktime/sktime/pull/6965#issuecomment-2290926139.
If there is a genuine issue with this model on macos, these tests must have been skipped on previous workflows since I didnot make any change in the code that would really increase the resource demand.

**Comment by fkiraly** [comment]
feels like genuine failures, potentially caused by changes in this PR. It is strange though that they are only on macs.

**Pull request merged**
