### PR TITLE
[DOC] Test GH workflow that automatically updates `CONTRIBUTORS.md`

### PR DESCRIPTION
**Pull request by achieveordie**
#### Reference Issues/PRs

Reference #4103

#### What does this implement/fix? Explain your changes.

I'm simply updating `.all-contributorsrc` for those contributors who have done more work than the current file suggests. I have taken permission to add these labels against their names. This serves as a purpose to check whether the GH workflow is working as we expect.

#### Does your contribution introduce a new dependency? If yes, which one?

None

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by achieveordie** [comment]
One can visit the relevant logs [here](https://github.com/achieveordie/sktime/actions/workflows/update_contributors.yml).

**Comment by achieveordie** [comment]
The workflow is not being triggered since currently it is only expected to run when changes are detected on `<fork>/main` wherever I've pushed a commit on `achieveordie/test_contributors_workflow`.

Optionally, it is also required that workflow is enabled on the fork. I believe this needs to be mentioned somewhere in the dev setup. I'll make another PR to bring these two changes, merge it to sktime/main and then merge sktime/main into this PR and then resume testing.

**Comment by fkiraly** [comment]
thanks - seems very fiddly.

In the end state, how would it impact someone making a PR?

**Comment by achieveordie** [comment]
> how would it impact someone making a PR?

It's seamless. If they have their workflow enabled on the fork then this workflow can run otherwise they can simply edit `.all-contributorsrc` and leave it at that. Next time someone with their workflow-enabled edits it, all the previous changes will be committed.

I believe it will 'fail' during merge-commits to sktime/main but since that is not a required checker it won't block anything.

**Comment by fkiraly** [comment]
FYI, https://github.com/sktime/sktime/pull/4323 is merged now

**Comment by fkiraly** [comment]
this works now, so the testing PR is no longer needed.

**Pull request closed without merging**
