### PR TITLE
[ENH] nnetsauce MTS

### PR DESCRIPTION
**Pull request by thierrymoudiki**
##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Comment by thierrymoudiki** [comment]
@fkiraly `1 workflow awaiting approval` again

**Comment by fkiraly** [comment]
pressed the button, CI runs now

**Comment by thierrymoudiki** [comment]
> pressed the button, CI runs now

Well... This needs approval after e.v.e.r.y push... 

`code-quality` is failing; only added 3-4 lines.

**Comment by fkiraly** [comment]
> Well... This needs approval after e.v.e.r.y push...

Only on your first pull request, I think.

You can avoid failing the code quality repeatedly and the waiting times by setting up local precommits:
https://www.sktime.net/en/latest/developer_guide/coding_standards.html#setting-up-local-code-quality-checks

(although I'm not sure if this covers everything)

**Comment by thierrymoudiki** [comment]
@fkiraly Or maybe (I'm stuck right now) run the tests **locally** in a virtual environment? How can I achieve that, please?

**Comment by fkiraly** [comment]
> @fkiraly Or maybe (I'm stuck right now) run the tests **locally** in a virtual environment? How can I achieve that, please?

You can use the `check_estimator` utility locally, see developer manual here:
https://www.sktime.net/en/latest/developer_guide/add_estimators.html#how-to-test-interface-conformance

Let us know if you need any help, on discord!

**Comment by thierrymoudiki** [comment]
Hi @fkiraly, @felipeangelimvieira 

Here's what I was able to do: https://github.com/thierrymoudiki/sktime/blob/nnetsauce-mts/examples/nnetsauce/2024-09-22-nnetsauce-MTS-example.ipynb

Please, I'd need your expertise to fix these points (see notebook):
- why specifying `fh` in `_fit` is necessary even though it's declared as `None`?
- In `_predict`, I can produce a named tuple (of data frames) for probabilistic forecasting, or a data frame. Seems like I'd have an issue with this here

**Comment by fkiraly** [comment]
> why specifying `fh` in `_fit` is necessary even though it's declared as `None`?

The `None` is just the default. The convention is that `fh` appears either in `_fit`, or in `_predict`, depending on whether the tag `requires-fh-in-fit` is True or False. You should decide whether the user must already pass the `fh` in `fit` or whether it is ok to pass it only in `predict`.

> In `_predict`, I can produce a named tuple (of data frames) for probabilistic forecasting, or a data frame. Seems like I'd have an issue with this here

If your estimator can do probabilistic forecasting, the right place to return these forecasts is not `_predict`, but `_predict_interval` or `_predict_quantiles` (you only need to implemen tone of the two).

Have a look at the `forecasting` extension template, which has blanks to fill in for proba forecasting.

Let us know if we can help with anything else, and feel free to use the discord dev-chat!

**Comment by thierrymoudiki** [comment]
Thanks @fkiraly. About 'Have a look at the forecasting extension template, which has blanks to fill in for proba forecasting.' Is it a different template from what I've been using? Any link?

Sure. We'll use the chat for the final adjustments

**Comment by thierrymoudiki** [comment]
Thanks @fkiraly.

**Comment by fkiraly** [comment]
> Thanks @fkiraly. About 'Have a look at the forecasting extension template, which has blanks to fill in for proba forecasting.' Is that a different template from the one I've been using? Any link?

This one: https://github.com/sktime/sktime/blob/main/extension_templates/forecasting.py

**Comment by thierrymoudiki** [comment]
@fkiraly Nailed it 🎉 

https://github.com/thierrymoudiki/sktime/blob/nnetsauce-mts/examples/nnetsauce/2024-09-22-nnetsauce-MTS-example.ipynb

Let's discuss the next steps on Discord then.

**Review by yarnabrina — CHANGES_REQUESTED** [review]
Hi @thierrymoudiki , thanks for your contribution. It seems your branch on your fork is quite diverged from our main branch, and hence conflicts are happening. Can you please fix the issue with merge or rebase from your end?

Also, the number of files being modified is too high. I'm not sure if changing in existing estimators (of multiple types) or notebooks are required to add your contribution, so please take a look at the changes again and minimise what is necessary.

Two specific observations is that how you're modifying dependencies and Makefile. Unless there is a very good reason, I don't think you will need to modify Makefile at all, and your changes look relevant for local testing only. Please consider to revert those. Regarding dependencies, we try to keep a minimal core dependency set, and hence do not add dependencies for specific estimators as part of core dependencies, those go as part of optional extras. For the same reason, kindly remove the new addition from dependencies section, and please refrain from doing a direct import at the module level unprotected by a check of presence of the package.

**Comment by fkiraly** [comment]
> Can you please fix the issue with merge or rebase from your end?

Maybe it is better to avoid rebase as it has the tendency to make small issues much worse, quite easily by accident...

I see a conflict only in `window_splitters.ipynb`, perhaps we can just copy over the file from the `main` branch, and then update from `main`?

**Comment by thierrymoudiki** [comment]
@yarnabrina @fkiraly created #7160 to fix

**Comment by yarnabrina** [comment]
Closing this in favour of #7160

**Pull request closed without merging**
