### PR TITLE
&yarnabrina [ENH] Add an explicit context manager during estimator dump

### PR DESCRIPTION
**Pull request by achieveordie**
@yarnabrina and @fkiraly  caught a possible memory leak in the saving method of our base object. I'm adding a context manager to explicitly close files that may or may not be closed by the garbage collector.

@fkiraly also suspects that this could be the culprit behind the memouts that DL estimators were suffering from. To test this, I'm temporarily skipping all excepted DL estimators.

### CODE REVIEW

**Comment by achieveordie** [comment]
The first check has passed, rerunning it a couple more times.

**Comment by achieveordie** [comment]
`MemoryError` in the fifth run is as follows (Windows, 3.9):
```
INTERNALERROR> def worker_internal_error(self, node, formatted_error):
INTERNALERROR>         """
INTERNALERROR>         pytest_internalerror() was called on the worker.
INTERNALERROR>     
INTERNALERROR>         pytest_internalerror() arguments are an excinfo and an excrepr, which can't
INTERNALERROR>         be serialized, so we go with a poor man's solution of raising an exception
INTERNALERROR>         here ourselves using the formatted message.
INTERNALERROR>         """
INTERNALERROR>         self._active_nodes.remove(node)
INTERNALERROR>         try:
INTERNALERROR> >           assert False, formatted_error
INTERNALERROR> E           AssertionError: Traceback (most recent call last):
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\_pytest\main.py", line 270, in wrap_session
INTERNALERROR> E                 session.exitstatus = doit(config, session) or 0
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\_pytest\main.py", line 324, in _main
INTERNALERROR> E                 config.hook.pytest_runtestloop(session=session)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\pluggy\_hooks.py", line 433, in __call__
INTERNALERROR> E                 return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\pluggy\_manager.py", line 112, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\pluggy\_callers.py", line 155, in _multicall
INTERNALERROR> E                 return outcome.get_result()
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\pluggy\_result.py", line 108, in get_result
INTERNALERROR> E                 raise exc.with_traceback(exc.__traceback__)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\pluggy\_callers.py", line 80, in _multicall
INTERNALERROR> E                 res = hook_impl.function(*args)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\xdist\remote.py", line 157, in pytest_runtestloop
INTERNALERROR> E                 self.run_one_test()
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\xdist\remote.py", line 174, in run_one_test
INTERNALERROR> E                 self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\pluggy\_hooks.py", line 433, in __call__
INTERNALERROR> E                 return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\pluggy\_manager.py", line 112, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\pluggy\_callers.py", line 155, in _multicall
INTERNALERROR> E                 return outcome.get_result()
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\pluggy\_result.py", line 108, in get_result
INTERNALERROR> E                 raise exc.with_traceback(exc.__traceback__)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\pluggy\_callers.py", line 80, in _multicall
INTERNALERROR> E                 res = hook_impl.function(*args)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\_pytest\runner.py", line 114, in pytest_runtest_protocol
INTERNALERROR> E                 runtestprotocol(item, nextitem=nextitem)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\_pytest\runner.py", line 133, in runtestprotocol
INTERNALERROR> E                 reports.append(call_and_report(item, "call", log))
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\_pytest\runner.py", line 224, in call_and_report
INTERNALERROR> E                 report: TestReport = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\pluggy\_hooks.py", line 433, in __call__
INTERNALERROR> E                 return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\pluggy\_manager.py", line 112, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\pluggy\_callers.py", line 133, in _multicall
INTERNALERROR> E                 teardown[0].send(outcome)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\_pytest\skipping.py", line 266, in pytest_runtest_makereport
INTERNALERROR> E                 rep = outcome.get_result()
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\pluggy\_result.py", line 108, in get_result
INTERNALERROR> E                 raise exc.with_traceback(exc.__traceback__)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\pluggy\_callers.py", line 80, in _multicall
INTERNALERROR> E                 res = hook_impl.function(*args)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\_pytest\runner.py", line 368, in pytest_runtest_makereport
INTERNALERROR> E                 return TestReport.from_item_and_call(item, call)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\_pytest\reports.py", line 362, in from_item_and_call
INTERNALERROR> E                 longrepr = item.repr_failure(excinfo)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\_pytest\python.py", line 1829, in repr_failure
INTERNALERROR> E                 return self._repr_failure_py(excinfo, style=style)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\_pytest\nodes.py", line 485, in _repr_failure_py
INTERNALERROR> E                 return excinfo.getrepr(
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\_pytest\_code\code.py", line 701, in getrepr
INTERNALERROR> E                 return fmt.repr_excinfo(self)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\_pytest\_code\code.py", line 989, in repr_excinfo
INTERNALERROR> E                 reprtraceback = self.repr_traceback(excinfo_)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\_pytest\_code\code.py", line 913, in repr_traceback
INTERNALERROR> E                 entries = [
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\_pytest\_code\code.py", line 914, in <listcomp>
INTERNALERROR> E                 self.repr_traceback_entry(entry, excinfo if last == entry else None)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\_pytest\_code\code.py", line 852, in repr_traceback_entry
INTERNALERROR> E                 source = self._getentrysource(entry)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\_pytest\_code\code.py", line 754, in _getentrysource
INTERNALERROR> E                 source = entry.getsource(self.astcache)
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\_pytest\_code\code.py", line 262, in getsource
INTERNALERROR> E                 astnode, _, end = getstatementrange_ast(
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\site-packages\_pytest\_code\source.py", line 185, in getstatementrange_ast
INTERNALERROR> E                 astnode = ast.parse(content, "source", "exec")
INTERNALERROR> E               File "C:\Miniconda\envs\test\lib\ast.py", line 50, in parse
INTERNALERROR> E                 return compile(source, filename, mode, flags,
INTERNALERROR> E             MemoryError
INTERNALERROR> E           assert False
INTERNALERROR> 
INTERNALERROR> C:\Miniconda\envs\test\lib\site-packages\xdist\dsession.py:197: AssertionError
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Miniconda\envs\test\lib\site-packages\execnet\gateway_base.py", line 1079, in _send
INTERNALERROR>     message.to_io(self._io)
INTERNALERROR>   File "C:\Miniconda\envs\test\lib\site-packages\execnet\gateway_base.py", line 518, in to_io
INTERNALERROR>     io.write(header + self.data)
INTERNALERROR>   File "C:\Miniconda\envs\test\lib\site-packages\execnet\gateway_base.py", line 483, in write
INTERNALERROR>     self._write(data)
INTERNALERROR> BrokenPipeError: [Errno 32] Broken pipe
INTERNALERROR> 
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Miniconda\envs\test\lib\site-packages\_pytest\main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "C:\Miniconda\envs\test\lib\site-packages\_pytest\main.py", line 324, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "C:\Miniconda\envs\test\lib\site-packages\pluggy\_hooks.py", line 433, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>   File "C:\Miniconda\envs\test\lib\site-packages\pluggy\_manager.py", line 112, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "C:\Miniconda\envs\test\lib\site-packages\pluggy\_callers.py", line 133, in _multicall
INTERNALERROR>     teardown[0].send(outcome)
INTERNALERROR>   File "C:\Miniconda\envs\test\lib\site-packages\pluggy\_result.py", line 108, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "C:\Miniconda\envs\test\lib\site-packages\pluggy\_callers.py", line 80, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Miniconda\envs\test\lib\site-packages\xdist\dsession.py", line 122, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "C:\Miniconda\envs\test\lib\site-packages\xdist\dsession.py", line 145, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "C:\Miniconda\envs\test\lib\site-packages\xdist\dsession.py", line 183, in worker_workerfinished
INTERNALERROR>     crashitem = self.sched.remove_node(node)
INTERNALERROR>   File "C:\Miniconda\envs\test\lib\site-packages\xdist\scheduler\load.py", line 218, in remove_node
INTERNALERROR>     self.check_schedule(node)
INTERNALERROR>   File "C:\Miniconda\envs\test\lib\site-packages\xdist\scheduler\load.py", line 191, in check_schedule
INTERNALERROR>     self._send_tests(node, min(num_send, maxschedchunk))
INTERNALERROR>   File "C:\Miniconda\envs\test\lib\site-packages\xdist\scheduler\load.py", line 290, in _send_tests
INTERNALERROR>     node.send_runtest_some(tests_per_node)
INTERNALERROR>   File "C:\Miniconda\envs\test\lib\site-packages\xdist\workermanage.py", line 298, in send_runtest_some
INTERNALERROR>     self.sendcommand("runtests", indices=indices)
INTERNALERROR>   File "C:\Miniconda\envs\test\lib\site-packages\xdist\workermanage.py", line 317, in sendcommand
INTERNALERROR>     self.channel.send((name, kwargs))
INTERNALERROR>   File "C:\Miniconda\envs\test\lib\site-packages\execnet\gateway_base.py", line 811, in send
INTERNALERROR>     self.gateway._send(Message.CHANNEL_DATA, self.id, dumps_internal(item))
INTERNALERROR>   File "C:\Miniconda\envs\test\lib\site-packages\execnet\gateway_base.py", line 1085, in _send
INTERNALERROR>     raise OSError("cannot send (already closed?)")
INTERNALERROR> OSError: cannot send (already closed?)
```

**Comment by fkiraly** [comment]
seems like one of the sporadic deep learning related errors?

**Comment by achieveordie** [comment]
> seems like one of the sporadic deep learning related errors?

It is, I was testing whether the issue with memouts was resolved now that we've added an explicit context manager but that doesn't seem to be the case. In any case, this is a much-needed change which needs to be added.

**Review by fkiraly — APPROVED** [review]
Agree - thanks for fixing.

**Pull request merged**
