### PR TITLE
[DOC]  Added example for lstmfcn and  mlp  # 4264

### PR DESCRIPTION
**Pull request by vandit98**
#### What does this implement/fix? Explain your changes.

Added examples to docstrings in sktime.regression.deep_learning module for rnn.py, lstmfcn.py and mlp.py. Along with it i have chages a parameter name from lr to learning_rate since lr was throwing an error whose image is attached below. 
Screenshot from 2024-03-16 14-41-33

#### Does your contribution introduce a new dependency? If yes, which one?

No

#### Did you add any tests for the change?
No

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks! Nice fix as well!

May I ask a few questions:

* could you kindly split the docs and the fix in two? I think we need to discuss more regarding the fix
* what concerns me is that that the tests did not catch this. The reason is, actually, that the estimator is entirely skipped. So, in the new PR, could you:
    * remove the regerssor from `tests._config`, from the exception list
    * the same problem probably exists for the classifier - so would be great if you re-enable the tests there too, and check whether the same fix is needed.

**Comment by vandit98** [comment]
Thanks, @fkiraly  for the comment. I will make the suggested changes.

**Comment by vandit98** [comment]
Hi @fkiraly 
i will create a new pr for the fix. Please review this pr.

**Review by fkiraly — APPROVED** [review]
Thx!

**Pull request merged**
