### PR TITLE
[BUG] fix pmdarima interfaces breaking for `X` containing more indices than forecasting horizon

### PR DESCRIPTION
**Pull request by fkiraly**
Fixes https://github.com/sktime/sktime/issues/3657.

The bug was caused by `pmdarima` models breaking when the `X` passed was strictly larger than the indices in the forecasting horizon.

The example code in #3657 has been added as a test (with minor generalization to cover more estimators).

In the future, we should probably also add test scenarios where `X` is strictly larger than the forecasting horizon.

Depends on:
* https://github.com/sktime/sktime/pull/4474, which fixes a bug that was masked by #3657
* https://github.com/sktime/sktime/pull/4483 for slicing `X`

### CODE REVIEW

**Comment by fkiraly** [comment]
strange: this test fails under 3.10 but not under 3.8

```python
from sktime.forecasting.compose import TransformedTargetForecaster
from sktime.utils.estimator_checks import check_estimator

check_estimator(TransformedTargetForecaster, fixtures_to_run="test_predict_time_index_with_X[TransformedTargetForecaster-1-y:2cols-fh=1-range-int-True]", return_exceptions=False)
```

**Comment by fkiraly** [comment]
this seems to be related to `statsmodels`, not sure what is happening there.

Reverting the change to the `statsmodels` adapter and moving to separate issue for investigation.

**Comment by SzymonStolarski** [comment]
Hi @fkiraly,

It's been quite some time since this has been created, however I was wondering if it would be possible to go back to this PR and check the issue with the tests in order to fix #3657?

I've been also playing around with the change in the `pmdarima` adapter proposed in this PR and it looks like the `evaluate` funtion works fine. One thing, however, that I noticed is the fact that this change loses the possibility of quickly passing `X` assumptions without `PeriodIndex` in `predict`, e.g.:

```python3
y = load_airline()
X = pd.DataFrame({
    'exo_1': y*5,
})

forecaster = ARIMA()
forecaster.fit(y=y, X=X) # Here we are passing data the standard way with `PeriodIndex`

# Here we would like to check the predictions passing quickly exo assumptions
forecaster.predict(fh=[1,2,3], X=pd.Series([123, 213, 321]) 
```

Will throw an error `KeyError: "None of [PeriodIndex(['1961-01', '1961-02', '1961-03'], dtype='period[M]')] are in the [index]"`. 

I assume predict would need to check if data passed in `X` contains `PeriodIndex` and based on that decide if:
```python3
# PeriodIndex case
fh_abs = fh.to_absolute(self.cutoff).to_pandas()
if X is not None:
    X = X.loc[fh_abs]
```
or
```python3
# No PeriodIndex case
fh_idx = fh.to_indexer(self.cutoff)
if X is not None:
    X = X.loc[fh_idx]
```

**Comment by fkiraly** [comment]
> I assume predict would need to check

That might be a fix?
Apologies, @SzymonStolarski, for not working on this - the "obvious" fix didn't work and failures were python version dependent.

Maybe we should have a look how this behaves after the `pandas 2` compatibility upgrade.

Also FYI @yarnabrina, who has recently been working on the `_StatsModelsAdapter`, perhaps he can spot sth. Return objects are highly idiosyncratic and not subject to a unified interface in `statsmodels` (or `pmdarima` which depends heavily on `statodels`).

**Pull request merged**
