### PR TITLE
DIAGNOSTIC - testing `pyproject.toml` based diff testing

### PR DESCRIPTION
**Pull request by fkiraly**
Diagostic test PR for https://github.com/sktime/sktime/pull/5727

Changes a line in `pyproject.toml` for `tbats` dependency, and intentionally breaks one of two forecasters having that dependency.

If everything works, the old tests should pick that up.

### CODE REVIEW

**Comment by yarnabrina** [comment]
Question: is it the correct understanding what you expect #5727 to do?

1. developer edits one or more lines with package specification in `pyproject.toml`
2. you extract package name from that line (I need to understand those conditions, but I think you're extracting `tensorflow` from `'tensorflow<=2.14,>=2; python_version < "3.12"'`)
3. if that name is specified in `python_dependencies` tag for an estimator, that must be tested even if that (and its entire hierarchy) is unmodified

If that is the case, changing `tbats` line in `pyproject.toml` should trigger testing for `TBATS` and `BATS`, even without a change in those estimators. But that is modified, is there a way to know it got triggered by which of the change?

Shouldn't we test either without modifying any non-pyproject file, or in case that doesn't trigger testing of forecasting component, by changing a different module and see if BATS/TBATS is tested or not? We can enable verbose flag in `pytest` to print what all tests are run.

**Comment by fkiraly** [comment]
> is it the correct understanding what you expect https://github.com/sktime/sktime/pull/5727 to do?

Yes, indeed.

> But that is modified, is there a way to know it got triggered by which of the change?

You are right, this is not strong enough of a test, as it does not allow to differetiate.

I now moved the exception to a test, conditional on `BATS` being tested.

**Comment by fkiraly** [comment]
Hm, I notice that also does not work, because it triggers condition 3...

**Comment by yarnabrina** [comment]
Why is the CI not running for more than 19 hours? I don't even see new CI jobs, and old jobs are queued. Any idea @fkiraly ?

**Comment by fkiraly** [comment]
> Why is the CI not running for more than 19 hours?

This is the update-contributors job. If it runs, it will be linked to the GUI table, and it looks like the CI is not running, but it actually is.

**Comment by fkiraly** [comment]
Hm, seems like it does *not* work, tests pass but should not

**Comment by fkiraly** [comment]
Works as expected now - `TBATS` and `BATS` are tested, and the failure is captured

**Comment by fkiraly** [comment]
PR has served its purpose of testing

**Pull request closed without merging**
