### PR TITLE
[ENH] Optimising `fit` method of `FinancialHolidaysTransformer`

### PR DESCRIPTION
**Pull request by sharma-kshitij-ks**
This commit streamlines the process by avoiding redundant data fetching and processing during fitting, enhancing the performance of the estimator by preloading the holidays data during initialization, making the fit method a no-op and improving overall efficiency.

With this modification, calling fit becomes efficient because the holidays data is preloaded and doesn't need to be fetched or processed during the fitting phase.

Also, to introduce at least two test parameter sets, i've another parameter set that covers substantially different settings compared to the default parameters. Here are the two distinct parameter sets:

(Default):
Market: "XNYS" 
Parameter Set 2:
Market: "XLON"

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks!

The general design of sklearn-like libraries is that the specification syntax, i.e., creation of an object, should cost minimal time and memory. So, `__init__` should have at most things like parameter handling, checking, etc. Bottlenecks (memory and computational) should be localized to `fit`, `update`, and similar methods.

For this reason, I do not think it is a good idea to preload the data in `__init__`. Storing it in `self` also increases the memory footprint of the estimator for no benefit I can see (while the current implementation does not do that).

Could you kindly explain your reasoning for proposing this, I might be missing something.

You could also add more test parameter sets to cover the existing parameters! That is a good idea!

**Comment by yarnabrina** [comment]
@sharma-kshitij-ks is the new test case working for you locally? Based on this reference, only `XNYS` and `ECB` are currently supported.

https://python-holidays.readthedocs.io/en/latest/index.html#available-financial-markets

**Comment by sharma-kshitij-ks** [comment]
The reason I proposed preloading the data in __init__ earlier was to address the efficiency concern raised regarding the fit method. However, after reevaluating the memory considerations, I agree that preloading the data in __init__ isn't the optimal approach.

Instead, it's more appropriate to load data dynamically when needed, such as during fit or transform operations. This approach aligns better with the design principles of sklearn-like libraries and as you mentioned in ensuring minimal memory usage during object creation while optimizing computational resources during the relevant operations.

Thank you for pointing out these considerations, and I apologize for any confusion caused by the earlier proposal. I was trying to demonstrate the concept of preloading, to enhance speed and including XLON was an oversight. Thank you for pointing it out. 

I'm closing this thread for now, until I've a better approach.

**Comment by fkiraly** [comment]
are you going to add more test cases? That was a good idea!

**Comment by fkiraly** [comment]
reopening temporarily so we can use this PR for adding test cases and track this idea and @yarnabrina's feedback on valid parameters.
Feel free to close if you prefer not to, or prefer another PR.

**Comment by sharma-kshitij-ks** [comment]
Please keep me updated regarding any subsequent developements, or any changes that I can help incorporating.

**Comment by yarnabrina** [comment]
> Please keep me updated regarding any subsequent developements, or any changes that I can help incorporating.

You can keep the new test case that you added after changing it to a supported market name, e.g. `ECB`. You need to remove the `preload` codes though. That will be a nice `test` contribution.

**Comment by sharma-kshitij-ks** [comment]
Please consider my application for Gsoc, this is my last chance in life to be the part of the program!

**Comment by sharma-kshitij-ks** [comment]
If you can attest to me, there will be no formalities needed. @yarnabrina 

I sincerely propose that my work will make a difference, to my life and to sktime.

I sincerely believe in my ability to complete the tasks that I've mentioned in my proposal.

I am committed to working very hard and in investing countless hours, striving to exceed expectations but I'll need your trust & support.

**Comment by fkiraly** [comment]
@sharma-kshitij-ks, since you write in public about GSoC, kindly let me answer to that:

I recognize your enthusiasm and work towards `sktime`, thanks a lot!

At `sktime`, we are running a process that we believe is fair towards all applicants, and we are trying to achieve this by being structured and following protocols that are meant to reinforce standardization, mutual scrutiny, and minimize bias.

All applicants (almost a hundred this year) have moved through the process in the same way, with the same rules meant to apply to everyone. While you certainly have shown that you are able to contribute in a meaningful way, there are a limited number of slots, funding and mentors, and we need to carry out a fair ranking.

If we were less restricted, we would give everyone with determination and commitment a paid stipend, but this is not possible because we do not have infinite (or a sufficiently large amount of) money, time, or mentors.
Plus, a step-out as you request (above also, openly), would mean that we deprive another candidate of their chance or reduce their chances.

Think about what you are asking here: you are, by consequence, asking us to tell one of the candidate in the rankings, "unfortunately we had to remove you from the list or change your ranking because of ... (e.g., this discussion in PR number 6319). We know that this other candidate did not go through the process the same way, but they were more vocal, and so we felt like doing them a favour at the last minute."

Given the rankings came out of what we think is a fair, multiple times reviewed, multi-tier, debiased, and structured process, we cannot do this.
This is, obviously, not something we are going to do, or would ever consider doing, it would violate our code of conduct (fair opportunities).

I hope that makes sense?

I also want to reiterate, we really appreciate your contributions - as stated in email, we are happy to offer you a slot in our unpaid mentoring programme, based on your PRs so far.

Since you are talking about employment prospects - skills and demonstrable technical achievement tend to be important, and that is certainly something you can acquire and showcase by contributing to open source.

We would also kindly ask you to minimize off-topic discussion on PR - if you have further questions about the GSoC process, or would be asking for feedback on your application, kindly use the official channels (sktime email).

**Comment by sharma-kshitij-ks** [comment]
I have added the necessary changes, I believe checks branch is good to merge now, after a review.

**Comment by sharma-kshitij-ks** [comment]
I've made the final draft. Please make any necessary changes.

**Pull request closed without merging**
