### PR TITLE
[BUG] fix for `make_reduction` with unequal panels time index for `global` pooling

### PR DESCRIPTION
**Pull request by kbpk**
This PR partially fixes a problem with the unequal panels' time index described in #4602.

However, the problem requires further investigation, especially how is `window_length` determined. Getting an index by `get_time_index` does not seem to be the proper way. There should not be a limit for window size dependent on data size, at most there will be no data (truncate). Also, `get_time_index` should return a min/max time interval over all panels (hierarchical data), then every split should be performed on its basis.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks! This looks like a really nice improvement!

Based on inspection, the changes make sense, although some test cases show a problem with zero samples - not sure whether that is coming from.

Further, the logic for `tr.truncate is None` seems a bit hacky - it changes the behaviour in an existing case, so it would require deprecation.
Can we avoid the `n_cut=0` case?

**Comment by fkiraly** [comment]
FYI @danbartl - any insight on the issue with the test cases?

**Comment by kbpk** [comment]
Currently, according to the docs, we can only have `WindowSummarizer` transformers. Thus, I've included the n=0 case. If you wish, I can remove that fragment. Just confirm.

**Comment by fkiraly** [comment]
ok, I suppose @danbartl is not going to respond. Apologies for the wait, @kbpk.

Primarily, we should ensure that the tests pass (and without hacks).

So, if the tests pass without the `n=0` fragments, I would be fine with that.

**Comment by fkiraly** [comment]
hm, it seems this is failing on the 3.7 versions?

Now 3.7 support will be removed as 3.7 will soon reach end of life - but it is still worth checking here if everything is correct and as intented with the logic.

**Comment by fkiraly** [comment]
scheduled for after 0.20.0 and 3.7 EOL due to 3.7 specific failures

**Comment by fkiraly** [comment]
updated from `main` - will merge if tests pass on 3.8-3.11

**Pull request merged**
