### PR TITLE
[ENH] fix input shape in `CNTCClassifier` and `CNTCRegressor`

### LINKED ISSUE #6467: [BUG] CNTCRegressor raises an error on calling .fit()
**Describe the bug**
There is an error raised on calling fit on a `CNTCRegressor`.

**To Reproduce**
```python
import pandas as pd
import numpy as np
from sktime.regression.deep_learning import CNTCRegressor

index = pd.MultiIndex.from_tuples([
    (0, 0),
    (0, 1),
    (1, 0),
    (1, 1)
], names=['instance', 'Time'])

# Define the DataFrame
df = pd.DataFrame({
    'LeftControllerVelocity_0': [-0.01, -0.01, 0.06, 0.06]
}, index=index)

regressor = CNTCRegressor(verbose=True)

regressor.fit(df, np.array([1, 0]))

print(regressor.predict(df))
```

**Expected behavior**
The model is fitted.
**Additional context**
The following error is raised:
```
d:\BAAI\.venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
Traceback (most recent call last):
  File "D:\BAAI\bug_report.py", line 19, in <module>
    regressor.fit(df, np.array([1, 0]))
  File "d:\BAAI\.venv\Lib\site-packages\sktime\regression\base.py", line 245, in fit
    self._fit(X, y)
  File "d:\BAAI\.venv\Lib\site-packages\sktime\regression\deep_learning\cntc.py", line 223, in _fit
    self.model_ = self.build_model(self.input_shape)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\BAAI\.venv\Lib\site-packages\sktime\regression\deep_learning\cntc.py", line 125, in build_model
    input_layer, output_layer = self._network.build_network(input_shape, **kwargs)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\BAAI\.venv\Lib\site-packages\sktime\networks\cntc.py", line 135, in build_network
    conc1 = keras.layers.Concatenate(
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\BAAI\.venv\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "d:\BAAI\.venv\Lib\site-packages\keras\src\layers\merging\concatenate.py", line 97, in build
    raise ValueError(err_msg)
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concatenation axis. Received: input_shape=[(None, 2, 1), (None, 64, 1)]
```

**Versions**
<details>
System:
    python: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
executable: d:\BAAI\.venv\Scripts\python.exe
   machine: Windows-11-10.0.22631-SP0

Python dependencies:
          pip: 24.0
       sktime: 0.29.0
      sklearn: 1.4.2
       skbase: 0.7.7
        numpy: 1.26.4
        scipy: 1.13.0
       pandas: 2.2.2
   matplotlib: 3.8.4
       joblib: 1.4.0
        numba: 0.59.1
  statsmodels: 0.14.2
     pmdarima: None
statsforecast: None
      tsfresh: None
      tslearn: 0.6.3
        torch: None
   tensorflow: 2.16.1
tensorflow_probability: None
</details>

### PR DESCRIPTION
**Pull request by sanskarmodi8**
Fixed #6467, by fixing input formatting.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks for your help, but this might not be the issue, see https://github.com/sktime/sktime/issues/6467

**Comment by sanskarmodi8** [comment]
> Thanks for your help, but this might not be the issue, see #6467

Ok then, let me check.

**Comment by sanskarmodi8** [comment]
I have update my Pull Request to discard any previous change I suggested and just remove the line `X = X.transpose(0, 2, 1)` from the fit method of CNTCRegressor Class. 

This will solve the below error that was occuring due to invalid input dimensions. `ValueError: A Concatenate layer requires inputs with matching shapes except for the concatenation axis. Received: input_shape=[(None, 2, 1), (None, 64, 1)]`

**Review by fkiraly — CHANGES_REQUESTED** [review]
Great, thanks!

* I see the estimator is skipped in tests currently, in `tests._config`. Could you try to run the `check_estimator` tests locally? Alternatively, we could see what happens if we reactivate the tests.
* have you checked if the same issue is there with `CNTCClassifier`?

**Comment by sanskarmodi8** [comment]
> Great, thanks!
> 
> * I see the estimator is skipped in tests currently, in `tests._config`. Could you try to run the `check_estimator` tests locally? Alternatively, we could see what happens if we reactivate the tests.
> * have you checked if the same issue is there with `CNTCClassifier`?

The `CNTCClassifier` also had the same issue so i fixed that and I have activated the tests for them.

**Review by fkiraly — APPROVED** [review]
Great, thanks!

Just to be sure, could you also run `check_estimator` locally and report the outcome? Just in case some mechanism still would cause the tests to be skipped.

**Comment by sanskarmodi8** [comment]
> Great, thanks!
> 
> Just to be sure, could you also run `check_estimator` locally and report the outcome? Just in case some mechanism still would cause the tests to be skipped.

The `check_estimator` tests passes successfully on manual testing.

**Comment by sanskarmodi8** [comment]
> Great, thanks!
> 
> Just to be sure, could you also run `check_estimator` locally and report the outcome? Just in case some mechanism still would cause the tests to be skipped.

@fkiraly I have done manual testing using `check_estimator` and there was no failure due to my change.

**Comment by fkiraly** [comment]
Great!

**Comment by sanskarmodi8** [comment]
> Great!

Thank you.

**Pull request merged**
