### PR TITLE
[DOC] add rubric for time series detectors to estimator overview

### PR DESCRIPTION
**Pull request by gavinkatz001**
##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Comment by gavinkatz001** [comment]
Created this second PR because I made the mistake of making a second push to the gk-detector-rubric branch while the readthedocs CI job was running. I think it messed up the way the page was rendering and did not properly incorporate my changes. I have thus closed PR #7385 for now and replaced it with this one on a fresh branch intended for the same purpose/feature as gk-detector-rubric.

**Comment by gavinkatz001** [comment]
I checked the _static/estimator_overview_db.json file and could not find "Detector" in any of the json objects under the  "Estimator Type" key. I also tried to run this code in a separate notebook:

from sktime.registry import all_estimators
detectors = all_estimators(estimator_types="detector")
print("Detectors found:", detectors)

and got this error:

ValueError: Parameter `estimator_type` must be None, a string or a list of strings. Valid string values are: ['aligner', 'classifier', 'clusterer', 'early_classifier', 'estimator', 'forecaster', 'global_forecaster', 'metric', 'network', 'object', 'param_est', 'regressor', 'series-annotator', 'splitter', 'transformer', 'transformer-pairwise', 'transformer-pairwise-panel', 'distribution'], but found: 'detector'

which indicated to me that perhaps sktime does not currently recognize detectors as a valid estimator scitype, which seems to be whats causing the issue with the json file. As a result, nothing renders when selecting detector from the dropdown menu (I will attached a separate image), and detector does not show up in the ALL table. I assume this is because the detection module has been under construction up until recently. I saw a message from @fkiraly saying that there will be a new release of sktime to PyPi soon. Will this new release have detectors incorporated into it as valid estimators?

**Comment by gavinkatz001** [comment]
image

**Comment by fkiraly** [comment]
> Created this second PR because I made the mistake of making a second push to the gk-detector-rubric branch while the readthedocs CI job was running. I think it messed up the way the page was rendering and did not properly incorporate my changes. I have thus closed PR #7385 for now and replaced it with this one on a fresh branch intended for the same purpose/feature as gk-detector-rubric.

Hm, that should make no difference to the build. You can push to your branch arbitrarily often, and readthedocs will rebuild from the most recent state. It may take some time of course.

**Comment by fkiraly** [comment]
> Will this new release have detectors incorporated into it as valid estimators?

This PR would need this PR to be finished: https://github.com/sktime/sktime/pull/7361

I believe we had this on the board as important conditionality, but it got picked up by a contributor from the internet and got stalled eventually: https://github.com/sktime/sktime/pull/7361

I will wrap it up and merge so this gets unblocked.

**Comment by fkiraly** [comment]
The PR is now merged, so if everything is complete with this PR, it should now work?

**Comment by gavinkatz001** [comment]
> The PR is now merged, so if everything is complete with this PR, it should now work?

Hi Franz, I just checked the readthedocs build and it now works. Thank you for looking into and fixing this for me!

**Comment by fkiraly** [comment]
excellent! Would you mind fixing the formatting issues?

General guide on setting this up on your local machine here:
https://www.sktime.net/en/latest/developer_guide/coding_standards.html

**Comment by gavinkatz001** [comment]
i pushed a new commit with my changes according to ruff and pre-commit. can you confirm that it is visible on your end? not sure if i did it entirely correctly

**Pull request merged**
