### PR TITLE
[DOC] Compose and deep learning classifier doc tidy

### PR DESCRIPTION
**Pull request by TonyBagnall**
fixes the docstring references and a couple of formatting issues in these packages

### CODE REVIEW

**Review by MatthewMiddlehurst — APPROVED** [review]
Difficult to tell as these aren't on the webpage, but just from the docstring these look like an improvement. 

Could possibly add defaults to some of the parameters, i.e.
```
estimators : list of tuples
        List of (name, estimator, column(s)) tuples specifying the transformer
        objects to be applied to subsets of the data.
```
does not currently display its default.

**Comment by TonyBagnall** [comment]
> Difficult to tell as these aren't on the webpage, but just from the docstring these look like an improvement.
> 
> Could possibly add defaults to some of the parameters, i.e.
> 
> ```
> estimators : list of tuples
>         List of (name, estimator, column(s)) tuples specifying the transformer
>         objects to be applied to subsets of the data.
> ```
> 
> does not currently display its default.

It doesnt actually have a default, it seems to be a required parameter. I dont want to change the structure of this here

**Comment by TonyBagnall** [comment]
@achieveordie @AurumnPegasus are these changes ok with you?

**Comment by MatthewMiddlehurst** [comment]
Oh, yes, it's the column ensemble so it requires estimators as a parameter. All good.

**Comment by TonyBagnall** [comment]
ah sorry, meant to wait to hear from @achieveordie @AurumnPegasus, please revert if necessary (I am doing something with the tests so didnt want to clash with https://github.com/sktime/sktime/pull/3761)

**Comment by achieveordie** [comment]
All changes definitely improve the documentation. Seems like I was late only by a small margin :)

**Comment by TonyBagnall** [comment]
thanks, not at all late, I was too hasty!

**Comment by AurumnPegasus** [comment]
I see it has been merged, but yes, the changes look good to me!

**Pull request merged**
