### PR TITLE
[ENH] Fix html representations of pipelines and nested estimators

### LINKED ISSUE #6903: [ENH] improvements for html repr of estimators
There are two major (but not breaking) issues with the current html representation of estimators, from `__repr__`:

1. Pipelines render left-to-right rather than top-to-bottom.

I am not sure how to fix this, the best would be to add a tag that somehow controls this for a given composite. See display below for the `ForecastingPipeline`.

```python
from sktime.forecasting.compose import ForecastingPipeline

ForecastingPipeline.create_test_instance()
```
yields 
image

2. The html display does not seem to correctly display dropdowns for multiple nested estimators across packages.

An example of this is the following estimator composite which has an sklearn estimator inside an skpro estimator, inside an sktime estimator:

```python
from sktime.forecasting.compose import DirectTabularRegressionForecaster
fs = DirectTabularRegressionForecaster.create_test_instances_and_names()
fs[0][2]
```

Interestingly, the sklearn estimator is displayed, but not the skpro estimator:
image

### PR DESCRIPTION
**Pull request by mateuszkasprowicz**
#### Reference Issues/PRs
Fixes #6903 

#### What does this implement/fix? Explain your changes.
- Fixes pipeline rendering direction from left-to-right to top-to-bottom
- Fixes HTML display for nested estimators

### CODE REVIEW

**Comment by mateuszkasprowicz** [comment]
Next step now would be to

1. Update https://github.com/sktime/sktime/blob/80c9eed218bac737dd4ca17a43d86a344236aaa4/docs/source/conf.py#L500-L511
2. Remove https://github.com/sktime/sktime/blob/80c9eed218bac737dd4ca17a43d86a344236aaa4/docs/source/estimator_overview.md?plain=1#L324-L337

And I believe this related to this https://github.com/sktime/sktime/issues/4905#issuecomment-2290981781

Any ideas how to deal with this at this time?

**Comment by fkiraly** [comment]
Yes, I would consolidate this into *python* code, as we will need to call this from two locations - would that work?

**Comment by mateuszkasprowicz** [comment]
How about 
1. remove `go2URL` altogether
2. import `_get_reduced_path` from `sktime.utils._estimator_html_repr` to `conf.py`
3. create a simple tag navigating directly to correct url
```python
reduced_path = _get_reduced_path(modpath)
modname = (
    f"""<a href='api_reference/auto_generated/{reduced_path}.html'>"""
    f"""{obj_name}</a>"""
)
```

**Comment by fkiraly** [comment]
agreed

**Comment by fkiraly** [comment]
FYI @yarnabrina, @duydl, any thoughts?

**Comment by mateuszkasprowicz** [comment]
btw, what's `import_path` used for? do we need it?
https://github.com/sktime/sktime/blob/5ae6c637de8fef5dcd6f1fe3ac376f2d36ca109f/docs/source/conf.py#L534

**Comment by fkiraly** [comment]
don't know, maybe it is a vestigial remnant of an earlier attempt to fix the import path issue gracefully?

**Review by fkiraly — APPROVED** [review]
Nice! This does not fix everything the mentioned issue entirely, namely the sequential display only for forecasting pipelines, but we can use this to build a tag based solution for all pipelines later.

**Comment by duydl** [comment]
> FYI @yarnabrina, @duydl, any thoughts?

I want to note that the problem with the API path in the docs is not because of parsing `_` annotating, but rather with inconsistencies in when modules imported into `__init__`, which shortens the path by one element. While it is the convention to import objects from a "_private" file into `__init__`, sktime does not always follow this. This also causes the API summary table to be disordered. One example is `CNNClassifier`, the link is currently broken in this PR: https://sktime--6930.org.readthedocs.build/en/6930/api_reference/auto_generated/sktime.classification.deep_learning.cnn.CNNClassifier.html. 
I believe there would be a lot more. 
I actually tried the current approach in `_estimator_html_repr.py` before, but had to create `go2URL` to cover all cases.


> btw, what's `import_path` used for? do we need it?
> 
> https://github.com/sktime/sktime/blob/5ae6c637de8fef5dcd6f1fe3ac376f2d36ca109f/docs/source/conf.py#L534

This is simply for adding import paths to a data frame then json then finally list it in the estimator table.

**Review by fkiraly — CHANGES_REQUESTED** [review]
I see, so what you're saying, this would break the links again that you fixed? Thanks for pointing this out, @duydl!

In this case, can we please separate the fixes to the visual blocks from the fixes to the path inference which may need more discussion?

For path inference, surely there is some deterministic algorithm that does not involve try/excpting - worst case, we have to attempt imports from all modules along the way?

Can we also note down three exemplary cases then, where original path works, where we shorten private modules, and where we have to shorten a public module, so we can use that in testing?

**Review by fkiraly — DISMISSED** [review]
What I'm going to do, I will revert changes to `docs/source` but merge changes to the rest, i.e., fixed html representations of composites.

This will avoid breaking links in the doc that currently work.

The current state of the PR is mirrored in the branch https://github.com/sktime/sktime/pull/6930, off which you can branch off to continue, @mateuszkasprowicz. Alternatively, you can continue working off your branch and open a new PR.

**Review by fkiraly — APPROVED** [review]

**Pull request merged**
