### PR TITLE
[ENH] Interface to stationarity tests from `arch` package

### PR DESCRIPTION
**Pull request by Vasudeva-bit**
#### Reference Issues/PRs

Towards #5382

#### What does this implement/fix? Explain your changes.

Implemented interface testing procedures (unit root tests for stationarity) from `arch` package.

#### What should a reviewer concentrate their feedback on?

Kindly verify design and compatibility. Also note that cointegration testing is yet to be added. Will add them in future commits.

#### Did you add any tests for the change?

No.

##### For all contributions
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [x] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [x] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [x] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Comment by Vasudeva-bit** [comment]
Cointegration tests take two series `x`, `y`. Shall I override `fit` in `cointegration.py` (to be added)? @fkiraly

**Review by fkiraly — CHANGES_REQUESTED** [review]
Nice, thanks! That's a lot!

Since there are now many classes in one file, may I ask you to split things up in multiple?

That is:
* replace `stationarity.py` by a folder `stationarity`
* in this folder, put private files, e.g., `_statsmodels` and `_arch` or more
* and an `__init__` which exports all classes

(the API ref can remain unchanged)

**Comment by Vasudeva-bit** [comment]
> Since there are now many classes in one file, may I ask you to split things up in multiple?
> 
> That is:
> 
> * replace `stationarity.py` by a folder `stationarity`
> * in this folder, put private files, e.g., `_statsmodels` and `_arch` or more
> * and an `__init__` which exports all classes

I will split them as suggested. I think two private files `_statsmodels.py` and `_arch.py` are enough. 

> Cointegration tests take two series `x`, `y`. Shall I override `fit` in `cointegration.py` (to be added)? @fkiraly

Kindly give your inputs for this as well.

**Comment by fkiraly** [comment]
> I think two private files `_statsmodels.py` and `_arch.py` are enough.

Agreed.

> Cointegration tests take two series `x`, `y`. Shall I override `fit` in `cointegration.py` (to be added)?

Cointegration, in general, is a procedure for multivariate time series with arbitrary number of variables.

I would, hence, leave the interface intact, and instead expect a bivariate `X: pd.DataFrame` whose two columns are taken to form the `cointegration`  `x` and `y`. I would also recommend a different PR, as this might result in some discussion and design experimentation.

**Comment by Vasudeva-bit** [comment]
> Cointegration, in general, is a procedure for multivariate time series with arbitrary number of variables.

I think ARCH has cointegration procedure only for bivariate time series. However, I think any cointegration test procedure follows commutative property therefore it could be extended by ensemble method or some other.

> I would, hence, leave the interface intact, and instead expect a bivariate `X: pd.DataFrame` whose two columns are taken to form the `cointegration`  `x` and `y`. I would take `y` as the first (0-th) column, and `x` the second (1-st) column, as `y` is often called "left-hand-side" in the context of EG and some other procedures.

Yeah, I could see this now.

> I would also recommend a different PR, as this might result in some discussion and design experimentation.

Ohkay, btw does it need any new issue?

> PS, I assume this would be a new `cointegration` module?

Yes, a new module.

**Comment by fkiraly** [comment]
> I think ARCH has cointegration procedure only for bivariate time series. However, I think any cointegration test procedure follows commutative property therefore it could be extended by ensemble method or some other for multivariate.

Unfortunately not true for all cointegration tests or models - for instance, Engle-Granger regresses `y` on `x`, which gives a model different from regressing `x` on `y`.

> Ohkay, btw does it need any new issue?

I think it's covered by #5382

**Comment by Vasudeva-bit** [comment]
> Unfortunately not true for all cointegration tests or models - for instance, Engle-Granger regresses `y` on `x`, which gives a model different from regressing `x` on `y`.

Yeah, I just realised after reading some subject content. Thanks for this.

**Review by fkiraly — APPROVED** [review]
Thanks, great!

**Pull request merged**
