### PR TITLE
[BUG] Enable pipeline.fit without X

### LINKED ISSUE #5653: [BUG] Graphical pipeline requires `X` in `fit` - contradiction to forecaster interface specs
**Describe the bug**

Building a pipeline with transforms working on `y` requires passing in a `X` in the fitting. I was hoping to be able to build a pipeline and transform `y` before passing it to the forecaster but that does not seem to work. 

**To Reproduce**

```python
from sktime.forecasting.compose import make_reduction
from sklearn.linear_model   import Ridge
from sktime.transformations.series.difference import Differencer
from sktime.transformations.series.lag import Lag
from sktime.datasets import load_airline
from sktime.split import temporal_train_test_split
from sktime.pipeline import Pipeline

y = load_airline()
y_train, y_test = temporal_train_test_split(y)

regressor = Ridge()
forecaster = make_reduction(regressor, window_length=12, strategy="recursive")

pipe = Pipeline()
pipe = pipe.add_step(Differencer(lags=[1,3,4,12]), "differencer", edges={"X": "y"})
pipe = pipe.add_step(Lag([1], index_out="original"),name="lag",edges={"X": "y"})
pipe = pipe.add_step(forecaster,
                  name="forecaster",
                  edges={
                      "X": ["lag","differencer"],
                      "y": "y"
                  })

pipe.fit(y=y_train) #<-- can't pass X=y_train since at predict time one would need to pass X=X_test=y_test
y_pred = pipe.predict(fh=[1, 2, 3])
```

**Expected behavior**

The expected behavior was no requirement for `X` in the fit function.

**Additional context**

**Versions**
<details>

System:
    python: 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
executable: [c:\Users\user\anaconda3\python.exe](file:///C:/Users/user/anaconda3/python.exe)
   machine: Windows-10-10.0.22621-SP0

Python dependencies:
          pip: 22.3.1
       sktime: 0.24.1
      sklearn: 1.0.2
       skbase: 0.6.1
        numpy: 1.23.5
        scipy: 1.9.3
       pandas: 1.4.4
   matplotlib: 3.6.2
       joblib: 1.1.1
        numba: 0.56.4
  statsmodels: 0.13.2
     pmdarima: None
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: 1.13.1+cpu
   tensorflow: None
tensorflow_probability: None
</details>

### PR DESCRIPTION
**Pull request by benHeid**
#### Reference Issues/PRs
Fixes #5653 

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Comment by benHeid** [comment]
@fkiraly the tests are currently failing due to a check in the testing framework (line 79 in `scenarios_classification.py`). There the second part of the if condition is raising the error since obj is a Pipeline instance. 

I think this would be fixed, if instead  of examining subclasses to determine applicability of a scenario the `object_type` tag would be used. I wonder if it should be changed here or if it was an explicit decision to use checks against subclasses.

**Comment by fkiraly** [comment]
Yes, instead of 
`if not isinstance(obj, regr_or_classf) and not issubclass(obj, regr_or_classf)`

it should be sth like `get_tag(obj, "object_type") in [...]`.

Would you kindly like to change this in a separate PR? There is a parallel locus in `scenarios_forecasting`, line 52.

**Comment by fkiraly** [comment]
> I wonder if it should be changed here or if it was an explicit decision to use checks against subclasses.

No, the scenarios predate the "typing-by-tag" design by a year, and I did not have the location on the radar, as we did not catch it in the refactor (partly because the single polymorphic example, `Pipeline`, did not have `get_test_params`).

**Comment by benHeid** [comment]
Failing tests probably due to #5673. Thus rebase after 5673 is merged.

**Comment by fkiraly** [comment]
> Failing tests probably due to https://github.com/sktime/sktime/pull/5673.

Yes, that's where I noticed the bug. #5673 should hopefully fix it.

**Review by fkiraly — APPROVED** [review]
With the use of `scitype`, this should work now.

**Pull request merged**
