### PR TITLE
[MNT] Bump isort to 5.12.0 in pre-commit config

### LINKED ISSUE #4162: [BUG] CI fails in `code_quality` `isort` hook, environment creation, at preparing metadata via `pyproject.toml`
Since a few minutes ago, `sktime` CI fails at the first step when trying to install the env, with this traceback below.

This seems to be coming from the `code_quality` job, in there the `isort` hook when the python environment is being created, probably when trying to parse a `pyproject.toml`.

As a temporary workaround, `isort` has been removed here: https://github.com/sktime/sktime/pull/4164
but it should be added back.

Below is the traceback:

```
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
    
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [14 lines of output]
          Traceback (most recent call last):
            File "/home/runner/.cache/pre-commit/repohskwxkw8/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
              main()
            File "/home/runner/.cache/pre-commit/repohskwxkw8/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
            File "/home/runner/.cache/pre-commit/repohskwxkw8/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
            File "/tmp/pip-build-env-3kaotqva/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 40, in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
            File "/tmp/pip-build-env-3kaotqva/overlay/lib/python3.10/site-packages/poetry/core/factory.py", line 57, in create_poetry
              raise RuntimeError("The Poetry configuration is invalid:\n" + message)
          RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
          
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
```

### PR DESCRIPTION
**Pull request by snnbotchway**
I updated the sort version in pre-commit to stop pre-commit checks from failing.

Closes #4162

### CODE REVIEW

**Comment by fkiraly** [comment]
Thanks a lot for helping out with this, @snnbotchway!

I thought I already tried updating `isort` - see here for the things I tried:
https://github.com/sktime/sktime/pull/4163

But I see you did it differently, so let's try what this does.

**Comment by snnbotchway** [comment]
A new release(5.12.0) was just released an hour ago.
This version solves the issue.

**Comment by fkiraly** [comment]
Ah! Well spotted!

**Comment by snnbotchway** [comment]
Thanks a lot for reviewing @fkiraly 
Merging this will be my first contribution

**Comment by fkiraly** [comment]
yes, that's true!
Feel free to add yourself to `all-contributorsrc` with a maintenance contribution badge!

**Comment by snnbotchway** [comment]
Sure, done!

**Review by fkiraly — APPROVED** [review]
Well, this works - thanks!

**Comment by fkiraly** [comment]
Thanks for fixing, @snnbotchway! This has caused me quite a headache today!

**Comment by snnbotchway** [comment]
Don't mention it!
Thanks for taking the time to review my PR

**Comment by fkiraly** [comment]
always!
If you'd like to continue contributing, free to pick up one of the good first issues and/or join one of the community sessions. Much appreciated.

**Comment by snnbotchway** [comment]
Sure

**Pull request merged**
