### PR TITLE
[ENH] test suite for splitters

### PR DESCRIPTION
**Pull request by fkiraly**
Adds a "test all" test suite for time series splitters.

Closes https://github.com/sktime/sktime/issues/5411

Adds exceptions for the splitters currently failing the tests.
These are now tracked in this issue: https://github.com/sktime/sktime/issues/6194

Bugs can now be fixed using TDD via `check_estimator`.

Also contains a fix for small unreported failures:
* `Repeat` failing for a certain parameter combination.
* `CutoffFhSplitter.get_n_splits` being broken
* default `_split` to get indices from `_split_loc`

### CODE REVIEW

**Review by benHeid — APPROVED** [review]
Thank you. This PR looks fine to me. 
There is only a non-blocking question: Should we also adapt the GitHub action?. I.e., should this test only run if splitters are changed?

**Comment by fkiraly** [comment]
> Should we also adapt the GitHub action?. I.e., should this test only run if splitters are changed?

It would run with the `others` group currently. Also, a lot depends on the splitters - e.g., grid search in multiple packages - no not sure what the best protocol is. FYI @yarnabrina

**Comment by yarnabrina** [comment]
My suggestion is to keep CI unaltered in this PR as out of scope. Let's plan CI stuff in #5706 .

Given the case that splitters themselves are seldom used on their own, I feel they should run in combination with others. We can have a dedicated step for splitters only, but not by removing their interactions. 

I posted a while back (in a different issue https://github.com/sktime/sktime/issues/5475#issuecomment-1802274345) that we should consider unit tests (logic for a specific component independent of others) and integration tests (logic for how multiple components work together) separately, not sure how you feel about that.

**Comment by fkiraly** [comment]
> I posted a while back (in a different issue [#5475 (comment)](https://github.com/sktime/sktime/issues/5475#issuecomment-1802274345)) that we should consider unit tests (logic for a specific component independent of others) and integration tests (logic for how multiple components work together) separately, not sure how you feel about that.

Agreed - although it is not 100% clear how to best reconcile this with conditional testing - e.g., an integration test should run iff any of the integrated parts change.

**Pull request merged**
