### PR TITLE
[DOC] documentation on workflow of adding a new dataset loader

### LINKED ISSUE #2019: [DOC] adding dataset instructions not very comprehensive, and incorrect for new file extensions
The "adding datasets" page is a bit brief/incomprehensible, and it also misses the `MANIFEST.in` for adding files with new extensions, see the discussion here in the PR.

This should be improved.

Current "adding datasets" documentation:
https://www.sktime.org/en/stable/developer_guide/add_dataset.html

### LINKED ISSUE #3686: [DOC] Collection of Documentation issues to get started on!
## Welcome to sktime!

Here is a collection of several good "documentation" issues that we are looking for people to take on! 

If you are interested in working on a particular problem we ask that you say so in a comment to avoid the issue of multiple people working on the same problem.

This issue will be updated with more issues/work items through Nov 16th.  We encourage you to check out our [contributing guide](https://www.sktime.org/en/latest/get_involved/contributing.html) and/or ask for help (the contributors channel on slack is also a good place to reach out!) if you get stuck!  [This issue](https://github.com/sktime/sktime/issues/1147) on good first issues and getting started also has a lot of great suggestions/resources for your first contribution to sktime. 

### Some open issues :
(more will be added)

- [ ] #3421
- [ ] #3314

[Here is a link](https://github.com/sktime/sktime/issues?q=is%3Aopen+is%3Aissue+label%3A%22documentation%22+) to all open "documentation" issues so that you can check out even more pending issues to work on!

### PR DESCRIPTION
**Pull request by templierw**
#### Reference Issues/PRs
Fixes #2019 

#### What does this implement/fix? Explain your changes.

* Corrected the layout
* Detailed the steps
* Added the reference to the list of supported file formats

#### What should a reviewer concentrate their feedback on?

* Clarity and comprehensiveness of the instructions

#### Any other comments?

**IMPORTANT**

The former doc contained an instruction about commenting out the `.gitignore` file:
`#downloaded datasets sktime/datasets/data/`

The current `.gitignore` only refers to
`#downloaded datasets
sktime/datasets/local_data/`

a folder not even in the current file tree...

Is this issue with `.gitignore` obsolete?

##### For all contributions
- [X] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [X] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

### CODE REVIEW

**Review by fkiraly — APPROVED** [review]
Nice, thanks!

I did not know you had to register the loaders like that.
Seems like redundant and brittle design - can we not improve this by introducing a single source of truth?

Either way, this is nothing about the doc which imo is excellent.

**Comment by templierw** [comment]
My pleasure, thanks!

Indeed I felt the same about the design: very redundant...

**Comment by fkiraly** [comment]
well, but clear documentation is the first condition for a useful refactor.
If no one understands the status quo, you can hardly make suggestions for improvement.

I suspect this is simply organically grown.

**Review by fkiraly — CHANGES_REQUESTED** [review]
Oh, and I think you made a change that broke linting?

I would kindly ask you to fix the linting. See guidance here:
https://www.sktime.org/en/stable/developer_guide/coding_standards.html

**Review by fkiraly — APPROVED** [review]
Linting passes now, thanks!

**Comment by templierw** [comment]
great, thanks to you!

**Pull request merged**
