### PR TITLE
[DOC] Added an example to CNNRegressor #4264

### PR DESCRIPTION
**Pull request by meraldoantonio**
#### Reference Issues/PRs
Adds to #4264 

#### What does this implement/fix? Explain your changes.
Added one usage example to `CNNRegressor`.

#### Does your contribution introduce a new dependency? If yes, which one?
No

#### What should a reviewer concentrate their feedback on?
Reviewing the example and my workflow

#### Did you add any tests for the change?
No

#### Any other comments?
No

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

### CODE REVIEW

**Comment by fkiraly** [comment]
Nice, thanks!

**Comment by meraldoantonio** [comment]
Hi @fkiraly, thanks for checking the PR! 
If everything is OK, could you please give me the permission to merge it?

**Review by fkiraly — APPROVED** [review]
Sure!

**Comment by meraldoantonio** [comment]
One required test failed because of invalid keras filepath, and I'm not too sure how to change this path.. Could someone please help me on this?

This is the error:

```
ValueError: Invalid filepath extension for saving. Please add either a `.keras` extension for the native Keras format (recommended) or a `.h5` extension. Use `tf.saved_model.save()` if you want to export a SavedModel for use with TFLite/TFServing/etc. Received: filepath=/tmp/pytest-of-runner/pytest-0/popen-gw1/test_cnn_model_save_and_load_p0/model/model/keras.
```

**Pull request merged**
