### PR TITLE
[ENH] added test parameters for `MatrixProfileClassifier`

### PR DESCRIPTION
**Pull request by MMTrooper**
#### What does this implement/fix? Explain your changes.

Towards #3429

I decided to add the estimator parameter and set it to the scikit-learn classifier `KNeighborsClassifier`. 

I also added my self as a contributor. Let me know if it was appropriate or I need to make a better implementation.
#### Any other comments?
Now the test is successful. 

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

### CODE REVIEW

**Comment by fkiraly** [comment]
These failures look like actual bugs - the next step would be trying to isolate them, and either fix, or report.

**Comment by MMTrooper** [comment]
@fkiraly I decided to just edit the return statement by removing the if else statement. It seems everything checks out now. Let me know if this is alright.

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks!

I notice that the `estimator` parameter is not covered in `get_test_params`, we should ensure we have one example where this is set.

`n_jobs` and `random_state` are covered elsewhere, these should not be covered by `get_test_params`.

**Comment by MMTrooper** [comment]
@fkiraly Ok, I've added the estimator parameter and everything seems alright. Let me know if there's more I need to do or changes I need to make for this pull request.

**Review by fkiraly — CHANGES_REQUESTED** [review]
Instead of changing the one existing parameter set, can you please add a new parameter set? Thanks.

**Review by fkiraly — CHANGES_REQUESTED** [review]
What I meant, can you please leave the first parameter set as it was? It is used in consistency checks.

**Comment by MMTrooper** [comment]
@fkiraly Apologies for the back and forth. I think I've implemented the changes correctly now. Thanks for you patience.

**Review by fkiraly — CHANGES_REQUESTED** [review]
No worries at all, I haven't been very clear.

Could you kindly return a length-2 list, where the original dictionary is the first element, and the new dictionary is second?

Thanks.

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks. Could you kindly return a length-2 list, where the original dictionary is the first element, and the new dictionary is second?

Kindly do not include a condition on `"results_comparison"`.

**Comment by MMTrooper** [comment]
@fkiraly Ok, I have removed the condition. However, I am uncertain if this iteration will pass the checks.

**Comment by fkiraly** [comment]
> However, I am uncertain if this iteration will pass the checks.

May I ask, why? Have you tried locally?

**Comment by MMTrooper** [comment]
@fkiraly The tests passed locally. I felt it may not pass because the second parameter set did cause a few failures earlier. I am glad that the all checks have been passed now. Once again, I appreciate your patience and willingness to help.

**Comment by fkiraly** [comment]
I see - the tests were still being skipped in `tests._config`, I now removed the skips and reactivated the tests.

**Comment by MMTrooper** [comment]
@fkiraly Ok, it seems that most tests passed except 2 that were skipped. Is there anything else I should do?

**Review by fkiraly — APPROVED** [review]
All good now!

**Comment by MMTrooper** [comment]
@fkiraly Thank you for accepting my changes! Can I tackle another task on issue #3429 or is there another good first issue that I should look at?

**Comment by fkiraly** [comment]
#3429 is good to start - you can look at more challenging "good first issues" as well! Up to you.

**Pull request merged**
