### PR TITLE
[BUG] Fix inconsistent date/time index in `plot_windows` #4919

### LINKED ISSUE #4919: [BUG] inconsistent date/time index in `plot_windows`
reported originally by @jpss95 in #519.

Confirmed by @fkiraly on 0.21.0, current `main`, windows, python 3.11

---
Hi all, the same thing is happening to me with the plot_windows method. (sktime==0.18.0)

Here a code to reproduce the bug:

```python
import pandas as pd
import numpy as np
from sktime.utils.plotting import plot_windows
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.model_selection import ExpandingWindowSplitter

forecast_steps= 5
initial_window_size= 40
step_length=1
fh = ForecastingHorizon(np.arange(1,forecast_steps+1))

#create dummy data
dates = pd.date_range(start='2016-01', end='2022-12', freq='M')
df = pd.DataFrame(index=dates)
df['y'] = np.random.rand(len(df))

cv = ExpandingWindowSplitter(fh=fh, initial_window=initial_window_size, step_length=step_length)

print(df)
plot_windows(cv, df)
```

image

The image clearly has wrong indexes

cc: @fkiraly

_Originally posted by @jpss95 in https://github.com/sktime/sktime/issues/519#issuecomment-1638671715_

### PR DESCRIPTION
**Pull request by geronimos**
#### Reference Issues/PRs

Fixes #4919 

#### What does this implement/fix? Explain your changes.
This PR 
- fixes the labels of the x-axis ticks of the figure plotted by `plot_windows` and
- makes `plot_windows` return the `matplotlib.figure.Figure` object such that the figure can be manipulted by API users on-demand.

#### Does your contribution introduce a new dependency? If yes, which one?

None

#### What should a reviewer concentrate their feedback on?

Check that returning the figure object does not raise any conflicts. Other plot functions also return the fig object. However, `plot_windows` returned None before.

#### Did you add any tests for the change?

No new tests are added

#### Any other comments?

None

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

### CODE REVIEW

**Review by fkiraly — APPROVED** [review]
That looks like it fixes it, thanks!

While I was looking at the code, I also have an idea for a new PR (not for this one).

For `matplotlib` plotting functions, it is best if there is an optional `ax=None` argument - if not provided, it creates a figure, if not, it uses that `ax` object. This is useful if somone has set up subplots and the like.

**Comment by geronimos** [comment]
Thanks for the quick response! 

Yes, having the optional `ax=None` argument would be great :) - good idea. I might add this at some point in another PR

**Comment by fkiraly** [comment]
For an example regarding `ax`, you can look at `plot_series`, although I just noticed the docstring is incomplete. I added an issue for the incomplete docstring here: https://github.com/sktime/sktime/issues/5323

**Review by fkiraly — DISMISSED** [review]
still approve - I would return both `fig, ax` though.

**Review by fkiraly — APPROVED** [review]
I added the `ax` handling so this is ready to go for the next release. Thanks for your contribution!

**Pull request merged**
