### PR TITLE
[DOC] speed-up changes to tutorial notebooks

### LINKED ISSUE #5041: [ENH] speed up notebooks and notebook tests
It seems the notebooks in `examples` take 50min to run, all taken together.

I remember times where this was closer to 20min - we should investigate where runtime is spent in the notebooks, and optimally replace by faster examples that illustrate the same point(s).

Good first issue - simply go through the notebooks, run them and check which cells take longest.

There are also a number of more "obscure" notebooks, we may consider removing them, or shortening them, or making the data sets smaller.

### PR DESCRIPTION
**Pull request by alexfilothodoros**
#### Reference Issues/PRs
-->
Towards #5041

#### What does this implement/fix? Explain your changes.
It makes the example notebooks faster.

#### Does your contribution introduce a new dependency? If yes, which one?

No
#### Did you add any tests for the change?
No

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks a lot!

It looks though that your changes are quite large (71 files), a you also committed some files in `mlruns` that should not be there.

Also, did you mea to change all the notebooks? Optimally, the difference is only aroud the cells where you made changes.

**Comment by alexfilothodoros** [comment]
@fkiraly Sorry for that

I run each notebook but I didn't clear the outputs.

Not sure what happened with `mlruns`.

Should I create a new PR?

Thanks

**Comment by fkiraly** [comment]
> Should I create a new PR?

You could update this one?

The easiest way would be to pick only the files you changed (how many are there?) and either:

* copy them to a new branch
* restore all other files to their original state

Not sure which of these is better, depends on how many change you made!

Perhaps we can start just with 1 file to iron out the usually very fiddly issues around jupyter notebook based PR?

**Comment by alexfilothodoros** [comment]
Hi

I've made a few more commits. In the last one, you will see (if I didn't mess anything up!) that 5-6 notebooks have some slight changes, mostly the number of epochs when forward propagation.

**Comment by fkiraly** [comment]
> In the last one, you will see (if I didn't mess anything up!) that 5-6 notebooks have some slight changes, mostly the number of epochs when forward propagation.

Thanks, that's exactly what I meant!

So that's where the runtime was coming from!
I completely forgot about those classification notebooks.

Much appreciated.

**Review by fkiraly — CHANGES_REQUESTED** [review]
There seems to be one minor linting failure, otherwise all looks good from my side!

The linting failure is blocking due to how the CI works, but it's really small and not your fault.

Seems in a part that you didn't change, but it checks the entire file when it's changed, I assume the linter policy has changed with one of the recent dependabot updates.

**Comment by alexfilothodoros** [comment]
Thanks for the feedback :)

I see the code quality test is failing. I will try to fix that.
The epoch numbers are smaller but the score results, still acceptable.

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks!

Fixing the linting failure unfortunately made the diff in the affected notebook huge again.

**Comment by fkiraly** [comment]
looks good now - let us know when it's finished!

**Comment by fkiraly** [comment]
Shall we merge this and we deal with the forecasting notebook later?

I'll just do that, and you can open another PR from the same branch in case you update that, just to expedite things and keep changes localized.

**Review by fkiraly — APPROVED** [review]

**Comment by alexfilothodoros** [comment]
Awesome, thanks @fkiraly :)

**Pull request merged**
