### PR TITLE
[DOC] Basic fix and enhancement of doc local build process

### PR DESCRIPTION
**Pull request by duydl**
#### Reference Issues/PRs

#6108  #6106

#### What does this implement/fix? Explain your changes.

This PR improves the local documentation build process to be more consistent with the online documentation and reduce build times for better observability.

1. Move Makefile into the source folder, as some functions of conf.py should be run inside source folder like in Readthedoc as stated in .readthedocs.yml. 

2. Removed `sphinx-apidoc` and related code as it was not configured in conf.py and so was not used by the build process on Readthedocs. This eliminates orphan pages in the local build documentation that are not present in the online documentation.
For example:
image
which does not appear in online doc: https://www.sktime.net/en/stable/api_reference/auto_generated/sktime.alignment.base.html

3. No longer remove build folder. Instead, add a clean target for situations where a clean build is necessary. This change allows sphinx-build to detect changes in both the documentation and the codebase and do its increment build from cache. 

4. Commented out `symlink_examples.sh`. Currently each example in docs is manually linked to sktime/examples. We must refractor the sktime/examples folder to the same structure assumed by docs before we could link it.  This change is made in #6210. 

5. Added an autobuild target using sphinx-autobuild. 

6. Modify docs page on building documentation locally to reflect the changes

The new Makefile significantly reduces build times for incremental changes, about 10 times faster than before. 

#### Does your contribution introduce a new dependency? If yes, which one?

No. But users could independently install `sphinx-autobuild` if needed. 

#### What should a reviewer concentrate their feedback on?

This PR won't have any effect on the online documentation. Please confirm on the efficient and consistent of local documentation build with online docs if you have time. 

#### Any other comments?

> 4. Commented out `symlink_examples.sh`.

The `symlink_examples.sh` file served no purpose, even before this PR, as the symlinks to examples are tracked. I keep it in the repo in case we need to dynamically create symlink to docs in the future.

### CODE REVIEW

**Comment by yarnabrina** [comment]
Is it not standard to have Makefile one level up source with Sphinx? I thought that's what happens even with sphinx-quickstart. Why should we move away from that?

I haven't used sphinx-autobuild though, so can you tell what's the benefit of this shift? 

Most of our pull requests (I'll guess >99%) don't involve Sphinx at all. Yes, the site gets automatically built with that plus other extensions to make the UI more useful for developers (e.g. copy button), but almost no one modifies these files directly except may be to add a new estimator in the overview rst document. If we use this new extension, is there any benefit to non "local sphinx development" cases?

Just to be clear, I'm not opposing your changes at all. I understand now local builds take long and it's frustrating, 
and I myself disabled quite a few things. But after you complete all the docs enhancements you are suggesting across issues and pull requests, I'm right now not sure if it'll be used any more or not in long term. If you can some pointers which shows that these will help RTD build times and performances and etc. as well, then that's awesome.

**Comment by duydl** [comment]
Just some examples of Makefile in same directory as conf.py
https://github.com/pallets/flask/tree/main/docs
https://github.com/django/django/tree/main/docs

And if you are hesitant to add more dependency, I could remove sphinx-autobuild. Just using sphinx-build would be good enough for fast increment build.

**Comment by duydl** [comment]
> I understand this may help your local development by speeding up things, but is there any long term benefit to all contributors as well?

I believe your vision of sktime is like Wikipedia, where users could find universal resources on timeseries tasks. I think a good documentation is crucial for the task, not just the API reference but tutorials and explanations of the tools. We should aim for the docs to also be like a blogging platform, like that of pytorch or tensorflow, where there are abundant resources to getting started.

**Comment by yarnabrina** [comment]
> Just some examples of Makefile in same directory as conf.py

I was referring to numpy, statsmodels, etc. If I'm not wrong, Sphinx gives two options: source/build separate directories and same directory. I believe both of your examples are following the latter, while sktime (and others what I checked) are following the first. I don't know when one is preferable over the other, can you please tell? Or if it's just a choice and has no other impact, that's also fine.

> And if you are hesitant to add more dependency, I could remove sphinx-autobuild. Just using sphinx-build would be good enough for fast increment build.

This was a concern, yes. Can you please tell me what does autobuild do additionally or in a better way? If nothing substantial, I think personally I'll prefer to keep dependencies minimal.

> I think a good documentation is crucial for the task, not just the API reference but tutorials and explanations of the tools. 

I completely agree. But I'm not sure about using it as a blogging platform part. If someone writes a tutorial or blog documenting usage of sktime, that's very much welcome, but I'm not sure if Sphinx based api reference/autogeneration tool is the right way for that.

I'd like to understand from you is how will these changes help in these tutorial example. Let's suppose you have written a blog on ARIMA using the sktime estimators and you want to contribute that notebook. I think as of now the process is to just commit that in the examples folder. Can you please point out what are the current issues that you have identified with this process, and how do you want to address these issues?

**Comment by yarnabrina** [comment]
By the way I see that other PR's have a build time of about 1115-1120 seconds on an average (checked 3-4), and this PR has about 1035, so it does improve build time on RTD as well. That's great.

**Comment by duydl** [comment]
> By the way I see that other PR's have a build time of about 1115-1120 seconds on an average (checked 3-4), and this PR has about 1035, so it does improve build time on RTD as well. That's great.

No it shouldn't affect build on RTD at all.

**Comment by yarnabrina** [comment]
> No it shouldn't affect build on RTD at all.

Okay...then I'm asking this again.

> If not, I want to know how it's going to help other than one time big local sphinx development for docs redesign.

---

Also, I wasn't aware committing in that folder wasn't enough. I suppose I misinterpreted that from seeing #5604. What are all the steps then?

(Should we discuss these in a issue instead of directly in a PR?)

**Comment by duydl** [comment]
> I understand this may help your local development by speeding up things, but is there any long term benefit to all contributors as well?

But regarding this, if the build does not cost 20 minutes all the time, but just 1 minute, contributors will be much more incentive to check the rendering of their contributions on the docs. 

Note: I move it from the my previous comment.

**Comment by fkiraly** [comment]
@duydl, @yarnabrina, what is the next step with this PR?

**Comment by duydl** [comment]
I think I would need to remove sphinx-autobuild from dependencies. Would it be fine to keep the sphinx-autobuild in the Makefile, so user could install it on their own if they want to use the command? 

Btw, this is an example Makefile on same level as source files with sphinx-autobuild: https://github.com/sqlalchemy/sqlalchemy/blob/main/doc/build/Makefile

**Comment by yarnabrina** [comment]
If `docs/build` does not exist, will it make sense to rename `docs/source` to just `docs`? Or, does that serve any other purpose?

Also, can you please tell me the difference between `make build` and `make html`?

**Comment by duydl** [comment]
> the difference between make build and make HTML?

sphinx-build could operate in many modes https://www.sphinx-doc.org/en/master/usage/builders/index.html, `html` is one of them. The old Makefile allows the mode param to be passed into `sphinx-build` through a catch-all rule i.e `make html` -> `sphinx-build html`. However, considering that RTD also uses html mode, the local build should default to `html` mode which is hard coded in `build` rule. 

> If docs/build does not exist, will it make sense to rename docs/source to just docs? Or, does that serve any other purpose?

For local build, the build will stay in docs/build though I am not sure where RTD stores its build, but likely not related to the repo structure. So it is not important as RTD build is isolated.

My experience is mostly about docs built with sphinx but hosted in local server not RTD, which depends a lot on the utility of Makefile. In sktime case however, the local doc just need to be the same as RTD build, with no consequence on the online docs. 
This PR primary goal is just to make sure that if users try building docs locally they will not be puzzled by missing examples and estimator table, or spend several tries rebuilding that cost 20 minutes each time. 
Though I have realized it is actually very rare for people to try the local build.

**Comment by fkiraly** [comment]
FYI @duydl

**Comment by duydl** [comment]
> If not, can you please update the PR summary above with the description of final changes and let us know?

Updated.

> Just wondering did you see this (https://github.com/sktime/sktime/issues/6108#issuecomment-1988719560)? Is it feasible?

I believe there are generally two ways to add that notification. One is with a setting in RTD. Like I added it in the docs of my fork. 
https://duydlsktime.readthedocs.io/en/latest/users.html

The other way is with some theme-specific settings. Though I think for sphinx-data we would need to create a switcher.json for that.

**Review by fkiraly — APPROVED** [review]
We can merge this, right, @yarnabrina?

**Pull request merged**
