### PR TITLE
[MNT] fix several spelling mistakes

### PR DESCRIPTION
**Pull request by yarnabrina**
Diagnoses #5638 

Depends on #5638

### CODE REVIEW

**Comment by yarnabrina** [comment]
@fkiraly the failure is coming from a known bug I think (#5658), not from CI. Ignoring in this PR as of now.

> FAILED sktime/tests/test_all_estimators.py::TestAllEstimators::test_multiprocessing_idempotent[TSFreshClassifier-ClassifierFitPredictMultivariate-predict] - ValueError: The feature names should match those that were passed during fit.
Feature names must be in the same order as they were in fit.

**Comment by yarnabrina** [comment]
@fkiraly rebased this PR with `main` after merging #5638. It just has fixes of several spelling mistakes, and no other change whatsoever.

**Comment by fkiraly** [comment]
... really hard to fid the single failing check among 380.

Is there a way to bundle these better?

**Comment by yarnabrina** [comment]
This (ref. https://github.com/sktime/sktime/actions/runs/7370225847/job/20056856638) is the failure.

> FAILED sktime/tests/test_all_estimators.py::TestAllEstimators::test_multiprocessing_idempotent[TSFreshClassifier-ClassifierFitPredictMultivariate-predict] - ValueError: The feature names should match those that were passed during fit.
> Feature names must be in the same order as they were in fit.

In the CI summary page (ref. https://github.com/sktime/sktime/actions/runs/7370225847), it highlights what all failed. You need to go to Checks -> validate code quality workflow -> Annotations.

image

I am not aware of any other easier options.

**Comment by yarnabrina** [comment]
@fkiraly after merging `main` to fetch #5673 changes, there's no CI failure any more. All changes for this PR are done from my side.

**Review by fkiraly — APPROVED** [review]
Thanks! Fine in-principle, though I want to note: 

the CI reportrs 1 out of 380 tests still queued, and I cannot find which one it is due to the list being so long. This is annoying, and we should think about reducing number of CI jobs spawned.

**Comment by yarnabrina** [comment]
image

All checks have passed. Merging this, and we can discuss in #5706 on how to reduce number of jobs, or if it's possible.

**Pull request merged**
