### PR TITLE
[ENH] add detector specific tags to the tag registry and tags API reference

### LINKED ISSUE #7374: [ENH] add detector specific tags to the tag registry and tags API reference
**Is your feature request related to a problem? Please describe.**
Add detector-specific tags to the tag registry and tags API reference.

**Describe the solution you'd like**

- Detector specific tags added to [docs/source/api_reference/tags.rst](https://github.com/sktime/sktime/blob/37d601786c27fbaed084dc6b79194c6d5554f648/docs/source/api_reference/tags.rst)
- Detector specific tags added to [sktime/registry/_tags.py](https://github.com/sktime/sktime/blob/37d601786c27fbaed084dc6b79194c6d5554f648/sktime/registry/_tags.py)

**Additional context**
This enhancement is facilitated by the bg_control team, the issue for their project is found here:
* https://github.com/RobotPsychologist/bg_control/issues/106
* https://github.com/RobotPsychologist/bg_control/issues/127
* HackMD document
* Extensions Template
* BaseClass Extensions
    * sktime
    * skchange
* Capability tags do not yet exist in some cases.

### PR DESCRIPTION
**Pull request by liya-zhu**
#### Reference Issues/PRs

 Fixes #7374

#### What does this implement/fix? Explain your changes.

- Added common detector tags to BaseDetector and detector extension template
- Added new detector tags documentation to tags registry
#### What should a reviewer concentrate their feedback on?

- Not sure about the type of the tags - whether they should be property/metadata/behaviour/capability/etc.
- I tried my best to understand what each tag entails and wrote a description but appreciate any feedback as it might be missing details or misrepresenting things
- Does there need to be alignment between the BaseDetector tags and the tags added by https://github.com/sktime/sktime/pull/7389 in docs/source/conf.py?
- Whether the added tags to BaseDetector and the detector extension template make sense, what tags are missing

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
This is great, exactly what was meant!

Some smaller remarks:

* in rst, the length of underline should be same as length of header
* not sure what the `distribution_type` tag does. are we still using it somewhere? @Alex-JG3, @tveten? If not, we may be better off moving it to the "to be removed" part (bottom of `_tags` registry), and not mentioning it in the API. (in case of no reply within a few days, that is what I would advise we do)

**Comment by Tveten** [comment]
> * not sure what the `distribution_type` tag does. are we still using it somewhere? @Alex-JG3, @Tveten? If not, we may be better 

I'm not using it.

**Comment by liya-zhu** [comment]
> This is great, exactly what was meant!
> 
> Some smaller remarks:
> 
> * in rst, the length of underline should be same as length of header
> * not sure what the `distribution_type` tag does. are we still using it somewhere? @Alex-JG3, @Tveten? If not, we may be better off moving it to the "to be removed" part (bottom of `_tags` registry), and not mentioning it in the API. (in case of no reply within a few days, that is what I would advise we do)

Thanks for the feedback Franz! I changed the underline length. 

Regarding the distribution type, I see the comment about it not being used now I think it got overwritten when I merged main into my branch. I included it because I saw it in the PoissonHMM class.

**Review by fkiraly — APPROVED** [review]
Thanks!

For now, I have removed the link to `distribution_type` from the API reference, but left the record in case we want to add it later.

I am thinking of this as a temporary solution until we know what the end state for that tag is.

**Pull request merged**
