### PR TITLE
[ENH] pipeline for anomaly, changepoint detectors and segmenters

### PR DESCRIPTION
**Pull request by fkiraly**
This PR adds an `AnnotatorPipeline` which provides a pipeline object for anomaly, changepoint detectors and segmenters.

Depends on #7073 which enables composability through making the base class more stringent.

### CODE REVIEW

**Comment by Alex-JG3** [comment]
This looks good to me and seems to be working as expected. Here is a little toy example:

```python
>>> import numpy as np                                                                                                                                                                        >>> import pandas as pd
>>> from sktime.annotation.stray import STRAY                                                                                                                                                 >>> from sktime.transformations.series.detrend import Detrender
>>>
>>> n = 100
>>> x = pd.Series(np.linspace(0, 5, n) + np.random.normal(0, 0.1, size=n))
>>> x.at[50] = 100
>>>
>>> pipeline = Detrender() * STRAY()
>>> pipeline.fit(x)
>>> y_hat = pipeline.transform(x)
>>>
>>> print(y_hat.sum())
3
```

**Comment by fkiraly** [comment]
I've added the example to the docstring

**Comment by fkiraly** [comment]
hm, it seems it does not, with the dunder! It creates a `TransformerPipeline`, which doe snot have `predict`, `predict_points`, etc

**Comment by fkiraly** [comment]
I've fixed the type, but now there are two problems:

* it is unclear how the `_predict_points` etc methods are supposed to be forwarded on the level of a given estimator.
Is this properly written up somewhere? I am getting confused.
I would have thought that the user implements `_predict` only, and the other two methods default to that based on the type.

* the tags in hte `__init__` are looking at the class tags, not the tags, so dynamic setting - as would be required in a pipeline - is not possible.

**Comment by Alex-JG3** [comment]
> it is unclear how the _predict_points etc methods are supposed to be forwarded on the level of a given estimator.

Would it be possible to use `predict` instead of `_predict_points`?

> I would have thought that the user implements _predict only, and the other two methods default to that based on the type.

My thinking was that users would implement `_predict_points` if they are creating a change point detection or outlier detection algorithms. Or, they would implement `_predict_segments` if they are creating a segmentation algorithm. Then `_predict` would either call `_predict_points` or `_predict_segments` depending on the algorithm type.

Your approach sounds like it would makes things simpler.

> Is this properly written up somewhere? I am getting confused.

No it is not.

Re: a transformer pipeline being created for STRAY. Is this because STRAY inherits from BaseTransformer not BaseSeriesAnnotator?

**Comment by Alex-JG3** [comment]
Another thing to keep in mind is that there are inconsistencies amongst the annotators that deliberately have not been broken to avoid undocumented breaking changes. For example:

* Some algorithms still switch between `dense` and `sparse` formats using the `self.fmt` attribute. If `_predict_points` and `predict_segments` were to call `_predict` for these models, then they break if `self.fmt` is `dense`. If we want to make the annotation module more consistent, we need to be prepared to make a breaking change here.
* Some annotators ignore the index type of `X` when making a prediction. Suppose we have a timeseries `X` that has a datetime index. These models will just predict the `iloc` location of the anomaly/change point not the datetime location. This is an issue when calling `sparse_to_dense` or `dense_to_sparse` which require the index to work. Again, I think we need to be prepared to make breaking changes here if we want to make the annotation module more consistent.

**Comment by fkiraly** [comment]
@Alex-JG3, I think I fixed the base interface inconsistencies in #7073 - this seems to leave some issues with date-like indices in the SubLOF anomaly detector - would you mind having a look?

**Pull request merged**
