### PR TITLE
[ENH] homogenization of `sktime` and `skchange` detection API - part 1 - base class and `y` argument

### PR DESCRIPTION
**Pull request by fkiraly**
This carries out the most substantial parts of issue https://github.com/sktime/sktime/issues/7323 to homogenize the `sktime` and `skchange` detection interface, with deprecation & change schedule to ensure downwards compatibility and user warnings.

* `BaseSeriesAnnotator` is changed to `BaseDetector` in the `sktime.detection` module, and in its downwards use. The `BaseSeriesAnnotator`, in its current export locations `sktime.annotation.base` and `sktime.detection.base` remains, but is changed to a child of `BaseDetector` with an added warning.
* signature of `fit` and fit-like methods is changed to take `y` instead of `Y`. As `y` takes the place of `Y`, making positional argument calls downwards compatible. To ensure keyword calls are also compatible, the argument `Y` is patched into `y` internally if passed, such a call raises a warning. To ensure extension contracts remain compatible, internally, we check which inner argument of `_fit` we need to pass `y` to.

### CODE REVIEW

**Comment by fkiraly** [comment]
FYI @mtveten, @Alex-JG3.

@Alex-JG3, it would be great if you could comment how to wrap up your PR to avoid merge conflicts.

**Comment by fkiraly** [comment]
FYI @mtveten, @Alex-JG3, @shivamj07, I am also adding clarification to the docstring that `predict` outputs are `iloc` references. This is how it is consistent with most of `sktime` and `skchange` afaik,

**Comment by Tveten** [comment]
I've compared the sktime detector with the skchange detector and made the following notes

- I agree on the `iloc` references as outputs.
- In skchange, checks include allow_index_names = True because I had issues with allow_index_names = False (the default) having the side effect of removing the index from X outside the class. I guess the best solution is to run checks with defaults, but make sure it doesn't have side effects. I should probably have opened an issue on this before.
- X input type across methods: Should only DataFrames be allowed? In `skchange` both series, data frame and numpy arrays are allowed. I don't have a strong opinion on this.
- We need to agree on the output content of `transform`. In `sktime`, the output depends on the `task`, while in `skchange`, the output is always integer labels.

   * Point anomaly detection outputs 0s at the normal ilocs and 1s at anomaly ilocs. To be consistent with the collective anomalies, each anomaly could get a separate integer label. Not sure if this is necessary.
   * Collective anomaly detection outputs 0s at the normal ilocs and labels 1, ..., K for ilocs inside each of the collective anomaleis.
   * Changepoint detection ouputs labels according to the segmentation provided by the changepoints. That is, labels k = 0, ..., K for ilocs inside each of the segments (cpt[k-1], cpt[k]]. I don't see the need for the 0-1-version of changepoint detection where 1 corresponds to the iloc of a changepoint. But I'm open to be convinced otherwise!

- Should it be transform_scores or predict_score and what should the output contract be? For several of the algorithms in `skchange`, the scores can be both multidimensional and doesn't need to be of the same length as the input X. So I suggest allowing a loose contract, maybe only that it needs to be a pd.DataFrame.

Docs:

- Go over and remove occurces of annotations. For example in .predict:
```
        X : pd.DataFrame
            Data to annotate (time series).
```
to something like (from `skchange`)
```
        X : pd.Series, pd.DataFrame or np.ndarray
            Data to detect events in (time series).
```

I think you mean to tag @Tveten and not Mtveten, btw :)

**Comment by fkiraly** [comment]
Thanks a lot for your detailed review, @Tveten!

May I kindly ask to add a post that converts the above in recommendations of concrete actions, and cluster them in blocking (you think this is critical/crucial), strong opinion, or weak/non-blocking.

**Comment by fkiraly** [comment]
> I think you mean to tag @Tveten and not Mtveten, btw :)

Yes, did you change your GH name at some point, by the way? I have tagged mtveten a lot...

Or am I confused because your discord name is mtveten, and your GH name has always been @Tveten?

**Comment by Tveten** [comment]
> > I think you mean to tag @Tveten and not Mtveten, btw :)
> 
> Yes, did you change your GH name at some point, by the way? I have tagged mtveten a lot...
> 
> Or am I confused because your discord name is mtveten, and your GH name has always been @Tveten?

The confusion is due to the Discord name, I think (which I changed now).

**Comment by fkiraly** [comment]
> The confusion is due to the Discord name, I think (which I changed now).

That's very kind, although I suspect/fear that will just confuse me more. But thanks 😁

**Comment by Tveten** [comment]
Block decisions:

- Make sure check_series(allow_index_names = False) doesn't have side effects. It currently removed the index from the input data X in place.
- Agree on the output content of `transform`. In `sktime`, the output depends on the `task`, while in `skchange`, the output is always integer labels. In `skchange`:

   * Point anomaly detection outputs 0s at the normal ilocs and 1s at anomaly ilocs. To be consistent with the collective anomalies, each anomaly could get a separate integer label. Not sure if this is necessary.
   * Collective anomaly detection outputs 0s at the normal ilocs and labels 1, ..., K for ilocs inside each of the collective anomaleis.
   * Changepoint detection ouputs labels according to the segmentation provided by the changepoints. That is, labels k = 0, ..., K for ilocs inside each of the segments (cpt[k-1], cpt[k]]. I don't see the need for the 0-1-version of changepoint detection where 1 corresponds to the iloc of a changepoint. But I'm open to be convinced otherwise!

- Should it be transform_scores or predict_score and what should the output contract be? For several of the algorithms in `skchange`, the scores can be both multidimensional and doesn't need to be of the same length as the input X. So I suggest allowing a loose contract, maybe only that it needs to be a pd.DataFrame.

Non-block decisions:

- X input type across methods: Should only DataFrames be allowed? In skchange both series, data frame and numpy arrays are allowed.
- Go over and remove occurces of annotations. For example in .predict:
```
        X : pd.DataFrame
            Data to annotate (time series).
```
to something like (from `skchange`)
```
        X : pd.Series, pd.DataFrame or np.ndarray
            Data to detect events in (time series).
```

**Comment by fkiraly** [comment]
@Tveten, I see. Regarding the meaning of `transform`, I think it should be as follows:

* we distinguish `predict_points` and `predict_segments`, but the user implements only `predict`. The `predict_ points` always gives individual points, and `predict_segments` segment-like outputs. Both are important in all cases where they make sense.
* In particular in the change-point identification case, the "point" version is important for metrics. I agree that the default `transform` output should be the `predict_segments`-like output.
* I do not agree with collective anomaly detection, it should be consistent with "normal" anomaly detection. I would go with the choice that makes things most consistent with using the `transform` output as the typical feature generation case. I would make the default 0/1, with 0 = normal and 1 = anomalous, but individual detectors can choose to further cluster the anomalies with non-zero integers.

Regarding the score methods, I would say `transform_score` is the most important one, and let´s have a loose contract only.

**Comment by fkiraly** [comment]
@Tveten, I made the changes with the above small modifications.

**Comment by Tveten** [comment]
> * we distinguish `predict_points` and `predict_segments`, but the user implements only `predict`. The `predict_ points` always gives individual points, and `predict_segments` segment-like outputs. Both are important in all cases where they make sense.

Good.

> * In particular in the change-point identification case, the "point" version is important for metrics. I agree that the default `transform` output should be the `predict_segments`-like output.

Good.

> * I do not agree with collective anomaly detection, it should be consistent with "normal" anomaly detection. I would go with the choice that makes things most consistent with using the `transform` output as the typical feature generation case. I would make the default 0/1, with 0 = normal and 1 = anomalous, but individual detectors can choose to further cluster the anomalies with non-zero integers.

Ok, so no strict contract on 0-1 output, just a default? In case, I would be ok with it.

> Regarding the score methods, I would say `transform_score` is the most important one, and let´s have a loose contract only.

Good.

**Comment by fkiraly** [comment]
> Ok, so no strict contract on 0-1 output, just a default? In case, I would be ok with it.

Yes, maybe we want to introduce a tag for whether it is 0/1 or also "clusters" of anomalies, etc, however I would not do that right now, just adopt a looser contract.

**Pull request merged**
