### PR TITLE
[DOC] Fixed sktime logo positioning in the README

### PR DESCRIPTION
**Pull request by Akhsuna07**
Fixed the position of the image which overlaps with the line.

earlier it was like this 
Screenshot 2024-10-22 151420
Now it is fixed like this 
Screenshot 2024-10-22 151440

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Comment by yarnabrina** [comment]
Thanks for your contribution. This is quite related to https://github.com/sktime/sktime/pull/7257, appears to be a strict subset of changes. Can you please take a look?

**Review by fkiraly — APPROVED** [review]
@yarnabrina, this is not exactly a subset of https://github.com/sktime/sktime/pull/7257, it fixes the formatting issue that went unresolved there. For example, #7257 centers the image, but it should be on the right, below the underline, like in this PR.

**Comment by yarnabrina** [comment]
In that case, @Akhsuna07 you can add yourself in `.all-contributorsrc` with `doc` role as part of this PR itself, and get a badge for your contribution. I've started the CI, and will merge post successful completion.

**Comment by Akhsuna07** [comment]
@yarnabrina Thank you for the suggestion! I'll add myself to .all-contributorsrc with the doc role as part of this PR. Appreciate the acknowledgment, and I'll wait for the CI to complete before you merge it.

**Pull request merged**
