### PR TITLE
[ENH] Implementing plot title for `plot_series`

### LINKED ISSUE #3944: [ENH]Plot Title
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Currently plot_series has no place to enter plot title
**Describe the solution you'd like**
A clear and concise description of what you want to happen, ideally taking into consideration the existing toolbox design, classes and methods.
It would be nice to introduce a user-defined parameter title that user can fill in.
**Describe alternatives you've considered**
None
**Additional context**
None

### PR DESCRIPTION
**Pull request by arnavrneo**
#### Reference Issues/PRs
Fixes #3944

#### What does this implement/fix? Explain your changes.
This implementation updates `plotting.py` under `utils` directory. The function `plot_series` is updated and now the user can enter the **plot title** for the figure. 

#### Changes:
- The function `plot_series` now has one more parameter: `suptitle` (default value is `None`) to which user can give the title of the plot or figure.

#### Does your contribution introduce a new dependency? If yes, which one?
No.

##### For all contributions
:white_large_square: I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
:white_check_mark: I've added unit tests and made sure they pass locally.
:white_check_mark: The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

### CODE REVIEW

**Comment by chillerobscuro** [comment]
Hey @arnavrneo, this looks like a nice new feature! 

Is it necessary to use `suptitle` instead of `title` when this function only makes plots with one `ax`?

Either way I'd suggest calling the argument `title` just to keep the interface as straight forward as possible, even if we do use `suptitle` under the hood.

**Comment by arnavrneo** [comment]
@chillerobscuro Thanks!

About `suptitle` or `title`, I read in the matplotlib documentation; about those two it stated the following:

### `suptitle`
> Add a centered suptitle to the figure.

This adds a self-centered title to the whole figure and not the axes.

### `title`
> Set a title for the Axes.
> Set one of the three available Axes titles. The available titles are positioned above the Axes in the center, flush with the left edge, and flush with the right edge.

This can be used for different axes.

So, as there was just one `ax` in the function, I went with `suptitle`. 

And for the arguments, you're right. It should be straight forward as possible. I'll update the code. So, is it good to go with `suptitle` or `title`?

**Comment by chillerobscuro** [comment]
Only difference I can see is `suptitle` is placed with a bit more spacing above the figure, which I think looks nice. Perhaps a core contributor will give a more weighty decision but IMO this looks good to go now.

**Review by miraep8 — APPROVED** [review]
Seems like a pretty straightforward change and it works for me.  Congrats on making your first contribution @arnavrneo Will merge tomorrow as long as there are no other change requests in the mean time!  You are also welcome/encouraged to add yourself to the list of contributors! :)

**Comment by arnavrneo** [comment]
Thanks!
I've one doubt. For adding myself to the contributor list, do I need to directly edit `.all-contributorsrc`?

**Comment by miraep8** [comment]
Hey @arnavrneo - congrats on making your first contribution to sktime! 

Apologies I merged this before you were properly added as a contributor, and I am sorry for not answering your questions before!  In short - yes - you can add yourself to that document! :)  You can either: a) do it yourself in a new PR, b) tack it on to your next PR to sktime or c) I can add you for you! :) 

Welcome to sktime again! :) 🎉 🎉 🎉

**Comment by arnavrneo** [comment]
No worries @miraep8! 

Okay, I got it now. I've created #4074. Can you please review it?

Thank you!

**Pull request merged**
