### PR TITLE
[MNT] replace `proba` module by `skpro` - diagnostic to ensure API consistency

### PR DESCRIPTION
**Pull request by fkiraly**
DO NOT MERGE

This PR carries out a naive replacement of `sktime`'s `proba` module by `skpro` (`distributions`), current `main` which has the unreleased upgrade of probability distribution objects.

The purpose is to check that the public API remains unchanged, regarding the parts required by `sktime`.

### CODE REVIEW

**Comment by fkiraly** [comment]
FYI @Alex-JG3, @frthjf, @malikrafsan, @ShreeshaM07, @yarnabrina

**Comment by fkiraly** [comment]
takeaways:

* interface-wise, direct replace is possible without problems from current `skpro` main
* minor issues where `sktime` checks inheritance from `BaseObject` - this needs to be changed from `sktime` `BaseObject` to `skbase` `BaseObject`, as these are distinct classes

**Comment by frthjf** [comment]
Neat! Is the plan to release this in the future or will skpro remain an optional dependency in sktime?

**Comment by frthjf** [comment]
Sorry, just saw that you've already discussed this in https://github.com/sktime/sktime/issues/6396. Will comment over there.

**Comment by fkiraly** [comment]
has served its purpose

**Pull request closed without merging**
