### PR TITLE
[ENH] Feature importance capability tag for classifiers

### LINKED ISSUE #5649: [ENH] feature importance capability tag for time series classifiers
There do not seem to be many sktime classifiers which can produce feature importances. Searching the docs to find them does not seem very efficient, and this information may change over time.

It would be nice if sktime's `all_tags()` had a boolean-valued tag for something like "Can provide feature_importances?", to assist the user in finding suitable functions.

### PR DESCRIPTION
**Pull request by sanjayk0508**
#### Reference Issues/PRs
fixes #5649 

#### What does this implement/fix? Explain your changes.
The implementation of `capability:feature_importance` will enable developers to identify classifiers containing `feature_importance`, using `all_tags()` or `all_estimators` developers can effortlessly fetch all classifiers which can provide feature importance.

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Comment by fkiraly** [comment]
Thanks!

Tipp: if you use "closing keywords" like "fixes #5649", then GitHub automatically links this PR to the issue, and closes the issue when the PR is merged.

**Comment by fkiraly** [comment]
hm, are there really only two such estimators? Not a very discriminative tag then...

**Comment by sanjayk0508** [comment]
> hm, are there really only two such estimators? Not a very discriminative tag then...

Yes, there aren't many classifiers that can provide feature importance (even I didn't expect that), though I thought it would be a useful good-first issue to solve.

**Review by fkiraly — APPROVED** [review]
Thanks!

**Pull request merged**
