### PR TITLE
[BUG] Fixes 1788 - Add statsmodels append() to _update() in _StatsModelsAdapter

### PR DESCRIPTION
**Pull request by chillerobscuro**
#### Reference Issues/PRs

Fixes [1788](https://github.com/sktime/sktime/issues/1788)

#### What does this implement/fix? Explain your changes.

When `update_params=False`, calling `update` with any `_StatsModelsAdapter` model does not work as expected. This PR changes behavior only when `update_params=False` and `self.is_composite=False`, and now uses the `statsmodels` `append` functionality to add new observed data without refitting the model.

#### Does your contribution introduce a new dependency? If yes, which one?

No
#### What should a reviewer concentrate their feedback on?

The following outstanding questions
#### Any other comments?

1. For now if the user doesn't pass data with the correct index to `update()`, they will get the error message from `statsmodels` that `ValueError: Given endog does not have an index that extends the index of the model.` I could add functionality to check if the updated data intersects with the original data and only take the new subset, but could use advice on which data types we would need to handle (pandas only? also numpy? etc).
2. In the base `update()` method, if `self._is_vectorized=True`, then `_vectorize("update", ...)` is called instead of `_update()`. Do we need to add logic to handle this case?
3. Do we need to update the logic if both `self.is_composite=True` and `update_params=False`? This PR does not affect current behavior in the composite case.

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

### CODE REVIEW

**Comment by chillerobscuro** [comment]
The test failed as only the "state space" family of `statsmodels` have the `append` method. For the classes in our wrapper this means:
    Models with `append` support: [SARIMAX, DynamicFactor, VARMAX, UnobservedComponents]
    Models without: [ExponentialSmoothing, AutoETS, ETS, VAR, VECM]

`statsmodels` does have state space implementations of the Exponential smoothing models, with slightly limited performance and functionality (no multiplicative models). But our wrapper calls the dedicated ES model instead.

Seems worthwhile to implement the fix in this PR as it will improve the `update()` method of several models. We can also add warning to the rest of the models that there is no true update without a refit. If this sounds right, how should I check which model is calling `_update`? I can create a list like that above and compare with `type(self._fitted_forecaster)`, but there is likely a cleaner way.

**Comment by fkiraly** [comment]
> If this sounds right, how should I check which model is calling _update?

The idea is to do this in `update`, not `_update`, see https://github.com/sktime/sktime/issues/1788, what I wrote:

>I would suggest to do the following in a separate PR (which you merge into this):
move the warning to update in BaseForecaster, and raise it only when the _update method is overridden. This can be checked by self._has_implementation_of("_update").

I would do this in a separate PR though.

**Comment by chillerobscuro** [comment]
This fix now passes the tests and improves results of `update()` and `update_predict()`, for example:
```
from sktime.forecasting.sarimax import SARIMAX
from sktime.datasets import load_airline

y = load_airline()
ytrain, ytest = y[:110], y[110:125]

model = SARIMAX()
model.fit(ytrain)
test_data_to_plot = model.update_predict(ytest, update_params=False)
```
image ---> image

`update()` was fixed with the first commit but to fix the behavior for `update_predict()`, this code now takes the set difference of the data passed in and the data the model has already seen using `pandas.Index.difference()`. This code only affects models within the `_StatsModelsAdapter` class, when `update_params=False`.

**Review by fkiraly — APPROVED** [review]
Looks good, nicely done!

**Pull request merged**
