### PR TITLE
[BUG] Expected fix in `_check_predict_proba` #5349 

### LINKED ISSUE #5349: [BUG] `test_predict_proba` is expecting column name of `pred_dist` to be `0` always.
**Describe the bug**

All the tests in `check_estimator` are expecting column names to be preserved, while a single test `check_predict_proba` function, invoked inside `test_predict_proba`, in `sktime.forecasting.tests.test_all_forecasters.py` is expecting column name of `pred_dist` i.e., the output of `predict_proba`, to be `0` always.

**To Reproduce**

location: [here](https://github.com/sktime/sktime/blob/12d2770c213382f1ee99bb05a03f19e7ab4cb5e6/sktime/forecasting/tests/test_all_forecasters.py#L529).
```python
# existing code
if isinstance(y_train, pd.Series):
    assert (pred_cols == pd.Index([0])).all()
else:
    assert (pred_cols == y_train.columns).all()

# expected code
if isinstance(y_train, pd.Series):
    assert (pred_cols == y_train.name).all()
else:
    assert (pred_cols == y_train.columns).all()
```

**Expected behavior**

The function mentioned above has to be modified such that, it checks for column names of `y_train`, `pred_dist`, like rest of the tests.

**Additional context**

Any changes in this test will affect existing univariate probabilistic forecasters such as `NaiveForecaster`. Therefore, fixing this issue also requires necessary changes in all the univariate probabilistic forecasters.

### PR DESCRIPTION
**Pull request by Vasudeva-bit**
#### Reference Issues/PRs

Fixes #5349

#### What does this implement/fix? Explain your changes.

Changes a if (check) condition in `_check_predict_proba` function of `sktime/forecasting/tests/test_all_forecasters.py` to preserve column name in univariate forecaster predictions.

Upon fixing this issue, `ARCH` doesn't require function `_predict_proba` as `BaseForecaster`'s `_predict_proba` is sufficient. Hence, removed that function.

#### What should a reviewer concentrate their feedback on?

A few tests are expecting name to be preserved even if it is `None`, [here](https://github.com/sktime/sktime/blob/12d2770c213382f1ee99bb05a03f19e7ab4cb5e6/sktime/utils/_testing/forecasting.py#L138). Thats why I didn't handle the `None` case separately. If the expected column name is `0` when original name is `None`, below code may be appropriate as recommended by @yarnabrina.
```
if isinstance(y_train, pd.Series) and y_train.name:
    assert (pred_cols == y_train.name).all()
elif isinstance(y_train, pd.Series):  # automatically implies empty name
    assert (pred_cols == pd.Index([0])).all()
else:
    assert (pred_cols == y_train.columns).all()
```

**Additional context**

Any changes in this test will affect existing univariate probabilistic forecasters only such as `NaiveForecaster`.

##### For all contributions
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

### CODE REVIEW

**Comment by fkiraly** [comment]
I've updated this PR with code along the lines suggested. I will turn on tests for all forecasters so we can see what happens.

**Comment by fkiraly** [comment]
Ok, I'm confused now - nothing else seems to fail. Any explanations?

**Comment by Vasudeva-bit** [comment]
After debugging for a while,
1. Firstly, the function `_check_predict_proba` is only testing for `y_train` generated from `_make_data(n_columns=n_columns)`. If the forecaster is univariate, then the `y_train` generated would always have column name `None` of type `str`. The `_check_predict_proba` checks whether the `_predict_proba` is changing `None` to `0` internally. Since every forecaster's `_predict_proba` doing it, all forecasters passed.
2. Actually `ARCH` should fail this test, because `_predict_proba` function is deleted in this PR. But, the `type(y_train.name)` is `str` (`'None'`), not `None`. Therefore, `None` case is skipped and checks whether `(pred_cols == y_train.name).all()` which is `None` of `str` equals `None` of `str` so, `ARCH` also passed.

I think it's my bad, there is no bug in `_check_predict_proba` as it is not designed to check whether column names are preserved. Changes should only be in `ARCH`'s `_predict_proba` like below:
1. If the column name is `None` of type `None`/`str`, do `pred_dist.name = pd.Index([0])`.
2. Otherwise, just return output of `Super()._predict_proba()` as it is, i.e., column names are preserved by default.

Hope it makes some sense now.

**Review by fkiraly — APPROVED** [review]
I see, so the issue was after all isolated to uarch - makes sense. Lets merge this as a fix then.

**Pull request merged**
