### PR TITLE
[BUG] Set batch size to 2 for pytorch forecasting

### PR DESCRIPTION
**Pull request by benHeid**
#### Reference Issues/PRs
towards #6922 

#### What does this implement/fix? Explain your changes.
* Set explicitly a batch size
* Reduce the size of DeepAR

### CODE REVIEW

**Comment by fkiraly** [comment]
hm, these are still failing, on 3.10?

**Comment by benHeid** [comment]
Yes.. I am unsure if this error is coming from some specific stuff in PyTorch... I updated the commit and trying PyTorch 2.3.1 instead of PyTorch 2.4.0, which was installed when the TFT was merged..

It seems that `_engine_run_backward ` is causing the error, which calls c++ code.

**Comment by Xinyu-Wu-0000** [comment]
https://github.com/sktime/sktime/blob/0803e2fde4d7bad07964430b9b2abf7697aa0506/sktime/forecasting/tests/test_all_forecasters.py#L1136-L1144

This data size could be reduced too.

**Comment by benHeid** [comment]
Closing since it was not fixing the timeouts

**Pull request closed without merging**
