### PR TITLE
[MNT] update `statsforecast` version in `forecasting` extra

### PR DESCRIPTION
**Pull request by yarnabrina**
PR #5920 intended to update bounds for `statsforecast` in all dependency specifications. As noted in #6057, it was done only in `all_extras` and `all_extras_pandas2`. This PR updates it for the missed single component optional dependency `forecasting`.

### CODE REVIEW

**Comment by fkiraly** [comment]
why did dependabot not catch this?

**Comment by yarnabrina** [comment]
I don't know why, but I noticed it never does for dependencies that have python version markers.

**Comment by fkiraly** [comment]
strange, but interesting observation

**Comment by yarnabrina** [comment]
CI took more than 18 hours, but it's finished finally. Ready for review+merge.

**Comment by fkiraly** [comment]
... why did it take 18 hours???

**Comment by yarnabrina** [comment]
All jobs were queued for about 10 hours. I don't know why, but don't think it's caused by new CI or this PR changes.

**Comment by fkiraly** [comment]
> As you explained earlier, job creations and setups takes a very significant time.

We should somehow address this, for PRs like this. Clogging the CI pipeline for half a day is not good.

**Comment by yarnabrina** [comment]
Agreed, triggering all tests even though mostly they do nothing but install is the culprit, and will happen for all PR's that modify pyproject.toml even slightly (I think, though I'm not 100% sure on that). Other than waiting for #5477 or #5719, not sure what to do, and those will need some good focused time which I currently lack.

**Review by fkiraly — APPROVED** [review]

**Pull request merged**
