### PR TITLE
Revert "[DOC] Update README.md"

### PR DESCRIPTION
**Pull request by aiwalter**
Reverts alan-turing-institute/sktime#3480

### CODE REVIEW

**Comment by aiwalter** [comment]
there was no link changed only package name, which was a wrong change

**Comment by fkiraly** [comment]
but the link works now. `fbprophet` is just the link alias, and that is how it´s referenced, too?

**Comment by fkiraly** [comment]
@aiwalter, I'm confused - wouldn't the revert break the link again?

**Comment by fkiraly** [comment]
I tested the link and it works now. It would break with the revert.
No comment was posted since a month.

I therefore assume this revert was made in error.

**Pull request closed without merging**
