### PR TITLE
&fkiraly [ENH] `Imputer`: docstring clarity improvement, conditional parameter handling logic

### PR DESCRIPTION
**Pull request by aiwalter**
updated content and description by @fkiraly

Minor improvements to `Imputer`:

* updates to the docstring to clarify conditionnality of parameters
* various corrections to the docstring
* change to parameter check logic so setting of conditional parameters is allowed when they are ignored, e.g., setting `forecaster` if `method` is not `"forecaster"`, and tests for this

---

#### What does this implement/fix? Explain your changes.
This changes the exception for `method="constant"` to always accept a `value` that is not `None`. This is required to make grid search over the `method` param and at same time give a `value` value.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
* the precise dependency of parameters should be commented on in the docstring, i.e., forecaster will not be used or value will not be used
* I would still raise a warning under the condition you removed
* the test should not remove coverage of previous cases

**Comment by fkiraly** [comment]
also, please write proper pull request descriptions.

* what exception is being changed?
* what is the precise condition prior and post?
* what you write in the PR description is not congruent with the content of this PR

**Comment by fkiraly** [comment]
and please attach the correct tags to the PR, e.g., `module:transformations` and `enhancement`

**Comment by aiwalter** [comment]
closing due to #4153

**Comment by fkiraly** [comment]
reasonable contribution, but needs:

* clear PR description
* docstring commenting on dependency of parameters
* ensure test coverage
* careful look at handling of warnings/exceptions

**Comment by fkiraly** [comment]
the delta is not big, someone else could look at it or I will at some point

**Comment by fkiraly** [comment]
(tests passed in job masked by "update contributors"

**Pull request merged**
