### PR TITLE
[BUG] Make EnsembleForecaster work with multivariate data

### LINKED ISSUE #3621: [BUG] Ensemble forecaster fails on multivariate data
**Describe the bug**

The `EnsembleForecaster` fail when ensembling multivariate forecasting models. 

This is because `EnsembleForecaster` has the `"scitype:y": "univariate"` tag which means that the ensemble forecaster is fitted on each column separately. But multivariate forecasting models such as VAR assume that all columns are passed.

**To Reproduce**

```python
from sktime.forecasting.compose import EnsembleForecaster
from sktime.forecasting.exp_smoothing import ExponentialSmoothing
from sktime.datasets import load_longley
from sktime.forecasting.var import VAR

# load data
_, y = load_longley()

# run ensembler
forecaster = EnsembleForecaster(
    forecasters=[("var1", VAR()), ("var2", VAR())],
    aggfunc="mean"
)
forecaster.fit(y)
forecaster.predict(fh=[1,2,3])
```

**Expected behavior**

The ensemble forecaster should ensemble all models without any failure.

**Additional context**

**Versions**
```raw
System:
    python: 3.8.9 (default, Oct 16 2021, 12:00:06)  [Clang 12.0.0 (clang-1200.0.32.29)]
executable: /Users/anhoang/Scratchpad/.venv/bin/python
   machine: macOS-12.5.1-x86_64-i386-64bit

Python dependencies:
          pip: 22.3
   setuptools: 49.2.1
      sklearn: 1.1.2
       sktime: 0.13.4
  statsmodels: 0.13.2
        numpy: 1.22.4
        scipy: 1.8.1
       pandas: 1.5.1
   matplotlib: None
       joblib: 1.2.0
        numba: 0.56.3
     pmdarima: None
      tsfresh: None
```

</details>

### PR DESCRIPTION
**Pull request by AnH0ang**
#### Reference Issues/PRs

Fixes #3621. 

#### What does this implement/fix? Explain your changes.

There are two problems why `EnsembleForecaster` failed when ensembling multivariate forecasting models:

1. The tags were set to `"scitype:y": "univariate"` which meant that only series were passed to the underlying ensembling models.
    * This was changed to `"scitype:y": "both"`
2. The method in which aggregated the predictions assumed that the model predictions are univariate.
    * This was also changed
    
#### Does your contribution introduce a new dependency? If yes, which one?

No

#### What should a reviewer concentrate their feedback on?

On the `_predict` method of the `EnsembleForecaster`. This is where the major changes took place.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [x] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] I've added unit tests and made sure they pass locally.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [x] I've added the estimator to the online documentation.
- [x] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by fkiraly** [comment]
the CI failures are probably unrelated, see https://github.com/sktime/sktime/pull/3624

with the temporary removal of the cause of failure (unrelated to this PR) it should now run through

**Review by fkiraly — CHANGES_REQUESTED** [review]
Excellent, thanks!
Really neat extension to multivariate and hierarchical.

One minor (but blocking) questions:
* why are you adding yourself as the author to the time series forest regression ensemble? You didn't do anything there, probably confused with the forecasting ensemble?

Non-blocking requests:
* we switched the author convention to GitHub IDs, would you mind replacing Markus Loning by @mloning if you are already changing that line?
* would you like to add yourself to the `.all-contributorsrc` file with a `code` contribution?

**Comment by AnH0ang** [comment]
Thank you for pointing that out @fkiraly! I just changed the PR based on your comments.

**Comment by fkiraly** [comment]
but now you accidentally (?) removed yourself as an author from the `_ensemble` file? You should be there, since you have added substantial functionality in there.

**Pull request merged**
