### PR TITLE
[DOC] Examples webpage

### LINKED ISSUE #2812: [DOC] sktime docs should link clearly to example notebooks
It seems that the sktime user journey does not lead clearly to the example notebooks when starting on the doc page.

This should be investigated and reworked.

Related issue: https://github.com/alan-turing-institute/sktime/issues/2127

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
Implements an examples webpage in the style of [sklearn](https://scikit-learn.org/stable/auto_examples/index.html) for all of the notebooks in the examples directory and adds it to the table of contents. This should close #2812, unless people believe there should be an even clearer link from the index page.

Read The Docs (may need to refresh with updates): https://sktime-mm.readthedocs.io/en/rtd/examples.html

### CODE REVIEW

**Comment by miraep8** [comment]
I know it is still a draft, so I didn't do a deep review, but checked out the read the docs preview and just wanted to say I think it looks really cool!  Great idea! :)  Would love to loop in any notebooks that people generate as part of the dev days into this page. 👍

**Review by fkiraly — DISMISSED** [review]
We need to make sure that we don't accidentally drop notebooks, like the advanced forecasting notebook.

I would also put classification and regression together.

**Comment by MatthewMiddlehurst** [comment]
I just put everything in the examples folder on the page, are there notebooks elsewhere or did I miss one?

Can swap regression and clustering so they are closer, I don't think they should be a single section (currently at least).

**Comment by MatthewMiddlehurst** [comment]
@miraep8 That was the intention, can either keep this PR up and merge it at the end or merge it and add to it as new notebooks are created.

**Comment by MatthewMiddlehurst** [comment]
Also, if anyone has suggestions for thumbnails feel free to add. It can be an image file or a code cell output.

**Comment by fkiraly** [comment]
> I just put everything in the examples folder on the page, are there notebooks elsewhere or did I miss one?

`01c_forecasting_hierarchical_global`

**Comment by MatthewMiddlehurst** [comment]
Looks like its there to me, https://sktime-mm.readthedocs.io/en/rtd/examples/forecasting/01c_forecasting_hierarchical_global.html (though the image in it seems to be broken)

notebooks which are not currently used in https://sktime-mm.readthedocs.io/en/rtd/user_guide.html have been put in subfolders.

**Review by TonyBagnall — APPROVED** [review]

**Pull request merged**
