### PR TITLE
[DOC] Miscellaneous aesthetic improvements to docs UI

### PR DESCRIPTION
**Pull request by duydl**
#### What does this implement/fix? Explain your changes.

- [ ] Add "theme-switcher" to navbar: Allow to switch between dark and light mode. 
- [ ] Remove search-field from left sidebar: The search field on left sidebar is confusing in term of UX.  When users click on the search bar on the top right, the cursor instead jumps to the left search bar. The default global search overlay is better and used by all docs with pydata-theme, also considering that search directs to a new page. 
- [ ] Change some icons with white background to transparent. They are apparent in dark mode. I happened to have a quick script for that. 
- [ ] Remove some empty left sidebars like of homepage. 

If the PR seems inconsequent I am sorry. I made these changes when testing the docs and still left them around. Figure there is no harm in some aesthetic improvement. If any changes not approved i would just revert them.

### CODE REVIEW

**Comment by yarnabrina** [comment]
> Remove search-field from left sidebar

Thanks a lot, I got confused by this thing countless times.

> Remove some empty left sidebars like of homepage

I think you can consider this for search results page too.

I didn't really notice any of your other changes, but I don't see any issues myself.

**Comment by duydl** [comment]
> I didn't really notice any of your other changes, but I don't see any issues myself.

It mostly relates to this, dark light mode switching and remove the white bg for dark mode page and browser. 
darklight

**Review by yarnabrina — APPROVED** [review]
Based on my experience with the UI, I'm approving the changes. Can not review the code changes itselves.

Two user perspective feedbacks if it can be improved in this PR or in a different one. Please let me know if it's out of scope or just not possible.

1. The icons get reorganised in a weird way depending on screen width. If there's a way to make this better, it'd be nice. I attached the screenshot below, as you can see the top bar height got increased the buttons got rearranged in 2 rows in a somewhat weird way (I would have expected all in one row probably, but don't feel very strongly).
2. Currently `sktime.net` does not work, but `www.sktime.net` does. Is it something that can be fixed?

image

**Comment by duydl** [comment]
> The icons get reorganised in a weird way depending on screen width. 

Other docs with pydata-theme have the same behavior too i.e https://numpy.org/devdocs/index.html https://pydata-sphinx-theme.readthedocs.io/en/latest/ . So I think it is likely out of scope for sktime.

> Currently sktime.net does not work, but www.sktime.net does. Is it something that can be fixed?

I think it could fixed on either RTD settings panel or the DNS provider for www.sktime.net though it is nothing I could do about. On RTD  Admins > Domains, adding sktime.net may resolve it if it registered, else there must be redirect setting on DNS providers

**Comment by yarnabrina** [comment]
Ok, I'm happy to merge when @fkiraly announces end of feature freeze.

@fkiraly can you also check if you get any such option?

> > Currently sktime.net does not work, but [www.sktime.net](http://www.sktime.net/) does. Is it something that can be fixed?
> 
> I think it could fixed on either RTD settings panel or the DNS provider for [www.sktime.net](http://www.sktime.net/) though it is not something I could do. On RTD Admins > Domains, adding sktime.net may resolve it if it registered, else there must be redirect setting on DNS providers

**Comment by fkiraly** [comment]
> @fkiraly can you also check if you get any such option?

What option? To merge?

Too late to check...

**Pull request merged**
