### PR TITLE
[ENH], [BUG]: Adds 27 fpp3 datasets; fixes/enhances plot_series(); stl decomposition plot; predict_interval() for polynomial forecaster

### LINKED ISSUE #5895: [BUG] Specification of xticks for matplotlib axis returned by plot_series does not work as expected
plot_series does some internal manipulations that seems to confuse matplotlib.dates utilities such as YearLocator()

The first code block below creates a plot that puts an xtick and xticklabel at every Jan. 1. YearLocator() finds these points. It works.
The code calls plot() and scatter() directly. In the succeeding code block the plotting is  done with plot_series(). After that the YearLocator() function does not work as expected.

```
import matplotlib.dates as mdates
y = load_airline()
y.index = y.index.to_timestamp()
fig1b, ax1b = plt.subplots()
ax1b.plot(y, label="all")
y_jan = y[y.index.month == 1]
plt.scatter(y_jan.index, y_jan.values, label="Jan", marker="o")
plt.legend()
years = mdates.YearLocator()   # every year
ax1b.xaxis.set_major_locator(years)
ax1b.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
plt.show()

```

```
import matplotlib.dates as mdates
fig4, ax4 = plt.subplots()
ax4 = plot_series(y, y_jan, labels=["all", "Jan"], markers=["", "o"], ax=ax4)
plt.legend()
years = mdates.YearLocator()   # every year
ax4.xaxis.set_major_locator(years)
ax4.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
plt.xticks(rotation=90)
plt.show()

```

### PR DESCRIPTION
**Pull request by ericjb**
#### Reference Issues/PRs

Fixes #5895

#### What does this implement/fix? Explain your changes.
1. Adds 27 datasets from Hyndman's fpp3. User entry point is sktime.datasets.load_fpp3().  The returned object has appropriate mtype with multiindex as required. The load_fpp3() function could be of interest to the broader Python community, including those not otherwise using sktime. See the accompanying pdf for details.
2. Adds a new method STLForecaster.plot_components() to plot the STL decomposition
3. sktime.utils.plot_series() now handles xticks following matplotlib defaults. (Fixes #5895) As a result fig,ax objects returned by plot_series() can be used correctly by matplotlib. See accompanying pdf for details including some before and after plot comparisons. 
4. Implemented predict_interval() method for sktime.forecasting.PolynomialTrendForecaster. Note that the intervals are computed based on Hyndman's formulas in FPP3 (Section 7.9). 
5. Fixed (or enhanced) sktime.utils.plot_series() so that it can plot multiple coverage levels if present in the pred_interval multiindex.

#### Did you add any tests for the change?
No.
#### Any other comments?
A reviewer should read the attached pdf that provides details. There is considerable information there, including details about the datasets and code examples for the new functionality (and bug fixes).

##### For all contributions
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.
[PullRequestNotes.pdf](https://github.com/sktime/sktime/files/15272479/PullRequestNotes.pdf)

### CODE REVIEW

**Comment by fkiraly** [comment]
This is excellent! Lots of useful contributions!

May I suggest to split these up into multiple PR, I would say four or five?

That makes it much easier to review, since this PR touches topics which need different reviewers etc.

I would suggest to leave this branch open until things are split into multiple PR, to avoid overwriting or deleting things by accident.

**Comment by ericjb** [comment]
I need some guidance on the Git issues related to doing the multiple PRs. i) would these all be relative to the same sktime branch? ii) if so, which branch? and iii) how do I start from that branch? [If the Git issues are a problem maybe it's not so bad to coordinate with the multiple reviewers?]

**Comment by fkiraly** [comment]
all PR should have their individual branches, and make PR to `main` - not another feature branch.

That should mean we have five feature branches, e.g., `hyndman-fpp-datasets`, `stl-plot`, etc, each with an associated PR to `sktime:main`.

Your fork's `main` now contains all changes, so this might be a bit tricky. Options:

* create a new fork and add the branches, changes, incrementally
* create a branch on your fork, e.g., `sktime-main` which is in sync with `sktime` main, leave `ericjb:main` intact. Branch off that branch, `ericjb:sktime-main`, with 5 branches corresponding to the parts, and PR to `sktime:main`.

If you are not sure how to do this, you can ask in `dev-chat`, or attend a meetup (1pm UTC, i.e., in a few minutes today or next week) for screensharing.

**Comment by fkiraly** [comment]
PS: I realize it might be slightly painful because everything is on your `main` - though it's a very very useful mini-workflow to learn, especially for someone as productive as you who has multiple ideas to work on at the same time! It's the only way to avoid a certain kind of catastrophic interaction from not separating too many innovations at once in the repo. `sktime` would long be collapsed if the core devs would not be doing that.

**Comment by fkiraly** [comment]
I thought of a third option, bit hacky but perhaps easiest to carry out:

* take your current `ericjb:main`
* make a branch for every featuer branch in the end
* in that branch, *copy the files from `sktime` `main` over the files you do not want to change*, commit
* make PR from all such branches to `sktime`

**Comment by ericjb** [comment]
I need some minor help with git. A few emails with a git expert should help resolve my issues and I will be able to take it from there. Thanks

**Comment by fkiraly** [comment]
sure! If you can make it on our discord, you can catch one of the core devs, and I am sure we can sort it in 10-20min of direct exchange.

Discord link: https://discord.com/invite/54ACzaFsn7

**Comment by fkiraly** [comment]
Also, related;

git_2x

**Comment by fkiraly** [comment]
👋 😃

**Comment by ericjb** [comment]
Thanks. 🙂 
I am getting back to sktime after completing some other projects. I am not sure why this PR got triggered - it was not intentional. I will be revisiting a couple of previous PRs that have been in limbo. Hopefully in the next few days.

**Pull request closed without merging**
