### PR TITLE
[MNT] CI element to test blogpost notebooks

### PR DESCRIPTION
**Pull request by fkiraly**
This PR adds a CI element to test blogpost notebooks for executability.

### CODE REVIEW

**Comment by fkiraly** [comment]
@yarnabrina, can I kindly ask for your help?

I wrote a GHA step and a bash script to execute the blog post notebooks, but it errors out - I do not understand why, I copied the bash script and the workflow element.
Do you perhaps understand why?

**Comment by yarnabrina** [comment]
@fkiraly I fixed the permission error using `chmod +x build_tools/run_blogposts.sh` and now the CI step at least start running (ref. https://github.com/sktime/sktime/actions/runs/7326558154/job/19952390536?pr=5663).

However it fails because of outdated imports, and I am not sure whether we should update the notebooks or keep them as it is for reference to original blogs. (FYI @onyekaugochukwu)

**Comment by fkiraly** [comment]
Yes, interesting question, what the procedure here is - this is a genuine failure case. I imagined the purpose of these noteoboks to get a warning when first and second party material gets outdated due to interface changes.

0.25.0 updates the location of `temporal_train_test_split`, to `sktime.split`, and the old location is no longer available - that is what causes failure.

I suppose in such a case, should ask the author to update? (not simply update the notebook)
FYI @onyekaugochukwu, @joanlenczuk

We could also leave `temporal_train_test_split` in the old location (for some more time, or forever) - 0.25.0 is not released yet.
Since it is a frequently occurring import, perhaps just leave it there forever, to allow legacy code to work?

**Comment by fkiraly** [comment]
PR https://github.com/sktime/sktime/pull/5667 restores the old export location of `temporal_train_test_split` and should delay the question.

**Pull request merged**
