### PR TITLE
[MNT] simplified CI - merge windows CI step with test matrix

### PR DESCRIPTION
**Pull request by fkiraly**
This PR simplifies the CI setup, by merging the windows CI step into the test matrix.

As a side effect, this removes the dependency on conda in the windows CI.

### CODE REVIEW

**Comment by achieveordie** [comment]
Thanks for the PR, Is there a reason this wasn't done in the first place?

**Review by yarnabrina — APPROVED** [review]
Approved. And as @achieveordie said above, I am also wondering why was it different earlier. Are there some special requirements for windows setup, may be for specific soft-dependencies?

PS: This is also being done as part of #5304.

**Comment by fkiraly** [comment]
> Thanks for the PR, Is there a reason this wasn't done in the first place?

no idea. Probably at one point in earlier days of GHA, windows didn't play game.

**Comment by fkiraly** [comment]
> PS: This is also being done as part of https://github.com/sktime/sktime/pull/5304.

Great minds think alike :-)

I needed to get rid of conda in the CI for pyhon 3.12, and this seemed like the cleanest fix on top of that requirement.

**Pull request merged**
