### PR TITLE
[ENH] Enable `TimeSince` trafo to transform multiindex dataframes directly

### PR DESCRIPTION
**Pull request by KishManani**
#### What does this implement/fix? Explain your changes.
This PR:
1.  allows the `TimeSince` transformer to operate directly on the time index of multi-index dataframes. This should give a performance boost when working with panel and hierarchical data.
2. simplifies the logic in `transform` and removes an unnecessary resampling of the dataframe when the index is of type `DateTimeIndex`. 
3. removes unnecessary copying of `X` unless `keep_original_columns=True`, in which case a copy of `X` is made so that we can return the original columns.

#### What should a reviewer concentrate their feedback on?
The use of `get_period_alias` to make it easier to convert from a datetime index to a period index.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [x] I've added unit tests and made sure they pass locally.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

### CODE REVIEW

**Review by fkiraly — DISMISSED** [review]
Makes sense to me - fine once the tests pass,

(you are yourself the author, so no author approval needed)

**Comment by fkiraly** [comment]
Re `get_period_alias`, it seems to make sense what you are doing - although in my experience `pandas` is capricious when it comes to `freq` and the devil is in the detail. To the extent I grasp what you are doing, I can spot no issue.

**Comment by KishManani** [comment]
Update:

I think this issue in Pandas https://github.com/pandas-dev/pandas/issues/36939 could cause problems if they change the behaviour of this method. To mitigate this I've added a test for when the data has weekly granularity starting on a Wednesday. If Pandas change the behaviour of `get_period_alias` to fix the issue attached (it's been open for 2 years now it seems) then the added test should fail.

**Review by fkiraly — APPROVED** [review]
Makes sense.
Together with the defensive bound for `pandas`, users should be safe and we should be able to detect it at release time.

**Pull request merged**
