### PR TITLE
[DOC] updated `dtw_distance` docstring example to include import

### PR DESCRIPTION
**Pull request by JonathanBechtel**
#### Reference Issues/PRs
Adds to #4264

#### What does this implement/fix? Explain your changes.
I updated the `dtw_distance` example to include the actual import.  This way someone can copy and paste the example given on the website and re-use it.

#### Does your contribution introduce a new dependency? If yes, which one?
No

#### What should a reviewer concentrate their feedback on?
Make sure the example in the docstring can be re-used if copied and pasted directly into a python file.

#### Did you add any tests for the change?
Since it's just an example I didn't add a test.

#### Any other comments?
This fixes a small pet peeve of mine with the current documentation, which is that the actual import for the technique is often not listed in the example, so you can't just copy and paste from the API reference to see how it works.  This inconvenience is compounded by the fact that the actual imports you need to use are often irregular and can't be easily inferred from the way different methods are listed in the API docs.  So you often have to go on a bit of a chase just to figure out how to import something.  

I know a lot of the distance / kernel calculations do NOT include the import, which makes it unnecessarily difficult for someone new to the library to just grab an example and go.  

This might need to be a separate issue from #4264 since it's enhancing existing documentation, but for now I put it under that.  

It'd also be relatively simple to fix this, since most of the distance and kernel calculations are contained within a few files and you could add the imports fairly quickly. 

It might also be worth nothing that a potential 3rd example could be used for time series examples with different lengths.  Right now all of the examples only use equilength time series, but it might be instructive to demonstrate how calculations like dtw can be used on time series with dissimilar shapes, since it might not be obvious to people that this is possible.  For instance, with the 2D example you can transpose one of the time series and still get a result.

##### For all contributions
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

### CODE REVIEW

**Comment by JonathanBechtel** [comment]
I realized I made a mistake when I deleted `compose.py`.  I was thinking that I'd remove it from the PR, not remove it from the actual codebase.  Not sure if it's easier for the reviewer to reinstate it or for me just to create an entirely new PR without the faux pas.

**Comment by fkiraly** [comment]
The best way would be to revert your latest commit which deletes the file.

Second best way: since PRs are squashed to a single commit to main, you can simply copy the file from main and commit it, but this is quite hacky.

**Comment by JonathanBechtel** [comment]
Ok, fixed.

**Review by fkiraly — APPROVED** [review]
makes sense, thanks.

I wonder how this could be tested in general, i.e., missing import in a doctest. It seems the test will pass since the module imports are present, but the user will miss it so the code will fail.

**Comment by JonathanBechtel** [comment]
Agreed.  More of a usability issue than a code issue, but I see these omissions a lot throughout sktime documentation and it does throw sand in the gears for getting started.  

Not sure if it's worthwhile to dig deep into the codebase for a cosmetic change like this......but long term it *does* seem like a good way to go about checking for it.

**Comment by fkiraly** [comment]
FYI, have you seen the issue I opened?
https://github.com/sktime/sktime/issues/4332

**Pull request merged**
