### PR TITLE
[MNT] carry out accidentally missed deprecation action for 0.15.0: in `WEASEL` and `BOSS`, remove `type_dict` and update default `alphabet_size=2`

### PR DESCRIPTION
**Pull request by xxl4tomxu98**
#### What does this implement/fix? Explain your changes.

Carries out missed deprecation actions for `WEASEL` and `BOSS` for 0.15.0 (missed since TODO note did not include full version number):
* remove `type_dict` argument
* change default `alphabet_size` parameter value to 2

#### Does your contribution introduce a new dependency? If yes, which one?
no

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [x] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by fkiraly** [comment]
No more notebooks, great!

Can you kindly copy over the pull request description from your first PR and close the other one still open?

**Comment by fkiraly** [comment]
also, kindly feel free to add yourself to the `allcontributorsrc` file for contributions!

**Comment by xxl4tomxu98** [comment]
added PR description and pushed up updates in allcontributorsrc

**Review by fkiraly — DISMISSED** [review]
Looks good to me now, thanks for helping out with the missed deprecation!

**Comment by xxl4tomxu98** [comment]
@fkiraly, I look at the failed tests, both test_windows(3.8) and test_unix(3.10) failed on the same module, `FAILED sktime/classification/tests/test_all_classifiers.py::TestAllClassifiers::test_classifier_on_unit_test_data[BOSSEnsemble] - AssertionError: 
Arrays are not almost equal to 2 decimals` I could not locate the file from the folder specified.

**Comment by fkiraly** [comment]
The reason is a unit test which checks predictions on a dummy data set against hard-coded expectations.

Since the default parameters have changed, the predictions will also change.
I'veupdated the `parameter_set` in `get_test_params` for `results_comparison` to match the old parameters, this should fix it.

**Comment by fkiraly** [comment]
One more thing, carrying out the deprecation action does not make you an owner of the algorithm. I've removed you from the owners list.

**Comment by xxl4tomxu98** [comment]
OK @fkiraly , understand! As I am intending to contribute more in the future, learning these rules is definitely helpful. Thanks

**Review by fkiraly — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
