### PR TITLE
[ENH] Added support for GluonTS PandasDataset as a series scitype

### PR DESCRIPTION
**Pull request by shlok191**
#### What does this implement/fix? Explain your changes.
This implements support for the GluonTS PandasDataset object as an sktime series scitype, and adds conversion functions to convert pd.DataFrame to a GluonTS PandasDataset. 

In addition, it fixes some prior GluonTS code and now enforces the test_interval_wrappers function!

Depends on https://github.com/sktime/sktime/pull/6838

#### Does your contribution introduce a new dependency? If yes, which one?
GluonTS, but that was added prior already

#### What should a reviewer concentrate their feedback on?
A reviewer should focus on the sktime/datatypes/_adapter/gluonts.py file for the new changes

#### Did you add any tests for the change?
No, I had already defined tests in a prior PR

#### Any other comments?
Assists with the #6659 PR.

##### For all contributions
- [X] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [X] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

### CODE REVIEW

**Comment by shlok191** [comment]
@fkiraly, I have made the new PR as requested! This does not skip the related test anymore, and has added PandasDataset as a series scitype. Hope that this is okay, I'll merge this branch into my LagLlama PR branch once all tests succeed :)

**Comment by fkiraly** [comment]
Nice!

I noticed the tests are off for converters, and the `gluonts` types were failing on `main`.

Could you merge https://github.com/sktime/sktime/pull/6838 into this PR to see whether your most recent changes fix the bugs?

**Comment by shlok191** [comment]
@fkiraly, thanks for pointing that out! I've been testing out `test_convert` locally, and one major challenge with GluonTS' PandasDataset is that it expects all timepoint indexes to be valid Datetime Objects. Some of the indexes in the examples for panels have timepoints as integers, which is what is largely breaking the test.

Is there anyway we could work around this? As I understand, I was working around this before by manually changing the timepoints via the date_range function, but I'm not sure if that'll work for this test :)

**Comment by fkiraly** [comment]
> one major challenge with GluonTS' PandasDataset is that it expects all timepoint indexes to be valid Datetime Objects. Some of the indexes in the examples for panels have timepoints as integers, which is what is largely breaking the test.

This is a bizarre restriction. Are you absolutely certain that only datetime-like indices are possible?

I've seen the opposite, i.e., only integer index is admissible, but not "only datetime", so far.

> Is there anyway we could work around this?

This sounds painful, the only workaround I can come up with:

* convert integers to days since January 1, 1970
* in the `store` dict of the converter, remember whether it was integer or not. If it was, convert back.

**Review by fkiraly — APPROVED** [review]
Thanks! Looks good to me!

**Pull request merged**
