### PR TITLE
[ENH] Resnet classifier

### LINKED ISSUE #3364: [ENH] Add ResNet Estimator
**Is your feature request related to a problem? Please describe.**
Enhancement 

**Describe the solution you'd like**
Migrating ResNet Classifier from sktime_dl to sktime

### PR DESCRIPTION
**Pull request by nilesh05apr**
#### Does your contribution introduce a new dependency? If yes, which one?
No

##### For all contributions
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by nilesh05apr** [comment]
@AurumnPegasus can you please help me fix test cases

**Comment by AurumnPegasus** [comment]
The issue does not seem to be in the code (atleast for now, will know more when those tests are executed) but from code quality.
Ensure that you have followed instructions for dev installation as mentioned [in the guide](https://www.sktime.org/en/stable/installation.html#development-versions)

Once you have done that, ensure you run `pre-commit` when you stage files for changes (BEFORE committing anything). Once the `pre-commit` tests pass, then commit your changes and push them to your branch.

In my opinion, I think you are skipping the `pre-commit` step, so let me know if it resolves your blocker

**Comment by fkiraly** [comment]
@nilesh05apr, as @AurumnPegasus said, you need to follow code formatting standards. How-to is outlined on this developer page:
https://www.sktime.org/en/stable/developer_guide/coding_standards.html

For quick inspection, you can also check the "details" next to the failed CI element "Install and test / code-quality (pull_request)"

**Review by fkiraly — CHANGES_REQUESTED** [review]
see above

**Comment by achieveordie** [comment]
Hey @nilesh05apr, do you still want to work on this? I'd had users ask me when this would be available in `sktime` and since you're almost done I wanted to nudge you regarding it.

I'll be happy to extend any support to you if required.

Thanks.

**Comment by nilesh05apr** [comment]
@achieveordie thanks for asking. I am working on it, but some tests are failing. let me try if it's not so urgent.

**Comment by achieveordie** [comment]
Absolutely!

Solving the failure due to `code-quality` check is actually very trivial. As per this [comment](https://github.com/sktime/sktime/pull/3365#issuecomment-1243042838) on this thread, you need to set up your dev setup properly.

Once you've done that you can make any slight change (like an additional space in the docstring) in your PR and commit it. `pre-commit` will then run and help you rectify problems relating to code formatting.

PS: I'd recommend resolving conflicts first.

**Comment by nilesh05apr** [comment]
@achieveordie , @AurumnPegasus i have added new pr as old one got clumsy.
please check test results for fix: pre-commit errors #3881

**Pull request closed without merging**
