### PR TITLE
[ENH] Momentfm CI Test with reduced observations in hierarchical tests

### PR DESCRIPTION
**Pull request by julian-fong**
relates to #6570, moving updates to hierarchical tests (reduces observations) here so CI can run to see if tests pass

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
I think this still contains all the changes from the other PR.

One hacky way to ensure only changes to the desired files are included are to copy-paste the files and commit them. Since we squash PR, one does not need to worry about order of commits within the PR branch.

**Comment by julian-fong** [comment]
> I think this still contains all the changes from the other PR.
> 
> One hacky way to ensure only changes to the desired files are included are to copy-paste the files and commit them. Since we squash PR, one does not need to worry about order of commits within the PR branch.

Yes this is intentional, because I think in its current state the observations from `_make_hierarchical_data` is too large, and causes crashes in the CI, so i opened a separate PR to reduce the number of observations to test the behaviour of the CI tests.

The main PR is still #6570 which should not contain changes from any non momentfm related code

**Comment by fkiraly** [comment]
Is there a PR which only changes the data size in tests?

**Comment by julian-fong** [comment]
> Is there a PR which only changes the data size in tests?

Yes, it is located in https://github.com/sktime/sktime/pull/6948

**Pull request closed without merging**
