### PR TITLE
[ENH] Convert the “date” column to a period with daily frequency in `load_m5`

### PR DESCRIPTION
**Pull request by SaiRevanth25**
#### What does this implement/fix? Explain your changes.
 converts the “date” column to a period with daily frequency in load_m5() function.

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
quick question:

could this change break downstream code? The function has already been released, so we need to think if this chane could break something for someone. If yes, we need to go through a period of warning and deprecation.

**Comment by SaiRevanth25** [comment]
The change won't break downstream code. The function remains fully compatible with existing implementations.

**Comment by fkiraly** [comment]
why does this not break downstream code? Suppose a user of the data set, performung further `pandas` operations.

**Comment by SaiRevanth25** [comment]
The change won't break downstream code because Pandas Period objects work smoothly with common operations like filtering, slicing, and grouping. Additionally, since the forecasters expect a time index with a frequency, this update ensures compatibility with existing implementations.

**Review by fkiraly — APPROVED** [review]
I suppose that makes sense.

**Pull request merged**
