### PR TITLE
[BUG] Add Informative Error messages for incompatible `scitype` in `BaseClusterer`

### LINKED ISSUE #4898: [BUG] Non informative Exception when fitting TimeSeriesKMeans with pd.Dataframe
**Describe the bug**
The fitting of TimeSeriesKMeans with pd.Dataframe produces an TypeError that is not informative. 

**To Reproduce**

```python
from sktime.clustering.k_means import TimeSeriesKMeans
import numpy as np
import pandas as pd
data = np.random.normal(0,1, (50, 12))
data_df = pd.DataFrame(data)
TimeSeriesKMeans().fit(data)
TimeSeriesKMeans().fit(data_df) # <- This line raises the TypeError
```

The resulting error message is:

```
TypeError: X is not of a supported input data type.X must be of type np.ndarray or pd.DataFrame, found <class 'pandas.core.frame.DataFrame'>Use datatypes.check_is_mtype to check conformance with specifications.
```

**Expected behavior**
Based on the discussion in Discord: The problem is that the the error message from `check_is_mtype` is not passed on. The problem is not that the python type is wrong, but that no panel specification is complied with (e.g., `pd-multiindex` needs 2 `pd.MultiIndex` levels). The error message should be more specific about the problem, e.g., by passing on the `check_is_mtype` error messages, such as in forecasting.

### PR DESCRIPTION
**Pull request by achieveordie**
#### Reference Issues/PRs

Fixes #4898

#### What does this implement/fix? Explain your changes.

As discovered by @benHeid, the error messages were quite unhelpful in the case there was a mismatch between the supported and provided type. I've updated the code to be a slightly more generalized validation function and more information is provided in case of an error.

I also found a very minor bug in forecasting's validation function and took the liberty to correct it.

Finally, `clusterer` was not added by the original authors into the registry so I added that as well.

#### Does your contribution introduce a new dependency? If yes, which one?

None

#### What should a reviewer concentrate their feedback on?

There are a bunch of `TODOs in `BaseForecaster`, we might want to take care of that in the upcoming PRs.

#### Did you add any tests for the change?

No test is required for this change.

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

Sorry for the delay!

### CODE REVIEW

**Review by fkiraly — APPROVED** [review]
Looks nice!

Non-blocking comments, perhaps for other PR:

* I think there is a bit of copy-paste here (from forecaster or transformers?), so this now seems like a natural starting point for a refactor that moves out the error message generation, e.g., into the `datatypes` module (new utility?)
* the classifiers and regressors are very similar to the clusterer, the same places could be improved there, too - I think?

**Comment by achieveordie** [comment]
There is a general question about how do we manage similar sanity checks across modules. In its current state, every module seems to implement its own version of validation on input data leading to repeated code, as you rightfully mentioned. Moving the validations into a separate entity brings the question of how modular we want our validations to be useful across modules.

Moving out the more obvious repetitions into a common utility seems trivial, but if we address the bigger issue [of how we centralize input validation] we might be able to get away with other surrounding issues.

**Comment by fkiraly** [comment]
I would start with the error messages for now, coming from `check_is_mtype`, and only after that go for the validation logic.
I think it needs to be more modular, but I feel it might be a bit tricky at the moment, especially with error handling, error messages, and vectorization mixed together.

**Comment by fkiraly** [comment]
Thanks for fixing the error message bug with the forecasting base class, btw.

**Pull request merged**
