### PR TITLE
[ENH] in `TransformedTargetForecaster`, ensure correct setting of `ignores-exogenous-X` tag if forecaster ignores `X`, but at least one transformer uses `y=X`, e.g., feature selector

### LINKED ISSUE #5518: [BUG] `ignores-exogeneous-X` is kept for `TransformedTargetForecaster` even if transformer would use exog
**Describe the bug**
`ignores-exogeneous-X` is kept for `TransformedTargetForecaster` even if transformer would use exog

I want to have a forecasting pipeline where I define part of the logic in the transformer. For example, I want to impute holidays data. Holidays mask is exogeneous. I have implemented a transformer that does the job, but it is not working because my final transformer `ignores-exogeneous-X`.

**To Reproduce**
```python
from sktime.forecasting.naive import NaiveForecaster
from sktime.transformations.series.feature_selection import FeatureSelection
from sktime.forecasting.fbprophet import Prophet

print(f"{Prophet().get_tag('ignores-exogeneous-X') = }")
print(f"{(FeatureSelection() * Prophet()).get_tag('ignores-exogeneous-X') = }")

print(f"{NaiveForecaster().get_tag('ignores-exogeneous-X') = }")
print(f"{(FeatureSelection() * NaiveForecaster()).get_tag('ignores-exogeneous-X') = }")
```

```python
Prophet().get_tag('ignores-exogeneous-X') = False
(FeatureSelection() * Prophet()).get_tag('ignores-exogeneous-X') = False
NaiveForecaster().get_tag('ignores-exogeneous-X') = True
(FeatureSelection() * NaiveForecaster()).get_tag('ignores-exogeneous-X') = True
```

**Expected behavior**
```python
Prophet().get_tag('ignores-exogeneous-X') = False
(FeatureSelection() * Prophet()).get_tag('ignores-exogeneous-X') = False
NaiveForecaster().get_tag('ignores-exogeneous-X') = True
(FeatureSelection() * NaiveForecaster()).get_tag('ignores-exogeneous-X') = **False**
```

**Versions**
```
System:
    python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:39:40) [Clang 15.0.7 ]
executable: /opt/homebrew/Caskroom/miniconda/base/envs/hcem_test/bin/python
   machine: macOS-13.2.1-x86_64-i386-64bit

Python dependencies:
          pip: 23.2.1
       sktime: 0.24.0
      sklearn: 1.3.1
       skbase: 0.5.1
        numpy: 1.25.2
        scipy: 1.11.3
       pandas: 2.1.1
   matplotlib: 3.8.0
       joblib: 1.3.2
        numba: None
  statsmodels: 0.14.0
     pmdarima: 2.0.3
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: None
   tensorflow: None
tensorflow_probability: None
```

### PR DESCRIPTION
**Pull request by fkiraly**
This PR fixes #5518.

II `TransformedTargetForecaster`, it ensures correct setting of `ignores-exogenous-X` tag if forecaster ignores `X`, but at least one transformer uses `y` (which is identical to some `X` in the pipeline), e.g., a feature selection transformer.

The implemented logic is as discussed in this post: https://github.com/sktime/sktime/issues/5518#issuecomment-1791465090

* if none of the transformers use `y`, i.e., all transformers have the tag `"y_inner_mtype": "None"`, then the resulting pipeline should have `"ignores-exogeneous-X": True`
* if at least one of the transformers uses `y`, i.e., at least one transformer has a tag `"y_inner_mtype"` with a value other than `"None"`, the resulting pipeline sohuld have `"ignores-exogeneous-X": False`

Also adds tests for a number of combination cases.

### CODE REVIEW

**Comment by SmirnGregHM** [comment]
Thanks for the very fast response on #5518! This looks good to me.

**Comment by fkiraly** [comment]
is this the logic you would expect?

**Comment by SmirnGregHM** [comment]
> is this the logic you would expect?

Yes

**Comment by yarnabrina** [comment]
@fkiraly , @SmirnGregHM can one of you please explain why transformers will take precedence over forecaster? If forecaster does not use `X`, does it matter if transformers use `y` (which is the exogenous `X` of forecasting) or not?

If it's just the pre-transformers, I fail to see why shall we set the `ignores-exogeneous-X` tag to be `False`.

(I'm not familiar with post-transformers in `sktime`, so not commenting for that case.)

**Comment by fkiraly** [comment]
> can one of you please explain why transformers will take precedence over forecaster? If forecaster does not use `X`, does it matter if transformers use `y` (which is the exogenous `X` of forecasting) or not?

Well, transformers may use an `y`-argument nontrivially. In the `TransformedTargetForecaster`, transformers are applied to `X=y`, i.e., the `y` of the forecaster is plugged into the `X` of the transformer, and vice versa - i.e., the `X` of the forecaster is plugged into the `y` of the transformer.

Due to the latter, if the transformer uses `y` in a nontrivial way, then the entire pipeline will use `X` in a non-trivial way, even if the forecaster does not.

This is perhaps understood most easily if you draw a diagram with trafos and forecasters, and `X` and `y` input nodes to either to visualize the data flow similar to the diagrams of @benHeid in here: https://github.com/sktime/sktime-workshop-pydata-prague-2023/blob/main/notebooks/04_advanced_forecasting_pipelines.ipynb

**Comment by fkiraly** [comment]
> why transformers will take precedence over forecaster

That is not the case, logically - the logic is a simple "or", so the tag will e set to `False`" iff at least one of the components - trafo or forecaster - does not ignore the pipeline-input-`X`. In a logical "or", none of the components take precedence, of course any component can "override" the tag to `False` if it uses `X`.

**Comment by fkiraly** [comment]
> I'm not familiar with post-transformers in `sktime`

same story - these apply to the forecast. A common example would be "coerce to a positive number".

**Review by yarnabrina — APPROVED** [review]

**Pull request merged**
