### PR TITLE
[ENH] test parameters for `RocketRegressor`

### PR DESCRIPTION
**Pull request by iaryangoyal**
#### Reference Issues/PRs

Issue - #3429

Please use keywords (e.g., Fixes) to create [link](https://github.com/sktime/sktime/issues/3429) to the issues or pull requests
you resolved, so that they will automatically be closed when your pull request
is merged. See https://github.com/blog/1506-closing-issues-via-pull-requests.
If no issue exists, you can open one here: https://github.com/sktime/sktime/issues

#### What does this implement/fix? Explain your changes.

 I've added another dictionary to the list returned by the method, where num_kernels is set to a different value (in this case, 100). This provides a second parameter set for testing the RocketRegressor estimator.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks!

Some requests:

* can you cover the other parameters too? (except `n_jobs`, `random_state`)
* there is no need for the "if", the test framework interprets conditionless returns as the default.

**Comment by iaryangoyal** [comment]
@fkiraly please check and merge the same as i have removed if statement.

**Comment by iaryangoyal** [comment]
@fkiraly what I need to do with this PR is it fine or I have to do some changes in it?

**Comment by iaryangoyal** [comment]
#6137 I have made changes in the Base.py of the regression file and added cloudpickle support to the serialization of regressors 
@fkiraly Please check

**Review by fkiraly — CHANGES_REQUESTED** [review]
That's great!

Would you mind not making two substantial changes in a single PR, and split your two contributions into two PRs? That would be great.

The addition of `cloudpickle` support also clashes with #6098, as discussed in https://github.com/sktime/sktime/issues/6137, could you branch off #6098 please?

**Comment by iaryangoyal** [comment]
Closing this PR and open #6149 for new references @fkiraly

**Pull request closed without merging**
