### PR TITLE
[ENH] `numpy 2` compatibility fixes - estimators

### PR DESCRIPTION
**Pull request by fkiraly**
This PR contains compatibility fixes for `numpy 2` for individual estimators. Towards https://github.com/sktime/sktime/issues/6625

* `STRAY` - replace deprecated `np.Inf` with `np.inf`
* `WindowSummarizer` tests - replace deprecated `np.NAN` with `np.nan`
* `pykalman` - handle deprecated `newbyteorder`

### CODE REVIEW

**Review by yarnabrina — APPROVED** [review]
Should be fine.

The only comment I have is with respect to checking of numpy version where they have an official recommendation. But since we have a ready function used everywhere else, it probably doesn't make sense to break consistency in just one place.

**Comment by yarnabrina** [comment]
Numpy migration guide suggests checking with `ruff`.

```shell
❯ ruff check sktime --select NPY201
sktime/annotation/stray.py:133:17: NPY201 [*] `np.Inf` will be removed in NumPy 2.0. Use `numpy.inf` instead.
sktime/benchmarking/evaluation.py:562:13: NPY201 `np.asfarray` will be removed in NumPy 2.0. Use `np.asarray` with a `float` dtype instead.
sktime/benchmarking/evaluation.py:570:13: NPY201 `np.asfarray` will be removed in NumPy 2.0. Use `np.asarray` with a `float` dtype instead.
sktime/transformations/panel/rocket/_rocket_numba.py:101:12: NPY201 [*] `np.NINF` will be removed in NumPy 2.0. Use `-np.inf` instead.
sktime/transformations/panel/rocket/_rocket_numba.py:134:12: NPY201 [*] `np.NINF` will be removed in NumPy 2.0. Use `-np.inf` instead.
Found 5 errors.
[*] 3 fixable with the `--fix` option.
```

Should we do these in this PR only?

**Comment by fkiraly** [comment]
yes, please.

The `newbyteorder` fix also does not seen to work, does the fix flatten arrays?
It would surprise me. See failure here: https://github.com/sktime/sktime/pull/6627

I also wonder why this does not fail in this PR. The `pykalman` lib should be tested because there is a change in it.

**Comment by fkiraly** [comment]
> Should be fine.

Kindly do not merge yet, @yarnabrina, as there are some remaining failures.

Further, why do we not see the failures from the `ruff` issues? Not all of them seem to get detected by running tests (some were).

**Comment by yarnabrina** [comment]
Confused, all tests seems to pass, where are the failures?

Please ignore. I just realised this PR does not yet use numpy v2, there's a different PR for that verification.

**Comment by fkiraly** [comment]
> there's a different PR for that verification.

Yes, we also need to check the fixes don't break for `numpy 1`...

Not sure how to do this systematically, I do not want to overload the matrix which already has `pandas 1` in it too.

**Comment by yarnabrina** [comment]
I do not know a systematic way either, may be some trick with environment setup with tox/nox? Not sure. But I think we may have to check numpy v1 for some time now in CI though, while other package add support for this.

Regarding pandas v1, can we now start skipping that separate check in CI? It's about 1.5 years from last v1 release. Do you plan to add any fixes if something starts failing only in pandas v1 jobs?

**Comment by fkiraly** [comment]
> Regarding pandas v1, can we now start skipping that separate check in CI? It's about 1.5 years from last v1 release. Do you plan to add any fixes if something starts failing only in pandas v1 jobs?

It's a different topic, and I wonder whether we should stop supporting. Given that every single `pandas 2` release breakes `freq` or sth else, I would guess many people are still on `pandas 1` with their production pipelines. Perhaps one more year?

**Pull request merged**
