### PR TITLE
[DOC] Added all feature names to docstring for DateTimeFeatures class

### LINKED ISSUE #4829: [DOC] `DateTimeFeatures` docstring should document all possible feature names for `manual_selection`
The current docstring of the `DateTimeFeatures` transformer does not document all possible feature names for `manual_selection` (e.g., `"day_of_week"`).

As far as I see, this information cannot be gleaned from the current API documentation, only by inspecting the code in the `_calendar_dummies` private function.

Further, the exact values should be documented, e.g., does this result in an integer based column, and if yes, is it 0- or 1- based offset, to what? E.g., to Mondays or Sundays?

FYI @KishManani, @VyomkeshVyas

### PR DESCRIPTION
**Pull request by Abhay-Lejith**
#### What does this implement/fix? Explain your changes.

This resolves #4829  . I have added all possible feature names along with their returned values for `manual_selection` in the `DateTimeFeatures` class.

#### Does your contribution introduce a new dependency? If yes, which one?

No
#### What should a reviewer concentrate their feedback on?

- if the docstring meets the required formatting.
#### Did you add any tests for the change?
No.

#### Any other comments?

This is my first pull request so any feedback would be helpful.
##### For all contributions

- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Excellent, thanks! Looks like you got all.

Blocking comment:

* I think we need to explain which index overlapping periods have, i.e., in cases where the shorter period can non-trivially overlap with the longer period, such as week of month. 0-based or 1-based is not enough. Let's say the 31st is a Monday, which index will the week commencing with this Monday have? Is the first full week in a month 0, is the first full week in a month 1, or is it the first week that has at least one day in the month? May require some testing to find out what really is the case, one ought to test at least a partial week and the week starting on the 1st if we don't know.
* we should also say that weeks start with Monday. They don't start on Monday in every country.

Non-blocking:

* regarding the "0-based" vs "1-based", perhaps it makes sense to add explanations like "i.e., January is 1, February is 2".

**Comment by fkiraly** [comment]
FYI @danbartl, @KishManani, @VyomkeshVyas

**Comment by Abhay-Lejith** [comment]
I will be a little busy for a week. I will work on the requested changes once I'm back.

**Comment by Abhay-Lejith** [comment]
I have worked on the requested changes and added explanations for the overlapping periods.

**Review by fkiraly — APPROVED** [review]
Thanks - very very nice! This will for sure help our users!

**Pull request merged**
