### PR TITLE
[ENH] Add SplineTrendForecaster

### LINKED ISSUE #7363: [ENH] Add Spline Forecaster
**Is your feature request related to a problem? Please describe.**
So far, when detrending, we can use linear regression with polynomial features. I would like something more flexible, i.e. fiting linear splines in a way that Prophet does it, but without the probabilistic programming overhead and with more control about what happens when extrapolating.

**Describe the solution you'd like**
I would like a new class like the `PolynomialTrendForecaster`, but `SplineTrendForecaster` or so. Internally, it would look like the `PolynomialTrendForecaster`, with (hopefully) the only difference being that instead of
```python
self.regressor_ = make_pipeline(
    PolynomialFeatures(degree=self.degree, include_bias=self.with_intercept),
    regressor,
)
```

we would have something like

```python
self.regressor_ = make_pipeline(
    SplineTransformer(degree=self.degree, n_knots=self.knots, extrapolation=self.extrapolation, include_bias=self.with_intercept),
    regressor,
)
```

We could maybe even write another class `PipelineTrendForecaster` that takes a scikit-learn pipeline. From that, we could easily derive `PolynomialTrendForecaster` and `SplineTrendForecaster`.

scikit-learn's `SplineTransformer` has the advantage that you can tell it how to extrapolate, either linearly, constant, periodic, or more.

### PR DESCRIPTION
**Pull request by Dehelaan**
Fixes #7363

#### What does this implement/fix? Explain your changes.

Implemented SplineTrendForecaster , according to the feature request, I have used the `_DelegatedForecaster` to create a shortcut for the above-mentioned forecaster.

#### What should a reviewer concentrate their feedback on?
1.Is `_DelegatedForecaster` implemented properly.
2.Are Tags, parameters correct.
3.If any extra things to be added please suggest.

####Any other comments? 
It's my first time making an estimator, previously I have added `get_params` in an estimator.  If any changes are required in the code, I will implement those sincerely, please try to point out every small error so that I could learn more. Thank you for providing opportunity.

##### For new estimators
- [X] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [X] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Comment by jgyasu** [comment]
Hello @Dehelaan, I just wanted to point out to [https://github.com/sktime/sktime/pull/7487](https://github.com/sktime/sktime/pull/7487)

A PR solving this issue is already in progress

**Comment by Dehelaan** [comment]
Hi @jgyasu, it's great to see you're also working on this issue! Ultimately, it's a win for the project as long as the issue gets resolved, regardless of which PR gets merged.

**Review by fkiraly — APPROVED** [review]
Looks mostly ok - I will merge this with https://github.com/sktime/sktime/pull/7487 and credit both authors.

**Review by fkiraly — CHANGES_REQUESTED** [review]
could you kindly make sure that tests pass?

I prefer the delegation approach above the inheritance one, and I would be happy to merge the two - kindly make sure that tests pass, first.

**Comment by jgyasu** [comment]
@Dehelaan I can help with the tests if you'd like

**Comment by felipeangelimvieira** [comment]
@Dehelaan I believe you `__init__` should look like this instead:

```python
spline_regressor = make_pipeline(
            SplineTransformer(
                degree=self.degree,
                n_knots=self.n_knots,
                extrapolation=self.extrapolation,
                include_bias=self.include_bias,
            ),
            clone(self.regressor),
        )

self.forecaster_ = TrendForecaster(spline_regressor)
super().__init__()
 ```

**Review by fkiraly — CHANGES_REQUESTED** [review]
I have fixed the issue with the `self.regressor` param and you deleted this - please do not revert my fixes.

**Review by fkiraly — DISMISSED** [review]
Merged with @jgyasu's PR

**Comment by Dehelaan** [comment]
> Can you ensure that the tests pass?
@fkiraly sorry for late reply, I wasn't near pc. I was about to make changes now but found out its merged with #7487. So, in order to not creating any merge conflicts, I am closing this PR.

**Comment by Dehelaan** [comment]
I opened up it again I was initially thinking that some merge conflicts were happening on my part, but I realized some changes are made by you (If I am correct).

**Review by fkiraly — APPROVED** [review]
That's right, I wanted to merge this with the other PR - I have finalized the merge now.

Apologies for assigning this to two people, and thanks for your great work!

**Pull request merged**
