### PR TITLE
[ENH] Add binary segmentation annotator for change point detection

### PR DESCRIPTION
**Pull request by Alex-JG3**
#### Reference Issues/PRs

Related to #6481.

#### What does this implement/fix? Explain your changes.

Implements binary segmentation as described in WILD BINARY SEGMENTATION FOR MULTIPLE
CHANGE-POINT DETECTION (https://arxiv.org/pdf/1411.0858).

#### Did you add any tests for the change?

Yes, added tests for the algorithm in `test_bs.py`.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [x] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [x] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Comment by Alex-JG3** [comment]
This is ready for someone to take a look at. Some points that we should think about:

* This is written as a univariate algorithm but I would like to extend it to handle multivariate timeseries using this paper as a starting point https://arxiv.org/pdf/1611.08639. I would like to do this in a future MR.
* This algorithm does not have a `fit_transform` method because it does not implement the `predict_points` method. This is because `predict_points` is not used yet in both `fit_predict` and `fit_transform` for compatability reasons. I think we should do some kind of check to see if `predict_points` is implemented which would change `fit`, and `fit_predict`. This feels a little clunky though so it would be good to head what others think.

**Comment by Alex-JG3** [comment]
@sktime/core-developers, could someone rerun the pipeline please?

**Comment by yarnabrina** [comment]
> @sktime/core-developers, could someone rerun the pipeline please?

Done. I think you should also have access? It's available from the Summary page for a run.

**Comment by fkiraly** [comment]
@Alex-JG3, you are a core developer too, so you should be able to restart it too!

**Review by fkiraly — APPROVED** [review]
Looks reasonable - I think the next thing to add should be adding a more general suite test, I find it a bit hard to check interface conformance just from inspection.

**Pull request merged**
