### PR TITLE
[ENH] Examples for `YtoX` transformer

### PR DESCRIPTION
**Pull request by fkiraly**
Adds examples for `YtoX` transformer in its docstring; also improves docstring formatting and clarity.

### CODE REVIEW

**Comment by geetu040** [comment]
@fkiraly That is an easy fix, if you ask me I'll be happy to check, test, fix and add the examples for this class.

**Comment by fkiraly** [comment]
Would you like to add more examples? Sure, if you would like to, in anothe PR?

**Comment by geetu040** [comment]
Thanks, I'll do in another PR

**Comment by fkiraly** [comment]
Sure! I recommend then branching off this branch, to avoid merge conflicts.

**Comment by fkiraly** [comment]
> I previously worked on EEG dataset and just realized how easy would have the things been if I used this approach.

Interesting statement - what this makes me think, and imagine reading between the lines, is that the tutorials are not as clear as they could be on building pipelines from the various components.

I would be keen to hear your opinions, on where/how *you specifically* would have expected explanations, or whether there were places where you felt more confused than informed.

**Comment by geetu040** [comment]
There were actually no example use-cases for `YtoX`. I only found one in this discussion https://github.com/sktime/sktime/discussions/5064.
I asked on discord for explanation and thankfully this PR in response made it clear for me. It was lacking dataset so it took some time for me to process, just that now I understand it.

It was simple, I was just not looking with the right approach. I just thought why to use a transformer to convert `Y` to `X` when I can just create a duplicate, process it and pass it as `X`. but I just realized using `YtoX` in a pipeline makes the code way easier and efficient.

Thanks

**Pull request merged**
