### PR TITLE
[MNT] pytorch_forecasting to pytorch-forecasting

### PR DESCRIPTION
**Pull request by Xinyu-Wu-0000**
This PR fixes `_check_soft_dependencies` returning False for:

`PytorchForecastingTFT` and `PytorchForecastingNBeats` in branch main
`PytorchForecastingDeepAR` and `PytorchForecastingNHiTS` in PR #6551

### CODE REVIEW

**Comment by Xinyu-Wu-0000** [comment]
@sktime/core-developers  Can we merge this PR and PR #6551 quickly. The not enough space error is fixed in PR #6551 and `pytorch_forecasting` is replaced with `pytorch-forecasting` in this PR. Without these two PRs, CI could fail if any other PR triggers tests on pytorch-forecasting models.

**Review by fkiraly — CHANGES_REQUESTED** [review]
there are a large number of other changes - is this intended, or included by mistake?

**Comment by Xinyu-Wu-0000** [comment]
> there are a large number of other changes - is this intended, or included by mistake?

It's inherited from https://github.com/sktime/sktime/pull/6551 since two forecasters are in #6551 not main.

**Comment by fkiraly** [comment]
What I would suggest, open a PR that changes only the tag on `main`. There are already two forecasters inheriting the tag, so that should trigger a test on them and of the change.

**Comment by Xinyu-Wu-0000** [comment]
> What I would suggest, open a PR that changes only the tag on `main`. There are already two forecasters inheriting the tag, so that should trigger a test on them and of the change.

New PR is #6830.

**Pull request closed without merging**
