### PR TITLE
[BUG] Possible solution for pickle persistency fail for DL models

### PR DESCRIPTION
**Pull request by achieveordie**
#### What does this implement/fix? Explain your changes.

Initially, `test_persistence_via_pickle()` of `test_all_estimators.py` was skipped for all DL models since there were problems correctly serializing the objects. So, added possibly corrected `__getstate__()` function for both `BaseDeepRegressor()` and `BaseDeepClassifier()`.

The current implementation seems to be working locally for `CNNClassifier`

#### Does your contribution introduce a new dependency? If yes, which one?

No

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

### CODE REVIEW

**Comment by achieveordie** [comment]
The failures are due to the known issue of not having the `optimizer` stored. Will fix it in the upcoming days.

**Comment by fkiraly** [comment]
yes, this is part of the interface contract.

Note, we do not need to rely on pickle, we could rely on a save/load interface instead that replaces pickle with sth else.

**Comment by achieveordie** [comment]
This PR can only be developed further after #3425 gets accepted since that deals with `.save()` / `.load()` class methods that will be used instead of pickle's `.dump()` / `.load()` for `test_persistence_via_pickle()`.

**Comment by fkiraly** [comment]
hm, what I would do is to leave the save/load tests skipped, and instead write a test for pickling?
So we test the functionality added by this PR with a test also added in this PR.
Not as part of the generic test suite, but for one example of neural networks.

What do you think?

**Comment by achieveordie** [comment]
The functionality in this PR is an outdated version of #3425. We still need to improve/correct/add test functionality which is the aim of this PR.
So after that PR is merged, we can continue updating the tests here. I could also copy-paste the relevant functions from that PR to this one but I think the former way is better.

**Comment by achieveordie** [comment]
Closing in favour of #3425. This feature will be implemented there.

**Pull request closed without merging**
