### PR TITLE
[ENH] second set of test parameters for `GMMHMM`

### PR DESCRIPTION
**Pull request by sanjayk0508**
Added second test parameter set for `GMMHMM` and included myself in the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).

#3429

### CODE REVIEW

**Review by yarnabrina — DISMISSED** [review]
I am not sure about `doc` badge, but rest looks good. Thanks for your contribution.

**Review by fkiraly — CHANGES_REQUESTED** [review]
Yes, you're right about the badges, @yarnabrina - this is only `test`.

We're confident you'll get the other badges too if you keep at it! But you're not yet there:

* `bug` is for reporting or diagnosing a bug
* `code` is for adding code logic, including bugfixes
* `doc` is for documentation improvements

**Comment by sanjayk0508** [comment]
@fkiraly , I see. I thought the badges were for indicating which area a contributor is interested in. Apologies for the oversight. I will update it.

**Comment by fkiraly** [comment]
> I thought the badges were for indicating which area a contributor is interested in.

Great to hear that you are interested in these areas, and looking forward to working with you! The badges are indeed for past contributions.

**Review by fkiraly — APPROVED** [review]

**Pull request merged**
