### PR TITLE
[MNT] Update sklearn compatibility to `1.2.x`, version bound to `<1.3`

### PR DESCRIPTION
**Pull request by aiwalter**
(@fkiraly update:) This PR updates the `sklearn` version bound to `<1.3`.

Includes fixes for `sklearn 1.2` compatibility:

* https://github.com/sktime/sktime/pull/3918
* https://github.com/sktime/sktime/pull/3919

### CODE REVIEW

**Comment by aiwalter** [comment]
there is an issue with `from sklearn.neighbors._base import _check_weights`  which ahhpens twice in the file `_time_series_neighbors.py`, ideally we should not import private functions from dependency packages bcz they tend to break as now. @jasonlines @TonyBagnall do you mind to have a look into this?

**Comment by fkiraly** [comment]
FYI, `KNeighborsTimeSeriesClassifier` is no longer the original version of @jasonlines and @TonyBagnall that "hacked" the `sklearn` one and used its private functions.

Some while ago, I change-refactored it to composition where `sklearn` is internally used. The fix should hence be easy (rather than requiring a substantial amount of rework):

https://github.com/sktime/sktime/pull/3918

**Comment by fkiraly** [comment]
moving my work here: https://github.com/sktime/sktime/pull/3922

there's too many changes, and I don't want to fiddle around too much in @aiwalter's PR.

please feel free to revert everything.

**Comment by fkiraly** [comment]
superseded by fixes in https://github.com/sktime/sktime/pull/3922

**Pull request closed without merging**
