### PR TITLE
[ENH] extend data loaders to handle regression ts files, add Tecator dataset for Time Series Regression - recovered copy

### PR DESCRIPTION
**Pull request by fkiraly**
Recovered copy of accidentally corrupted #5322

### CODE REVIEW

**Comment by JonathanBechtel** [comment]
@fkiraly IMO the updated PR before this one is more appropriate to look at, since it's more DRY, and was submitted after @hazrulakmal 's enhancements of the `datasets` section.

**Comment by fkiraly** [comment]
> @fkiraly IMO the updated PR before this one is more appropriate to look at, since it's more DRY, and was submitted after @hazrulakmal 's enhancements of the datasets section.

Sure, feel free to use this one as you prefer (up to closing it). I just recovered it as it looked like #5322 had an accident, and the loader logic for the "prolemtype" field is missing.

**Comment by JonathanBechtel** [comment]
I made unnecessary additions to the ts file specification since I didn't know metadata was already included to specify time series regression datasets.

**Comment by JonathanBechtel** [comment]
If it's alright I think I'd prefer to close this one and use the more recent one.  See my comments above.

**Comment by fkiraly** [comment]
superseded by https://github.com/sktime/sktime/pull/5428

**Pull request closed without merging**
