### PR TITLE
[ENH] forecaster `fit_predict` with `X_pred` argument for `predict`

### PR DESCRIPTION
**Pull request by fkiraly**
This PR adds an `X_pred` argument to `fit_predict`, which allows to pass different `X` to `predict`.

This should partially address https://github.com/sktime/sktime/issues/4839

### CODE REVIEW

**Review by yarnabrina — COMMENTED** [review]
Looks okay, but I want to clarify a doubt. Instead of changing signature, is it okay to do `return self.fit(y, X=X, fh=fh).predict(X)` always? That seemed to work for all of `ForecastX`, `YfromX` and `make_reduction`. Didn't check with SARIMAX what @arnaujc91 faced isuues with though.

(Also, the index filtering mentioned in #5401 can also be added in base class I guess, if it's not there already.)

I understand it's not a breaking change, but passing X_pred separately seems different from `sklearn` so wanted to avoid.

**Comment by fkiraly** [comment]
> is it okay to do `return self.fit(y, X=X, fh=fh).predict(X)` always?

Do you mean `return self.fit(y, X=X, fh=fh).predict(X_pred)`?

Wasn't sure whether this would be deprecation safe, so I left everyting the same in the old case, for now.

Also, there's the matter of converting `X` twice, i.e., an efficiency question.

**Comment by yarnabrina** [comment]
No, I meant `X` only, without introduction of a new argument `X_pred`. That seemed to work for the models I tried.

Another improvement without adding a new argument could be to split X inside fit_predict based on y index, and then pass appropriately to fit and predict. I'm not sure whether this would be possible always or not, but this seems to be same as what @arnaujc91 was doing in the issue comment.

**Comment by arnaujc91** [comment]
hi everyone i would also prefer to have `forecaster.fit_predict(y, X, fh)` and probably expect the `fit_predict` to figure out the index needed for `X` from `y` and `fh`, *seems* it should not be that hard to be done.

**Comment by fkiraly** [comment]
I see - the problem with "working out the index" are two-fold:

* not all `predict`-s expect the `X`-index to be strictly aligned with `fh`
* for "working out", we need to deal with many data mtypes, it seems obvious only for a few `pandas`-based ones what to do

I was going to do that, though perhaps in a different PR?
Of course unless you feel strongly about not adding `X_pred`.

**Comment by arnaujc91** [comment]
Hi @fkiraly so you wanna do `forecaster.fit_predict(y, X, fh)` in another PR? Like implement there the automatic computations to find the `X` index given `y` and `fh`? In that case i think would be a bit weird to now introduce a new kind of `X` called `X_pred` and then removing it (i assume?). Not sure if i got it right. 


Given that we have to work with many m-types, would it not be convenient to accept multiple types for the open api of the `fit_predict` but then always convert everything into a given type and forget about the type passed by the user? I mean if you accept multiple types for `X` or `fh` always convert whatever is passed by the user to some "canonical" type that from now on the rest of the class will be using. I guess thats what you are already doing probably in the sktime library though.

**Comment by fkiraly** [comment]
> In that case i think would be a bit weird to now introduce a new kind of `X` called `X_pred` and then removing it (i assume?). Not sure if i got it right. 

I'd just leave it, as a means to specify `X_pred` explicitly.

> would it not be convenient to accept multiple types for the open api of the `fit_predict` but then always convert everything into a given type and forget about the type passed by the user?

It would, unfortunately the internal type can also vary, i.e., what we need to convert it *to*.
So the splitting may, worst case, lead to three unnecessary conversions.

**Comment by arnaujc91** [comment]
Ok, sounds good to me. Worst case scenario `X_pred` can be removed later in case people get confused. In my opinion it would be significantly simpler with just one `X` rather than having one `X` and then an optional `X_pred` but thats a matter of taste and i don't want to make things more complicated in terms of work. So fine by me :)

So we agree that later we will come back to the `sklearn` api where you just need to pass `y` and `X` and also you can optionally pass `X_pred` right?

**Comment by fkiraly** [comment]
> So we agree that later we will come back to the `sklearn` api where you just need to pass `y` and `X` and also you can optionally pass `X_pred` right?

Yes, and this is an "official" workaround for the breaking cases until we have the former covered with tags, splitting logic, etc.

Which, actually, reminds me that we can simply use a splitter!
Question: do we have a splitter currently available that does the "right split" as we want it? We would have to input `fh` and `cutoff`, I suppose.

**Comment by fkiraly** [comment]
hm, `CutoffSplitter` seems similar, but not exactly.
E.g., it assumes a window backwards from cutoff, and only `iloc` indexing via `fh`.

**Comment by arnaujc91** [comment]
What about [temporal_train_test_split](https://www.sktime.net/en/stable/api_reference/auto_generated/sktime.forecasting.model_selection.temporal_train_test_split.html) ?

**Comment by fkiraly** [comment]
Attempt in #5575 for that splitter

**Pull request merged**
