### PR TITLE
[ENH] Link to docs in object's html repr

### PR DESCRIPTION
**Pull request by mateuszkasprowicz**
#### Reference Issues/PRs

Implements #6812

Depends on https://github.com/sktime/sktime/pull/6882 for the css fix

#### What does this implement/fix? Explain your changes.

- Adds a (?) icon with a link to docs to object's html representation
- Updates the html repr CSS style

#### Does your contribution introduce a new dependency? If yes, which one?
No

#### What should a reviewer concentrate their feedback on?
- Naming conventions I used

#### Did you add any tests for the change?
Yes

#### Any other comments?

- `_estimator_html_repr.py` is based on skbase with doc link added based on sklearn
- `_estimator_html_repr.py` is based on sklearn with "fitted" classes removed as we don't use "fitted" indicator in html repr

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Comment by fkiraly** [comment]
hm, doc build appears to be failing - looks like circular imports to me

**Comment by fkiraly** [comment]
FYI, if you want to override, you need to inherit

`class BaseObject(_HTMLDocumentationLinkMixin, _BaseObject)`,

and not `class BaseObject(_BaseObject, _HTMLDocumentationLinkMixin)`

because the MRO puts earlier parent classes at the last overrides.

Changed, to see what that does.

**Comment by fkiraly** [comment]
strange, it does not seem to find the css file?

**Comment by mateuszkasprowicz** [comment]
> FYI, if you want to override, you need to inherit
> 
> `class BaseObject(_HTMLDocumentationLinkMixin, _BaseObject)`,
> 
> and not `class BaseObject(_BaseObject, _HTMLDocumentationLinkMixin)`
> 
> because the MRO puts earlier parent classes at the last overrides.
> 
> Changed, to see what that does.

good catch, thx

**Comment by fkiraly** [comment]
restarted tests

**Comment by yarnabrina** [comment]
@fkiraly any idea why is CI proceeding to schedule so many jobs, as initial ones failed?

**Comment by fkiraly** [comment]
The reason is that most jobs are gated behind `test-nosoftdeps` rather than `test-nodevdeps`, and the latter is failing.

It is in general unusual that tests are failing in this combination, i.s., `test-nosoftdeps` runs while `test-nodevdeps` fails. Very peculiar, and both myself and @mateuszkasprowicz are unable to reproduce the failures locally, too.

**Comment by yarnabrina** [comment]
I pushed an attempted fix, kindly review and revert if not working and/or incorrect.

This is my hypothesis:

1. You are testing locally with editable install, so site-packages is not being used. CI does not do editable install, so what goes as part of package matters.
2. CSS or any non-python files are not going into packages, unless you explicitly configure them. So they were missing in CI, but was working fine locally.

**Comment by fkiraly** [comment]
* the new failures are related to pyproject parsing. I fixed an issue there, and merged the fix into this.
* what I am now wondering about, why does the failure related to the missing css not occur in all the other test cases? We should ensure we run code that requires the css to be present.

**Comment by fkiraly** [comment]
The failures are unrelated, they seem to be caused by this: https://github.com/sktime/sktime/issues/6884

**Review by fkiraly — APPROVED** [review]
Works for me, brilliant! I tested this with various estimators, and composites such as `ForecastingPipeline` and `DirectReductionForecaster`.

Two issues that came up and I think we ought to address:

1. Pipelines render left-to-right rather than top-to-bottom.

I am not sure how to fix this, the best would be to add a tag that somehow controls this for a given composite. See display below for the `ForecastingPipeline`.
image

However, this is not something new and has already been like this for the old html display.

2. The html display is no longer cross-compatible with the previous one, so estimator composites out of the two will not render.

An example of this is the following estimator composite which has an sklearn estimator inside an skpro estimator, inside an sktime estimator:

```python
from sktime.forecasting.compose import DirectTabularRegressionForecaster
fs = DirectTabularRegressionForecaster.create_test_instances_and_names()
fs[0][2]
```

Interestingly, the sklearn estimator is displayed, but not the skpro estimator:
image

However, this also seems to be an issue with the old display, again not something introduced by this PR.

**Comment by fkiraly** [comment]
Since these seem to be existing problems and not introdued or changed by this PR, moving them to a new issue: https://github.com/sktime/sktime/issues/6903

**Review by fkiraly — APPROVED** [review]

**Pull request merged**
