### PR TITLE
[BUG] `plot_cluster_algorithm`: fix error "`predict_series  is undefined`" if `X` is passed as `np.ndarray`

### PR DESCRIPTION
**Pull request by hakim89**
#### What does this implement/fix? Explain your changes.
currently plot_cluster_algorithm function in sktime/clustering/utils/plotting/_plot_partitions.py throws an error if X is passed as a numpy array in the function. Error is because predict_series is undefined

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by miraep8** [comment]
Hey @hakim89, this looks like a reasonable bug change to me 👍 Thanks for spotting it.  

Regarding the linting failure - the easiest way to fix it (and make sure you don't run into future issues in sktime contributions) would be to install our pre-commit.  Instructions for how to do that [here](https://pre-commit.com/).  Ping me if you run into any issues though! :)  

Cheers!

**Comment by hakim89** [comment]
Thank you @miraep8. I ran pre-commit locally and pushed the white-space changes. Hopefully I did it correctly (first time contributing ). That same file (and few functions in it) might need some optimization and I might push more changes soon. Currently it fails silently to draw timeseries data into centers if the number is large.

**Review by fkiraly — APPROVED** [review]
Thanks for the fix, @hakim89!

**Comment by fkiraly** [comment]
Feel free to add yourself as a contributor to `all-contributorsrc` with the `bug` badge!

**Pull request merged**
