### PR TITLE
[ENH] Make `TimeSince` trafo faster by changing period diff calculation

### PR DESCRIPTION
**Pull request by KishManani**
#### What does this implement/fix? Explain your changes.
Inspired by how @ltsaprounis calculated the integer time difference when using a `PeriodIndex` in the `FourierFeatures` transformer, I've switched to using this alternative method which is *much* faster. I measured a factor of ~100 speed up in `_transform`.

An example to measure the difference:
```Python
from sktime.utils._testing.hierarchical import _make_hierarchical
from sktime.transformations.series.time_since import TimeSince

df =_make_hierarchical(hierarchy_levels=(10000,), min_timepoints=200, max_timepoints=200)

trafo = TimeSince(freq="D")
trafo._fit(df)
trafo._transform(df)
```

This PR will have conflicting changes with https://github.com/sktime/sktime/pull/4015. Once https://github.com/sktime/sktime/pull/4015 has merged I will resolve the conflicts in this PR. 

#### What should a reviewer concentrate their feedback on?
Code quality. I'm having to write a lot of comments to explain the context of what's going on. I'm unsure whether this is a bad smell. 

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [x] I've added unit tests and made sure they pass locally.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

### CODE REVIEW

**Comment by fkiraly** [comment]
Merged https://github.com/sktime/sktime/pull/4015 so avoiding conflicts should now be easier.

**Review by fkiraly — APPROVED** [review]
I can confirm the speedup.
In a fresh python 3.10 env on windows, the example is reduced from 7 sec to 300 msec.

Functionality seems unaffected.

**Comment by KishManani** [comment]
It appears there are no conflicts 🤷‍♂️ , that saves some time then!

**Comment by fkiraly** [comment]
Re comments: I think this is a bit of a smell, but I would say, ultimately it's coming from `pandas` (and how it handles indices). The dependent code isn't bad.

**Pull request merged**
