### PR TITLE
[ENH], [BUG] utils/plotting.py: change `plot_series` to use `matplotlib` conventions; enhance `plot_interval`

### PR DESCRIPTION
**Pull request by ericjb**
1. `sktime.utils.plot_series` now handles `xticks` following `matplotlib` defaults. (Fixes https://github.com/sktime/sktime/issues/5895) As a result fig,ax objects returned by `plot_series` can be used correctly by matplotlib. See accompanying pdf for details including some before and after plot comparisons. (section 3 in the pdf)

2. Fixed (or enhanced) sktime.utils.plot_series() so that it can plot multiple coverage levels if present in the pred_interval multiindex. (section 5 in the pdf)

[PullRequestNotes.pdf](https://github.com/sktime/sktime/files/15298401/PullRequestNotes.pdf)

Fixes issues highlighted in revert https://github.com/sktime/sktime/pull/6498 as follows:

`markersize = 4` changed to `s = 4` in call for `matplotlib` scatter plot

### CODE REVIEW

**Comment by ericjb** [comment]
It seems the changes I made addressed the previous issues. Some of the most recent tests (last 20 minutes or so) seem to have been cancelled but it is not clear to me what the issues are. Any guidance would be appreciated. Thanks

**Comment by fkiraly** [comment]
>  Some of the most recent tests (last 20 minutes or so) seem to have been cancelled but it is not clear to me what the issues are.

Sorry, I've cancelled them to make space for release related CI today.

Announcements like that are made on the dev-chat channel of the discord:
https://discord.com/channels/1075852648688930887/1080978709412069426

**Comment by ericjb** [comment]
I tried to use that link to the discord dev-chat but it didn't work. I have never used discord before so it is possible/probable I am doing something wrong. Thanks for any help

**Comment by fkiraly** [comment]
Here's the generic invite to the server in case you have not signed up yet: https://discord.com/invite/54ACzaFsn7
(let us know if htis works)

**Comment by ericjb** [comment]
The Discord link worked. I signed up for the dev-chat channel. Tnx

**Pull request merged**
