### PR TITLE
[DOC] add proper author credits to 1:1 interface classes - aligners, distances, forecasters, parameter estimators

### PR DESCRIPTION
**Pull request by fkiraly**
This PR adds proper author credits to a larger range of interface classes, in line with the decision in https://github.com/sktime/sktime/issues/5938. This covers the time series alignment, distance/kernels, forecasting, and parameter estimator modules, and should add all missing credits within (any omissions are unintentional).

These are mainly older classes, prior to the policy #5938.

I am tagging everyone and would appreciate comments if you think you should not be on the list, should be on the list in a different position, should be on a list on which you are not, or think someone else is missing.

Detail list of changes:

* @tonigi for all estimators interfacing `dtw-python`
* @rtavenar and @yanncabanes were missing on one `tslearn` estimator, `SoftDtwDistTslearn`
* @bashtage for all estimators interfacing `arch`
* @bashtage for `statsmodels` `ARDL`
* @bashtage for `statsmodels` `AutoREG`
* @cotterpl for all estimators interfacing `tbats`
* @benHeid for `CINNForecaster`, pykan based forecaster (I consider these to be original enough to be non-1:1)
* @chadfulton and @bashtage for `statsmodels` `DynamicFactor`
* @bashtage, @wooqo for `statsmodels` `HoltWinters`
* @bletham, @tcuongd for all estimators interfacing `prophet`
* @mixiancmx, @ailingzengzzz for `cure-lab` ltsf-linear family
* @JoaquinAmatRodrigo, @JavierEscobarOrtiz, @FernandoCarazoMelo for `skforecast` auto-regressor
* @ChadFulton and @bashtage for `UnobservedComponents` in `statsmodels`
* @yogabonito, @ChadFulton, @bashtage, @josef-pkt for `statsmodels` `VAR`
* @ChadFulton and @bashtage for `statsmodels` `VARMAX`
* @yogabonito, @bashtage, @josef-pkt for `statsmodels` `VECM`
* updated GitHub account name of @AzulGarza in all references
* @AzulGarza, @jmoralez for `statsforecast` theta
* @AzulGarza, @jmoralez, @MMenchero for `statsforecast` `AutoCES`
* @AzulGarza and @jmoralez for `statsforecast` `AutoETS`
* @MMenchero, @AzulGarza, and @jmoralez for `statsforecast` `GARCH`
* @MMenchero and @jmoralez for `statsforecast` `AutoTBATS`
* @AzulGarza and @jmoralez for `statsforecast` `MSTL`
* @yarnabrina, @arnaujc91 and @luca-miniati are credited in all `statsforecast` facing classes for work on the interface adapters

### CODE REVIEW

**Comment by fkiraly** [comment]
one question to @chadfulton, @bashtage: from inspecting the `statsmodels` `git` history, I gather that 12 or 13 years ago some models were migrated from another code base, with earlier commit history possibly list. Is someone missing there?

**Comment by josef-pkt** [comment]
about statsmodels history

git includes all commits, even though the repo has changed several times
https://github.com/statsmodels/statsmodels/commits/main/?after=d02d785b618afc3ce79859b9417ea7c0165d89ea+15350

github history, especially on file level, either stops with renaming of the package or with switching from launchpad to git/github.

However, AFAICS all tsa code that you refer to is relatively recent code with the correct author list.
I think there are no old estimators left, which was mainly the old ARIMA that has been removed. 

VAR is still mostly the original code. (gh history stops at `REF: Move scikits/statsmodels -> statsmodels` while first commit seems to be 2010 https://github.com/statsmodels/statsmodels/commit/f37161497fe029f6de876cdf378ad7554bb57020  (found in blame)

Some supporting tsa code like acf or pacf in tsatools or stattools is old and still mostly or partially the original code which, IIRC, started around 2010.

**Comment by fkiraly** [comment]
Interesting!

While I have your attention, @josef-pkt, I've noticed there are two different SARIMAX models in `statsmodels` - is this correct?
``tsa.arima.model.ARIMA`` and ``tsa.statespace.SARIMAX``, both actually being SARIMAX.

I have been wondering about an explanation here, and the history of this. Should these be considered different estimators?

**Comment by josef-pkt** [comment]
> tsa.arima.model.ARIMA and tsa.statespace.SARIMAX

I stopped working on tsa years ago. @ChadFulton and @bashtage are handling those and know the details.
AFAICS, arima.model.ARIMA subclasses SARIMAX, but it includes additional estimation/fit methods that are simpler and faster in less general cases and was a replacement for the original ARMA/ARIMA classes.
For example, hannan_rissanen was often used as preliminary estimator to get start_params for ARMA MLE because it is much faster.

**Comment by fkiraly** [comment]
It's a bit weird that it lives in another module and subclasses. I gathered that there are different fitting strategies, but the rationale behind the situation eludes me (and I was also unable to reconstruct from the full docs). It is also relevant for crediting, as the subclassing is a kind of model forking into what are now, at least at face value, separate estimators.

**Comment by josef-pkt** [comment]
That's not really different from similar cases for other models.
GLM versus discrete and OLS, same underlying models, different estimators with potentially different properties.
VAR versus VARMAX, the former is least squares, the latter is full MLE.

Estimator even for the same underlying model may differ in computational performance, options and, substantively, different robustness to partial misspecification. For example, parameter estimates in OLS and GLM are robust to misspecified variance/heteroscedasticity, full MLE is not and might fully depend on correctly specified likelihood function.

(I never looked at misspecification robustness of e.g. least squares VAR versus full MLE VAR(MAX), or other tsa cases.)

As for location: that depends on whether a directory is dedicated to only one class of estimators.
`statespace` has only statespace models with full MLE AFAIK, while other parts of tsa might have more eclectic estimators (like ARIMA) but might still use a statespace representation as computational tool.
(Similar, `genmod` GLM has only one-parameter linear exponential families with possible variance/dispersion parameters as auxiliary, analogous to OLS. `discrete` only has full MLE models. For large parts estimators overlap and produce essentially the same results, in other cases they differ in what is estimated.)

**Comment by fkiraly** [comment]
I see, so do I understand correctly then, estimators are ordered by fitting strategy and internal modelling strategy, e.g., MLE or state space representation etc.

**Comment by josef-pkt** [comment]
the `statespace` folder is a hybrid, it includes both the statespace tools implementation and specific models, sarimax, varmax, eponential smoothing, ..., estimated by MLE of the statespace representation.
Other directories in tsa include a specific model which may or may not use the statespace representation to estimate. 
I just saw that there is tsa.exponential_smoothing and tsa.statespace.exponential_smoothing.

Part of it is literature and historical development of estimators.
e.g. I guess tsa.exponential_smoothing tries to match features for ets (in R, ...) while tsa.statespace.exponential_smoothing is just a specific application of the statespace model framework.

GLM versus discrete is also largely a historical distinction, the formerly developed by statisticians, the latter developed mainly by econometricians, aside from the remaining statistical differences that we maintain. (e.g. R, SPSS and other packages lump models into GLM that are not based on linear exponential families)

So, model directories can focus on one underlying model with various estimators or one estimation framework with several models based on it (like statespace), or some topic (like forecasting, treatment outside tsa, ...)

Deciding on the module and directory structure is work and not trivial. It's not always obvious where to put new things. 
(I'm struggling with this outside tsa, either  several directories would match or no directory matches well for a new feature and new directories are unclear what they will include in future development and what their name and theme should be.)
The current module structure is partially historical path dependent and maybe not be the best given recent and future development.

**Comment by fkiraly** [comment]
> Deciding on the module and directory structure is work and not trivial. It's not always obvious where to put new things.

Hah, indeed! Just ask @yarnabrina about it, e.g., see:
https://github.com/sktime/sktime/issues/4950

It also becomes more difficult to change once users depend on it, as changes will break backwards compatibility...

My most radical idea in this sense is a completely flat, unique namespace for estimators, but using tags, which can define hierarchies as the user wants them. Of course that does not solve the issue that there can be only one "ARIMA", when adopting a flat namespace...

**Comment by fkiraly** [comment]
There actually is one issue on all the ARIMA models already: https://github.com/sktime/sktime/issues/2402

**Comment by josef-pkt** [comment]
What I prefer for the final user is to use a method (or maybe in your case a backend) keyword option for high level or application classes, i.e. option

* should there be one backend-independent "dispatcher"

I usually add a minimal "results" instance that is method neutral and attach the original results as attribute for when the user wants to check the details.
The main advantage for users is that there is a common interface, except for `kwargs`.

I don't know how well that would apply in your case.

**Comment by fkiraly** [comment]
It might apply, the problem is that `sklearn` compatible interfaces - at least if treate idiomatically - want all parameters explicit in the `__init__`, since that is also the locus of inspection for which parameters are present.

Different ARIMAs will have different sets of parameters, which makes the dispatching solution difficult.

**Comment by tonigi** [comment]
Since we are there, is it possible to link docstrings mentions of `dtw-python` to its main page https://dynamictimewarping.github.io/ ? (and ideally the JOSS paper). I can create a clean PR if needed.

**Comment by fkiraly** [comment]
> Since we are there, would it be possible to link docstrings mentions of dtw-python to its main page https://dynamictimewarping.github.io/ ? (and ideally the JOSS paper). I can create a clean PR if needed.

Of course! Please go ahead with a clean PR!

Also, if you want, you can also add your name to the maintainers tag to take ownership.

**Comment by fkiraly** [comment]
@tonigi, for convenience here is the list of estimators depending on `dtw-python`:

* `AlignerDTW`
* `AlignerDTWfromDist`
* `DtwPythonDist`

**Pull request merged**
