### PR TITLE
[MNT] fixed typo in docstring

### PR DESCRIPTION
**Pull request by yarnabrina**
- Fixed typo identified by `codespell`
- Creating PR from branch in personal fork to debug `codecov` upload issues

### CODE REVIEW

**Comment by yarnabrina** [comment]
@fkiraly any idea why code-quality job is not running? It's not even queued!!

image

**Comment by fkiraly** [comment]
> @fkiraly any idea why code-quality job is not running? It's not even queued!

perhaps the conflict with `main`?

**Comment by yarnabrina** [comment]
> perhaps the conflict with main?

The `test.yml` in this PR (#5950) is identical to that in #5949, I actually copy pasted. I don't understand why that one does not show conflicts, and why that one triggers CI. Does Github not detect conflict in same repository branches?

**Comment by fkiraly** [comment]
Yes, a conflict is triggered:

image

**Comment by yarnabrina** [comment]
> Yes, a conflict is triggered:

I wasn't saying it is not. I was pointing out that my changes were identical in both PR's, so it makes no sense to me why git will detect conflict for one and not for other.

---

I am considering that debugging is complete, at lease what was in scope for this PR. Removing debug changes and keeping the PR open for review and merge as a normal typo fix PR.

**Review by fkiraly — APPROVED** [review]

**Pull request merged**
