### PR TITLE
[DOC] ExponentialSmoothing default method change from L-BFGS-B to SLSQP

### PR DESCRIPTION
**Pull request by manuel-munoz-aguirre**
#### Reference Issues/PRs
While exploring #6175, realized that the default parameter for `method` in Exponential Smoothing should be `SLSQP`. This also affects statsmodels documentation and there is already an [open PR](https://github.com/statsmodels/statsmodels/pull/9129) in their repo to fix this.

#### What does this implement/fix? Explain your changes.
Changes `method='L-BFGS-B'` to `method='SLSQP'`.

#### Does your contribution introduce a new dependency? If yes, which one?
No

#### What should a reviewer concentrate their feedback on?
See [statsmodels default](https://github.com/statsmodels/statsmodels/blob/192670b31c9069b247b0901d66013853e2ca47b7/statsmodels/tsa/holtwinters/model.py#L1142C1-L1142C55)

#### Did you add any tests for the change?
N/A

#### Any other comments?
N/A

##### For all contributions
- [X] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [X] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks!

Quick question, may I clarify which of the following is the case:

* `None` translates to `SLSQP` in `statsmodels` already
* `None` will translate to `SLSQP` in `statsmodels` at some future point, when a planned PR is going to be merged and the default will change
    * this, and `statsmodels` is not raising a deprecation warning
    * this, and `statsmodels` is, or will be raising a depercation warning

Depending on what is the case here, we may have to take additional steps, in accordance with change/deprecation policy:
https://www.sktime.net/en/latest/developer_guide/deprecation.html 

As a first step, I feel we should change the default from `None` to what it currently is in `statsmodels`. FYI @benHeid, @yarnabrina

**Comment by yarnabrina** [comment]
@fkiraly based on the shared link above, it seems `statsmodels` uses `SLSQP` already when `method` is specified as `None`, and the Git blame is 4 years old. We may not need deprecation cycle as no behaviour will change, and this PR can be considered just as a docs update.

https://github.com/statsmodels/statsmodels/blame/192670b31c9069b247b0901d66013853e2ca47b7/statsmodels/tsa/holtwinters/model.py#L1142

**Review by fkiraly — APPROVED** [review]
Makes sense.

In that case, we should consider changing the `sktime` default to `"SLSQP"` (separate from this PR), to avoid behaviour switching again.

**Comment by manuel-munoz-aguirre** [comment]
Should I go ahead and open a new PR switching the default value from None to SLSQP? @fkiraly

**Comment by fkiraly** [comment]
Not sure whether we should. Since it is a very small change, how about this - you open a PR, and then we discuss with other core devs what they think?

**Pull request merged**
