### PR TITLE
[ENH] bagging/bootstrap forecaster extended to multivariate, exogeneous, hierarchical data

### LINKED ISSUE #6042: [ENH] improvements to `BaggingForecaster`
Improvement todos for `BaggingForecaster`, with a view towards integation with `tsbootstrap`:

* the functionality should be extended to multivariate, possibly hierachical forecasters
* the implementation of `predict_quantiles` should be removed in favour of one of `predict_proba`, using `Empirical` distribution
* A test should be introduced, or test parameter set, with the new `tsbootstrap` bootstrap transformer.

### LINKED ISSUE #6340: [BUG] Exogenous variables in ARIMA are not passed into BaggingForecaster
**Describe the bug**
Hi, I want to flag that exogenous variables in ARIMA are not passed into BaggingForecaster. It looks like regardless whether I fit the function with/without exogenous variables, BaggingForecaster always fit ARIMA without exogenous variables. 

**To Reproduce**

```python
import pandas as pd
from sktime.forecasting.arima import ARIMA
from sktime.datasets import load_airline
from sktime.transformations.bootstrap import STLBootstrapTransformer
from sktime.forecasting.compose import BaggingForecaster

y = load_airline()
y = y.reset_index(drop = False)
y['month'] = y.Period.dt.month

# add monthly dummies
y = pd.concat([y.drop(['month'], axis = 1), pd.get_dummies(y['month'], dtype='int32')], axis = 1)
y.columns = ['period', 'passengers', 'fq_1', 'fq_2',  'fq_3',  'fq_4' , 'fq_5',  'fq_6',  'fq_7',  'fq_8',  'fq_9',  'fq_10',  'fq_11',  'fq_12']
 
y_train = y[:-24]
# y_test = y[-24:]

transformer = STLBootstrapTransformer(2, sp = 12, random_state = 1234)
arima = ARIMA(order = (1, 0, 0), seasonal_order=(0, 0, 0, 12))
forecaster =  BaggingForecaster(
                                transformer, arima)

# X variables are monthly dummies in AR(1)
baggingforecaster.fit(X = y_train[['fq_1', 'fq_2',  'fq_3',  'fq_4' , 'fq_5',  'fq_6',  'fq_7',  'fq_8',  'fq_9',  'fq_10',  'fq_11']], y = y_train['passengers'])
```
[
image001-2
](url)
**Expected behavior**
I tested arima. Exogenous variables flow through as expected

```python
arima.fit(X = y_train[['fq_1', 'fq_2',  'fq_3',  'fq_4' , 'fq_5',  'fq_6',  'fq_7',  'fq_8',  'fq_9',  'fq_10',  'fq_11']], y = y_train['passengers'])
```
Screenshot 2024-04-26 at 9 38 19 AM

**Additional context**

**Versions**
sktime == 0.26.0

</details>

### PR DESCRIPTION
**Pull request by fkiraly**
This PR extends `BaggingForecaster` (the main consumer of bootstrap transformers) to support:

* exogeneous data
* multivariate data
* hierarchical and panel data
* full probabilistic prediction (empirical)

Closes #6042, fixes #6340

Depends on:

* https://github.com/sktime/sktime/pull/6066 for the probabilistic mode
* https://github.com/sktime/sktime/pull/6341 for the probabilistic mode
* https://github.com/sktime/sktime/pull/6067 for `predict_var`

FYI @astrogilda, @benHeid

### CODE REVIEW

**Comment by fkiraly** [comment]
Very odd - the failures are `pandas.MultiIndex` related, and I cannot reproduce them locally (`pandas 2.2.1`, windows, python 3.11)

**Comment by sanjayk0508** [comment]
@fkiraly I looked into the PR, and here are some potential problem areas I could spot:

1. In the `_base.py` file, it indicates that there is currently no support for multivariate data. If the hierarchical data is multi-dimensional, it would cause problems.
2. While the `BaggingForecaster` is designed to handle hierarchical and panel data, non-uniqueness in the index of the hierarchical data might lead to `pandas.MultiIndex` related errors, which appears to be occurring on your end.
3. The implementation of the full probabilistic prediction involves rearranging bootstrapped index level - `y_bootstraps_pred = y_bootstraps_pred.reorder_levels([-2] + list(range(n_ist_lv)) + [-1], axis=0)`. There is a possibility that the logic for index rearrangement could be incorrect or failing for some scenarios, potentially causing errors.
4. The `_update` method concatenates the old `self._y` and new `y` data and then transforms it using the bootstrap transformer. If the data is not compatible with the transformation or has some inconsistencies, it could lead to an error during the update.

If the problem still persists, you might want to look into how the bootstrapped indices are handled both for predictions and when creating the empirical distribution.

**Comment by sanjayk0508** [comment]
Regarding your questions:
1. In the `_base.py` file, I noticed the [comment](https://github.com/sktime/sktime/pull/6052/files#diff-18a6ee59945d0bba8c0c53e4ac2fbbec3f8002b41455d74e0c344187ba06fda0L2295) `# todo: this works only univariate now, need to implement multivariate`, so I thought it might be a possible issue.
2. I meant to suggest checking the uniqueness of the index in the hierarchical data, which can be found [here](https://github.com/sktime/sktime/blob/main/sktime/datatypes/_panel/_check.py#L412). This could potentially be where the issue lies.
3. I'm not entirely sure either, however, I thought it would be worthwhile to point out these potential areas of concern.

These are just some of the things that I could find which could potentially be causing the problem.

**Comment by fkiraly** [comment]
Just for completeness, the first reply is copied from discord, and here's my reply to that:

Thanks a lot for looking into this! Generally, it's best to put detail comments like these on the PR.
Would appreciate if you could repost on the PR and we continue there?

Some quick replies:
1.  you mean the tag? These are just default settings, and there's boilerplate handling (broadcasting), that's probably not hte problem.
2. how do you infer this? Where exactly?
3. hm, I thought it's correct though. Where is it failing in your opinion? Could be, of course.
4. the errors are not coming from `_update` afaik.

**Comment by fkiraly** [comment]
> 1. In the _base.py file, I noticed the [comment](https://github.com/sktime/sktime/pull/6052/files#diff-18a6ee59945d0bba8c0c53e4ac2fbbec3f8002b41455d74e0c344187ba06fda0L2295) # todo: this works only univariate now, need to implement multivariate, so I thought it might be a possible issue.

Ah, I see! That's actually fixed by #6067 imo, so the comment can be removed. I will do it in #6067 directly.

> 2. meant to suggest checking the uniqueness of the index in the hierarchical data, which can be found [here](https://github.com/sktime/sktime/blob/main/sktime/datatypes/_panel/_check.py#L412). This could potentially be where the issue lies.

Ah, I understand. Yes, that's a good idea, will check if that's causing problems.

> 3. I'm not entirely sure either, however, I thought it would be worthwhile to point out these potential areas of concern.

Yes, agreed, I don't like it ending up this way either, I've opened an issue here to discuss design of probability distributions with hierarchical index:
https://github.com/sktime/skpro/issues/212

**Pull request merged**
