### PR TITLE
[BUG] Addition of feature_kind metadata attribute to GluonTS Datatypes

### LINKED ISSUE #6860: [BUG] `feature_kind` metadata missing in gluonTS scitype causing errors in CI
**Describe the bug**

Errors in CI because the `feature_kind` metadata is not stored for the newly added gluonTS scitypes.
Example error in CI: https://github.com/sktime/sktime/actions/runs/10131002407/job/28014414057#step:10:2644

**Additional context**

FYI @shlok191 
Similar problem occurred with polars and has been resolved. 
Here is the link to comment where I have explained what needs to be done - https://github.com/sktime/sktime/issues/6815#issuecomment-2244310505
Let me know if you need any clarification.

</details>

### PR DESCRIPTION
**Pull request by shlok191**
#### Reference Issues/PRs
Fixes #6860 

#### Does your contribution introduce a new dependency? If yes, which one?
No added dependencies

#### What should a reviewer concentrate their feedback on?
`sktime/datatypes/_panel/_check.py` and `sktime/datatypes/_series/_check.py`

#### Did you add any tests for the change?
I did not

#### Any other comments?
No comments

##### For all contributions
- [X] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [X] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [X] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

### CODE REVIEW

**Comment by shlok191** [comment]
@fkiraly, Hello Franz! I have made changes to the GluonTS code to incorporate the new metadata requirements. :)
Thanks for waiting on me and for the temporary fix you implemented!

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks!

I do not think it is a good idea to convert to entire data container to pandas in the checker, just to obtain the pandas dtypes! Sure, this works, but it is contingent on a peripheral conversion utility, and is wasteful of memory and compute.

Surely there is sth simpler we can do?

**Comment by shlok191** [comment]
@fkiraly, Yes, I agree that was not the best way to go about this! 😅 I have updated the implementation for `GluonTS_ListDataset` now however which should not be putting the passed object through a pandas conversion.

I hope this is better! I will be using this to complete my LagLLama PR as well

**Review by fkiraly — APPROVED** [review]
This works for me!

Question, are the types really always float in the `listDataset`? I honestly don't know, but I trust you checked this.

**Pull request merged**
