### PR TITLE
[ENH] removed py37.dockerfile and update doc entry for CI

### LINKED ISSUE #5309: [ENH] update and test python versions in dockerized tests; remove python 3.7
We should update the python versions in the dockerized tests we provide for convenience.

We should also remove the python 3.7 docker, as python 3.7 has reached EOL.

The docker files are in `build_tools/docker`.

Good first issue for anyone with basic docker familiarity.

### PR DESCRIPTION
**Pull request by kurayami07734**
### Changes
- [x] Removed dockerized test for python 3.7 (as it has reached EOL)
- [x] Updated corresponding doc entry for dockerized test

### Concerns
While trying to update the other dockerfiles, I came across a bug (See also #5352), such that tests are unable to run.

### CODE REVIEW

**Comment by yarnabrina** [comment]
Thanks for your contribution.

I'll suggest to update the base images, e.g. from 3.8.16-bullseye to 3.8-slim-bullseye. This will use latest patch releases, and will also decrease the image size.

Note: slim may require installation of few system dependencies separately with apt-get or something, as by default a lot of things are installed in the non-slim image.

**Comment by kurayami07734** [comment]
Please consider adding the hacktoberfest label to this issue

**Comment by achieveordie** [comment]
If we are changing our base image, we might as well choose `bookworm` which is the current stable version of Debian. [Info](https://wiki.debian.org/DebianBookworm) about bookworm. We can choose to use the more efficient version as @yarnabrina suggested but I think that is beyond the scope of this PR.

I've created a new issue #5359 where we can discuss the appropriate choice for our base image.

**Comment by yarnabrina** [comment]
Agreed on `bookworm`. We can use just `3.8-slim` etc. then I suppose.

**Review by fkiraly — DISMISSED** [review]
@kurayami07734, this does not close #5309 since only part is carried out - having said that, it seems fine to merge, a 3.7 has reached EOL

**Comment by kurayami07734** [comment]
Why are the workflows not running?

**Comment by achieveordie** [comment]
PRs from first time contributors need to be specifically approved before they can run. I've started the runners, this PR should pass without any problems since we only have documentation changes here.

Thanks for the contribution!

**Comment by kurayami07734** [comment]
It would be really nice, if you could add the hacktoberfest labels

**Review by achieveordie — APPROVED** [review]

**Comment by fkiraly** [comment]
> Please consider adding the hacktoberfest label to this issue

The repo has the tag so it would count.

Just read @yarnabrina's request, would you mind also addressing that efore we merge, @kurayami07734? Seems in scope to me.

**Comment by kurayami07734** [comment]
> The repo has the tag so it would count, no need to extra tag PRs.

screenshot-2023-10-06_23:39:15
I had asked because of the above

> Just read @yarnabrina's request, would you mind also addressing that i a separate PR, while we are at it, @kurayami07734?

Sure, I have no problem with that

**Comment by fkiraly** [comment]
> But how would I run the tests (See https://github.com/sktime/sktime/issues/5352)

You would have to diagnose and repair the issue with the missing ranch first.

**Comment by kurayami07734** [comment]
How has this conflict emerged?

**Review by fkiraly — APPROVED** [review]
Sure, we can merge this.

The conflict appeared since you didn't update from `main` regularly - it is recommended to update from main regularly while you develop. In this specific case, the automatic contributor list generation conflicted with the list from this PR and the list from main.

**Pull request merged**
