### PR TITLE
[MNT] include unit tests in `sktime/tests` in per module tests

### LINKED ISSUE #6352: [BUG] logic problem with new CI - coverage of `TestAllEstimators` and `TestAllObjects` incorrect
I think there is a bug in the new CI. The coverage is not affected since "old CI" is still running.

The issue occurs when, say, a forecaster changes.

The new CI will then trigger tests in `sktime.forecasting`, but not in `sktime.tests` which contains `TestAllEstimator`.
So, we run the forecaster specific tests for the changed forecaster, but not the object and estimator specific tests.

FYI @yarnabrina, is there a way to fix this?
The "one liner" to "run all tests for estimator X" is `check_estimator` - however, this is intentionally avoided in the original setup as an entry point since this distributes less well across workers, via `pytest-xdist`.

### PR DESCRIPTION
**Pull request by yarnabrina**
Fixes #6352

This PR adds coverage of `sktime/tests` for per module CI workflows.

### CODE REVIEW

**Review by fkiraly — APPROVED** [review]
I agree that this will fix the lack of coverage situation.

While it will not fix "too much tests", I think it is fine as that is a rare case.

**Review by fkiraly — CHANGES_REQUESTED** [review]
Perhaps let's pause until we know what is going on with collection, see https://github.com/sktime/sktime/issues/6352 - or the Ci will become impracticably slow.

**Comment by yarnabrina** [comment]
@fkiraly is there anything pending from my side on this one? I'm aware that we have not narrowed down what is going wrong with timeouts really, but not sure if that'd be part of this PR's scope (other than more tests possibly increasing that chance further).

**Comment by fkiraly** [comment]
should we merge?

**Comment by yarnabrina** [comment]
Yes, I'd like to. It'll also let us know how much it has an effect on increased times on the main branch.

**Review by fkiraly — APPROVED** [review]
Ok, sure. Seems low risk, and we are far from the May release.

**Pull request merged**
