### PR TITLE
EXPERIMENTAL: [MNT] python 3.11 compatibility with `numba` as soft dependency

### PR DESCRIPTION
**Pull request by fkiraly**
Experimental PR which tests python 3.11 compatibility after `numba` is turned into a soft dependency.

This is a merge of two PR:

* PR https://github.com/sktime/sktime/pull/3843 which turns `numba` into a soft dependency
* PR https://github.com/sktime/sktime/pull/3647 which updates package metadata to 3.11 support

with the modifications that:

* `numba` is part of the `all_extras` only for python 3.10 and lower.
* `tensorflow` is part of the `all_extras` only for python 3.10 and lower.

### CODE REVIEW

**Comment by patrickzib** [comment]
89 files touched for an issue that will be solved by the numba developers in the coming months! Also note that conda does not even support python 3.11 by now. This is the main reason, that here is no numba support. Bugfixes should be minimally invasive. I am calling for a vote on this PR, too.

**Comment by patrickzib** [comment]
Here is the reason for the missing numba support: 

> Our build and release process is based around conda. We can't run CI reliably without an official Python 3.11 package being released via anaconda.org. Hence we are currently blocked by that. We hope to get this merged up and a new version released as soon as the required packages become available. Until then, please be patient, thank you!

https://github.com/numba/llvmlite/pull/869#issuecomment-1313215683

**Comment by fkiraly** [comment]
> 89 files touched for an issue that will be solved by the numba developers in the coming months!

No, `numba` developers will not solve the issues of dependency isolation and that our users all are forced to install `numba`

**Comment by patrickzib** [comment]
You are the only one that does not want to install numba.

**Comment by fkiraly** [comment]
why is this trying to install `numpy 1.19`?

**Comment by fkiraly** [comment]
can be closed, same as #3843 under current `main`

**Pull request closed without merging**
