### PR TITLE
[ENH] Interface of `AutoReg` from `statsmodels` as a forecaster

### PR DESCRIPTION
**Pull request by pranavvp16**
#### What does this implement/fix? Explain your changes.
Added interface for AutoReg from statsmodel to sktime

#### Does your contribution introduce a new dependency? If yes, which one?
NO

#### Did you add any tests for the change?
Added test to compare the forecaster with statsmodel forecaster. The test is added in tests folder of forecasters

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [x] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by fkiraly** [comment]
looks great!

Small thing, code formatting checks are failing, see here for the guide:
https://www.sktime.org/en/stable/developer_guide/coding_standards.html

**Comment by pranavvp16** [comment]
I have changed the some linting and code formatting style , should pass code quality checks this time !

**Comment by pranavvp16** [comment]
changed code format locally by pre-commit

**Review by fkiraly — CHANGES_REQUESTED** [review]
Nice! This looks great!

The failing tests indicate that there is something wrong with how exogeneous data is treated, i.e., `X`, when it is passed. All seems fine when `X=None`, from the looks of it.

**Comment by pranavvp16** [comment]
@fkiraly  so do I need to make any changes , if yes then what changes ?

**Comment by fkiraly** [comment]
> @fkiraly  so do I need to make any changes , if yes then what changes ?

I do not know precisely which changes without debugging, so I would recommend you do the same. Use `check_estimator` to run the test-fixture combination for one of the failing tests, I suspect it is the same problem for all of them.

Try to match what you do with `X` to the interface expectations of `statsmodels.AutoReg`.
Let us know if you get stuck with debugging and an `sktime` can take a look later.

**Comment by fkiraly** [comment]
superseded by https://github.com/sktime/sktime/pull/4774

**Pull request closed without merging**
