### PR TITLE
[MNT] Dataset downloader testing workflow

### PR DESCRIPTION
**Pull request by yarnabrina**
Replaces #5004
Depends on #5304

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Nice!

Main problem: this does not remove the download items from the existing tests, so it duplicates, instead of replacing.

Non-blocking: names of the CI steps should be clearer. Writing "step" everywhere is also redundant and makes things harder to read.

**Comment by yarnabrina** [comment]
@fkiraly Ignoring non-blocking shorter names for the moment, unless you have some ready suggestions. Can be done as part of the new issue you created.

I don't understand the duplicating. New CI do not test datasets at all. It only tests per extra, and even in the new PR where I added test of everything else using all_extras, I intentionally skipped datasets so that this PR is the only one dealing with datasets folder.

Can you please clarify what you mean?

**Comment by fkiraly** [comment]
> Can you please clarify what you mean?

Of course - afaik the dataset downloads are *still* run as part of the workflows named "install and test", in `workflows/test.yml`.

So, in a situation where the downloads start failling, they still would paint the `test.yml` workflows red.

**Comment by yarnabrina** [comment]
I was focusing on the new CI and didn't want to modify the old CI.

I've removed it from old CI now as per review suggestion. Requesting review.

**Comment by fkiraly** [comment]
thanks! I rememer when I did this in in #5004, it somehow turned off the matrix testing and differential testing logic, and I never figured out why.

**Comment by yarnabrina** [comment]
Based on job times and number of tests, at least that problem seems to be solved.

(I can't explain why it happened in #5004 though.)

**Comment by fkiraly** [comment]
Yes, indeed.

**Review by fkiraly — APPROVED** [review]

**Pull request merged**
