### PR TITLE
[BUG] fast test parameters for `TapNet` estimators and docstring/interface cleanup

### LINKED ISSUE #3525: [BUG] TapNet test failures and long test times
TapNet is currently failing the macOS 3.7 test (`Install and test / test-unix (3.7, macOS-11) (pull_request)`) in PR #3523. The PR makes no changes relevant to TapNet or DL estimators, and the test times are extremely high.

https://github.com/sktime/sktime/actions/runs/3174214839/jobs/5170841022

image

### PR DESCRIPTION
**Pull request by achieveordie**
#### Reference Issues/PRs

Fixes #3525

#### What does this implement/fix? Explain your changes.

- Add `get_test_params()` for `TapNetRegressor` and `TapNetClassifier` with two parameter set.
- Remove the redundant `is_fitted` variable from TapNet estimators.
- Correct minor typos.

#### Does your contribution introduce a new dependency? If yes, which one?

No

#### What should a reviewer concentrate their feedback on?

@TonyBagnall LMK if we should make any more changes here.

### CODE REVIEW

**Comment by fkiraly** [comment]
@achieveordie, every estimator should have at least 2 sets of test parameters, covering a good range of typical values.

**Comment by achieveordie** [comment]
So should I change it to have a different set of parameters for a different value of `parameter_set`? Something like the one that I have for `default` and larger parameter values for a new one called ``slower`? Or should I just change the default values since these values are already there for `TapNetClassifier`? I'm not sure I understand.

**Comment by fkiraly** [comment]
look at the example in `NaiveForecaster`.

The goal is to get a good decision coverage and parameter value coverage:
https://en.wikipedia.org/wiki/Code_coverage#Modified_condition/decision_coverage
https://en.wikipedia.org/wiki/Code_coverage#Parameter_value_coverage

**Comment by TonyBagnall** [comment]
I think he wants you to define two parameter sets and return them as a list like this https://github.com/sktime/sktime/pull/3428/files

**Comment by TonyBagnall** [comment]
https://github.com/sktime/sktime/issues/3429
could you do this for the tap net classifier too? (please make them small parameters!)

**Comment by fkiraly** [comment]
yes, but not just any parameter sets, but with a good test coverage

**Comment by achieveordie** [comment]
Alright, I understood, will do this in a while. Thanks!

**Pull request merged**
