### PR TITLE
[BUG] ensure `Catch22` parameter setting `n_jobs = -1` uses all cores

### PR DESCRIPTION
**Pull request by julnow**
Changed n_jobs = -1 to use all cores instead of 1 as per comment: "remove in v0.16 and add to docstring: ``-1`` means using all processors"

=
#### Reference Issues/PRs
Fixes https://github.com/sktime/sktime/issues/5360

#### What does this implement/fix? Explain your changes.
n_jobs=-1 in catch22 will actually use all cores.

### CODE REVIEW

**Comment by fkiraly** [comment]
ah, looks like this action got forgotten, thanks!

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks!

Re contribution acknoledgment, please do not edit the contributors.md directly, but the .all-contributorsrc in the root dir, the former is auto-generated from the latter.

Your fix qualifies you for the bug and the code badge (you reported the bug and fixed it too).

**Comment by julnow** [comment]
@fkiraly Fixed this, thanks for clarification!

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks.

You accidentally deleted some brackets it seems so `.all-contributorsrc` will now fail. Can you kindly ensure all opening brackets are matched by closing brackets? Just follow the pattern.

Also, thanks for the contrib on `Catch22` - while you are looking at it, might I interest you in this issue https://github.com/sktime/sktime/issues/2254 to speed the estimator up? It is somewhat slower than it needs to be due to the obscure data type it is using internally.

**Comment by julnow** [comment]
@fkiraly sorry, should work now

I'll try and look at https://github.com/sktime/sktime/issues/2254

**Review by fkiraly — APPROVED** [review]
Thanks, all fixed now.

**Pull request merged**
