### PR TITLE
[BUG] in `CNNRegressor`, fix `self.model not found` error when `verbose=True`

### PR DESCRIPTION
**Pull request by morestart**
#### What does this implement/fix? Explain your changes.

In the original code, setting verbose=True leads to an AttributeError: 'CNNRegressor' object has no attribute 'model' error. So change

```python
if self.verbose:
    self.model.summary()
```

to

```python
if self.verbose:
    self.model_.summary()
```

because at [code line 187](https://github.com/sktime/sktime/blob/d86114f33aaa3398306f2b93ce3ce03c56b19877/sktime/regression/deep_learning/cnn.py#L187) ,we don't have define `self.model` in our code
##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Review by yarnabrina — CHANGES_REQUESTED** [review]
@morestart thanks for your contribution. It definitely looks like a bug that you fixed correctly, it seems your PR description has no details about the changes. Please add some details on the original case where it was causing issues where it won't any more once this is merged.

If you can add a test for this bug, may be using your example only, that'd be great. 

Also, please feel free to add yourself as a contributor. :)

**Comment by fkiraly** [comment]
PS: test coverage could be added by adding `verbose` to one of the test parameter sets in `get_test_params`.

**Comment by morestart** [comment]
Just add verbose=True to line [99 ](https://github.com/sktime/sktime/blob/d86114f33aaa3398306f2b93ce3ce03c56b19877/sktime/regression/tests/test_all_regressors.py#L99)in the test code, right?

**Comment by fkiraly** [comment]
yes

**Comment by fkiraly** [comment]
No, in `get_test_params` of `CNNRegressor`

**Comment by morestart** [comment]
now, may be we can merge this pr

**Review by fkiraly — APPROVED** [review]
Indeed! Thanks!

**Pull request merged**
