### PR TITLE
[DOC] Improve Docstring for PinballLoss

### PR DESCRIPTION
**Pull request by Ram0nB**
#### Reference Issues/PRs

Issue #4303

#### What does this implement/fix? Explain your changes.

Enhances the PinballLoss docstring: example added

#### Does your contribution introduce a new dependency? If yes, which one?

No

#### Any other comments?

This is my first contribution. Please let me know where I can improve - also for setting up this Pull Request. Many thanks!

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks a lot!

Might I request the following change - for expressions going over multiple rows, like `y_pred = ` etc, from the second row on you need to use `... ` rather than `>>> `, or this will give problems with testing and display in the docs.

**Review by yarnabrina — CHANGES_REQUESTED** [review]
Thanks for the contribution. Apart from what @fkiraly has said above already, did you mean to edit `_BaseProbaForecastingErrorMetric` class? Your example, and title of this PR, seem to be more suitable for `PinballLoss` class?

**Comment by Ram0nB** [comment]
First of all, thanks for your quick replies!

> Might I request the following change - for expressions going over multiple rows, like `y_pred = ` etc, from the second row on you need to use `... ` rather than `>>> `, or this will give problems with testing and display in the docs.

Change processed.

> Thanks for the contribution. Apart from what @fkiraly has said above already, did you mean to edit `_BaseProbaForecastingErrorMetric` class? Your example, and title of this PR, seem to be more suitable for `PinballLoss` class?

I indeed meant to edit the `PinballLoss` class. I now moved the example to the `PinballLoss` class - sorry about this.

Also, the checklist for all contributors state that:

- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.

Should I also add myself to the https://github.com/sktime/sktime/blob/main/.all-contributorsrc file in this pull request? If not - how do I add myself?

**Comment by fkiraly** [comment]
> Should I also add myself to the https://github.com/sktime/sktime/blob/main/.all-contributorsrc file in this pull request?

Yes, with a `doc` contribution!

**Comment by fkiraly** [comment]
Minor linting issue, you have trailing whitespaces.

See here for general coding style and how to set up automated checking locally:
https://www.sktime.net/en/latest/developer_guide/coding_standards.html

(or, just go on the failing test and see where the problem is)

**Review by fkiraly — APPROVED** [review]
Fixed it now.

**Comment by yarnabrina** [comment]
The `numpy` issue is out of scope for this PR, but I don't understand why there are so many fatal bad revision in the logs.

@fkiraly, you updated this with latest `main` right? I see no such fatal revision stuff in `main` CI logs, but quite a lot here. Any idea what is causing this?

**Comment by fkiraly** [comment]
@yarnabrina, there are two separate issues:

* the fatal revisions are due to the `git_diff` utility running in `test-nosoftdeps-full` but the `main` branch not being present. This is fixed in https://github.com/sktime/sktime/pull/5084 (would appreciate review)!
* the `numpy` equality failures are due to equality comparisons to `np.ndarray` having deprecated at some point and we haven't tested it, making the weighted versions of metrics fail. The problem and the lack of tests are fixed in https://github.com/sktime/sktime/pull/5086 (would appreciate review)

Swift reviews for both would be appreciated if you have time, then we can put this in the 0.21.1 release. Especially the failure of weighted metrics seems important.

**Comment by fkiraly** [comment]
@Ram0nB, thanks a lot for this PR - the manually generated `y_pred` is very useful for testing, and this has led us to discover some issues with the weighted losses! (including that this was not properly tested)

Starting from the explicit `y_pred`: we're currently trying to cut down on test time, see https://github.com/sktime/sktime/issues/2890. We're close to the 10min target!

What we've discovered, the fixture generation for `y_pred` uses actual forecasters' predictions, and that takes ca 3 sec per test run for dozens of tests, so we could get far by replacing the fixtures with explicit `y_pred`!

Would you be inclined to help with that?

It is just replacing `y_pred = forecaster.predict(etcetc)` with an explicit generation of `y_pred` like in your doctest.

The precise location is `performance_metrics.forecasting.probabilistic.tests.test_probabilistic_metrics`, and in there the fixture called `sample_data`. As said, any logic that calls `NaiveForecaster` to generate the forecasts should be replaced with an explicit `y_pred = pd.DataFrame(etc)` (or possibly `pd.Series`)

**Comment by fkiraly** [comment]
FYI, my commits are coming from testing this with the branch #5104 - they shouldn't be in the diff in the end.

**Pull request merged**
