### PR TITLE
 [GOV] Appointment of CC and CoC members

### PR DESCRIPTION
**Pull request by aiwalter**
#### Reference Issues/PRs
#3865 

#### What does this implement/fix? Explain your changes.
Propose change in nomination of CC and CoC members. This PR removes the gate keeping sections

### CODE REVIEW

**Comment by fkiraly** [comment]
Formally voting this down.

This proposes to remove separation of powers/duties between CC and CoC committee.

It is also a problematic attempt to influence currently ongoing CoC proceedings, therefore CoC relevant.

**Comment by fkiraly** [comment]
please don't revert the PR title.

PR titles should reflect the change in content as concretely as possible, and not be labelled vaguely or misleadingly

**Review by GuzalBulatova — COMMENTED** [review]
@aiwalter do you have a counter-suggestion about tie situations?

**Comment by aiwalter** [comment]
Its a basic democratic principle that a government (CC) has no power to decide who will be the government after tenure ending. Not even the worst banana republics have this 😅 . Same for judicial (CoCC), a judicial can not decide who will be the next judicial after tenure ending. That is all what this PR is aiming to do. Currently we have a centralization of power, e.g. a single person is now controlling the CoCC and could in theory stay there forever and block all new appointments. This is a precarious situation which I would like to fix with this PR.

**Review by MatthewMiddlehurst — APPROVED** [review]

**Review by lmmentel — APPROVED** [review]

**Comment by fkiraly** [comment]
> Same for judicial (CoCC), a judicial can not decide who will be the next judicial after tenure ending.

@aiwalter, that's not true, and especially dangerous in combination with your other PR on [term limitation of the CoC committee](https://github.com/sktime/sktime/pull/3868).

You are removing [judicial independence](https://en.wikipedia.org/wiki/Judicial_independence).

One common mechanism to ensure judicial independence is *life tenure* for judges, i.e., they do not have a term limitation at all, such as in the US or Germany.

A counterexample is the recent controversy around reduction of judicial independence in Poland which the [United Nations High Commission has expressed concerns about](https://www.ohchr.org/en/press-briefing-notes/2019/12/press-briefing-poland?LangID=E&NewsID=25447).

Regaring appointment, democratic countries tend to have a soft or a hard requirement for judges to be trained in the law, i.e., they need to satisfy certain conditions that the law profession checks. (sometimes this is not a hard requirement, but then it is a soft requirement, i.e., individuals who are not lawyers are much more unlikely to be proposed or appointed)

**Comment by fkiraly** [comment]
@aiwalter, your current PR title is entirely misleading.

This is not about *nomination*, it is about the *appointment condition*.

**Comment by aiwalter** [comment]
> This is not about nomination, it is about the appointment condition.

Probably just semantics, but happy to change the title if it helps you convincing to approve 😄

**Comment by fkiraly** [comment]
formal downvote.

Reasons explained here: https://github.com/sktime/sktime/issues/3882

**Review by GuzalBulatova — APPROVED** [review]
Ok, again for special cases let's address in separate PRs

**Comment by aiwalter** [comment]
results of core-dev vote is >2/3 of casted votes, therefore merging this
image

**Pull request merged**
