### PR TITLE
[ENH] `MultiplexRegressor` - autoML multiplexer for time series regressors

### PR DESCRIPTION
**Pull request by ksharma6**
#### Reference Issues/PRs
Fixes issue #5655 

#### What does this implement/fix? Explain your changes.
Implemented MultiplexRegressor based on MultiplexForecaster

#### Does your contribution introduce a new dependency? If yes, which one?
No

#### What should a reviewer concentrate their feedback on?
Possible syntax errors

#### Did you add any tests for the change?
No, I was not entirely sure if it was applicable however please let me know if my assumption is incorrect

#### Any other comments?
Thank you for letting an open-source beginner contribute to your project :)

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks! Good start!

Is this still work in progress? Either way, it would be good if you test your regressor. The current test parameters are invalid, becaues `DummyRegressor` does not have the strategies as provided.

You can test estimators by running `sktime.utils.check_estimator` on them, also see the developer guide on adding estimators. https://www.sktime.net/en/stable/developer_guide/add_estimators.html

Nice start, almost there - let us know if you need any help.

**Comment by ksharma6** [comment]
Hi @fkiraly I hope you had a nice weekend. I was able to test my estimator and updated the params. I am still failing some tests and I haven't been able to source my mistake:

FAILED: test_clone[Error:estimator_instance]
FAILED: test_constructor[MultiplexRegressor]
FAILED: test_create_test_instance[MultiplexRegressor]
FAILED: test_create_test_instances_and_names[MultiplexRegressor]
FAILED: test_get_params[Error:estimator_instance]
FAILED: test_get_test_params[MultiplexRegressor]
FAILED: test_set_params[Error:estimator_instance]
FAILED: test_set_params_sklearn[MultiplexRegressor]
FAILED: test_valid_estimator_tags[Error:estimator_instance]
FAILED: test_fit_does_not_overwrite_hyper_params[Error:estimator_instance-Error:scenario]
FAILED: test_fit_returns_self[Error:estimator_instance-Error:scenario]
FAILED: test_fit_updates_state[Error:estimator_instance-Error:scenario]
FAILED: test_multioutput[Error:estimator_instance]
FAILED: test_multivariate_input_exception[Error:estimator_instance]
FAILED: test_regressor_output[Error:estimator_instance-Error:scenario]

I feel I am missing something obvious and my errors have something to do with `test_clone` but I wasn't able to figure it out. I  would appreciate a nudge in the right direction

**Review by fkiraly — CHANGES_REQUESTED** [review]
If you look at the failure message, it tells you what to do: `DummyRegressor.__init__() got an unexpected keyword argument 'strategey'` (there´s a typo here)

Nice work overall!

* for the dunder to work properly, you also need to add it to `BaseRegressor`, see `__or__` and `__ror__` in `BaseClassifier` for the pattern (this is blocking)
* an example would also be nice for the docstring (not blocking)

**Comment by fkiraly** [comment]
let us know when you are ready for a review!

**Comment by ksharma6** [comment]
Hi @fkiraly Sending what I have thus far, still resolving a bug with  my implementation of TSRGridSearchCV

**Review by fkiraly — CHANGES_REQUESTED** [review]
@ksharma6, this is nice!

I would however strongly recommend not to do all of this in a single pull request! There are multiple independent pieces here that are easily separable, and imo it will also make your life easier to have them tested, reviewed, merged, one-by-one, instead of having one mega-PR.

My recommendation how to split it:

* multiplexer and dunders, tests for that
* any bugfixes you need for things to work, e.g., `score` (this might be resolved in PR by @Cyril-Meyer already)
* grid search for TSR

**Comment by ksharma6** [comment]
PR https://github.com/sktime/sktime/pull/6075 is the implementation of the MultiplexRegressor

**Pull request closed without merging**
