### PR TITLE
[ENH] Add SimpleRNN DL Estimator

### PR DESCRIPTION
**Pull request by ArushikaBansal**
migrates simple RNN regressor from sktime-dl, see https://github.com/sktime/sktime/issues/3351

### CODE REVIEW

**Comment by ArushikaBansal** [comment]
Made necessary changes.
issue #3351

**Review by ArushikaBansal — COMMENTED** [review]
Removed soft dependencies

**Review by fkiraly — CHANGES_REQUESTED** [review]
Very nice, thanks, @ArushikaBansal!

Before we merge, may I ask you to fix the systematic error that @achieveordie had found here?
https://github.com/sktime/sktime/issues/4067

That is, parameteres that should be passed to the undlerying network - here, `RNNNetwork` - were not actually being passed.

Have a look how this is done in `CNNRegressor.__init__` after @achieveordie fixed it, and let us know if you have any questions.

**Comment by fkiraly** [comment]
Looks almost good now!

The failing test says you are probably missing a `super.__init__` call in the constructor.

**Comment by fkiraly** [comment]
I think, still? In `RNNNetwork`, have a look at the error message in the CI test.

**Comment by fkiraly** [comment]
added the `super` call that I think was missing, hope you don't mind (otherwise we can revert)

**Review by fkiraly — CHANGES_REQUESTED** [review]
Nice work!

I think we have now fixed the `super` issues.

However, before merge:

* `__init__` of `SimpleRNNRegressor` passes an argument `batch_size` to the `RNNNetwork` which it does not have - this will break if passed! I'm also surprised none of the tests break, have you checked with `check_estimators`?
* we should also add test parameters, i.e., `get_test_params`, with at least two test parameter settings for each object added. See the extension templates (in `extension_templates`) for how to fill this in.

**Comment by fkiraly** [comment]
I now added test parameters and fixed things like the naming and init.

**Review by achieveordie — APPROVED** [review]
LGTM

**Comment by fkiraly** [comment]
will merge after 0.18.0

**Pull request merged**
