### PR TITLE
[MNT] [ENH] Several updates in direct statsforecast interface estimators

### PR DESCRIPTION
**Pull request by yarnabrina**
## Per estimator lower bound

I checked the imports in `_get_statsforecast_class` for all direct estimators, and first tag in StatsForecast repository where that class is present. Accordingly, updated the `python_dependencies` tag per concrete estimators as follows:

1. `AutoARIMA`: `v1.0.0`
2. `AutoCES`: `v1.1.0`
3. `AutoTheta`: `v1.3.0`
4. `AutoTheta`: `v1.3.2`
5. `ARCH` and `GARCH`: `v1.5.0` (FYI @eyjo)
6. `MSTL`: `v1.2.0` (FYI @luca-miniati)

## Missing credits

1. @arnaujc91 has contributed significantly to `_GeneralisedStatsForecastAdapter` by adding support for argument differences across versions, added in the `authors`.
2. Both @arnaujc91 and @luca-miniati (author of `StatsForecastBackAdapter`) were missing from `__author__`, added there.
3. Added `StatsForecastBackAdapter` in `__all__`.
4. Author/maintainer information for @eyjo was missing for `StatsForecastARCH`, added there.

## Enhancements

1. `v1.7.1` adds a new `phi` parameter to `AutoETS`, added support for the same.
2. `pydocstyle` was failing due to missing docstrings, added one liner summaries (unlikely to be user facing methods).

## MSTL changes

1. `StatsForecastMSTL` was initialising the attributes after call to `super().__init__`, which was causing `AttributeError` in tests that check for presence of properties. This PR moves those initialisations prior to that call. FYI @luca-miniati.
2. Disabled probabilistic capability of `StatsForecastMSTL`, as it was not working as reported by @EliasKng in #5720. FYI @luca-miniati.

## Update of lower/upper bounds

1. No existing direct estimator support `statsforecast<1.0.0` with their current imports, not even `AutoARIMA`, updated lower bound from `0.5.2` to `1.0.0`. Previous adapter by @FedericoGarza was importing from a different location. `v0.5.2` was released in March 2022, and `v1.0.0` was released in August 2022, so I think chances of affecting users is quite low.
3. Recently added `AutoTBATS` needs `v1.7.2`, so updated upper bound from `1.7.0` to `1.8.0`.

### CODE REVIEW

**Comment by fkiraly** [comment]
> Missing credits

Apologies, I did a mindless bulk migration - might be my mistake, might be not having been entered properly in the first place.

**Comment by yarnabrina** [comment]
> Minor note, StatsForecastBackAdapter should not be user facing, it is used ony as an internal adapter afaik.

Agreed, but `pydocstyle` was complaining about this being public, so added docstrings and __all__ just for that. It's still not exposed through __init__, so hopefully no effect on users.

---

The failing tests are all from `StatsforecastMSTL`, especially where anything is trying to use probabilistic predictions. The bug was already reported in #5703, and I think the previous results problem reported in #5586 may also be related. My inference is these failures are not caused by my changes in this PR, because the only effect this PR will have on it is to force running the tests and nothing else.

**Comment by fkiraly** [comment]
to avoid blocking this PR, can we skip `MSTLForecaster` for now?
I see two options: setting the `capability:pred_int` tag to `False` (this would make sense if none of the methods work), or adding the entire estimator - or just the failing tests - to the set of exceptions in `tests._config`.

**Comment by yarnabrina** [comment]
> to avoid blocking this PR, can we skip `MSTLForecaster` for now? I see two options: setting the `capability:pred_int` tag to `False` (this would make sense if none of the methods work), or adding the entire estimator - or just the failing tests - to the set of exceptions in `tests._config`.

I thought the same, but wasn't sure if it's an acceptable solution. Since you also suggested, doing it for now by combining both options.

1. Test added specifically in `test_statsforecast.py` by @sd2k is skipped in `_config`, plus added a `skip` decorator with a reason.
2. Set `capability:pred_int` and `capability:pred_int:insample` as `False` -> this is breaking change, even though it was already not working
3. Manually set the tags once more in `__init__` as `_check_supports_pred_int` method in `_GeneralisedStatsForecastAdapter` that @arnaujc91 added overrides class tag during `super().__init__()`
4. Skipped `test_pred_int_tag` tests in `_config`, as the tag set for `StatsForecastMSTL` is incompatible with generic capability of `_GeneralisedStatsForecastAdapter`

**Comment by yarnabrina** [comment]
> Can I ask a quick question: why did test_statsforecast_mstl previously pass?

I do not know. Unchecked guess: specific `statsforecast` version.

I checked locally that running following commands works only if I have `statsforecast==1.6.0`.

```shell
> pytest sktime/forecasting/tests/test_statsforecast.py
> pytest sktime/forecasting/tests/test_all_forecasters.py -k "StatsForecastMSTL"
```

It fails with `1.5.0` (error is `ImportError`) and `1.7.0` (`AttributeError`). This is too narrow (just one minor version) supported range in my opinion.

**Comment by yarnabrina** [comment]
@fkiraly @benHeid @achieveordie please let me know if there are any suggestions for this PR.

**Review by fkiraly — APPROVED** [review]
Nothing more to do - my request (test skip) has been addressed

**Pull request merged**
