### PR TITLE
[MNT] refactoring new CI to fix some bugs and other minor enhancements

### LINKED ISSUE #5559: [BUG] behaviour of new CI changed suddenly
As observed in https://github.com/sktime/sktime/pull/5447 and https://github.com/sktime/sktime/pull/5339, new CI is not behaving as it was during the original PR and it's diagnostic ones. It seems to have changed the behaviour ever since the introduction of the new modifications.

Observations about `.github/workflows/test_components.yml` from both the PR's:

1. `detect` job works successfully and detect what all component needs to be tested.
2. `test` job does not even get detected by the CI, but it should run for detected components.
3. This does not happen for `detect_components_without_extras` + `test_components_without_extras` combination.

Possibilities (just guesses at this point):

1. similar names have some conflicts?
2. small typo somewhere?
3. change in GHA behaviour?
4. change in action behaviour?

### PR DESCRIPTION
**Pull request by yarnabrina**
Fixes #5559 (indirectly depends on #5670 for all tests to pass as part of #5639)

This fixes few bugs (typos, possibly unreliable coverage, etc.) and added some minor enhancements in new CI.

1. fix main typo: sktime-component was using detect_components_with_extras which is undefined
2. split test_components into two separate workflows:
    1. one to test individual components using dedicated extras and reuse defined actions
    2. one to test all other components without extras using all_extras_pandas2
3. split long commands into multiple lines using YAML multiline strings (ref. https://yaml-multiline.info/)
4. skip duplicated testing of base as part of testing components without dedicated extras
5. remove coverage in partial tests
6. add coverage in full tests if missing
7. added validation of all_extras_pandas2
8. minor changes (mostly renaming) in some places

The changes are tested in #5639 and as it can be seen in https://github.com/sktime/sktime/actions/runs/7339442367, both components with and without extras trigger sub-jobs as expected.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
I am confused with the PR title - it says it fixes typos, but there are entire files added in `workflows` - is this a mistake, or are file renames and changes happening in the same PR?

**Comment by yarnabrina** [comment]
> I am confused with the PR title - it says it fixes typos, but there are entire files added in `workflows` - is this a mistake, or are file renames and changes happening in the same PR?

The typo fix is the main change what was causing the issue. However copilot and github docs suggested some other changes to simplify maintenance, so added those as well.

I renamed the PR now, but not sure if it's suitable. All the details are part of the description.

**Review by fkiraly — APPROVED** [review]
I'm happy with this after discussions on the discord channel.
The release cycle will also give us at least a few weeks to test this out.

We will still need to resolve:
outstading questions on how and which parts of current CI to deprecate or replace
https://github.com/sktime/sktime/issues/5559
https://github.com/sktime/sktime/issues/5525
https://github.com/sktime/sktime/issues/5523

Related discussion also in:
https://github.com/sktime/sktime/issues/5671
https://github.com/sktime/sktime/issues/5436
https://github.com/sktime/sktime/issues/5477
https://github.com/sktime/sktime/issues/5292

**Comment by yarnabrina** [comment]
Notes/Summary

#5559 - addressed by this PR.
#5525 - not addressed yet, was attempted in #5498, but didn't work, reverted in 1dee835dcd140fe433a3dde981d9dcadbb73c3dc.
#5523 - not adressed yet, but it's more good-to-have than necessary in my opinion.

#5671 - partially addressed as `pyproject` changes would be tested, no explanation on `dependabot`'s partial attempt.
#5436 - not addressed and out-of-scope for CI, but may be that issue can be broadened to even 3.12.
#5477 - not addressed, very good-to-have to decrease runtime of new CI, open for suggestions.
#5292 - not addressed, open for suggestions, indirectly can be tested by manual runs of `test_all` workflow on that branch.

**Pull request merged**
