### PR TITLE
[ENH] adding second test parameters for `TBATS`

### PR DESCRIPTION
**Pull request by NguyenChienFelix33**
#### Reference Issues/PRs

Towards #3429

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Review by fkiraly — APPROVED** [review]
Thanks, looks good!

Non-blocking note, kindly make sure that PR titles and PR description are clear about what is in the PR.

**Comment by NguyenChienFelix33** [comment]
Thank you so much professor.
I will keep continue to add parameters.

**Comment by fkiraly** [comment]
> I will keep continue to add parameters.

That's helpful, thanks! We may of course also like think of a more challenging project now.

For test parameter sets, you can check which estimators are lacking test parameter sets by looking at this branch:
https://github.com/sktime/sktime/pull/5114
they will fail the modified `test_get_test_params`.

You can look in the remote CI, or try to run the test locally for all estimators - if you are not sure how to do that, that could be the next challenge: use pytest to programmatically find all the estimators which do not have enough test parameter sets.

**Comment by NguyenChienFelix33** [comment]
Thank you professor for your suggestion, it looks GREAT to work with.

Fews day ago, i looked at the issues GlobalArima #5021. It is frustrating and really no clue. 
I have some questions about that issues but just to understand a little bit ( If i am not wrong at understanding, the GlobalArima have static parameters so what data we should use to train parameters of Global Arima or something?) 

( so sorry that if this question is not good , this question is just to understand the issues)

**Comment by fkiraly** [comment]
A short answer here: https://github.com/sktime/sktime/issues/5021#issuecomment-1880150299

**Pull request merged**
