### PR TITLE
[MNT] enable concurrency settings in 'Install and Test' GHA workflow

### LINKED ISSUE #6036: [BUG] "cancel on push" workflow runs after impacted "install and test"
Good first issue for people experienced with GitHub Actions.

The "cancel on push" workflow runs after "install and test", severely compromising its usefulness.

In a situation like current, where there are regularly periods in which more CI are queued than can simultaneously run, this leads to significant parts of the "install and test" running before the cancellation of them gets triggered.

Notably, this causes significant test load to be carried out that - by how the logic currently stands - in jobs that are intended to be eventually cancelled, hence this is completely superfluous.

The logic issue comes from the limitation of maximal simultaneous workers. This can lead to workers that the "cancel on push" job is meant to cancel getting priority over the "cancel on push" job, triggered later.

The obvious solution is ensuring that, out of the two jobs triggered, "cancel on push" is always executed first, or at least with prioity before any other workers are assigned to "install and test".

Is there a way to give "cancel on push" absolute priority before anything else?

### PR DESCRIPTION
**Pull request by MEMEO-PRO**
#### Reference Issues/PRs
Fixes #6036 

##### For all contributions
- [*] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)

### CODE REVIEW

**Review by fkiraly — DISMISSED** [review]
Nice!

How do you suggest we test whether this works as intended?

**Comment by MEMEO-PRO** [comment]
> Nice!
> 
> How do you suggest we test whether this works as intended?

I tested it by putting a dummy workflow file and then executing the test.yml, it worked perfectly(I know this approach is bad). We can also use act tool to run GitHub Actions workflows locally. It simulate the workflow execution environment and verify the behavior of your workflows without pushing changes to GitHub

**Comment by fkiraly** [comment]
FYI @yarnabrina, @achieveordie

**Review by achieveordie — APPROVED** [review]
I believe this should work. Thanks @MEMEO-PRO!

**Comment by yarnabrina** [comment]
(Not a review, just doubt clarification) 

Question to @MEMEO-PRO and @achieveordie : is this concurrency setting applicable only for the top level workflow, or also for all child workflows that it creates? For example, suppose a PR modifies sktime/base, and hence triggers per component workflows. If a new commit comes while it's still running, what is the expectation?

**Comment by MEMEO-PRO** [comment]
Concurrency setting specified at the top level of a workflow applies only to that specific workflow. It does not automatically propagate to child workflows or other workflows triggered by events within the parent workflow. In the scenario of a new pr changes to sktime/base, it triggers per-component workflows, each of these child workflows will not inherit the concurrency settings of the parent workflow. 
If a new commit triggers a new child workflow run while another child workflow run is still in progress, the GitHub Actions scheduler will queue the new workflow run. The queuing behavior depends on the concurrency settings and limitations defined within each individual workflow.

**Comment by yarnabrina** [comment]
Another question: why is there no CI in this PR?

---

> If a new commit triggers a new child workflow run while another child workflow run is still in progress, the GitHub Actions scheduler will queue the new workflow run. The queuing behavior depends on the concurrency settings and limitations defined within each individual workflow.

I'm not sure if you have seen our entire CI setup or not, but there is no way for some chimd workflow to be triggered without triggering the parent workflow. Here's a _slightly_ **outdated** summary of what the current CI does.

So if I make a change in `sktime/base`, in ny understanding the parent workflow at `test.yml` gets created,  and it triggers child workflows at `test_base.yml`, `test_other.yml` and `test_module.yml` with different inputs as applicable. Now suppose I make another commit, and similar to @fkiraly I'd like to have all jobs (either directly in parent or in child ones) to be cancelled and new run for `test.yml` to be triggered, which again will create child workflows. Is this going to happen with your changes, and/or is this possible to achieve?

(@fkiraly please correct me if I misunderstood your expectation.)

**Comment by MEMEO-PRO** [comment]
yep ive seen that while using GitHub Actions docs(https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency) do not explicitly mention it.
Note: Concurrency ensures only one workflow or job with the same concurrency key runs at any given time if `cancel-in-progress: true` is used.

**Comment by MEMEO-PRO** [comment]
> I'd like to have all jobs (either directly in parent or in child ones) to be cancelled and new run for `test.yml` to be triggered, which again will create child workflows. Is this going to happen with your changes, and/or is this possible to achieve?
> 

Yes

**Comment by yarnabrina** [comment]
@fkiraly should we merge into main to test from new PR's to test this? Curious how to test it though, as CI do not necessarily start when we create a PR and gets queued behind other running CI runs.

(I think @MEMEO-PRO is confident it's going to satisfy the expectation, and I am happy to test that which is probably impossible without merging into main first. If not the case, we can revert and try again.)

**Comment by fkiraly** [comment]
yes, let's test - we can always revert before the release if it doesn't work as expected.

**Pull request merged**
