### PR TITLE
DIAGNOSTIC - failures if `pandas==2.2.0` is set

### PR DESCRIPTION
**Pull request by fkiraly**
Diagnostic PR to inspect failures if `pandas==2.2.0` is set.

From discussion with @yarnabrina, here: https://github.com/sktime/sktime/pull/6057#issuecomment-1977930595

### CODE REVIEW

**Comment by fkiraly** [comment]
@yarnabrina, this is very strange - 2.2.0 gets installed here. How does this fit together with #6057?

**Comment by yarnabrina** [comment]
> @yarnabrina, this is very strange - 2.2.0 gets installed here. How does this fit together with #6057?

Please compare https://github.com/sktime/sktime/pull/6063#issuecomment-1978949768 against https://github.com/sktime/sktime/pull/6057#issuecomment-1978948552, and specifically check for `skpro`. On #6057, it was possible to install latest `skpro` with `pandas==2.1.4`, but in #6063 that is not possible and it went below till `2.0.1` which allowed all arbitrary `pandas>=1.1.0`.

**Comment by yarnabrina** [comment]
Interaction between these:

https://github.com/sktime/sktime/blob/b931ca971d63a6713526366d2d2259c451408548/pyproject.toml#L186

https://github.com/sktime/skpro/blob/95b77bc10401a21ccedeea588a00db8948909227/pyproject.toml#L45

**Comment by fkiraly** [comment]
obsolete with 0.28.0

**Pull request closed without merging**
