### PR TITLE
[ENH] rewrite test_probabilistic_metrics using proper pytest fixtures

### LINKED ISSUE #4907: [ENH] rewrite `test_probabilistic_metrics` using proper `pytest` fixtures, or directly generate `pd.DataFrame`.
From profiling `pytest` test collection runs, we've discovered that, at current, major increase to runtime comes from `test_probabilistic_metrics` which fits and predicts every time upon module import.

This doesn't follow best `pytest` practice where fixture generation should not happen every time in the module, only at test time. The fit/predict also seems redundant, as we are only using the output.

There is a "software engineer" and a "data scientist" way to fix this, doing at least one should solve the problem - but it would be better to do both.

* the "software" appraoch would be moving the generation of the lists of `DataFrame`-s in lines 63 - 89 (`uni_data` etc) to `pytest` fixtures.
* the "data science" way would eliminate the need to fit/predict using the forecaster, after all we only use the output as a fixture, and it would be more robust to create these directly (i.e., using `pd.DataFrame` constructor) rather than getting them from an estimator's fit/predict

Good first issue for anyone who knows `pytest` or `pandas` - and it would help a lot of developers as the `pytest` test construction time is long.

### PR DESCRIPTION
**Pull request by julia-kraus**
#### Reference Issues/PRs
Fixes #4907 

#### What does this implement/fix? Explain your changes.
Moved the sample data generation inside fixtures, so it doesn't run with each import, but only when testing is performed. 
Moreover refactored the tests such that the output tests for interval predictions and quantile predictions are separated.

Reason: With only one parametrized test were 96 parameter combinations, which made the test very slow and CPU heavy. 
Also, some parameter combinations are not necessary (quantile metrics belong to quantile forecast only and interval metrics only to interval forecast) - please correct me if I'm wrong. 
Separating the tests speeds up the testing process considerably and makes debugging easier.

#### Does your contribution introduce a new dependency? If yes, which one?

No

#### What should a reviewer concentrate their feedback on?

I left the original `test_output` with the many parameter combinations in working and refactored state commented out. 
Decide if you still need it and if not, delete the commented out function.

#### Did you add any tests for the change?

Added the test `test_sample_data()` to check if the sample data generating fixture `sample_data()` is working correctly.

#### Any other comments?
The output test function contains many nested if - else statements. In my opinion, these should be separate tests with separate parametrized inputs, instead of putting all inputs in one test, and then distinguishing with if-else statements.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
NICE! This speeds up test collection time massively for me.

Minor but important thing - linting is failing.

See here for linting & precommit:
https://www.sktime.net/en/latest/developer_guide/coding_standards.html

**Comment by fkiraly** [comment]
> Also, some parameter combinations are not necessary (quantile metrics belong to quantile forecast only and interval metrics only to interval forecast) - please correct me if I'm wrong.

Hm, I think they should work at least the way round that quantile metrics should be applicable to quantile for interval forecasts - this makes mathematical sense since interval upper/lower define quantile forecasts. If this was tested before and didn't raise errors, it means it's actually implemente that way.

**Comment by julia-kraus** [comment]
ok, then I'd leave the original big function in the hope that the test server can handle it :)
thumbs up?

**Review by fkiraly — DISMISSED** [review]
Thanks!

On details regarding what exactly to test, I think we ought to revisit this anyway with a class inheriting from `TestAllObjects`, so I'd not spend too much effort on the details of what is tested.

As far as I can see, your code is an 1:1 translation.

**Comment by julia-kraus** [comment]
@fkiraly 
So I kept the two different functions for the tests for intervals and quantiles, but run all metrics on both.

The tests finish green on my machine. However, both take an hour to complete. This should be fine, but if you're looking for performance improvements in the future, that might be the place to look :)

**Comment by fkiraly** [comment]
> There's a memory error on the test runner as well.. I guess the vectorized tests from before

This is unrelated to your changes - it is an instance of this sporadic error
https://github.com/sktime/sktime/issues/4610
which we haven't managed to properly diagnose yet.

**Pull request merged**
