### PR TITLE
Change order of object types to enable pipelines

### PR DESCRIPTION
**Pull request by benHeid**
Alternative to #7135 #7136

### CODE REVIEW

**Comment by XinyuWuu** [comment]
Did we run these tests on global forecasters before?

```py
"test_fit_does_not_overwrite_hyper_params",
"test_non_state_changing_method_contract",
"test_fit_idempotent",
"test_persistence_via_pickle",
"test_save_estimators_to_file",
```

**Comment by fkiraly** [comment]
Hm, I see - it seems the selection is only by the *first* scitype in the list, so at current the tests are run *either* those in `TestAllForecasters`, or `TestAllGlobalForecasters`, because the latter does not inherit from the former!

To run all the appropriate tests on global forecasters, we would either need to:

* leave things as they are, but ensure `TestAllGlobalForecasters` inherits from `TestAllForecasters`
* modify the logic in test collection, so tests run if at least one type appears
* cleanest but most work: introduce an "is_a" type method for all objects, and use that in the test logic when collecting.

**Comment by fkiraly** [comment]
> Did we run these tests on global forecasters before?

According to the above, the answer would be "no". Very sorry that I missed it.

**Comment by fkiraly** [comment]
Hm, update: I think the answer would be yes, actually? `all_estimators("forecasters")` is used in the test utility, so it *should* retrieve the global forecasters for `"forecaster"`, no matter the positoin of the type in the list.

I just tested it and it does. Therefore, my statements in https://github.com/sktime/sktime/pull/7137#issuecomment-2360080799 and https://github.com/sktime/sktime/pull/7137#issuecomment-2360077711 were *incorrect*.

**Pull request closed without merging**
