### PR TITLE
[ENH] Added GluonTS datasets as sktime datatypes

### LINKED ISSUE #2860: [ENH] data conversion adapters to gluonts
We should write adapters to the glonts time series.

This should involve:
* conversion data frame (sktime pd.DataFrame and multiindex format) to gluonts
* conversion glounts to data frame (sktime pd.DataFrame and multiindex format)

### PR DESCRIPTION
**Pull request by shlok191**
#### Reference Issues/PRs
Fixes #2860

#### What does this implement/fix? Explain your changes.
This is an implementation that adds support for GluonTS implemented data types in the sktime library to make it easier for users to utilize both libraries together.

#### Does your contribution introduce a new dependency? If yes, which one?
I believe GluonTS was added as soft dependency in an earlier PR, but I will check this.

#### What should a reviewer concentrate their feedback on?
A reviewer should focus on my implementations in the `sktime/datatypes/_table` directory, specifically in the `_registry.py` and `_check.py` files.

#### Did you add any tests for the change?
Not yet, but planning on doing so!

#### Any other comments?
Hello everyone! I have tried to add data types on my own, but I am not sure if I am doing it correctly. I have a feeling that I will need to add more functionality to fully add support for `ListDataset` (planning on adding `FileDataset` as well to support larger datasets which likely might be common for many use cases) but I would really appreciate feedback on if I have the right idea of how to add a new datatype to sktime.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

### CODE REVIEW

**Comment by shlok191** [comment]
@fkiraly, I started work on adding in the GluonTS datatypes! Could you please let me know if I am making changes in the correct place and if so, what a rough roadmap could look like to add complete support for the `ListDataset` objects? Thank you!

**Comment by shlok191** [comment]
@fkiraly, sorry about the repeated messages! I am trying to utilize the `convert_from_multiindex_to_listdataset` as the backend functions to convert sktime mtypes to gluonTS's `ListDataset`. However, I keep running into errors when I try to run the function.

Is it possible the function is possibly outdated? Thank you for the help!

**Review by fkiraly — CHANGES_REQUESTED** [review]
I think you are in the right module, but for time series, you need to use the `_panel` and `_series` directories, the `Panel`, and `Series` scitypes.

`Series` is single time series, `Panel` is collection of time series.

It is very possible that the existing functions are outdated - I do not think any tests have been added since the converters were contributed in 2022, so it is very much possible that they need to be updated.

**Comment by shlok191** [comment]
@fkiraly, could you please review the PR and let me know if it all looks good? Thank you so much! 😄

**Review by fkiraly — APPROVED** [review]
Looks good to me! Great!

**Comment by shlok191** [comment]
Thank you so much @fkiraly! Could you merge this into main so that I can use it for the new #6658 issue?

**Pull request merged**
