### PR TITLE
[MNT] Restructure the trend_forecasters

### PR DESCRIPTION
**Pull request by benHeid**
Restructure the trend.py into a trend folder since the file is quiet large and will get even larger if the FunctionForecaster is added.

#### Reference Issues/PRs

see discussion in #5240

### CODE REVIEW

**Comment by benHeid** [comment]
@fkiraly is there a possibility that github tracks the file changes correctly and recognises that I just copied the code and moved it to different files?

**Comment by fkiraly** [comment]
> is there a possibility that github tracks the file changes correctly and recognises that I just copied the code and moved it to different files?

I think it isn't smart enough to recognize partial moves - only if entire files are moved, unchanged.

**Review by fkiraly — CHANGES_REQUESTED** [review]
ok, though I'd make all the submodules of `trend` private, to avoid direct imports in case we need to reshuffle in the future.

**Review by fkiraly — APPROVED** [review]
Thanks!

Strange how there's a dependency in the detrender tests, but it's only tests so should not contribute to the kind of coupling that matters.

**Review by fkiraly — APPROVED** [review]

**Pull request merged**
