### PR TITLE
&fkiraly [ENH] Fix `BaseDetector` for segmentation and HMM estimators

### LINKED ISSUE #7410: [ENH] Fix failing output tests for the PoissonHMM detector
## Summary

The following tests for the PoissonHMM detector fail and thus have been added to the list of excluded tests:

* `test_predict_points`
* `test_predict_segments`
* `test_transform_output_type`

We should fix PoissonHMM to make sure these tests pass.

## Related PR

The tests were added in #6958.

### PR DESCRIPTION
**Pull request by y-mx**
(Updated by @fkiraly)

This PR updates the HMM detectors to be in line with the new interface specifications.

Some issues with the `BaseDetector` methods were also uncovered and fixed in the process.

Fixes https://github.com/sktime/sktime/issues/7414, fixes https://github.com/sktime/sktime/issues/7410

### CODE REVIEW

**Review by fnhirwa — COMMENTED** [review]
hey @y-mx 
Thanks for the PR 😊
Merge conflicts are blocking the CI run.
Would you resolve these to allow CI to run?
Thanks

**Comment by y-mx** [comment]
Hi, I've resolved the conficts, thanks!

**Review by fkiraly — CHANGES_REQUESTED** [review]
I have resolved the merge conflicts, and it appears that all this PR does is removing the test skips - is that intended or a mistake?

The original PR made changes to the base file in the `annotation` module, after move to `detection` it turns out the file is identical.

**Review by fkiraly — APPROVED** [review]
I finished this to ensure this gets merged soon, thanks for your contribution!

**Pull request merged**
