### PR TITLE
[DOC] Updates documentation for channel selection

### PR DESCRIPTION
**Pull request by haskarb**
#### Reference Issues/PRs

#1821

#### What does this implement/fix? Explain your changes.

Doc update.
#### Does your contribution introduce a new dependency? If yes, which one?

No

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Makes sense!

Change requests:
* you need to use the name of the class(es)
* should the transformer go to the "feature selection" section, "these transformers select features in `X` based on `y`?

**Comment by haskarb** [comment]
> Makes sense!
> 
> Change requests:
> 
>     * you need to use the name of the class(es)
Done.
>     * should the transformer go to the "feature selection" section, "these transformers select features in `X` based on `y`?
Moved.

**Review by fkiraly — APPROVED** [review]
Great!

I thought it was already part of the API docs. Sorry I missed this in review.

**Comment by haskarb** [comment]
No problem. Thanks!

**Review by GuzalBulatova — APPROVED** [review]
Looks all good to me 👍

**Pull request merged**
