### PR TITLE
Release v0.15.0 

### PR DESCRIPTION
**Pull request by fkiraly**
Release PR for 0.15.0.

* version number bump
* changelog

### CODE REVIEW

**Review by aiwalter — CHANGES_REQUESTED** [review]
Pls include #3916

**Comment by fkiraly** [comment]
I left comments on #3916 which you have not yet replied to.

**Review by ltsaprounis — CHANGES_REQUESTED** [review]
#3975 was merged with change requests pending. The introduced mlflow dependencies set is specific to AWS because of the mock in the tests. This would mean that a user who would install sktime with `pip install sktime[mlfow]` would involuntarily install a lot of AWS things they may not need. We should find a more straightforward way of dealing with our mlflow test dependencies.

**Comment by fkiraly** [comment]
@ltsaprounis, I think that's a valid point. Would this https://github.com/sktime/sktime/pull/3979 be an acceptable solution?
I summarized the different requirements we need to satisfy there imo.

An important requirement is "tests continue running", the last one, which implies afaik some kind of dependency isolation away from `dev` or `all_extras`.

**Comment by fkiraly** [comment]
Decision by me as release manager:

* #3916 is not ready, it has open PR change requests to address. Not a reason to block the release.
* #3979 decision is resolved and explained in the PR

With this, no blocking requests to this PR.

**Pull request merged**
