### PR TITLE
[BUG] Fix pykan forecaster

### LINKED ISSUE #7116: [BUG] KANForecaster fails with newest version (2.6.0)
**Describe the bug**
In the CI (https://github.com/sktime/sktime/actions/runs/10824795191/job/30045061812) the fit of the KANForecaster fails due to `TypeError: MultKAN.fit() got an unexpected keyword argument 'device'`, since the device is not a key word of fit anymore. Now it is a parameter of `__init__`

### PR DESCRIPTION
**Pull request by benHeid**
#### Reference Issues/PRs
fixes #7116 

#### What does this implement/fix? Explain your changes.
* set the lower bound of pykan
* set the device only in initialization not during fit.

#### Does your contribution introduce a new dependency? If yes, which one?

No

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Questions:

* wouldn't we still have to pass `device` somewhere?
* this change would be breaking, could we instead make a case distinction depending on the pykan version?

**Comment by benHeid** [comment]
It is passed in the initialisation. Where it is already passed. So I am not quiet sure if the bug exist also with previous pykan versions. I can check the different version this evening.

**Comment by fkiraly** [comment]
where exactly is it passed?

**Comment by benHeid** [comment]
Line 174 and line 181

**Review by fkiraly — CHANGES_REQUESTED** [review]
I see thanks.

Strange that we were passing it twice then, in the first place.

Other question, blocking until resolved: do we need to raise the lower bound then? Given that it has already been passed in lower versions as well.

**Comment by benHeid** [comment]
> I see thanks.
> 
> Strange that we were passing it twice then, in the first place.
> 
> Other question, blocking until resolved: do we need to raise the lower bound then? Given that it has already been passed in lower versions as well.
I checked, it does not be that restrict. I set the lower bound to 0.2.1, since 0.2.0 is not working at all locally.

**Review by fkiraly — APPROVED** [review]

**Comment by fkiraly** [comment]
makes sense. Let's merge quickly then to remove the failure on `main`.

**Pull request merged**
