### PR TITLE
[BUG] Update `_shapelet_transform_numba.py` to improve numerical stability

### PR DESCRIPTION
**Pull request by stevcabello**
Improved numerical stability by setting a tolerance threshold for standard deviation calculation in shapelet transform. This change from use_std = std != 0 to use_std = std > 1e-8 prevents potential NaN values by avoiding division by extremely small numbers, addressing issues related to the precision limits of floating-point arithmetic.

#### Reference Issues/PRs

This PR addresses the NaN issue discussed in [#4073](https://github.com/sktime/sktime/issues/4073). By introducing a tolerance threshold for the standard deviation calculation, it aims to resolve the NaN values encountered in certain cases.

#### What does this implement/fix? Explain your changes.
Enhances the `_online_shapelet_distance` function's robustness by introducing a tolerance threshold (`1e-8`) for the standard deviation (`std`) calculation, ensuring numerical stability and preventing NaN values in shapelet transform calculations.

#### Does your contribution introduce a new dependency? If yes, which one?
No new dependencies introduced.

#### What should a reviewer concentrate their feedback on?
- The choice of the `1e-8` threshold for numerical stability.
- Potential impacts on the accuracy and performance of the shapelet transform function.

#### Did you add any tests for the change?
No new tests were added. Existing tests cover the functionality, but input on additional testing is welcome.

#### Any other comments?
I welcome any feedback or suggestions on this improvement.

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks!
We can merge this, or sth similar, before I'd kindly ask to adhere to code formatting, see https://www.sktime.net/en/stable/developer_guide/coding_standards.html, or the failing test (e.g., line length, spacing before comment, etc).

Further, I've been trying to look at the logic of the function, but this just raises more questions. Could you help me understand what is going on here? This looks like a lot of custom variation around the common algorithm.

Maybe it is better to discuss this in a separate issue?
Some observations:

* line 24, `std` is not a standard deviation, it is a variance. Is not a square root missing here?
* consequently, lin line 26, the normalization seems off by a factor of a standard deviation of the sample
* what is, in general, going on with the case treatment that std/var =0? Both in line 61 and 73. Naively, the result should be treated as infinite, but it is treated as zero. That is, the condition in line 65 should be triggered if `std` is 0.
    * So, naively, I wouldn't go and execute line 61, but do `if std = 0: break`, because that is equivalent to `temp` being infinitely large, so `dist` is, therefore `dist > best_dist`.

Perhaps if you are familliar with the algorithm: do you have a paper or math reference for this part of the code?

**Comment by stevcabello** [comment]
Thank you @fkiraly for the review and for raising important technical questions. I've updated the pull request to address the code formatting feedback. 

Regarding the algorithm's logic and the points mentioned, my understanding of the detailed workings of this implementation is limited. However, I believe the logic might be inspired by Algorithm 2 in the paper by Jon Hills et al., "Classification of time series by shapelet transformation". Data Min Knowl Disc 28, 851–881 (2014). Hope that helps!

**Comment by fkiraly** [comment]
Hm, @stevcabello, thanks for the reference. This has highlighted some possible issues with the algorithm, I'll open an issue about it.

Summarizing, I think:

* the paper is a bit of a mess with regards to normalization
* I think there are possible mistakes regarding normalization in the paper
* the algorithm is closer to the paper (and possible mistakes in it) than to other literature cited about normalization in the paper, but it is also not an 1:1 implementation, as the `sktime` implementer seems ot have corrected some - but not all - of the normalization related issues.

Technical details at the bottom.

#### How to deal with this 

So, we might want to think what to do here.

There's definitely worth in having the algorithm itself, as it has been used in benchmarking studies etc, but I feel it is based possibly on some calculation mistakes and will not do what is intended unless the time series (and/or sub-sequences) are already approximately normalized to begin with.

One could also think about a re-implementation where the normalization issues are all corrected, this would be a different algorithm though - and also different from the paper algorithm 2.

#### technical details re normalization

Normalization of shapelets uses - or is meant ot use - a simple linear algebra algorithm.

Denote by:

* $m: \mathbb{R}^n \rightarrow \mathbb{R}, x\mapsto \langle 1, x\rangle$ the mean function, where 1 is the all-ones $n$-vector
* $v: \mathbb{R}^n \rightarrow \mathbb{R}, x\mapsto m(x\odot x) - m(x)^2$ the variation function, where $\odot$ denotes element-wise multiplication (Hadamard product)
* $n: \mathbb{R}^n \setminus S \rightarrow \mathbb{R}^n$, defined as $n(x) := (x - m(x)) / \sqrt(v(x))$, where $S$ denotes the set of vectors $x$ such that $v(x) = 0$.

Now, for any vector $x\in \mathbb{R}^n$ such that $v(x) \neq 0$, it holds that $m(n(x)) = 0$, and $v(n(x)) = 0$.

So, the algorithm of "apply $n$" produces a "normalized" version of the vector $x$. This is denoted by "norm" in the paper.

Or, almost - the paper omits the square root in the denominator of $n$, in algorithm 2 (subsequence normalization), while not making an explicit definition of the "norm" symbol.

The `sktime` implementation omits the square root in the overall normalizaiton, but adds it in the subsequence normalization, where it was missing in the paper (algorithm 2).

**Comment by fkiraly** [comment]
@stevcabello, as it looks like this may be going off-topic regarding the bugfix, I've opened a new issue here where we can continue discussing if you want: https://github.com/sktime/sktime/issues/6152

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks for fitting the formatting issues.

Instead of using the threshold strategy, how about doing the following which is more faithful to the original implementation:

At the start of the loop (line 61), do `if std == 0: break`?

**Review by fkiraly — APPROVED** [review]
Finished this so it can go in the release

**Comment by fkiraly** [comment]
(failures unrelated, sporadic)

**Pull request merged**
