### PR TITLE
[ENH] automatic inference of file ending in data loaders for single file types

### LINKED ISSUE #2576: [ENH] data loaders for single file types should not require file ending specified
data loaders such as `load_from_tsfile` should not requires specification of the file ending, since there is only one file ending the function accepts.

for instance, it would be good if load_from_ts assumed the file extension .ts if none was given, so that these two worked equivalently 

```python
X, y = load_from_tsfile("C:\Temp\Chinatown\Chinatown_TRAIN.ts",
                        return_data_type="numpy2d")
X, y = load_from_tsfile("C:\Temp\Chinatown\Chinatown_TRAIN",
                        return_data_type="numpy2d")
```

### PR DESCRIPTION
**Pull request by SaiRevanth25**
#### Reference Issues/PRs
 Fixes #2576 

#### What does this implement/fix? Explain your changes.
 I've created a function which takes two parameters (path, suffix). If the path does not have the specified file extension, the funciton appends it(suffix) to the path. (It basically eleminates the need of adding specified file ending for data loaders)

#### Does your contribution introduce a new dependency? If yes, which one?

No

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks!

two comments:

* I think the logic is problematic: namely, if the file already has an extension, but a different one, it appends the extension. Is this intended?
* The code added does not comply with `sktime` code formatting, see here how to enable that quickly: https://www.sktime.net/en/stable/developer_guide/coding_standards.html

**Comment by fkiraly** [comment]
I would suggest the following logic:

* check if file name already has extension
* if not, check if file name without extension exists
* if not, add extension

I.e., only add the extension if the name does not already have one, and a file without the extension does not exist.

**Comment by SaiRevanth25** [comment]
```
def get_path(p:str or pathlib.Path, ext:str) -> str:
    p_ = pathlib.Path(p).expanduser().resolve()
    path_ = str(p_)
    if not p_.suffix:
        if not os.path.exists(path_):
            path_ += ext
    return path_
```
    
how about this, any changes to make?? @fkiraly

**Comment by fkiraly** [comment]
yes, good idea. I think windows does the same?

**Comment by SaiRevanth25** [comment]
yes it does. I'll check with the coding standards and update soon.

**Comment by fkiraly** [comment]
nice! I think this is still failing code formatting, feel free to ask in discord/dev-chat for help if you get stuck with that. Developer guide is as in the link above.

**Comment by SaiRevanth25** [comment]
I think this should be good to go!! @fkiraly

**Review by fkiraly — CHANGES_REQUESTED** [review]
Yes, I think all comments re logic are addressed, thanks!

The code formatting should be fixed before we can merge, though.

**Review by fkiraly — APPROVED** [review]
Nice!

The loaders module could use a bit of clean-up, in case you are interested - that's a separate story though.

**Comment by SaiRevanth25** [comment]
Any specific issue that i can work on?? @fkiraly

**Comment by fkiraly** [comment]
@SaiRevanth25, yes - there is a refactor plan that has been partly but not entirely been carried out, here:
https://github.com/sktime/sktime/issues/5105
(by @hazrulakmal)

There are further issues, some design, some bugs, here: https://github.com/sktime/sktime/issues?q=is%3Aopen+is%3Aissue+label%3Amodule%3Adatasets%26loaders

One interesting project might be to make the collection of data sets tagged and searchable - let me know if that is of interest, and I can summarize.

**Comment by SaiRevanth25** [comment]
yeah! i'm interested to work on it (collection of datasets tagged and searchable). @fkiraly

**Pull request merged**
