### PR TITLE
[DOC] Refactor examples directory and link to docs/source/examples

### LINKED ISSUE #6148: [DOC] [BUG] Different directory structures between examples and docs/source/examples
#### Describe the issue linked to the documentation

Properly related to #3246. Mention in #6128. 

As discussed in some other threads before, each notebook in examples is manually linked to docs/source/examples with a different folder structure. Below the full list of notebooks that are added to examples but not linked, found with a script: 
 
03_transformers.ipynb
Overview_of_sktime_functionalities_for_forecasting.ipynb
mlflow.ipynb
03b_forecasting_transformers_pipelines_tuning.ipynb
02c_classification_multivariate_inceptiontime.ipynb
00_sktime_intro.ipynb
03a_transformers_cheat_sheet.ipynb
04_benchmarking_v2.ipynb
02b_classification_multivariate_lstmfcn.ipynb 

In addition, because some notebook have image references from examples/img. After being linked they could no longer find the images i.e https://www.sktime.net/en/stable/examples/annotation/segmentation_with_clasp.html in the second section. 

#### Suggest a potential alternative/fix

Refractor root/examples and add a function in either pre-commit or conf.py to link the whole folder to docs.

### PR DESCRIPTION
**Pull request by duydl**
#### Reference Issues/PRs

Fixes #6148. 

#### What does this implement/fix? Explain your changes.

I rearranged the examples dir to be similar to the docs/source/examples, replaced docs/source/examples containing individual sym links inside with just one directory sym link to examples, and adjusted the path of some image links. 

For comparison: 
https://www.sktime.net/en/stable/examples.html
https://duydlsktime.readthedocs.io/en/patch-docs-examples-0/examples.html in case PR docs not yet rendered

### CODE REVIEW

**Comment by duydl** [comment]
@fkiraly hi. sorry I didn't pay attention but seems like this PR is missed somehow.

**Review by fkiraly — CHANGES_REQUESTED** [review]
Apologies, I indeed missed this. I mistakenly filed it under, another core dev has replied (not sure why).

Thanks a lot for looking into this!

My main comment revolves around the user journey - is important content adequately presented with priority?

There are "major", "secondary", and "minor" tutorials in my mental model.

* major - entry guide for a task or module, e.g., forecasting intro. Basis guide to the framework.
* secondary - follow-on from the entry guide, focus on one specific topic, e.g., probabilistic, hierarchical, etc. Require knowledge of basis guide, and are a manual to advanced features.
* minor - cover specific estimators, use cases, research studies, etc. Does not cover any  (or only minimal) framework content.

Imo users should be pointed prominently to the major guides, and from there, or after that, to the secondary ones. The "minor" ones should be showcased somehow, but not be presented with equal prominence, as that could confuse users and is typically not what they are looking for primarily.

So far, how we managed it is the numbering, which lets the "major" notebooks appear at the top.

If we move things into folders (e.g., `03_transformers` which is important), this structured user journey gets a bit muddled.

So the main question would be, how do we keep your great changes, but also ensure we have a structured user journey? I don't have a "prescriptive" answer, but I think we should spend a round of thinking on this.

**Comment by duydl** [comment]
I assume this is in terms of the root examples / binder because the current arrangement mirrors that of the docs till now. 

Then the solution would be to move all the important (numbered) notebooks out of subdir into examples/ and just include them manually in the relevant section on examples page. Then those notebooks would also be auto added to the user guide page which is probably another desirable outcome.

**Comment by duydl** [comment]
For more detail user journey like you envision, this would involve editing the notebooks themselves. It would probably resemble the user-guide of scikit-learn, some would have links to relevant examples in the middle, as well as references to white paper etc.

**Comment by fkiraly** [comment]
> Then the solution would be to move all the important (numbered) notebooks out of subdir into examples/ and just include them manually in the relevant section on examples page. Then those notebooks would also be auto added to the user guide page which is probably another desirable outcome.

Yes, I think that's a good quick way to get close to the optimal state.

> For more detail user journey like you envision, this would involve editing the notebooks themselves. 

That's more work, so perhaps not for this PR?

**Comment by duydl** [comment]
@fkiraly I moved the numbered nb into examples and added those manually to examples.rst . It is only based on whether one is numbered as there some cases may need clarified in the future: 
    
>  examples/04_benchmarking.ipynb
    examples/04_benchmarking_v2.ipynb

Two versions. What are the plans for these?
    
> examples/02a_classification_multivariate_cnn.ipynb
    examples/02b_classification_multivariate_lstmfcn.ipynb
    examples/02c_classification_multivariate_inceptiontime.ipynb

They are all very short with nearly identical content. Consider combining?    

> That's more work, so perhaps not for this PR?
    
Yes. And other nb specific adjustments also IMO. Would be a good task for GSoD i.e going through the current notebooks, optimizing, linking etc.

**Review by fkiraly — APPROVED** [review]
Thanks a lot for going through this!

I think the hierarchy you propose makes sense.

> Two versions. What are the plans for these?

These relate to two benchmarking frameworks currently in sktime. We intended to unify these, but the project did not get carried out yet. For now, I think it makes sense to present both.

> They are all very short with nearly identical content. Consider combining?

These are weird notebooks. I don't think there is any added content, compared to the main notebook, we just fit some estimators here on random data? I would advocate to remove these entirely. Didn't realize we had these.

> Would be a good task for GSoD i.e going through the current notebooks, optimizing, linking et

Yes, absolutely! I included it as a point 1 next to the 3 detail points you elaborated on.

**Comment by duydl** [comment]
Sorry, I forgot to revert the change of image links in one notebook after returning its location.

**Review by yarnabrina — APPROVED** [review]

**Pull request merged**
