### PR TITLE
[ENH] fix `ForecastingHorizon.freq` handling for `pandas 2.2.X`

### PR DESCRIPTION
**Pull request by fkiraly**
IMPORTANT: when merging, this should not change `pyproject.toml`. The `pandas` bound should be raised only at 0.28.0, separately via https://github.com/sktime/sktime/pull/5841, after this is merged.

This PR patches `ForecastingHorizon.freq` handling for `pandas 2.2.X`, possibly the best solution for now barring a full rework.

* expected frequency strings are different form 2.2.0, this has been adapted in tests
* conversion of `M` frequency from time stamp to period works different from 2.2.0, this needed to be addressed directly in `ForecastingHorizon`.

Also removed `test_set_freq` which was an 1:1 duplicate of `test_infer_freq`.

### CODE REVIEW

**Comment by fkiraly** [comment]
@yarnabrina, `pandas` version in the `forecasting` dep set is 2.1.4 - any idea what keeps it strictly under 2.2.0?

**Comment by yarnabrina** [comment]
I'm not sure, I think we need to install this branch locally in a new environment and see what pipdeptree says.

I see another issue, which is a bit more weird. I see in the logs statsforecast 1.6.0 is being installed, but I uodated the upper bound as <1.8 in TBATS Pr and I see the same on main. That's a bit worrying, is this branch up to date with main?

**Comment by fkiraly** [comment]
> is this branch up to date with main?

Yes, it is.

**Comment by fkiraly** [comment]
opened diagnostic PR with `pandas==2.2.0` here: https://github.com/sktime/sktime/pull/6063

**Comment by yarnabrina** [comment]
`pipdeptree` output

```bash
(6057) root@c501597730f4:/sktime# pipdeptree -r -p pandas
pandas==2.1.4
├── arch==6.3.0 [requires: pandas>=1.1]
├── cmdstanpy==1.2.1 [requires: pandas]
│   └── prophet==1.1.5 [requires: cmdstanpy>=1.0.4]
├── pmdarima==2.0.4 [requires: pandas>=0.19]
│   └── tbats==1.1.3 [requires: pmdarima]
├── prophet==1.1.5 [requires: pandas>=1.0.4]
├── qpd==0.4.4 [requires: pandas>=1.2.0]
│   └── fugue==0.8.7 [requires: qpd>=0.4.4]
│       └── statsforecast==1.6.0 [requires: fugue>=0.8.1]
├── skpro==2.1.3 [requires: pandas>=1.1.0,<2.2.0]
├── sktime==0.27.0 [requires: pandas>=1.1,<2.3.0]
├── statsforecast==1.6.0 [requires: pandas>=1.3.5]
├── statsmodels==0.14.1 [requires: pandas>=1.0,!=2.1.0]
│   ├── arch==6.3.0 [requires: statsmodels>=0.12]
│   ├── pmdarima==2.0.4 [requires: statsmodels>=0.13.2]
│   │   └── tbats==1.1.3 [requires: pmdarima]
│   └── statsforecast==1.6.0 [requires: statsmodels>=0.13.2]
└── triad==0.9.5 [requires: pandas>=1.3.5]
    ├── adagio==0.2.4 [requires: triad>=0.6.1]
    │   ├── fugue==0.8.7 [requires: adagio>=0.2.4]
    │   │   └── statsforecast==1.6.0 [requires: fugue>=0.8.1]
    │   └── qpd==0.4.4 [requires: adagio]
    │       └── fugue==0.8.7 [requires: qpd>=0.4.4]
    │           └── statsforecast==1.6.0 [requires: fugue>=0.8.1]
    ├── fugue==0.8.7 [requires: triad>=0.9.3]
    │   └── statsforecast==1.6.0 [requires: fugue>=0.8.1]
    ├── fugue-sql-antlr==0.2.0 [requires: triad>=0.6.8]
    │   └── fugue==0.8.7 [requires: fugue-sql-antlr>=0.1.6]
    │       └── statsforecast==1.6.0 [requires: fugue>=0.8.1]
    └── qpd==0.4.4 [requires: triad>=0.9.0]
        └── fugue==0.8.7 [requires: qpd>=0.4.4]
            └── statsforecast==1.6.0 [requires: fugue>=0.8.1]
```

**Comment by fkiraly** [comment]
updated after dependabot has bumped `skpro` bound - the envs with soft deps should now run with `pandas 2.2.X`

**Review by yarnabrina — APPROVED** [review]
Approved ignoring the failures as they seem to be from Implement watch and autobuild with sphinx-autobuild or watchdog to observe changes, and selectively rebuild the documentation.

Question: this PR changes pandas, one kf the core dependencies. Because of CI trigger logic, all jobs were triggered,  but are all estimators tested? Or did they got filtered out by no change in soft dependency logic?

**Comment by fkiraly** [comment]
> Question: this PR changes pandas, one kf the core dependencies. Because of CI trigger logic, all jobs were triggered, but are all estimators tested? Or did they got filtered out by no change in soft dependency logic?

Good point, they were not all tested. Let's check that in a diagnostic PR before we merge.

**Review by yarnabrina — CHANGES_REQUESTED** [review]
(Just to withdraw approval as the diagnostic PR shows failures)

Should we add core dependencies in the test trigger logic too? They are probably not part of any tag I think,  so some new logic may be necessary.

**Comment by fkiraly** [comment]
> Should we add core dependencies in the test trigger logic too? 

I see - good point.

**Pull request merged**
