### PR TITLE
[DOC] improved docstring for `TimeSeriesForestClassifier`

### PR DESCRIPTION
**Pull request by fkiraly**
Fixes https://github.com/sktime/sktime/issues/5740:

* corrects location for the configurable time series forest
* adds explanation on annother optionn, building the tsf from scratch
* formatting and typos

### CODE REVIEW

**Comment by fkiraly** [comment]
> I'm very interested to see the new content on "adds explanation on annother optionn, building the tsf from scratch"!

You can see it in the code - it basically points you to `BaggingClassifier` and says you can use any TSC as a base estimator inside, e.g., a pipeline of feature extractor and sklearn `DecisionTreeClassifier`.

Might also be helpful to say what components give rise to the concrete `TimeSeriesForestClassifier` as a special case, logic-wise?

**Comment by jmwhyte** [comment]
> Might also be helpful to say what components give rise to the concrete `TimeSeriesForestClassifier` as a special case, logic-wise?

I think that would be very helpful. It can be difficult to follow the logic sometimes - there seems to be this huge palette of possibilities, but not always enough content to inform a choice. For those of us starting with a simple system and looking to add complexity in an organised manner (so we can build on knowledge gained elsewhere in sktime), extra info is welcome. (So are examples, btw. I have sometimes found the docs quite difficult to interpret when looking to try out a new classifier, such as `ComposableTImeSeriesForestClassifier`.)

**Comment by fkiraly** [comment]
> I think that would be very helpful.

Yes, although right at this point I do not know the exact composition, due to me not knowing which time series classifier is the base classifier inside. Do you pehaps now off the top of your head, @jmwhyte?

**Comment by jmwhyte** [comment]
> > I think that would be very helpful.
> 
> Yes, although right at this point I do not know the exact composition, due to me not knowing which time series classifier is the base classifier inside. Do you pehaps now off the top of your head, @jmwhyte?

I'm not so sure about details, but I think I remember seeing an error that mentioned `DecisionTreeClassifier`, and that's the classifier that comes up in examples, such as in one from @TonyBagnall here: https://github.com/sktime/sktime/issues/1536 .

**Pull request merged**
