### PR TITLE
[ENH][BUG] Second test parameter set for shapeDTW

### PR DESCRIPTION
**Pull request by Xinyu-Wu-0000**
Towards https://github.com/sktime/sktime/issues/3429

Adds a second test parameter set for shapeDTW

### CODE REVIEW

**Comment by benHeid** [comment]
Hi @Xinyu-Wu-0000, thank you for your pull request. In the CI pipeline, a linting step is failing. Thus, please execute black and update this pull request :)

**Comment by fkiraly** [comment]
Guide how to set up linting locally on your computer: https://www.sktime.net/en/stable/developer_guide/coding_standards.html

**Comment by Xinyu-Wu-0000** [comment]
Thank you for your comments, I updated my linting setup and the pull request.

**Comment by fkiraly** [comment]
Nice, thanks! Started the tests.

**Comment by Xinyu-Wu-0000** [comment]
`FAILED sktime/classification/tests/test_all_classifiers.py::TestAllClassifiers::test_multioutput[ShapeDTW-1] - TypeError: __init__() got an unexpected keyword argument 'n_neighbours'`

Maybe the error above is not cased by my commits. Mismatch `n_neighbours` != `n_neighbors` is already in main branch:

  line 41 in `sktime/classification/distance_based/_shape_dtw.py`: n_neighbours
  image
  
  line 126 in `sktime/classification/distance_based/_shape_dtw.py`: n_neighbors
  image
  
  line 241 in `sktime/classification/distance_based/_shape_dtw.py`: n_neighbours
  image

**Comment by fkiraly** [comment]
Hm, looks like you found a bug! That's why it's useful to have more test parameters!
(I added two badges, for bug report and bugfix, `bug` and `code`)

Btw, can you explain why it did not fail previously? Why is the constructor with the wrong variable name never called in the first test case!

**Comment by fkiraly** [comment]
(I'll review when test results are here)

**Comment by Xinyu-Wu-0000** [comment]
> Btw, can you explain why it did not fail previously? Why is the constructor with the wrong variable name never called in the first test case!

To my understanding, the constructor will only be called when `shape_descriptor_function == "compound"` and  "metric_params["weighting_factor"] unset, then `ShapeDTW` will try to call the contstructor to tune the `weighting_factor`.

**Comment by Xinyu-Wu-0000** [comment]
For the new error `UnboundLocalError: local variable '_reset' referenced before assignment` in `sktime/classification/distance_based/_shape_dtw.py, line 187, in _fit`:

If `metric_params` is not `None`, then `_shape_dtw.py, line 167, in _fit` will not be excecuted, `_reset` will be unbound:
image

However,  `_shape_dtw.py, line 187, in _fit` will always be excecuted whether `metric_params` is `None` or not.
image

**Comment by Xinyu-Wu-0000** [comment]
```python
        else:
            _reset = False
```
is added to `_fit` to fix the unbound error.

Now `check_estimator` will return `All tests PASSED!`:
```python
from sktime.classification.distance_based import ShapeDTW
from sktime.utils.estimator_checks import check_estimator

check_estimator(ShapeDTW, raise_exceptions=True)
```

**Comment by Xinyu-Wu-0000** [comment]
For the other error in [`test-mlflow`](https://github.com/sktime/sktime/actions/runs/8241811892/job/22541170510?pr=6093), it seems the filepath extension is invalid.
 
"sktime/classification/deep_learning/base.py line 314" in `_serialize_using_dump_func`
image

If `self.model_` is returned by  `self.build_model` in  `sktime/classification/deep_learning/cnn.py line 185`:
image


Then `self.model_.save` is `keras.models.Model.save` as defined in `sktime/classification/deep_learning/cnn.py line 157`
image

It will be `keras.models.Model.save(path / "keras/")`. 

In the [`test-mlflow`](https://github.com/sktime/sktime/actions/runs/8241811892/job/22541170510?pr=6093) `path` is `PosixPath`
image

I don't know how to fix it. What `path` should be? Or is the error inevitable with `path / "keras/"` be passed to `save`?

**Comment by Xinyu-Wu-0000** [comment]
The invalid filepath extension error happens in other pull requests too: [test-mlflow](https://github.com/sktime/sktime/actions/runs/8238639351/job/22530207366?pr=6107) in #6107 and [test-mlflow](https://github.com/sktime/sktime/actions/runs/8223561153/job/22489250797?pr=6102) in #6102.

**Comment by yarnabrina** [comment]
You can ignore those errors in mlflow and pandas v1 tests. Those are being tracked in #6094 and #6098 by @benHeid should fix those when merged in main.

**Comment by Xinyu-Wu-0000** [comment]
> You can ignore those errors in mlflow and pandas v1 tests. Those are being tracked in #6094 and #6098 by @benHeid should fix those when merged in main.

Thank you for the guiding. All tests passed except mlflow and pandas v1. If my fix on `_reset` in commit [2a776ae](https://github.com/sktime/sktime/pull/6093/commits/2a776aebf53e88def920283885e1b6829621dbdf) is ok, I think this PR could be merged.

**Comment by Xinyu-Wu-0000** [comment]
Not sure about the error in job [commit-and-push](https://github.com/sktime/sktime/actions/runs/8359195691/job/22882031049?pr=6093). It seems that the Github action tried to find the branch `test_params_shape_dtw` in sktime repository. Maybe it' caused by the last commit merging my fork into this PR.
One of the Limitations & Gotchas of this [Github action: stefanzweifel/git-auto-commit-action@v5](https://github.com/stefanzweifel/git-auto-commit-action#:~:text=No%20support%20for%20git%20rebase%20or%20git%20merge.%20There%20are%20many%20strategies%20on%20how%20to%20integrate%20remote%20upstream%20changes%20to%20a%20local%20repository.%20git%2Dauto%2Dcommit%20does%20not%20want%20to%20be%20responsible%20for%20doing%20that.) is no support to integrate remote upstream changes to a local repository. From the perspective of the Github action, sktime is the local repository and my fork is the remote.
> No support for git rebase or git merge. There are many strategies on how to integrate remote upstream changes to a local repository. git-auto-commit does not want to be responsible for doing that.

I am merging main into `test_params_shape_dtw` so that the last commit won't be merging remote into local.

**Pull request merged**
