### PR TITLE
Revert "[ENH] isolating `scipy` imports, part 1"

### PR DESCRIPTION
**Pull request by patrickzib**
For reference: I did vote this down on 8th of December.

image

And you confirmed that my vote is unaffected:
image

### CODE REVIEW

**Comment by patrickzib** [comment]
@aiwalter could you revert this PR please. See reasons above

**Review by aiwalter — APPROVED** [review]

**Comment by fkiraly** [comment]
I have not seen your post on slack relating to #3707, and - if you look closely - the dates on your posts do not match:

* in German, the first says December 8
* the second translates to " 22 days ago", which would make it December 5 or 6

This reverses the implied chronology and dues not support your tacit implication

#3707 has been open for almost two months now and you did not find it contentious before the entire episode that got you banned.

You - or anyone - could have posted on the PR itself, since early November.

And,  you *opened an issue that proposed to turn `scipy` into a soft dependency*: https://github.com/sktime/sktime/issues/3875

So you were (formally) in favour of doing the thing that you are now voting against.

Please be constructive in your posts, and civil in your activity on the `sktime` GitHub.

**Comment by patrickzib** [comment]
Simple causality: You confirmed that my vote is unaffected on 5.12.. And I wrote on 12.12. that I am blocking the PR on slack, when I was not able to do anything on github. 

Do not see, why I have to write it twice. Please accept it as it is.

**Comment by patrickzib** [comment]
Also stop blaming me.

**Comment by fkiraly** [comment]
@patrickzib, please stay civil and refrain from accusations.

I'm giving you the benefit of the doubt and will revert the PR.

**Pull request merged**
