### PR TITLE
[BUG] ForecastingBenchmark giving an error when the dataloader returns the tuple (y, X)

### LINKED ISSUE #6964: [BUG] ForecastingBenchmark giving an error when the dataloader returns the tuple (y, X)
**Describe the bug**
 When using the ForecastingBenchmark with a data loader that returns a tuple (y, X) (where y is the endogenous data and X is the exogenous data), I encounter the following error:
`TypeError: Expected y dtype ['Series', 'Panel', 'Hierarchical']. Got <class 'tuple'> instead.`

**To Reproduce**
```python

from sktime.benchmarking.forecasting import ForecastingBenchmark
from sktime.performance_metrics.forecasting import MeanAbsolutePercentageError
from sktime.forecasting.naive import NaiveForecaster
from sktime.forecasting.exp_smoothing import ExponentialSmoothing
from sktime.forecasting.theta import ThetaForecaster
from sktime.split import ExpandingWindowSplitter

def load():
    return (y, X) # both are Hierarchical type dataframes

cv = ExpandingWindowSplitter(initial_window=60, step_length=24, fh=np.arange(1, 25))

benchmark = ForecastingBenchmark()

benchmark.add_estimator(NaiveForecaster(strategy='mean'))
benchmark.add_estimator(ExponentialSmoothing())
benchmark.add_estimator(ThetaForecaster())

benchmark.add_task(dataset_loader=load, cv_splitter=cv, scorers=[MeanAbsolutePercentageError()], task_id="M5_mape")

benchmark.run(output_file= 'results.txt')
```
image

### PR DESCRIPTION
**Pull request by SaiRevanth25**
#### Reference Issues/PRs
 Fixes #6964 

#### What does this implement/fix? Explain your changes.
 Checks if the parameter `y` is an instance of tuple. if yes it unpacks the tuple into two variables y and X

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
This is not the place I would unwrap it, it changes the contract of `evaluate` which imo is quite sensible.

The place I would change it is wherever it is called from in the benchmarking framework.

**Review by fkiraly — APPROVED** [review]
yes, this is what I meant!

**Comment by fkiraly** [comment]
FYI @benHeid, would appreciate you looking

**Review by benHeid — APPROVED** [review]
Nice looks good to me

**Pull request merged**
