### PR TITLE
[ENH] improved `plot_series` utility

### PR DESCRIPTION
**Pull request by ericjb**
#### What does this implement/fix? Explain your changes.
Fixes bug 5895 by allowing matplotlib to deal with index (i.e. x-axis) manipulations

#### Does your contribution introduce a new dependency? If yes, which one?
no

#### What should a reviewer concentrate their feedback on?

The seaborn graphics package is no longer used to create basic plots; now uses matplotlib directly; this may change the plot theme (from the seaborn default theme to the matplotlib default theme); initial inspection did not see particular differences but I did not compare a lot of plots

#### Did you add any tests for the change?

No

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks!
Changes look mostly fine, I have some questions:

* why is the deepcopy at the start needed?
* is there any parameter combination of `plot_series` that previously worked and now does not?
* could you paste some pre/post comparisons for other reviewers?
* you are changing the signature of `plot_interval`. This seems not to have been used or documented, but let´s check this explicitly: has this been used elsewhere? Or is it a private function (even if it does not start with an underscore)

**Comment by ericjb** [comment]
In order:
1. >> why is the deepcopy at the start needed?
   It is actually only needed (AFAIK) in the case that the index of the incoming series has type PeriodIndex, which matplotlib seems to have issues with. I will modify the code so that the copy is only done in this special case. Otherwise, I will just use a reference. 
2. >> is there any parameter combination of plot_series that previously worked and now does not?
   I have not seen that yet but I have not done a lot of testing. I will be doing additional testing.
3. >> could you paste some pre/post comparisons for other reviewers?
   comparisons of what? plots? (as images?)
4. >> you are changing the signature of plot_interval. This seems not to have been used or documented, but let´s check this explicitly: 
   I am not changing the signature but I am ignoring one of the parameters. I think the function is doing what is expected. (I hardly touched it.) If desired, the caller can pass the desired subset via the first argument. Ignoring the 3rd argument is necessary because it relies on the no-longer-used internal representation of the x-axis. I suppose I could test whether the 3rd argument is being passed as None, and if not I could issue a warning that this parameter has been deprecated. If you like this idea, please point me to some sktime code that issues the type of warning you would want here.

**Comment by fkiraly** [comment]
> I will modify the code so that the copy is only done in this special case. Otherwise, I will just use a reference.

Hm, ok. Might be worth checking how this interacts with the converter utility. Only after that you can assume that you have a `pandas` object.

>>could you paste some pre/post comparisons for other reviewers?
>comparisons of what? plots? (as images?)

Yes, to have a clearer view of what the changes are effecting.

> I am not changing the signature but I am ignoring one of the parameters.

Yes, I meant, you are changing the behaviour given parameters.

If the function was purely used as private - after all, it had no docstring, no warning etc needs to be done, as long as `plot_series` does not change behaviour.

**Comment by ericjb** [comment]
>> Hm, ok. Might be worth checking how this interacts with the converter utility. Only after that you can assume that you have a pandas object.

How could it interact? The plot_series function does not modify any of the arguments and only returns graphics objects.

**Comment by fkiraly** [comment]
> How could it interact?

If you check for index type at a point where the series doesn't have an index attribute yet (before conversion)

**Comment by ericjb** [comment]
Now I understand what you meant by the interaction. Good point. My latest changes do the conversion before the test. (Not checked in yet.)

**Comment by fkiraly** [comment]
let us know if you need any reviews

**Pull request closed without merging**
