### PR TITLE
[MNT] remove use of `abc` and metaclasses

### PR DESCRIPTION
**Pull request by fkiraly**
This PR removes any use of `abc` and metaclasses from `sktime`.

Several reasons:

* consistency across base class designs
* use of abc is very limited, no advanced pattersn are used, only `abstractmethod` decoration which can be easliy replaced by tests or raises, as done in this PR
* I strongly suspect this is causing failures due to abc decorators interacting with strong type checks in 3.9 precommit updates in https://github.com/sktime/sktime/pull/6331 and https://github.com/sktime/sktime/pull/6330

### CODE REVIEW

**Comment by yarnabrina** [comment]
Sorry for disagreement, I am not sure if I am in much favour of this PR. Abstract methods are very standard in defining expectations from child classes, and I am quite fond of that design (so biased to be honest).

Since I see other estimators with abstract methods didn't fail, my guess is that something may be the issue in how those two specific classes are defined (admittedly I do not know the specifics as of now).

**Comment by fkiraly** [comment]
It's a guess - let's see what happens in https://github.com/sktime/sktime/pull/6538.

If it were `abc` classes, then their removal simultaneous with 3.9 codestyle upgrade would be the only currently known way to ensure downwards compatibility with earlier `skbase` versions.

I have a neutral opinion about `abc` but a strong opinion about retaining downwards compatibility, as a force-upgrade worth a jump of a year may hit users behind longer package approval processes hard.

**Comment by fkiraly** [comment]
Cleaning up some old PR, @yarnabrina - what are we supposed to do with this one?

**Comment by yarnabrina** [comment]
I'll have no complaints if we close this PR and drop this branch altogether. It was created to address the pre-commit issues, and a specific subset of it (removal of just `abc.ABC`, but NOT of `abc.abstractmethod`) was enough to fix #6330.

**Pull request closed without merging**
