### PR TITLE
[ENH] `statsforecast` `AutoTheta` direct interface estimator

### PR DESCRIPTION
**Pull request by yarnabrina**
#### Reference Issues/PRs

Depends on #4629
Part of #4643 

#### What does this implement/fix? Explain your changes.

This PR adds and interface to the `AutoTheta` model provided in `statsforecast`. It's exposed to users as `StatsForecastAutoTheta`.

#### Does your contribution introduce a new dependency? If yes, which one?

No.

#### Did you add any tests for the change?

No.

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [x] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by yarnabrina** [comment]
> @yarnabrina, great! I notice the import errors on 3.7, this is due to some types like `Literal` only being present from 3.8. I would say, let's try to avoid these imports.
> 
> Regarding the return type, it's a matter of conversion - `sktime` estimators expect the return to be the same data type as the input to `_fit`.

Removed the `Literal` as suggested.

I don't think I could follow your comment on returns. Can you please elaborate? I thought it is failing because of the existing adapter for `statsforeast` which may be too specific for ARIMA case. If it is related to `sktime` expectations as well, I'd need some time to analyse. Will check this over weekend.

**Comment by fkiraly** [comment]
> Can you please elaborate?

Sorry for expressing myself obscurely.

I meant, the output mtype (e.g., `pd.Series` or `pd.DataFrame`) of the `_predict` return should be the same as the input mtyep for `y`, of the `_fit` arguments. Note the underscores.

**Comment by yarnabrina** [comment]
Note: putting it on a hold for around one or two weeks. attempting adapter rewrite for statsforecast. If it works and is approved, will add theta forecaster from that branch in future.

**Review by fkiraly — APPROVED** [review]
Excellent, thanks!

**Pull request merged**
