### PR TITLE
[DOCS] Adding invite to fall dev days to website landing page.

### PR DESCRIPTION
**Pull request by miraep8**
Adding an invite to the sktime website for people to register for the upcoming dev days.

### CODE REVIEW

**Review by lmmentel — APPROVED** [review]
:raised_hands:

**Comment by lmmentel** [comment]
I just noticed that you added the video under version control :grimacing: Would it be possible to put it somewhere to be served as static content and  link to it form the docs? Maybe google drive and share publicly?

**Comment by miraep8** [comment]
Yea that might be a better way to do it.  Was honestly just testing a few things out for now, can try your suggestion!

**Comment by RNKuhns** [comment]
@miraep8 you could also consider adding this as an announcement banner on every page of docs via [pydata-sphinx-theme](https://pydata-sphinx-theme.readthedocs.io/en/v0.11.0/user_guide/announcements.html).

**Comment by miraep8** [comment]
@RNKuhns I think that is a great idea!  Thanks/will do! :)

**Review by lmmentel — APPROVED** [review]
Looks good

**Review by fkiraly — CHANGES_REQUESTED** [review]
I think the bets way to serve the video would be:

* put it on the youtube channel (FYI @Lovkush-A )
* youtube link here

**Comment by miraep8** [comment]
Sure, I do not have access to the youtube channel, but would be happy to update the link if I get one.  

In the meantime though I do think the current solution works (ie the video at least seems to show up correctly in the docs preview), so I am wondering if it would be possible to either:

- a ) - Merge as is?
- b) - I remove the link to the video and we can add it back in later.

**Comment by lmmentel** [comment]
I would go with merge as it since it gets the message out there and you can always upload to youtube later if need be and update the docs.

**Review by fkiraly — APPROVED** [review]
yes, it's time sensitive, agree with @lmmentel. Please consider unblocked and approved.

@Lovkush-A I think can help with the youtube channel.

**Comment by Lovkush-A** [comment]
i do not have experience with the youtube channel; nor do i know who has uploaded videos in the past

**Pull request merged**
