### PR TITLE
[BUG] Empty dummy step's buffer only if new data arrive

### LINKED ISSUE #5830: [BUG] Graphical pipeline requires `X` in `predict`
**Describe the bug**
The graphical pipeline requires `X` in the prediction step if a transformation on `y` is present in the pipeline. This doesn't make too much sense because `X` has been computed in the `fit` step and can't be provided in the `fit` by the user. 

**To Reproduce**

```python
from sktime.forecasting.compose import make_reduction
from sklearn.linear_model import Ridge
from sktime.transformations.series.difference import Differencer
from sktime.transformations.series.lag import Lag
from sktime.transformations.series.impute import Imputer
from sktime.datasets import load_airline
from sktime.split import temporal_train_test_split
from sktime.pipeline import Pipeline

y = load_airline()
y_train, y_test = temporal_train_test_split(y)

forecaster = make_reduction(Ridge(), window_length=12, strategy="recursive")

pipe = Pipeline()
pipe = pipe.add_step(Differencer(lags=[1, 3]), "differencer", edges={"X": "y"})
pipe = pipe.add_step(
    forecaster, name="forecaster", edges={"X": "differencer", "y": "y"}
)
# can't pass X=y_train, at predict-time this would be X=X_pred=y_pred
pipe.fit(y=y_train)
y_pred = pipe.predict(fh=[1, 2, 3])
```
Output:
```
ValueError: `X` must be passed to `predict` if `X` is given in `fit`.
```
**Expected behavior**

The expected behavior is that `X` is also computed in the predict step similar to the fit.  

**Additional context**

I'm working with the sktime-dev installation including the changes from (https://github.com/sktime/sktime/pull/5656)

**Versions**
<details>

System:
    python: 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
executable: [c:\Users\user\anaconda3\python.exe](file:///C:/Users/user/anaconda3/python.exe)
   machine: Windows-10-10.0.22621-SP0

Python dependencies:
          pip: 22.3.1
       sktime: 0.25.0
      sklearn: 1.0.2
       skbase: 0.6.1
        numpy: 1.23.5
        scipy: 1.9.3
       pandas: 1.4.4
   matplotlib: 3.6.2
       joblib: 1.1.1
        numba: 0.56.4
  statsmodels: 0.14.1
     pmdarima: 2.0.4
statsforecast: 1.7.1
      tsfresh: None
      tslearn: None
        torch: 1.13.1+cpu
   tensorflow: None
tensorflow_probability: None

</details>

### PR DESCRIPTION
**Pull request by benHeid**
Fix pipeline.predict if inner X are derrived by y by not emptying the buffer of the y dummy step.

#### Reference Issues/PRs
Fixes #5830 

#### What does this implement/fix? Explain your changes.
Avoid to empty the buffer if no new data is arriving during `predict` call. 

#### Does your contribution introduce a new dependency? If yes, which one?
No

#### Did you add any tests for the change?

* [x] TODO
##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

### CODE REVIEW

**Comment by benHeid** [comment]
TODO
* [ ] Add test

**Comment by fkiraly** [comment]
ready for review?

**Comment by benHeid** [comment]
Yes

**Review by fkiraly — CHANGES_REQUESTED** [review]
Could you kindly explain why this is a fix? I can't quite link the change to the bug.

**Comment by fkiraly** [comment]
So, the buffers remember data from `fit`?

**Comment by benHeid** [comment]
> So, the buffers remember data from `fit`?

yes

**Review by fkiraly — APPROVED** [review]
Discussed today - this patches the use case, but there is a wider discussion on transformations that do not produce a transformed series of the same index.

That is taking place in this issue: https://github.com/sktime/sktime/issues/5879

**Pull request merged**
