### PR TITLE
[BUG] fixed `dask.dataframe` import error in dask_to_pd.py script

### LINKED ISSUE #7250: [BUG] AttributeError: module 'dask' has no attribute 'dataframe' when using ARIMA
**Describe the bug**
When fitting an ARIMA model with a 3D numpy array, I receive the error described aboce.

**To Reproduce**

```python
import sktime.forecasting.arima
from sktime.datatypes import get_examples

model = sktime.forecasting.arima.ARIMA()
data = get_examples(mtype="numpy3D", as_scitype="Panel")[0]
model.fit(data)
```

**Expected behavior**
As the input data format should be fine, I expect the model to fit.

**Additional context**
`import dask.dataframe` should be added in the `check_dask_frame() `function in the `dask_to_pd.py` script

**Versions**

System:
python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
executable: /home/josef/Schreibtisch/slope_forecast/venv/bin/python3
machine: Linux-6.5.0-14-generic-x86_64-with-glibc2.35

Python dependencies:
         pip: 23.0.1
       sktime: 0.33.1
      sklearn: 1.3.0
       skbase: 0.8.3
        numpy: 1.24.4
        scipy: 1.11.1
       pandas: 2.1.4
   matplotlib: 3.7.2
       joblib: 1.2.0
        numba: None
  statsmodels: 0.13.2
     pmdarima: 2.0.1
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: 1.12.1
   tensorflow: 2.10.0

### PR DESCRIPTION
**Pull request by sanskarmodi8**
Closes #7250 by adding missing import statement in `check_dask_frame`.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks!

Could we perhaps do the check directly instead? I.e.,

```python
import dask.dataframe as dd

if not isinstnace (obj, dd.DataFrame)
```

I suspect the "core" path is not stable across versions.

**Comment by sanskarmodi8** [comment]
> Thanks!
> 
> Could we perhaps do the check directly instead? I.e.,
> 
> ```python
> import dask.dataframe as dd
> 
> if not isinstnace (obj, dd.DataFrame)
> ```
> 
> I suspect the "core" path is not stable across versions.

Thanks for the suggestion. I have done the changes accordingly.

**Comment by fkiraly** [comment]
Is there a test that we could add? None of the tests on `main` are failing, but it is best practice to have a test.

Is it perhaps only on lower `dask` versions?

**Comment by sanskarmodi8** [comment]
> Is there a test that we could add? None of the tests on `main` are failing, but it is best practice to have a test.
> 
> Is it perhaps only on lower `dask` versions?

Without import dask.dataframe statement it was failing on both of the 2 versions I tried - 2024.9.1 and 2024.8.0.
I am working to add the test accrodingly.

**Comment by sanskarmodi8** [comment]
I have added the test for this. Are we good now?

**Comment by fkiraly** [comment]
hm, it is strange that this does not fail in the tests.

The code in question should be called in `datatypes.tests.test_check`, from the test `test_check_positive` - could you verify?

**Review by fkiraly — CHANGES_REQUESTED** [review]
Have you actually run the code you added to the test?

It will break for two reasons: `pd` is not imported, and you are trying to unpack four returns from `check_dask_frame`, but it has only three.

Is this AI generated code?

Further, I have run a corrected version of the test code in the test on current `main`, that is, without the alleged fix. 

Nothing breaks, so I think you might not have identified the correct failure condition yet.

Can you please make sure:

* the test code runs after the fix
* the test code fails before the fix

Thanks

**Comment by sanskarmodi8** [comment]
> Have you actually run the code you added to the test?
> 
> It will break for two reasons: `pd` is not imported, and you are trying to unpack four returns from `check_dask_frame`, but it has only three.
> 
> Is this AI generated code?
> 
> Further, I have run a corrected version of the test code in the test on current `main`, that is, without the alleged fix.
> 
> Nothing breaks, so I think you might not have identified the correct failure condition yet.
> 
> Can you please make sure:
> 
> * the test code runs after the fix
> * the test code fails before the fix
> 
> Thanks

Thanks for noticing. I am working on it.

**Comment by sanskarmodi8** [comment]
I have corrected the test and it correctly fails on running `pytest sktime/datatypes/_adapter/tests/test_dask_pd.py` without the fix and runs successfully after the fix.

**Review by fkiraly — APPROVED** [review]
Looks good, thanks!

**Comment by sanskarmodi8** [comment]
> Looks good, thanks!

Your welcome 😀

**Pull request merged**
