### PR TITLE
[DOC] added new slack link

### PR DESCRIPTION
**Pull request by hadifawaz1999**
##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Review by miraep8 — APPROVED** [review]
🎉 🎉 🎉

**Comment by MatthewMiddlehurst** [comment]
Both links work for me, are people having issues with the previous one?

**Comment by miraep8** [comment]
@MatthewMiddlehurst yes I had at least one person besides Ali tell me that the old link was broken, and we also confirmed with them that this new link works! I agree though - from someone who is already in the slack channel it is hard to tell that the old link doesn't work - one way to tell (I think) is if you try to use the old link in incognito mode you should get the error that new users were experiencing. 

On a plus side this new link should "never expire" or at least that is what slack told me when I made it, so hopefully we don't run into this problem again.

**Review by MatthewMiddlehurst — APPROVED** [review]

**Comment by hadifawaz1999** [comment]
@MatthewMiddlehurst yes I actually tried the link for the first time and did not work for me but it did using the new link that was provided to me. Before adding the new link I noticed that the old one is working for me now (after that I have joined the slack) so I tested it in a FireFox private tab and it did not work, such as @miraep8 explained. After adding the new one I tested it and it works.

**Comment by fkiraly** [comment]
🎉 , welcome @hadifawaz1999 !

**Pull request merged**
