### PR TITLE
[ENH] Shapelet transform interfacing pyts 

### LINKED ISSUE #5399: [ENH] F-Stat as an optional quality measure for ShapeletTransformClassifier
**Is your feature request related to a problem? Please describe.**
Hills et al 2014 claim F-stat measure is both faster and more discriminative  than information gain. It would be nice to have it as an option for the classifier and the transforms in general.

**Describe the solution you'd like**
Add quality_measure as a parameter to the shapelet-related classes, add f-stat as an option next to information_gain (and other quality measures ideally) and replace uses and calculations of the information gain with the quality measure given from the parameter. Now the classes seem to all be hard coded to use information gain.

### PR DESCRIPTION
**Pull request by Abhay-Lejith**
#### Reference Issues/PRs

This fixes #5399 .

#### What does this implement/fix? Explain your changes.

This implements a Shapelet Transformer which interfaces pyts.
#### Does your contribution introduce a new dependency? If yes, which one?
No.

#### Did you add any tests for the change?
Yes.

##### For all contributions
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [x] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [x] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [x] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Comment by Abhay-Lejith** [comment]
Also unable to fit the new transformer. 
```python
from sktime.transformations.panel.shapelet_transform import ShapeletTransformPyts
from sktime.datasets import load_gunpoint
X_train, y_train = load_gunpoint(split="TRAIN")
trf = ShapeletTransformPyts() 
trf.fit(X_train,y_train)
```
Gives this error:
```
TypeError: Unsupported input data type in ShapeletTransformPyts, input y must be in an sktime compatible format. Allowed scitypes for y in transformations depend on X passed. Passed X scitype was Panel, so allowed scitypes for y are Panel.
```

But load_gunpoint returns `nested_univ` for `X` which is `Panel` and `np.ndarray` for `y` which is `Series`. Not sure about what to do here.

**Comment by fkiraly** [comment]
`y` is acutally `Table` (or `Primitives`).

The error maybe comes from you misspelling the `X_inner_mtype` tag, it should start with a capital letter. 

The tag for table-shaped numpy is `numpy1D` or `numpy2D`, see `ShapeletTransform`.

**Comment by Abhay-Lejith** [comment]
> `y` is acutally `Table` (or `Primitives`).
> 
> The error maybe comes from you misspelling the `X_inner_mtype` tag, it should start with a capital letter.
> 
> The tag for table-shaped numpy is `numpy1D` or `numpy2D`, see `ShapeletTransform`.

After making these changes, I am now getting a different error:
```
TypeError                                 Traceback (most recent call last)
File ~/.local/lib/python3.10/site-packages/pandas/core/series.py:230, in _coerce_method.<locals>.wrapper(self)
    229     return converter(self.iloc[0])
--> 230 raise TypeError(f"cannot convert the series to {converter}")

TypeError: cannot convert the series to <class 'float'>

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
/tmp/ipykernel_12008/260219713.py in ?()
      1 from sktime.transformations.panel.shapelet_transform import ShapeletTransformPyts, ShapeletTransform
      2 from sktime.datasets import load_unit_test
      3 X_train, y_train = load_unit_test(split="TRAIN")
      4 trf = ShapeletTransformPyts()
----> 5 trf.fit(X_train,y_train)
      6 
      7 
      8 

~/sktime/sktime/transformations/base.py in ?(self, X, y)
    494         vectorization_needed = isinstance(X_inner, VectorizedDF)
    495         self._is_vectorized = vectorization_needed
    496         # we call the ordinary _fit if no looping/vectorization needed
...
   1999         if (
   2000             astype_is_view(values.dtype, arr.dtype)
   2001             and using_copy_on_write()

ValueError: setting an array element with a sequence.
```
Not quite sure what's happening here. Is it because `X_train` is a `nested_univ` where each instance is a `pd.Series` ? But since that's how it's being loaded using load_unit_test, should we convert it to some other form before passing it to fit?

**Comment by Abhay-Lejith** [comment]
I need to create a `tests` subfolder within the `shapelet_transform` folder and move `test_shapelet_transform.py` into it as well right?
And I also have to create a new test py file for the ShapeletTransformPyts ?

**Comment by fkiraly** [comment]
Not necessarily "have to", but imo it's a good idea!
That way the tests are organized better.

**Comment by yarnabrina** [comment]
Note: failed jobs match https://github.com/sktime/sktime/issues/6094 exactly, but 3.9 had some extra failures corresponding Shapelet I believe. Can you please check the logs here?

https://github.com/sktime/sktime/actions/runs/8213559495/job/22465465416#step:10:2093

**Comment by Abhay-Lejith** [comment]
The few extra failures seem to be coming from some problem in one of the tests(`TestAllEstimators`::`test_non_state_changing_method_contract` ) when `array_equal` which is a numpy source function is called. I'm not very familiar with how the tests are implemented and it seems to go a bit deep so I'm not really able to figure out what exactly the issue is.

**Comment by Abhay-Lejith** [comment]
The few extra failures seem to be coming from some problem in one of the tests(`TestAllEstimators`::`test_non_state_changing_method_contract` ) when `array_equal` which is a numpy source function is called. I'm not very familiar with how the tests are implemented and it seems to go a bit deep so I'm not really able to figure out what exactly the issue is.

**Comment by fkiraly** [comment]
> and it seems to go a bit deep so I'm not really able to figure out what exactly the issue is.

Something in the estimator produces nested `np.arrays`, and the tests don't expect that weird type.

Ultimately, they would be testing that there are no side effects etc, but sth produces nested `numpy`.

If you can isolate the failure better, I can look into this.

**Comment by Abhay-Lejith** [comment]
Ok so I've managed to narrow it down a bit further. Essentially in this test, we are trying to compare the dict of the estimator attributes before and after transform.
Initially in the test function: (from logs)
```
dict_after = {'_config_dynamic': {'backend:parallel': None, 'backend:parallel:params': None, 'check_clone': False, 'clone_config': True, ...}, '_converter_store_X': {}, '_is_fitted': True, '_is_vectorized': False, ...}
dict_before = {'_config_dynamic': {'backend:parallel': None, 'backend:parallel:params': None, 'check_clone': False, 'clone_config': True, ...}, '_converter_store_X': {}, '_is_fitted': True, '_is_vectorized': False, ...}
```
This is passed to the `deep_equals` function which passes it on to `deep_equals_custom` and then to `_dict_equals`.
Now while extracting the values of the dict using xi = x[keys] and similarly for y , the following output is obtained as seen in logs.
```
x          = {'_config_dynamic': {'backend:parallel': None, 'backend:parallel:params': None, 'check_clone': False, 'clone_config': True, ...}, '_converter_store_X': {}, '_is_fitted': True, '_is_vectorized': False, ...}
xi         = array([array([0.16914503, 0.3726148 ]), array([0.30599427, 0.35772757]),
       array([0.0326517 , 0.59138912]),
     ...5]),
       array([0.00114001, 0.50747685]), array([0.0262576]),
       array([0.01370503, 0.62347828])], dtype=object)
xkeys      = {'_config_dynamic', '_converter_store_X', '_is_fitted', '_is_vectorized', '_pyts_shapelet_transform', '_tags_dynamic', ...}
y          = {'_config_dynamic': {'backend:parallel': None, 'backend:parallel:params': None, 'check_clone': False, 'clone_config': True, ...}, '_converter_store_X': {}, '_is_fitted': True, '_is_vectorized': False, ...}
yi         = array([array([0.16914503, 0.3726148 ]), array([0.30599427, 0.35772757]),
       array([0.0326517 , 0.59138912]),
     ...5]),
       array([0.00114001, 0.50747685]), array([0.0262576]),
       array([0.01370503, 0.62347828])], dtype=object)
ykeys      = {'_config_dynamic', '_converter_store_X', '_is_fitted', '_is_vectorized', '_pyts_shapelet_transform', '_tags_dynamic', ...}
```
`xi` and `yi` have become some form of nested array and this when passed to the numpy `array_equal` function is causing an error. Ideally I think it is supposed to return the inner dicts which are then recursively checked for equality by the _dict_equals function.

**Comment by fkiraly** [comment]
> Ideally I think it is supposed to return the inner dicts which are then recursively checked for equality by the _dict_equals function.

Yes, you are probably right - the "equals" plugin assumes only flat `numpy` array, no nesting. There is clearly a lack of error or assumption catching here.

What is really strange why this nested object appears - and why it appears only on a specific OS/version combination.

So, while there *is* some lack of coverage in `deep_equals` for nested numpy, imo nested numpy should never occur if everything is doing its job.

I suspect there is a second, more consequential bug, either in the `sktime` boilerplate logic, or `pyts` itself.

**Comment by fkiraly** [comment]
PS: if we were to extend `deep_equals`, the place would be `skbase`.

Here's another, very recent example of fixing an uncovered type condition, by @MBristle:
https://github.com/sktime/skbase/pull/290

**Comment by Abhay-Lejith** [comment]
Is it really an issue with deep_equals though? Because the error is somehow only occurring on the test-unix-pandas1 with python3.9. It doesn't occur on the older 3.8 or the later versions. What could potentially be a reason for this?

**Comment by fkiraly** [comment]
> Is it really an issue with deep_equals though?

I think there is *at least* such an issue, since it is triggered by nested numpy. I would be guessing that whenever `deep_equals` receives nested numpy, it will crash. But I would also guess this is not the main problem, just a secondary phenomenon, since nested numpy should not be created in the first place imo.

Conversely, the condition that triggers nested numpy is either *sporadic* (i.e., occurs at random once in a while), or specific to pandas 1, python 3.9. I would guess that this condition and subsequent behaviour are the actual root problem.

Typically, if a failure occurs only in one very specific version/OS combination, it is something to do with a specific version/OS - could be of packages, or of python - or it is random, e.g., it occurs every 20th time, so for a typical test run you observe it once or twice or not at all. To distinguish the two, you re-run the tests and see whether the failure changes location.

**Comment by Abhay-Lejith** [comment]
The previous time the error occurred four times. Now after re-running the test, it's occurred only twice. Can we conclude that it is random then? Or is another run of the test required?

**Comment by fkiraly** [comment]
> Can we conclude that it is random then? Or is another run of the test required?

Yes, I would say it is both sporadic, and tied to the condition "pandas 1". These are the most unpleasant kinds of errors. Just to be safe that we got the condition right, I'm going to re-run all tests.

The way to debug would be to guess the condition right, and then set up a script with lots of repetitions, optimally one that reports the random seed if that's relevant. The estimator has `random_state`, so you could just loop through integers until you find one where the error occurs on your local system.

**Comment by fkiraly** [comment]
PS: this is normal, although things like this occur at random. Often, packages from the fragmented time series ecosystem are less stringently maintained and tested, so you get sporadic stuff like this. Sometimes we directly compensate in `sktime`, another option is to report the bug in the upstream repository - this tends to be an interesting experience, they then think what kind of black magic we employ to find failures under very specific conditions (where all we do is, of course, systematic testing).

Ofc, it's not yet certain this is a bug in `pyts`, we'll need to investigate.

**Review by fkiraly — APPROVED** [review]
Great addition, all tests seem to pass now

**Pull request merged**
