### PR TITLE
[DOC] added fork usage recommendations

### PR DESCRIPTION
**Pull request by yarnabrina**
added recommendations about contribution from forks

1. avoid modifying `main`
2. use dedicated branches from `main` for separate tasks
3. delete merged local and remote branches in forks
4. use new branch from existing branch only if the new task depends on old task and old task PR is not merged yet

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Great!

I would request to add a new subsection, "managing branches:"

* point 13, I would make it the basis of the new subsection, "managing branches".
* I would also move point 12 there, and importantly, not have it as a numbered point, but perhaps a second bullet point.

This is from a perspective of a new, semi-confused contributor. If you read the points only with half attention, this may lead to a premature deletion by accident. You could move it to the section suggested below

Having less steps also makes it look friendlier.

**Comment by yarnabrina** [comment]
Ref. https://sktime--6827.org.readthedocs.build/en/6827/developer_guide/git_workflow.html

image

**Comment by fkiraly** [comment]
@yarnabrina, I've made some changes that I consider improvements, please have a look.

When you said "repeat steps 7-11", I realized that the steps at the start were mixing first-time with every-time instructions, so I split that section in two, and added clarifications.

I also structured the new section into two.

Please let me know what you think, and feel free to change or revert.

**Comment by yarnabrina** [comment]
I'm okay with new changes. RTD CI was failing, not sure why. Rebasing from `main` to update the branch plus to retrigger the CI.

**Comment by fkiraly** [comment]
I think the RTD failures are sporadic and related to long build times, see here:
https://github.com/sktime/sktime/issues/6772

In case you have any ideas how to reduce RTD build times.

We got test times down, so that might ultimately also be manageable...

**Review by fkiraly — APPROVED** [review]

**Pull request merged**
