### PR TITLE
[BUG] fix `ExpandingCutoffSplitter` for case where `fh` is not continuous

### PR DESCRIPTION
**Pull request by ninedigits**
#### What does this implement/fix? Explain your changes.

Fixes bug where existing ExpandingCutoffSplitter assumed `fh` was continuous. 

See: https://github.com/sktime/sktime/blob/58615b694cc2928fbbc7fd5e82bdf0adb337d1d1/sktime/split/expandingcutoff.py#L127

#### Did you add any tests for the change?
Yes. See the following pytest added to `sktime/split/tests/test_expandingcutoff.py`:
```python3
def test_expandingcutoff_fh():
    """Test different forecast horizon configurations"""
    # Datetime cutoff
    y = _make_series(n_timepoints=10, index_type="period", random_state=42)
    fh_configs = ([1], [1, 2, 3], [4], [2, 4])
    for _fh in fh_configs:
        fh = ForecastingHorizon(_fh)
        index_num = 3
        cutoff = y.index[index_num]

        # Behavior of cutoff and window splitter should be identical in this scenario
        cv1 = ExpandingCutoffSplitter(cutoff=cutoff, fh=fh, step_length=1)
        cv2 = ExpandingWindowSplitter(initial_window=index_num, fh=fh, step_length=1)

        splits1 = list(cv1.split(y))
        splits2 = list(cv2.split(y))

        for (split_train_a, split_test_a), (split_train_b, split_test_b) in zip(
            splits1, splits2
        ):
            np.testing.assert_array_equal(split_train_a, split_train_b)
            np.testing.assert_array_equal(split_test_a, split_test_b)
```
The existing `ExpandingCutoffSplitter` fails this test, as it only accounts for continuous forecast horizons that start at 1.

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
This is quite subtle! Well spotted!

Though, it looks like it accidentally reverts your fixes to the docstring formatting...

**Comment by ninedigits** [comment]
> Though, it looks like it accidentally reverts your fixes to the docstring formatting...

This was actually intentional. Looks like it didn't render even with the triple back ticks. 
https://www.sktime.net/en/latest/api_reference/auto_generated/sktime.split.ExpandingCutoffSplitter.html

What I did instead was copy the format of ExandingWindowSplitter.

https://github.com/sktime/sktime/blob/4ec47811a42c24e2d6b0020944d8f2524871b704/sktime/split/expandingwindow.py#L37-L46

**Review by fkiraly — CHANGES_REQUESTED** [review]
I see - this is removing the "c" indicator though, somehow?

**Comment by ninedigits** [comment]
> I see - this is removing the "c" indicator though, somehow?

It is, I wasn't sure if that was creating more problems that it was solving. You think we should keep it? I suppose it's useful to point out visually where the cutoff value is.

**Comment by fkiraly** [comment]
yes, I think it is helpful to the reader - I hope we can restore it somehow, and also manage to display this properly...

**Comment by ninedigits** [comment]
Added it back in. Is there a way to tell if it will render before committing?

**Comment by fkiraly** [comment]
> Added it back in. Is there a way to tell if it will render before committing?

Yes, you can see a full build of the docs if you go on "details" of the docs job:

image

**Review by fkiraly — DISMISSED** [review]

**Review by fkiraly — APPROVED** [review]
Thanks! I fixed the docstring formatting.

**Pull request merged**
