### PR TITLE
[MNT] speed improvement of `partition_based_clustering` notebook

### LINKED ISSUE #5041: [ENH] speed up notebooks and notebook tests
It seems the notebooks in `examples` take 50min to run, all taken together.

I remember times where this was closer to 20min - we should investigate where runtime is spent in the notebooks, and optimally replace by faster examples that illustrate the same point(s).

Good first issue - simply go through the notebooks, run them and check which cells take longest.

There are also a number of more "obscure" notebooks, we may consider removing them, or shortening them, or making the data sets smaller.

### PR DESCRIPTION
**Pull request by alexfilothodoros**
#### What does this implement/fix? Explain your changes.

This PR is making `examples/partition_based_clusterting` faster

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

### CODE REVIEW

**Comment by fkiraly** [comment]
I see, thanks! Perhaps, could you add the `dtw` option in comments, I feel the user might look for time warping as a basic option, and it is good to spell it out, even if the code is not executed.

**Comment by fkiraly** [comment]
Thanks!

Could you kindly explain what is happening with the forecasting notebook?
I would also advise, let's make different notebooks different pull requests, to avoid interactions and separate discussion. That way we merge content independently, and faster.

**Comment by alexfilothodoros** [comment]
Hi @fkiraly 

Yes you are absolutely right. Just the changes in the forecasting notebook were so small I thought I'd just commit them here.

These changes are a left over from https://github.com/sktime/sktime/pull/5169

The same changes, like now, were introduced but diff was huge.

**Comment by fkiraly** [comment]
> The same changes, like now, were introduced but diff was huge.

Sure - would be great if you could split this into two pull requests.

**Comment by alexfilothodoros** [comment]
Sure!
For now I replaced the forecasting notebook with the previous version.

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks.

Could you replace the valuative "is a better option" (only under certain conditions and dependent on the data!) with sth like `or "dtw" for dynamic time warping`

**Review by fkiraly — APPROVED** [review]
Thanks!

**Pull request merged**
