### PR TITLE
[BUG] fix wrong setting of `failed_at_step` in `FallbackForecaster`

### PR DESCRIPTION
**Pull request by yarnabrina**
Fixes https://github.com/sktime/sktime/pull/5779#discussion_r1466764459

### CODE REVIEW

**Comment by yarnabrina** [comment]
FYI @ninedigits , @fkiraly

**Review by ninedigits — APPROVED** [review]
Looks good to me. Sorry for missing this!

**Comment by fkiraly** [comment]
Thanks - the release has not finished yet, so I've aborted and will ship with this.

**Comment by fkiraly** [comment]
apologies for overlooking

**Pull request merged**
