### PR TITLE
[BUG] In `plot_series`, trim unused levels when verifying dataframe formatting

### PR DESCRIPTION
**Pull request by SultanOrazbayev**
This resolves the issue with pandas holding on to the unused levels after subsetting the dataframe, see https://github.com/sktime/sktime/discussions/6753 for an example.

### CODE REVIEW

**Comment by fkiraly** [comment]
Hm, interesting - could you expand on which levels exactly remain in there, unused?

I am wondering whether this issue is more general, maybe we should requires as part of the contract that returned multiindices contain no unused levels? That is:

* in the contract checkers, in `datatypes._proba._check`, assert that there are no unused levels
* in the `BaseForecaster` `predict_interval` and `predict_quantiles`, do `remove_unused_levels` as suggested in this PR

The `check_interval_df` utility should not mutate if I understand correctly.

**Comment by SultanOrazbayev** [comment]
Thanks for the quick response!

I wouldn't consider this to be a mutation, since this change is isolated to the check itself and will not propagate to the original. However, the origin of the issue is old (e.g. see this thread https://github.com/pandas-dev/pandas/issues/2770), somehow it's a feature and not a bug.

**Comment by SultanOrazbayev** [comment]
Moving this to `predict_interval` and `predict_quantiles` will not resolve the issue, if I understand correctly. In the original question by Sakai #6753 , we would still have all the levels at the `predict_interval` stage (so there wouldn't be any unused levels to drop).

**Comment by fkiraly** [comment]
I see - this happens only in the plotting function, then?

**Comment by fkiraly** [comment]
Could you also kindly add your failing case as a `pytest` test? (or sth that covers the same issue)

Just copy it into one of the test files in a test function, following the pattern. We should test that it does not break.

**Review by fkiraly — CHANGES_REQUESTED** [review]
requesting addition of a test certifying for the bug being fixed, see above

**Review by fkiraly — CHANGES_REQUESTED** [review]
also, the CI test run indicates that the change - while fixing your case - breaks another case from the notebooks.

I think it is because `FrozenList` does not have `remove_unused_levels`, so there may have to be a case distinction to make on mutable and immutable levels.

I also think we should add the notebook case as a test, this dooes not seem covered by the main CI

**Comment by SultanOrazbayev** [comment]
Thanks for the feedback, @fkiraly ! I converted this PR to draft and will work on these changes.

**Comment by SultanOrazbayev** [comment]
@fkiraly : Hello, Franz, this is ready for review now.

**Review by fkiraly — DISMISSED** [review]
Looks good to me!

FYI @benHeid, as author of the plotting utility

**Comment by SultanOrazbayev** [comment]
Fixed the failing test by checking for the dependencies.

**Review by fkiraly — APPROVED** [review]
Ready to merge for the release.

**Review by fkiraly — APPROVED** [review]

**Pull request merged**
