### PR TITLE
[ENH] forecasting compositor to ignore exogenous data

### PR DESCRIPTION
**Pull request by fkiraly**
This PR adds `IgnoreX`, a forecasting compositor that allows a user to control whether exogenous data is ignored.

As indirectly requestd by @hliebert in https://github.com/sktime/sktime/discussions/5768

### CODE REVIEW

**Review by yarnabrina — CHANGES_REQUESTED** [review]
I think we should have a test to confirm that `X` is unused if `ignore_x` is True, and vice versa.

"How" may be a bit tricky though, not sure if there's an easy way to check that.

**Comment by fkiraly** [comment]
I added a test using `MagicMock`, hope that is sufficient?

**Comment by hliebert** [comment]
I've tested this and it works in our setting. Thanks!

**Comment by fkiraly** [comment]
> I'm not familiar with `MagicMock` at all, let me research a bit. But it seems tests are failing in `classification` in old CI.

I suspect some dependency updated and is breaking now?

**Pull request merged**
