### PR TITLE
[MNT] Set torch threads to one (based on main)

### PR DESCRIPTION
**Pull request by benHeid**
#### Reference Issues/PRs
Fixes the segmentation faults in the CI (macOS Runner).  (Not sure, if there is a corresponding issue..)
 
#### What does this implement/fix? Explain your changes.
It set the threads of PyTorch to one. 

Based on some rabbit hole issue and PR reading based on the following entry points:
* https://github.com/pytorch/pytorch/issues/44282
* https://github.com/neuml/txtai/issues/300

### CODE REVIEW

**Comment by benHeid** [comment]
@julian-fong @fkiraly I suppose this is ready for review. No segmentation faults anymore.

Test failures are due to:
* pykan changed their interface #7116 
* DARTS timeouts
* Zip Header file mismatches. Perhaps just random error..
  <details>

  ```
    2024-09-15T07:00:18.4520551Z FAILED sktime/forecasting/tests/test_all_forecasters.py::TestAllForecasters::test_predict_time_index[PytorchForecastingDeepAR-2-y:1cols-fh=1-period-int-True] - RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted
  2024-09-15T07:00:18.4522967Z FAILED sktime/forecasting/tests/test_all_forecasters.py::TestAllForecasters::test_update_predict_predicted_index[PytorchForecastingDeepAR-3-y:1cols-update_params=True-5-fh=[2 5]] - RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted
  ```
  </details>


Before merge, wait on PR #7122  and check if there is also no segmentation fault.

**Comment by benHeid** [comment]
> Before merge, wait on PR #7122 and check if there is also no segmentation fault.

PR #7122 looks good as well :)

**Review by fkiraly — CHANGES_REQUESTED** [review]
This may fix the segfaults on CI, but we need to be careful as the module is imported whenever a user calls `check_estimator`, and potentially on other occasions. This might inadvertently set the num_threads for them, which seems like an unintended side effect.

We need to address this, or at least explain it away.

If this is indeed an issue for the user condition, we could try:

* if it is specific to one estimator, do this in `get_test_params` perhaps?
* if it is specific to all `torch` estimators, we need to identify the exact condition when we want to do this - only at test time, or everytime? If only at test time, the right place might be in one of the test classes, or linked to the pytest conf.

**Comment by benHeid** [comment]
Mhm I agree. We might also try to set instead the environment variable OMP_Num_THreads. Perhaps this is sufficient as a fix. However would disable it also for non torch CI runs.

**Comment by benHeid** [comment]
Preferred solution is to set OMP_NUM_THREADS

**Pull request closed without merging**
