### PR TITLE
[ENH] Add tecator dataset for time series regression as `sktime` onboard dataset

### PR DESCRIPTION
**Pull request by JonathanBechtel**
#### Reference Issues/PRs
https://github.com/sktime/sktime/issues/4314
#5322 

#### What does this implement/fix? Explain your changes.
It adds a time series regression dataset to the dataset repository, which is currently missing.  

#### Does your contribution introduce a new dependency? If yes, which one?
No

#### What should a reviewer concentrate their feedback on?
This PR is a direct continuation of #5322, but I don't think any of its changes made it through to the PR it got merged with.  

With that said, here are the changes made from that PR:

 - Added citations to the docstring of `load_tecator`
 - Added the dataset while avoiding making any changes to the ts specification.  I hadn't realized that @achieveordie  had already accounted for regression datasets with the `targetLabel` tag, which I wasn't aware of last time.

So overall this is a cleaner implementation since it leaves everything else alone.

#### Did you add any tests for the change?
I added `load_tecator` to the UNIVARIATE list in `test_single_loaders.py` so it could be included in the current set of unit tests for `.ts` files.

### CODE REVIEW

**Comment by fkiraly** [comment]
> I don't think any of its changes made it through to the PR it got merged with.

It looks like #5322 accidentally got corrupted in a merge of yours locally, e.g., it shows 1000 files changed.

I pushed a recovered version of the PR prior to that here: https://github.com/sktime/sktime/pull/5429
I think your changes should have made it through the merge with the refactor.

FYI, this PR seems to e missing the extension to the loader logic.

**Comment by JonathanBechtel** [comment]
@fkiraly It turns out the loader logic didn't need to be changed.  You can add the label `@targetLabel` to specify a regression dataset.  I just didn't know it existed because it's not used anywhere.  But this PR:  https://github.com/sktime/sktime/pull/3436 already did the same thing, so there's no need to re-invent the wheel.

**Comment by fkiraly** [comment]
> Any chance these failed tests are upstream of this PR?

Yes, they were caused upstream and solved by this: https://github.com/sktime/sktime/pull/5434

If you regularly update from `main`, you have a greater chance to evade these...

**Comment by JonathanBechtel** [comment]
> > Any chance these failed tests are upstream of this PR?
> 
> Yes, they were caused upstream and solved by this: #5434
> 
> If you regularly update from `main`, you have a greater chance to evade these...

Is there a recommended course of action I ought to take to satisfy the failed tests?

**Comment by fkiraly** [comment]
> Is there a recommended course of action I ought to take to satisfy the failed tests?

These are not on you, but failing in other parts of the code base - @yarnabrina and I are working on fixing, or at least separating these so they do not annoy contributors...

**Review by fkiraly — APPROVED** [review]
Seems fine now - sorry for the corruption from the merge sequence.

**Pull request merged**
