### PR TITLE
[MNT] Fix linting issues in transformations module

### PR DESCRIPTION
**Pull request by SamiAlavi**
#### Reference Issues/PRs
#4182

#### What does this implement/fix? Explain your changes.
- Fix B028 No explicit stacklevel keyword argument found
- Fix pydocstyle errors (D103, D100, D200, D403, D205, D400, D401, D410, D411)

#### Does your contribution introduce a new dependency? If yes, which one?
No

#### What should a reviewer concentrate their feedback on?
- [ ] B028 No explicit stacklevel keyword argument found
- [ ] pydocstyle errors (D103, D100, D200, D403, D205, D400, D401, D410, D411)

#### Did you add any tests for the change?
No

#### Any other comments?
No

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by fkiraly** [comment]
Well, as suspected in #4182 - it wants *all* linting issue fixed in files that are touched. Not sure though, some of these seem like `isort` issues which should get fixed automatically?

**Comment by SamiAlavi** [comment]
Yeah. I'll push a commit for the auto fixes for this module in this PR, and then create another PR for all other auto fixes.

**Comment by SamiAlavi** [comment]
There are `flake8` errors, for which I'm not sure what to do. If we fix these errors, then there are multiple errors related to docstrings. Should we ignore the error in these lines?

```
sktime/transformations/panel/signature_based/_window.py:24:89: E501 line too long (101 > 88 characters)
sktime/transformations/panel/signature_based/_window.py:128:89: E501 line too long (91 > 88 characters)
```

The `docstring` might have to be updated for the below modules since currently I do not have the necessary knowledge about the working of those modules.

- `sktime/transformations/__init__.py`
- `sktime/transformations/panel/__init__.py`
- `sktime/transformations/panel/dictionary_based/tests/__init__.py`
- `sktime/transformations/panel/signature_based/__init__.py`
- `sktime/transformations/panel/signature_based/tests/__init__.py`
- `sktime/transformations/panel/summarize/tests/__init__.py`
- `sktime/transformations/panel/tests/__init__.py`
- `sktime/transformations/series/tests/__init__.py`

**Comment by fkiraly** [comment]
> Should we ignore the error in these lines?

I'm not sure what is going on in the errors, are these long lines in docstrings?
If yes, you can see whether you can introduce a line break; if that breaks the formatting, add a ` # noqa: E501` to the end of the line to silence it.

> I do not have the necessary knowledge about the working of those modules.

I would suggest, go with the "minimum" docstring, something like `sktime.transformations.panel module` - this is better than no docstring and can always be filled in.

**Review by fkiraly — APPROVED** [review]
NICE!

Thanks a lot, this must have taken quite some time to go through, much appreciated!

**Comment by SamiAlavi** [comment]
No problem. Yes, this module had the most linting issues.

**Pull request merged**
