### PR TITLE
[BUG] Fix wrong tag in FeatureSelection and add tests

### PR DESCRIPTION
**Pull request by aiwalter**
#### What does this implement/fix? Explain your changes.
A tag was set wrongly in `FeatureSelection` as it can also return `None` in `transform` if `method="none"`.
Added unit tests for `FeatureSelection`

#### Does your contribution introduce a new dependency? If yes, which one?

No

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
I think the tag is currently set up that it can return only one scitype. This will surely break things.

Can you give an example where what is returned is not a `Series`?
In the empty case, should be an empty container then.

**Comment by aiwalter** [comment]
The custom tests were passing but might be that the generic tests are failing. If we do `FeatureSelection(method="none")` then its basically dropping all features by setting `X=None` which is a `Primitive`?

**Comment by aiwalter** [comment]
Example:
```python
from sktime.datasets import load_longley
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.transformations.series.feature_selection import FeatureSelection

y, X= load_longley()
y_train, y_test, X_train, X_test = temporal_train_test_split(y, X, test_size=3)
t = FeatureSelection(method='none')
t.fit(X_train)
X_hat = t.transform(X_test)
X_hat is None
```

**Review by fkiraly — CHANGES_REQUESTED** [review]
Can you please describe what `FeatureSelection` will do?

Given what condition on parameters and inputs, what output will be returned?

It should be described in the docstring at least, and I'm not sure whether it makes sense at all to have an output polymorphic transformer.

**Comment by aiwalter** [comment]
closing due to #4153

**Comment by fkiraly** [comment]
I still haven't understood what this was supposed to be doing, addressing, or why, so I suppose we can leave this one closed.

**Pull request closed without merging**
