### PR TITLE
[MNT] replace author names by GitHub ID in author fields

### LINKED ISSUE #4335: [MNT] Set author names in files to GitHub names
The official style guide [PEP 8](https://peps.python.org/pep-0008/#module-level-dunder-names) provides an example with only one author. However, web archive's page [Python Coding Guidelines 12/14/07](http://web.archive.org/web/20111010053227/http://jaynes.colorado.edu/PythonGuidelines.html#module_formatting) lists multiple authors as comma separated values in __author__ with type str.

We can also list authors like this

https://github.com/sktime/sktime/blob/254427259a21c6a701623c714bd8b025ae51bc2b/extension_templates/forecasting.py#L45-L46

### PR DESCRIPTION
**Pull request by SamiAlavi**
#### Reference Issues/PRs
Fixes #4335

#### What does this implement/fix? Explain your changes.

- `__author__` names to their GitHub IDs
- `__author__` type `str` to `List[str]` for consistency
- use `__author__` instead of `__authors__`

#### Does your contribution introduce a new dependency? If yes, which one?
No

#### What should a reviewer concentrate their feedback on?

- `__author__` names to their GitHub names
- `__author__` type `str` to `List[str]` for consistency
- use `__author__` instead of `__authors__`

#### Did you add any tests for the change?
No

#### Any other comments?
No

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by SamiAlavi** [comment]
- [ ] No authors found in `sktime/utils/_testing/annotation.py`
https://github.com/sktime/sktime/blob/5f1f4016c773924b3511e8f2c1c42e6d589504c3/sktime/utils/_testing/annotation.py#L3

- [ ] Author was already defined at the start of `sktime/classification/distance_based/_proximity_forest.py`. However, it was again defined later in class in the same file.
https://github.com/sktime/sktime/blob/5f1f4016c773924b3511e8f2c1c42e6d589504c3/sktime/classification/distance_based/_proximity_forest.py#L769

- [ ] TODO found in `sktime/transformations/panel/dictionary_based/_sax.py`
https://github.com/sktime/sktime/blob/5f1f4016c773924b3511e8f2c1c42e6d589504c3/sktime/transformations/panel/dictionary_based/_sax.py#L13-L17

**Comment by fkiraly** [comment]
> no authors found

I would advise, look into the coit history of the file, and add the committers to the authors

> authors defined multiple times

I would say, put them in a single list

> todo

not sure - does this cause a linting error?

**Comment by SamiAlavi** [comment]
> not sure - does this cause a linting error?

No, it does not. Found a TODO comment, hence wanted to highlight it here.

**Review by fkiraly — APPROVED** [review]
Thanks a lot for meticulously going through all these files!

**Pull request merged**
