### PR TITLE
[BUG] fix polymorphic estimators missing in estimator overview, e.g., `pytorch-forecasting` forecasters

### LINKED ISSUE #6801: [ENH] `pytorch-forecasting` global forecasters do not appear in estimator overview
The `pytorch-forecasting` based forecasters do not seem to appear in the estimator overview
[estimator overview forecasters](https://www.sktime.net/en/latest/estimator_overview.html#filter=forecaster&tags=%7B%22capability%3Ainsample%22%3Afalse%2C%22capability%3Apred_int%22%3Afalse%2C%22capability%3Apred_int%3Ainsample%22%3Afalse%2C%22handles-missing-data%22%3Afalse%2C%22ignores-exogeneous-X%22%3Afalse%2C%22scitype%3Ay%22%3Afalse%2C%22requires-fh-in-fit%22%3Afalse%2C%22X-y-must-have-same-index%22%3Afalse%2C%22python_dependencies%22%3Atrue%2C%22authors%22%3Afalse%2C%22maintainers%22%3Afalse%7D)

I just tested whether `all_estimators("forecaster")` retrieves them, and it does - which makes this a bit strange, because I thought that python request is what is behind the automated population of the estimator overview.

FYI @benHeid, @Xinyu-Wu-0000

### PR DESCRIPTION
**Pull request by fkiraly**
Fixes #6801, the missing `pytorch-forecasting` forecasters in the forecaster estimator overview. This was a consequence of a more general bug where subsetting specifically for the estimator overview was incorrect for polymorphic, i.e., multi-type estimators.

The reason for the bug was that the estimator overview subsetting reimplemented type subsetting logic in `all_estimators`, and subsetted only to the first type in case there were multiple.
(and `pytorch-forecasting` forecasters are polymorphic, since currently global forecasting is implemented as a separate type, from "ordinary" forecasting)

We should refactor and deduplicate the code in `docs/conf.py`, but for now I've fixed the logic mistake.

### CODE REVIEW

**Review by benHeid — DISMISSED** [review]

**Comment by fkiraly** [comment]
please do not merge yet, this does not seem to work properly

**Comment by fkiraly** [comment]
very strange. I tested the population of `records` manually, in `conf.py`, and can confirm that the pytorch based forecasters are in the list, with `"forecaster"` type. This should correctly filter later when using the dropdown, but they do not appear. Very odd.

Any thoughts, @yarnabrina, @benHeid, @duydl?

**Comment by yarnabrina** [comment]
1. I navigated to <https://sktime--6803.org.readthedocs.build/en/6803/estimator_overview.html>.
2. I changed the drop down from `All` to `Forecaster`.
3. I see the following, containing `PytorchForecastingNBeats` and `PytorchForecastingTFT`

image

Can you please tell me what is the behaviour you are expecting, and how is it wrong here?

**Comment by fkiraly** [comment]
oh, then probably my browser cache is giving the old table still. In that case, it works. Did not think about resetting browser cache.

**Pull request merged**
