### PR TITLE
[ENH] Fix B016 Cannot raise a literal error in `Distances` module

### PR DESCRIPTION
**Pull request by SamiAlavi**
#### Reference Issues/PRs
#4182 

#### What does this implement/fix? Explain your changes.
Fixed B016 Cannot raise a literal. Did you intend to return it or raise an Exception?

#### Does your contribution introduce a new dependency? If yes, which one?
No

#### What should a reviewer concentrate their feedback on?
- [ ] `sktime/distances/_ddtw.py:119:13`: B016 Cannot raise a literal. Did you intend to return it or raise an Exception?
- [ ] `sktime/distances/_ddtw.py:221:13`: B016 Cannot raise a literal. Did you intend to return it or raise an Exception?

#### Did you add any tests for the change?
No

#### Any other comments?
No

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Review by fkiraly — APPROVED** [review]
Great, Thanks!

not a blocker, since this PR is an improvement, but changing this would be appreciated:

I would raise a `TypeError` (and not the very general `Exception`), since this exception seems to be about the type of the arg `compute_derivative`.

**Review by fkiraly — APPROVED** [review]
Thanks!

**Comment by SamiAlavi** [comment]
Hi @fkiraly, is it okay for this PR to get merged? I'm waiting so that I can easily create branches for the fixes in other modules too.

**Comment by fkiraly** [comment]
yes, I was just waiting for the tests to pass.

**Pull request merged**
