### PR TITLE
[MNT] Changed line endings of `ElectricDevices.csv` and `GunPoint.csv` from `CRLF` to `LF`

### PR DESCRIPTION
**Pull request by yarnabrina**
#### Reference Issues/PRs

See also #4446 

#### What does this implement/fix? Explain your changes.

Most datasets in `sktime` have `LF` line endings, except `ElectricDevices.csv` and `GunPoint.csv`. This triggered auto-fix if configured in global gitattributes or global gitconfig. This PR attempts to convert those into `LF` line endings.

##### Before

```console
❯ git ls-files --eol | grep -E "*.csv"
i/lf    w/lf    attr/                   sktime/datasets/data/Airline/Airline.cs
i/lf    w/lf    attr/                   sktime/datasets/data/Longley/Longley.cs
i/lf    w/lf    attr/                   sktime/datasets/data/Lynx/Lynx.csv
i/lf    w/lf    attr/                   sktime/datasets/data/PBS_dataset/PBS_dataset.csv
i/lf    w/lf    attr/                   sktime/datasets/data/ShampooSales/ShampooSales.csv
i/lf    w/lf    attr/                   sktime/datasets/data/Uschange/Uschange.csv
i/mixed w/mixed attr/                   sktime/datasets/data/segmentation/ElectricDevices.csv
i/mixed w/mixed attr/                   sktime/datasets/data/segmentation/GunPoint.csv
i/lf    w/lf    attr/                   sktime/datasets/data/solar/solar.csv
```

##### After

```console
❯ git ls-files --eol | grep -E "*.csv"
i/lf    w/lf    attr/text               sktime/datasets/data/Airline/Airline.csv
i/lf    w/lf    attr/text               sktime/datasets/data/Longley/Longley.csv
i/lf    w/lf    attr/text               sktime/datasets/data/Lynx/Lynx.csv
i/lf    w/lf    attr/text               sktime/datasets/data/PBS_dataset/PBS_dataset.csv
i/lf    w/lf    attr/text               sktime/datasets/data/ShampooSales/ShampooSales.csv
i/lf    w/lf    attr/text               sktime/datasets/data/Uschange/Uschange.csv
i/lf    w/lf    attr/text               sktime/datasets/data/segmentation/ElectricDevices.csv
i/lf    w/lf    attr/text               sktime/datasets/data/segmentation/GunPoint.csv
i/lf    w/lf    attr/text               sktime/datasets/data/solar/solar.csv
```

#### Does your contribution introduce a new dependency? If yes, which one?

No

#### What should a reviewer concentrate their feedback on?

* Does any of the functionality break that is not covered by unit tests?

#### Did you add any tests for the change?

No

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Review by fkiraly — COMMENTED** [review]
Looks simple enough, although the diff says there is a change in 13405 lines.
Can I ask for the clarification: the problem is *in every single line*, not just in the final line?

**Comment by yarnabrina** [comment]
> Can I ask for the clarification: the problem is _in every single line_, not just in the final line?

I would guess so, not certain. To be specific, this is all I did:

1. open old file VS Code
2. change from CRLF to LF in bottom right
3. stage + commit

**Comment by fkiraly** [comment]
hm, I see.

Can I ask what is, to your knowledge, the easiest way to compare the content to be equal pre and post PR?
These are moderatly important benchmarking data sets, so we should avoid changing the content by accident (and I'm not sure how to best check that)

**Comment by yarnabrina** [comment]
> Can I ask what is, to your knowledge, the easiest way to compare the content to be equal pre and post PR?

Something like this?

```shell
git difftool --tool=vimdiff origin/fix-line-endings origin/fix-line-endings~1
```

It shows me this (it's in LESS mode)

image

And `^M` is carriage return character only, so not unexpected to see that difference from CRLF -> LF.

(There are probably better ways, I just don't know.)

**Review by fkiraly — APPROVED** [review]
Yes, these have the same content except for line endings changed.
Line endings are also consiste across data files post-PR.

**Comment by fkiraly** [comment]
> Does any of the functionality break that is not covered by unit tests?

I don't think so - loading these is actually also tested, with some dependent functionality.

**Pull request merged**
