### PR TITLE
[ENH] refactor `InstanceSplitter` to a utility `apply_split` to apply an `sklearn` split to a time series collection

### PR DESCRIPTION
**Pull request by ksharma6**
#### Reference Issues/PRs
Towards https://github.com/sktime/sktime/issues/7021 , see also https://github.com/sktime/sktime/issues/6852
https://github.com/sktime/sktime/issues/6708

#### What does this implement/fix? Explain your changes.
InstanceSplitter was unable to apply the same index to split X and y without throwing an error when X was a multi-index dataframe and y was a 1D array. This PR fixes this issue by generating plain indices for splitting 

#### Does your contribution introduce a new dependency? If yes, which one?
No

#### What should a reviewer concentrate their feedback on?
Function docstring and variable names

#### Did you add any tests for the change?
No

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Great, plain refactor!

Since we now have a new public function in `utils.multiindex`, may I request to add specific tests for it, in `test_multiindex`?

**Comment by ksharma6** [comment]
Ran into a `TypeError: len() of unsized object` that appears to be tied to 

```python
 y_loc = inst_ix[np.array(iloc_ix)
```

To reproduce:
```python
X_train, y_train = load_arrow_head(split="train", return_type="pd-multiindex")
splitter = InstanceSplitter(KFold(3))
iloc_x = splitter.split(X_train)

apply_split(X_train, iloc_x)
```

**Comment by fkiraly** [comment]
I think you want `.split(y_train)`, because otherwise `iloc_x` will have more instances than `X_train`?

**Comment by ksharma6** [comment]
Hi @fkiraly 

Starting with the Docstring, I believe this better captures what we need apply_split to do:

```python
def apply_split(y, iloc_ix):
    """Generates indices to apply split from indexer onto dataset.

    Parameters
    ----------
    y : sktime or compatible multiindex data container
    iloc_ix: 1D numpy array containing indices for splitting

    Yields
    ------
    y_iloc : 1D numpy array containing plain indices for splitting.
    """

How can this be improved/is there a standardized language/style I should be using when writing docstrings for sktime?

**Comment by ksharma6** [comment]
```python
import pandas as pd
import numpy as np

def apply_split(y, iloc_ix):
"""Generates indices to apply split from indexer onto dataset.
Parameters
----------
y : sktime or compatible multiindex data container
iloc_ix: 1D numpy array containing indices for splitting
Returns
------
"""
    y_iloc : 1D numpy array containing plain indices for splitting.
    if not isinstance(y, pd.MultiIndex):
        zeros = [0] * len(y)
        y = pd.MultiIndex.from_arrays([zeros, y])

    inst_ix = y.droplevel(-1).unique()
    iloc_ixer = pd.DataFrame(pd.RangeIndex(len(y)), index=y)

    y_loc = inst_ix[np.array(iloc_ix)]
    y_np = [iloc_ixer.loc[x].to_numpy().flatten() for x in y_loc]
    y_iloc = np.concatenate(y_np)

    return y_iloc

from sktime.split.instance import InstanceSplitter
from sklearn.model_selection import KFold
from sktime.datasets import load_arrow_head

X_train, y_train = load_arrow_head(split= "Train", type = "multiindex")
splitter = InstanceSplitter(KFold(3))
iloc_ix = splitter.split(X_train)
#Iterate through generator object (used in InstanceSplitter._split() and will be used in evalute())
for y_train_inst_iloc, y_test_inst_iloc in splitter.split(X_train):
    y_train_iloc = apply_split(y, y_train_inst_iloc)

    print( y_train_iloc)
    break
```

**Comment by ksharma6** [comment]
**INPUTS to apply_split**:
y = y_train; 1d np array containing values 0, 1, or 2 of shape: (36,)
y_train_inst_iloc = an array of indices defined as [3012, 3013,...,9035]

**EXPECTED OUTPUT**
y_train_iloc = y[12:]

**Nature of the bug:**
IndexError: index 3012 is out of bounds for axis 0 with size 1

my y_train_inst_iloc is length 6024 while my y is length 36. I suspect I need to do some kind of a
conversion to make the indices work as intended. Since Kfold =3, I need the returned indices to be the
final 2 thirds of y... so y[12:]


**Last line that executes, w/ values of variables**
iloc_ixer = pd.DataFrame(pd.RangeIndex(len(y)), index=y)
- y is a multiindex dataframe of len 36
([(0, '0'),
(0, '1'),
(0, '2'),...
(0, '0'),
(0, '1'),])


First line that breaks w/ values of variables
y_loc = inst_ix[np.array(iloc_ix)]
inst_ix: Index([0], dtype=
'int64')
iloc_ix: array of indices defined as [3012,...,9035]

**I am not entirely sure what y_loc should look like**


Do the values deviate from expectation?
No

**Comment by fkiraly** [comment]
Thanks!

Main comment is, I do not think your `y` satisfies the assumption of the function input contract. It should be in the format `pd-multiindex`, i.e., `pd.DataFrame` with row multiindex and additional assumptions as detailed in the data type API reference.

**Review by fkiraly — DISMISSED** [review]
I fixed it to wrap it up now. Thanks for your contribution.

**Comment by pabx06** [comment]
hi any news ?

**Pull request merged**
