### PR TITLE
[ENH] Added test parameters for the LSTM FCNN network

### PR DESCRIPTION
**Pull request by shlok191**
#### PR Contributes to #3429
Added 2 test parameters for the `LSTMFCNNNetwork` as mentioned here: https://github.com/sktime/sktime/issues/3429. One of the parameters sets out a simpler version of the model, and the other tests a more sophisticated model

#### What does this implement/fix? Explain your changes.
I have added 2 test parameters for the LSTM-FCNN network returned via the `get_test_params` function. The test parameters aim to explore 2 quite different variations of the model in the hope to capture a broad spectrum of the model's parameters.

#### Does your contribution introduce a new dependency? If yes, which one?
It does not!

#### What should a reviewer concentrate their feedback on?
I would direct anyone's attention to the added function: `sktime/networks/lstmfcn.py/get_test_params` starting from line 128. I can absolutely work on improving the parameters if they are not quite as good, but that is the only major place I have made a change!

#### Did you add any tests for the change?
I have not added any tests for the commits I made

##### For all contributions
- [X] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)

- [X] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

### CODE REVIEW

**Comment by fkiraly** [comment]
Thanks!

For the tests to run, kindly ensure you adhere to sktime code formatting standards:
https://www.sktime.net/en/stable/developer_guide/coding_standards.html

**Comment by shlok191** [comment]
Oh I see! Thank you so much for the help @fkiraly. I have set up pre-commit now and verified that my code meets the standards before pushing the final fix commit. Hopefully this one works! 😃

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks!

Can you make sure to:

* include an empty parameter set - i.e., empty `dict`?
* don't set `random_state`?

**Comment by shlok191** [comment]
Got it, just pushed a commit with the desired changes!

**Review by fkiraly — APPROVED** [review]

**Pull request merged**
