### PR TITLE
&fkiraly [ENH] enhanced estimator overview table - tag display and search

### PR DESCRIPTION
**Pull request by duydl**
#### Reference Issues/PRs

#6105 #6106 #4905

The additional build on RTD can be found here in case it is not yet rendered on sktime own RTD. 
https://duydlsktime.readthedocs.io/en/latest/estimator_overview.html

#### What does this implement/fix? Explain your changes.

An enhancement to estimator overview table. Support filtering by estimator type and displaying tag. 

#### Does your contribution introduce a new dependency? If yes, which one?

It is implemented in vanilla js. 

#### Any other comments?

1. Generating markdown-overview-table/db in conf.py during sphinx-build cost additional time in local and RTD build. Perhaps we should do this in a different stage like in pre-commit and keep the md/json tracked in the repos.

2. Related to issue #4905. Assuming that all estimators should belong to a subcategory in their category and have two import paths, currently the broken links in the table are orphaned i.e without subcategory. Their rendering in the api-reference pages would be multiple single tables stacked on each other. 

For examples: 
ARDL in https://www.sktime.net/en/stable/api_reference/forecasting.html#structural-time-series-models
Annotation Estimators https://duydlsktime.readthedocs.io/en/latest/api_reference/annotation.html

I think a refractor by adding import path to __init__ and adjustment of corresponding in rst would be a better fix. We could approach to not break current user import but just adding a shorten import path when possible.  Like this PR #6116. 

3. This is WIP. Issues to address: 
- [x] Suitable way to adjust width of column for efficient display
- [x] Sorting for column
- [ ] Tags rename? Remove unneeded tags?
- [x] Better logic in generating json
- [x] pre-render all-table HTML during build to reduce initial load time

### CODE REVIEW

**Comment by yarnabrina** [comment]
The new filter feature is awesome, thank you for this contribution.

Few feedbacks:

1. Not sure if it's due to some extensions or not, but loading estimator overview page is taking some good amount of time for me on Firefox after this change. Stable/latest versions are not affected.
2. When `ALL` is selected, there are no options for `Check to Show Tags:`. May be that can be hidden?
3. For others, I think checkboxes for different tags can shown in different rows instead of one long line?
4. Changing the filter modifies the column width (and style?), can something be done for consistency?

I've no experience in UI works, so not sure if these are possible or not, just sharing as feedbacks. Also, in future (probably in a different PR), if we can filter these tables as well based on different tag values as well, that'd be great.

**Comment by duydl** [comment]
@yarnabrina I think it reached a good milestone now and would benefit some further feedback.

Here the update of the current state: 
* 1
> Sorting for column

Using search box would suffice

> Tags rename? Remove unneeded tags?

Need feedback from maintainers. 

* 2
> Not sure if it's due to some extensions or not, but loading estimator overview page is taking some good amount of time for me on Firefox after this change. Stable/latest versions are not affected.

This was addressed by pre-rendering the all-table when compiling docs. It is much faster but not instant like static included. 

> When ALL is selected, there are no options for Check to Show Tags:. May be that can be hidden?

Some universal tags might be used in the ALL table, though I saw that some of them are only specific to one type or all null.  

> For others, I think checkboxes for different tags can shown in different rows instead of one long line?

I think for some types the number of tags would be too many and would take too much space. Maybe some spacing between tags would be enough?

> Changing the filter modifies the column width (and style?), can something be done for consistency?

This was addressed. 


* Other task: 
[ ] instead of rendering change display to none
[ ] add column filter to search

**Comment by yarnabrina** [comment]
> > Tags rename? Remove unneeded tags?
> 
> Need feedback from maintainers.

I have no comments, requesting @fkiraly / @benHeid to pitch in.

---

> > For others, I think checkboxes for different tags can shown in different rows instead of one long line?
> 
> I think for some types the number of tags would be too many and would take too much space. Maybe some spacing between tags would be enough?

Agreed, one per line can be too much. May be you can show multiple tags a row with a fixed (or dynamic based on screen width) number of columns separated by tabs?

---

I just have three additional feedbacks, and rest looks okay to me 👍🏽 

1. If I navigate to https://sktime--6147.org.readthedocs.build/en/6147/estimator_overview.html and then search for `statsmodels` and select `Forecaster` in the dropdown, my expectation is I'll get all forecasters that have statsmodels in the name, so intersection of the search and dropdown. Currently it does not seem to be the case. Based on the results and few trial and errors, I think either the search or the dropdown effect is there, depending on what was modified later and ignores the other one. This is counter-intuitive to me at least, let me know what you think.

2. If I search for `statsforecast`, I see few results which all have dependencies listed as `scikit-learn` and `statsforecast`. But in `https://github.com/sktime/sktime/blob/main/sktime/forecasting/statsforecast.py`, only `statsforecast` is mentioned, so I am confused what is happening. @fkiraly do you know if any utility automatically adds `scikit-learn` everywhere or not?

3. This is more of a clarification question than a feedback. If I do not search for anything and just choose `Forecaster` in the dropdown, I no longer see `Authors` or `Dependencies`. Is it intentional?

**Comment by fkiraly** [comment]
This is very nice!

Major comments:

* to reiterate, very nice!
* I agree with @yarnabrina that the visuals could be more streamlined. I added a mockup in this issue for discussion of how it should look like and behave: https://github.com/sktime/sktime/issues/6343
* I do not have the "loading time" problem that @yarnabrina reports, on firefox
* re not showing all columns: I would show, by default, the user facing tags, when subsetting to an estimator type. It might be worth to hardcode the set and its order

Minor:

* it is odd that under the dependencies, `scikit-learn` comes up everywhere. Many estimators do not require `scikit-learn`. That should not be the case, should it? Where is that coming from, did you change anything about the tag logic?
* idea: links from tags to their API reference? There is now an API reference for tags: https://www.sktime.net/en/latest/api_reference/tags.html

**Comment by fkiraly** [comment]
I refactored some calls, hope you don't mind, @duydl.

**Comment by fkiraly** [comment]
FYI @sktime/core-developers, I've cleaned up the presentation, subset the tags to some user facing ones, and added instructions.

**Comment by fkiraly** [comment]
Looks like this now:

image

**Review by fkiraly — APPROVED** [review]
lgtm now

**Pull request merged**
