### PR TITLE
[MNT] Handle deprecations from `pandas`

### PR DESCRIPTION
**Pull request by fkiraly**
Handles various deprecations from `pandas`:

* remaining instances of use of deprecated `"M"` frequency
* deprecated `unit` argument in `pd.TimeDelta` constructor

### CODE REVIEW

**Review by yarnabrina — COMMENTED** [review]
While M -> ME is required for new pandas versions, old versions of pandas will likely fail. If we are using new version only changes, are we moving towards dropping support for pandas<2.2?

**Comment by fkiraly** [comment]
I think the code will still run on older versions - as far as changes are in the tests, there should be no issues, but you are right, the data loaders should probably not be changed this way but instead return version dependent outputs with supported freqs

**Comment by fkiraly** [comment]
added a distinction based on pandas version - or, should we go through deprecation?

**Comment by yarnabrina** [comment]
> added a distinction based on pandas version - or, should we go through deprecation?

I've nothing against either option. If it was up to just me, I'd have started planning for dropping support for older pandas versions, but I understand you are concerned about restrictions for users based on previous discussions.

**Comment by fkiraly** [comment]
> I've nothing against either option. If it was up to just me, I'd have started planning for dropping support for older pandas versions, but I understand you are concerned about restrictions for users based on previous discussions.

Yes, in particular about the kind of user that has lots of deps that force pandas 1, which imo is still not uncommon in the time series space

**Pull request merged**
