### PR TITLE
[DOC] fix odd formatting in deprecation timeline example

### PR DESCRIPTION
**Pull request by fkiraly**
This PR fixes some odd formatting in the deprecation timeline example.

### CODE REVIEW

**Comment by yarnabrina** [comment]
(Suggestion: merge without wait for full CI - the queue is very big, partly because I triggered test-all to see full coverage on main)

**Comment by fkiraly** [comment]
well, at least docs should pass...

**Comment by fkiraly** [comment]
random thought, with the folders filter, couldn't we just ensure no CI except docs runs if changes are only in `docs`?

**Comment by yarnabrina** [comment]
I think currently only old CI jobs will run, plus code quality. New CI should not run.

**Pull request merged**
