### PR TITLE
[ENH] Add time series segmentation via clustering

### LINKED ISSUE #6750: [ENH] time series segmentation via clustering - reduction of time series segmentation to tabular clustering
A simple reduction strategy for time series segmenters: pool the samples, and apply an `sklearn` clusterer that has a `transform` method. The different segments are the different clusters.

The syntax would be sth like `ClusterSegmenter(my_clusterer)`.

### PR DESCRIPTION
**Pull request by Ankit-1204**
#### Reference Issues/PRs
Implements and closes #6750 

#### What does this implement/fix? Explain your changes.
Implements  time series segmentation using clustering algorithm, default being KMeans algorithm

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Great contribution, thanks!

* May I kindly ask you to change `fit` and `predict` to `_fit` and `_predict`, using the extension template `annotation.py`?
* could you add at least one more parameter set to the `get_test_params`, e.g., the empty dict to test thedefault as well?
* `__init__` should never change value of an init parameter, this should be written to `self._clusterer`
* the argument `n_clusters` is superfluous, since it is an argument of `KMeans` already, I would suggest to remove it
* the clusterer should be cloned before being fitted, via `sklearn` `clone`

**Comment by fkiraly** [comment]
Let us know when you would like another review!

**Comment by Ankit-1204** [comment]
@fkiraly : kindly review this. 
(i wrote the clusterer to self._clusterer, but check_estimate was raising the error, couldn't find the parameter 'clusterer', so i wrote clusterer to self.clusterer and self._clusterer both, and only used self._clusterer internally. i am not sure if that was the correct way. )

**Comment by fkiraly** [comment]
looks good - restarted  the tests

**Comment by Ankit-1204** [comment]
I checked the test summary and I think it probably failed because of this mistake I made :  
             `self.n_instances, self.n_timepoints = X.shape`
Here I assumed X to be a dataframe rather than a Series, i'll make the necessary changes.
If there is anything else I missed, please share.

**Comment by Ankit-1204** [comment]
Last failure happened because of a silly mistake I made, checking the test summary it happened here 
  `self.n_instances, self.n_timepoints = X.shape`
I treated X as a dataframe which resulted in a error, I made the change to check if it is a Series. If there was anything else I missed, please do share.

**Comment by Ankit-1204** [comment]
Fewer tests passed compared to last, not sure what went wrong here.

**Comment by fkiraly** [comment]
FYI @fnhirwa, @yarnabrina, this seems to be related to the "OS dependencies" setup step newly introduced. Any ideas?

**Comment by fkiraly** [comment]
perhaps this has been resolved in more recent PR.
I always recommend to keep your fork up to date, and not use your `main` for contribution (which you are).
See here for the developer guide: https://www.sktime.net/en/latest/developer_guide/git_workflow.html

To keep your fork up to date, you can do this via the GUI for your fork. Then you need to merge into your branch.
I juts updated this branch to see if that resolves the issue.

**Comment by Ankit-1204** [comment]
sry wasn't able to check on this in a while. Looking at the error i realize i made some mistake abstracting how this will be used, So what i had initially thought was like we provide a time series, calculate its centroids and then eventually return the centroids using predict.   
But, the test that failed basically involved fitting the model on some n timepoints data and then predicting for some m timepoints data like any traditional model, which failed because i hadn't thought about that. It should be a small fix, in this way any new data that is used for prediction will also be segmented on fitted segments. the question i had was, is this the also intended use of this feature?

**Review by fkiraly — DISMISSED** [review]
I think this looks great!

Simple algorithm, but important reduction!

FYI @Alex-JG3, if you would also like to review.

**Comment by fkiraly** [comment]
Non-blocking, but a request: could you kindly add the new estimator to `docs/source/api_reference/annotation.rst`?

If you want a more challenging task, we could do window-based clustering segmentation - I have written it up here if interested :-)
https://github.com/sktime/sktime/issues/7142

**Comment by Ankit-1204** [comment]
@fkiraly Added the estimator to the .rst file.
Window Clustering looks interesting, I can start working on that by next week, after my midterms.

**Review by fkiraly — APPROVED** [review]

**Comment by Ankit-1204** [comment]
@fkiraly are the test needed to be restarted again? Also are there any other documentation changes i should have done?

**Comment by fkiraly** [comment]
No, all is fine, tests just need to be approved by a core dev

**Pull request merged**
