### PR TITLE
[BUG] Fix side-effect of predict_residuals

### LINKED ISSUE #3473: [BUG] Calling predict_residuals() is writing in-sample index to self.fh which should not happen
**Describe the bug**
Calling `forecaster:predict_residuals()` is setting the `forecaster.fh` to the in-sample index. This should not happen.

**To Reproduce**

```python
from sktime.datasets import load_airline
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.forecasting.theta import ThetaForecaster
from sktime.performance_metrics.forecasting import mean_absolute_percentage_error
from pandas.testing import assert_series_equal
from sktime.forecasting.naive import NaiveForecaster

y = load_airline()
y_train, y_test = temporal_train_test_split(y)
fh = ForecastingHorizon(y_test.index, is_relative=False)
forecaster = NaiveForecaster(sp=12)
forecaster.fit(y_train, fh=fh)

y_pred_1 = forecaster.predict()
print(forecaster.fh)
y_resid = forecaster.predict_residuals()
print(forecaster.fh)
y_pred_2 = forecaster.predict()
assert_series_equal(y_pred_1, y_pred_2)
```

**Expected behavior**
Above example should work.

**Additional context**

**Versions**
<details>

</details>

### PR DESCRIPTION
**Pull request by aiwalter**
#### Reference Issues/PRs
closes #3473

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Happy with the idea in general.

Some change requests:
* I think this will probably fail if an `fh` has already been passed to `fit` in a case where it does not need to be
* is there a way to do this without a copy of self? That can be large. Can we get away with just avoiding steps that write `fh` to self, e.g., `_check_fh`?
* we should also add a test for the expected logic. If we think `fh` being written is a bug, we should add a test in `test_base` that pins down the behaviour we want.
* the docstring should clearly mention what is written to self or not, like in `fit` or `predict`.

**Comment by aiwalter** [comment]
> we should also add a test for the expected logic. If we think fh being written is a bug, we should add a test in test_base that pins down the behaviour we want.

I added a test?

**Comment by aiwalter** [comment]
> I think this will probably fail if an fh has already been passed to fit in a case where it does not need to be

This case is covered by the test.

> is there a way to do this without a copy of self? That can be large. Can we get away with just avoiding steps that write fh to self, e.g., _check_fh?

I copy now only `fh`, that will be faster

> the docstring should clearly mention what is written to self or not, like in fit or predict.

Done

**Review by lmmentel — APPROVED** [review]
LGTM!

**Pull request merged**
