### PR TITLE
[GOV] Remove ability of CC to overrule core dev decisions

### PR DESCRIPTION
**Pull request by aiwalter**
#### Reference Issues/PRs
#3865 

#### What does this implement/fix? Explain your changes.
Remove ability of CC to overrule decisions made by core devs.

### CODE REVIEW

**Comment by fkiraly** [comment]
I formally vote this down.

This is a substantial change of how we currently decide, and would strengthen patterns like hounding/piling that are currently already problematic.

Scikit-learn and wikipedia both have this kind of overruling mechanism and I strongly argue we need to keep it.

CC should be able to overrule a dogpile of single-issue-voters based on architectural or strategic viewpoints. This proposal would remove the stage 3 option.

**Comment by aiwalter** [comment]
I am not having a strong opinion here, if the PR #3868 is merged then I am fine with not having this one actually.

**Comment by GuzalBulatova** [comment]
I agree with @fkiraly  that CC should have an option to overrule simple majority decisions, given that it's CC consensus that the majority decision isn't in the best interests of sktime

**Comment by aiwalter** [comment]
I still think this PR would be an improvement, but I am happy to put this PR to draft for now. If we have merged the other gov PRs I think this will become more an optional part of lower priority. So lets focus discussion for now on the other gov PRs 👍🏻

**Review by TonyBagnall — APPROVED** [review]

**Review by lmmentel — APPROVED** [review]

**Comment by fkiraly** [comment]
formal downvote.

Reasons explained here: https://github.com/sktime/sktime/issues/3882

**Comment by aiwalter** [comment]
a core dev vote was invoked on this PR in the private core dev Slack channel and will end after 7 days.

**Comment by aiwalter** [comment]
results of core-dev vote is >2/3 of casted votes, therefore merging this
image

**Pull request merged**
