### PR TITLE
[MNT] bound `tensorflow<2.16.0`

### PR DESCRIPTION
**Pull request by fkiraly**
This PR temporarily bounds `tensorflow<2.16.0` until the issues in https://github.com/sktime/sktime/issues/6094 are resolved.

The breaking version is `2.16.1`, and `2.16.0` is a release candidate (not full release)

### CODE REVIEW

**Comment by yarnabrina** [comment]
Latest Tensorflow version is `2.16.1` as per https://pypi.org/project/tensorflow/.

As per blame, I added that upper bound while adding the per component bounds. I guess at that point of time 2.13.x was the latest and I decided to use `2.14` as the upper bound. The equality was probably a typo. If it was intentional then I do not remember what was the reason.

I think @benHeid is also updating the bound in #6098. I oppose the current change in this PR (but pretty sure it's a typo) as it's in principle breaking, as users who are currently able to use with tensorflow 2.6 to 2.15 will no longer be able to use.

**Comment by fkiraly** [comment]
oh

yes, you are right.
I am not sure what I looked at, have I hallucinated the "1" away?
I will change the bound accordingly.

**Comment by fkiraly** [comment]
Hm, would this still be a breaking change for anyone who has `2.16.1` installed right now? It's only load/save that is not working.

**Comment by yarnabrina** [comment]
Hopefully #6098 will be merged before next sktime release, so I guess not as that will add back the support.

**Comment by yarnabrina** [comment]
Since it's going to trigger 200+ jobs, requesting to cancel this, add the abound to all_extras_pandas2 as well, and then let the CI run.

**Comment by fkiraly** [comment]
I think with #6074, the CI will automatically cancel on update, so no need to manually cancel!

**Review by yarnabrina — APPROVED** [review]

**Comment by fkiraly** [comment]
Oh, how I have longed to see the green tickmark again...
image

**Comment by yarnabrina** [comment]
Merging this into main so that other PR's can pull main to avoid same 5 failures everywhere. We can revert this or fix directly once @benHeid 's PR is done.

Hopefully that's okay.

**Pull request merged**
