### PR TITLE
&fkiraly [DOC] updates to distances API reference page

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
update by @fkiraly 

this PR was split into three: this PR, and #4027 and #4028 for different content.

This PR now only adds the API reference for `numba` distances, to the existing distances API reference.

Additional updates to the API reference:

* adds panel distances and kernels that were missing from the API reference
* adds explanation on how to construct common (flat or aggregate) distances and kernels

---

- Adds distance function API page for `distances`.
- Moves clustering base classes to the bottom of the page to conform with classification and regression
- Adds `all_estimators` snippet from the regression page to classification and clustering

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
I would suggest, merge with `dists_kernels`, otherwise it will be confusing that there are two API references pertaining to distances.

**Review by TonyBagnall — APPROVED** [review]

**Comment by TonyBagnall** [comment]
well there are in fact two packages related to distances for some reason. I feel the API should reflect the code structure, otherwise it is confusing.

**Comment by fkiraly** [comment]
moved the `all_estimators` references to https://github.com/sktime/sktime/pull/3852

**Comment by fkiraly** [comment]
moved docstring improvements to `dtw_distance` to PR https://github.com/sktime/sktime/pull/4028, with fixes and updates

**Pull request merged**
