### PR TITLE
[DOC] add examples for loading data from common tabular csv formats

### PR DESCRIPTION
**Pull request by TonyZhangkz**
#### Reference Issues/PRs

Attempts to respond to #4581.

#### What does this implement/fix? Explain your changes.

I added a section 4 to the notebook "AA_datatypes_and_datasets.ipynb" as suggested by @fkiraly to demonstrate how to load & convert from a csv file to a sktime-compatible data container. I showed with the "mtype" function that they are indeed compatible for each case.

#### Does your contribution introduce a new dependency? If yes, which one?

No.

#### What should a reviewer concentrate their feedback on?

This is my first PR. I would appreciate feedback on any fundamentals or specifics.

#### Did you add any tests for the change?

No.

#### Any other comments?

I have yet to add myself to list of contributors. Will figure this out later.

##### For all contributions

- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
thanks, that's a great start! Welcome to sktime!

One thing that's confusing for the reader is that you are saving the data before you are reading it.

However, some of thet data is already avaiable as `csv` in `datasets/data/Airline` etc.
For the panel dataset, you can also save one of the smaller datasets as `csv` for the sake of demomstration.

Could you change that, swe use (small) `csv` already shipping with `sktime` to demonstrate the loaders?

**Comment by TonyZhangkz** [comment]
> > One thing that's confusing for the reader is that you are saving the data before you are reading it.  However, some of thet data is already avaiable as `csv` in `datasets/data/Airline` etc. For the panel dataset, you can also save one of the smaller datasets as `csv` for the sake of demonstration. Could you change that, so we use (small) `csv` already shipping with `sktime` to demonstrate the loaders?
> 
> Thank you for pointing that out! I didn't know there are already such csv files so I fell back to creating ones on my own. Will update that!
> 
> Also, would there be any other use cases that are typically challenging for users? I'm happy to expand this section further when I finish with other interesting issues.

**Comment by TonyZhangkz** [comment]
Update: Done with modifications.

**Review by fkiraly — CHANGES_REQUESTED** [review]
Great content!

Minor but blocking request: can you ensure the code formatting checks pass?
Guide is here: https://www.sktime.net/en/latest/developer_guide/coding_standards.html

**Comment by TonyZhangkz** [comment]
@fkiraly Thank you so much for the feedback and for the source! I'm rather new to the community so I did not know the norms. Is there a way I can run the other checks myself to ensure we do not run into these mechanical errors when making a PR? Thanks!

**Comment by fkiraly** [comment]
yes, of course! Have you seen the guide? It has instructions how to set up the pre-commit locally.

**Comment by TonyZhangkz** [comment]
Yes (and thanks again!), I'm following the guide for pre-commit right now. For some reason, my commits are not being properly pushed or synced to this GitHub PR. I'll try to debug this myself.

**Comment by TonyZhangkz** [comment]
@fkiraly My pushes have not been updated since last night. I'm contacting support and will try to update this PR soon.

**Comment by fkiraly** [comment]
@TonyZhangkz, that's odd, sorry to hear!
Have you checked whether your problem is with GitHub, or with git?

Feel free to ask in the help-desk channel on discord, there might be a simple explanation.

**Comment by TonyZhangkz** [comment]
@fkiraly Thanks a lot! That's actually very good suggestion as I didn't know it could be a local git bug. I'm able to update the PR now. May I know if I could run the tests (e.g. code quality) myself instead of pending them in the PR?

**Comment by fkiraly** [comment]
@TonyZhangkz, a maintainer has to run the tests, I've started them now

**Review by fkiraly — DISMISSED** [review]
Really great, thanks! This will be really helpful to sktime users!

I've added some section headers, updated the table of contents, straightened some explanations, and added a third (difficult) example, hope you're ok with that.

**Comment by TonyZhangkz** [comment]
> I've added some section headers, updated the table of contents, straightened some explanations, and added a third (difficult) example, hope you're ok with that.

Great, and thanks again for everything on my first PR! I've learned quite some from how you'd do the explanations. And I was actually gonna raise the question for whether or not we're doing the .tsv files. So I'm more than OK with the changes.

**Pull request merged**
