### PR TITLE
[DOC] Add hall-of-fame widget to README (Added the Hall-of-fame section) #3716 

### LINKED ISSUE #3716: [DOC] Add hall-of-fame widget to README
#### Describe the issue linked to the documentation

We'd like to celebrate our contributors and make the most active / recent ones more visible. After discussion in https://github.com/sktime/community-org/issues/36 , community decided to go with this option for improvement in README.

#### Suggest a potential alternative/fix

Add https://github.com/sourcerer-io/hall-of-fame widget to sktime/README.md

### PR DESCRIPTION
**Pull request by KaustubhUp025**
#### Reference Issues/PRs
Add Hall-of-Fame section, fixes #3716 

#### What does this implement/fix? Explain your changes.
The Hall-of-Fame section is added after (How-to-get-involved)

#### Does your contribution introduce a new dependency? If yes, which one?
No

#### What should a reviewer concentrate their feedback on?
The code written for keeping track of contributions to the repository.

#### Did you add any tests for the change?
Not Yet

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, for added estimators: I've added myself and possibly to the `maintaners` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [👍 ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Comment by fkiraly** [comment]
Nice! Quick question before review:

why or how is this getting the information from open collective? I am surprised since that's where the `svg` points to.

**Comment by fkiraly** [comment]
For the emoji, perhaps sth that has closer connotations to thankfulness, achievement or community?

E.g., one of 🏆 , 🌟 , 🚀 , 🚤 , 🎶 ?
🎓 has an achievement connotation, but not that much of thanks and community?

**Review by fkiraly — DISMISSED** [review]
Great addition!

I think this is worth merging and making minor adjustements later.

Most importantly, we should track the discrepancy to the `all-contributorsrc` and that it does not acknowledge contributions other than code.

**Comment by KaustubhUp025** [comment]
For the question that from where open collective is getting this information, I am finding it the answer for the same but I am in doubt so still searching in the code base. But what I can tell is it derives the data from *all-contributorsrc* in my opinion.

Also Yes I will give the change to the emoji. @fkiraly 

And for the reference for doing this PR, I took reference from the given repo :- 
[https://github.com/epicmaxco/vuestic-admin/blob/master/README.md?plain=1](url)

**Comment by KaustubhUp025** [comment]
@fkiraly Could you suggest how could we look into the discrepancy involving the *all-contributorsrc*.

I will make a modification to the emoji as well

**Comment by fkiraly** [comment]
>  But what I can tell is it derives the data from all-contributorsrc in my opinion.

I think it doesn't, as far as I understand, it gets it from here:
https://github.com/sktime/sktime/graphs/contributors

Which is the code contribution summary.

**Comment by fkiraly** [comment]
> @fkiraly Could you suggest how could we look into the discrepancy involving the all-contributorsrc.

I think these are just two separate data sources, and it is very unclear how to reconcile them in the hall-of-fame display. As said, this is probably hard, so let's open an issue where we track this, and get 80% the way there with this PR.

**Review by fkiraly — APPROVED** [review]

**Comment by KaustubhUp025** [comment]
Thank you so much @fkiraly for your help. So should I do anything else with this PR or move to another issue.

**Comment by fkiraly** [comment]
I'd suggest you open an issue which describes the remaining todos (e.g., which source is it from, discrepancies), and then I'd consider it complete. Make sure to link this PR for details.

**Comment by KaustubhUp025** [comment]
Thanks @fkiraly, I will add the given points

**Pull request merged**
