### PR TITLE
Remove ChrisHolder from active core devs, removes jasonlines from codeowners, upon their own request

### PR DESCRIPTION
**Pull request by chrisholder**
I am making this PR on behalf of myself, @TonyBagnall and @MatthewMiddlehurst. @TonyBagnall and @MatthewMiddlehurst cannot make this PR themselves as they have been banned from the repository.

We are removing ourselves from the project as we no longer believe in the vision and direction of Sktime.

We would like to thank everyone for their time and involvement in the project we have had so much fun and we are sad it is ending this way.

### CODE REVIEW

**Comment by fkiraly** [comment]
> I am making this PR on behalf of myself, @TonyBagnall and @MatthewMiddlehurst. @TonyBagnall and @MatthewMiddlehurst cannot make this PR themselves as they have been banned from the repository.
We are removing ourselves from the project as we no longer believe in the vision and direction of Sktime.

Tony and Matthew have been banned due to serious code of conduct violations.
They have been given opportunity for remedial which they chose not to exercise.

Regarding the vision of `sktime` in general, without necessarily referring to the particulars of the above:

`sktime` is a project which takes its commitment to fair opportunities, for everyone, very seriously.

We are a community with a zero tolerance policy towards harassment, mobbing, scientific misconduct, systemic discrimination, and institutional corruption.

We, the leaders of `sktime`, belive that fairness and diversity are not just "nice to haves" to commit lip service to, but constantly require standing up for, especially when it is hard, and especially when it comes at significant personal cost.

**Review by fkiraly — CHANGES_REQUESTED** [review]
We should make sure that we don't violate the "ownership contract" of algorithms, a cornerstone of `sktime` governance, so we need to check a few things.

* Matthew and Tony should directly confirm to an `sktime` core developer of their choice, that they indeed want to give up ownership of the estimators in question. This giving up would be voluntary, the algorithms haven't been taken away from them.
* @abostrom and @jasonlines are third individuals that this PR attempts to remove, too. As far as I see, they have not consented to this, so it should not been done.

**Comment by chrisholder** [comment]
In regards to @TonyBagnall and @MatthewMiddlehurst they are banned from the repository so cannot interact with this issue all I can tell you is they explicitly asked me to make this PR on their behalf (how can they be a code owner anyway if they can't see or interact with the code they 'own' anyways as they are banned).

For Jason see pr: https://github.com/sktime/sktime/pull/3625 for confirmation.

I've reached out to @ABostrom to get a confirmation as well.

**Comment by jasonlines** [comment]
I'm happy to be removed as owner for the files referenced in this PR. Thanks

**Comment by chrisholder** [comment]
All the above have been resolved and it has been over a week so approving and pushing in.

**Comment by fkiraly** [comment]
@chrisholder, thanks - I will carry out *only the removals that have been explicitly confirmed*.
A ban does not mean that algorithms are taken away, and there is also email or other means of communication by which confirmation could be given.

**Pull request merged**
