### PR TITLE
[GOV] proposal: CC and CoC should have disjoint membership

### PR DESCRIPTION
**Pull request by aiwalter**
#### Reference Issues/PRs
#3865

#### What does this implement/fix? Explain your changes.
This adds separation of power between CC and CoC. A person should not be able to have the two positions at same time due to separation of power. This is a typical principle of democracy.

### CODE REVIEW

**Comment by fkiraly** [comment]
agreed on the general idea of separation of duties/powers.

But then you should not simultaneously give the power to one chamber to appoint or revoke the members of the other two!
https://github.com/sktime/sktime/pull/3866
incorrectly labelled as "remove gate keeping"

Separation of powers was already discussed here: https://github.com/sktime/sktime/pull/3675/files

Please ensure you comment on the existing alternative proposal.

**Review by MatthewMiddlehurst — APPROVED** [review]

**Review by TonyBagnall — APPROVED** [review]

**Review by lmmentel — APPROVED** [review]

**Comment by fkiraly** [comment]
formal downvote.

Reasons explained here: https://github.com/sktime/sktime/issues/3882

**Comment by aiwalter** [comment]
a core dev vote was invoked on this PR in the private core dev Slack channel and will end after 7 days.

**Review by GuzalBulatova — APPROVED** [review]

**Review by ltsaprounis — APPROVED** [review]

**Review by miraep8 — APPROVED** [review]

**Comment by fkiraly** [comment]
This PR has violated governance rules on how to vote multiple times.

* gov rules clearly say, we vote publicly. Martin opened votes in private.
* Martin has used some app to vote anonymously in a private slack channel that had people in it who were not eligible to vote.
* this is a substantial change so would formally require a STEP, which implies 7 days discussion period.

Further, we are violating the "spirit" of how to vote.

* some people are now on holiday and will be unable to vote until they return.
* some people wanted to pause from votes after this and will not see the second vote in time.

I think we should just stop this and base the changes on consensus.

I.e., start over in January when everyone is back from holidays or pause.
Then, work out how elections work with term limits and clear rules.

**Review by patrickzib — APPROVED** [review]

**Pull request closed without merging**
