### PR TITLE
[ENH] draft design for refactoring `datatypes` module - classes

### PR DESCRIPTION
**Pull request by fkiraly**
Implements https://github.com/sktime/sktime/issues/3512, related to #2957

This adopts the design proposed in the issue, with a class for mtypes, and a class for conversions, both being `BaseObject`.

The design is meant ot make the `datatypes` module more extensible, and making it easier to manage soft dependencies in data type such as `xarray`, `polars`, or `temporian` `EventSet` (FYI @ianspektor, @achoum).

Currently in draft state for review, contains only the proposed class structure and refactor of a single mtype (`pd.DataFrame`),
FYI @sktime/core-developers

### CODE REVIEW

**Comment by fkiraly** [comment]
Note to self: this would also solve the issue of documenting the mtype specifications, if we (a) do it in the class docstring, and (b) list them in the API reference. A minor issue is displaying the naming of mtypes, though this can be taken care of in the first line of the class docstring.

**Comment by julian-fong** [comment]
Since `skpro` is a 'playground' of sorts - maybe we can play incorporate this in `skpro` and see how we can improve it for `sktime`? I am not sure if there is a similar pr for this in `skpro` yet

**Comment by fkiraly** [comment]
hmm - good idea!

**Comment by fkiraly** [comment]
do you want to try copy this, or should I do that?
Just concerned about merge conflicts.

**Comment by julian-fong** [comment]
You can copy it - is it possible after wards for me to work on the your branch that you made?

**Comment by fkiraly** [comment]
sure. Let me adapt it, and then you try to merge with your `polars` PR, I would recommend a separate PR though after you have added via the "old" system.

**Comment by fkiraly** [comment]
superseded by https://github.com/sktime/sktime/pull/7161

**Pull request closed without merging**
