### PR TITLE
[MNT] python 3.11 support

### PR DESCRIPTION
**Pull request by fkiraly**
update, Feb 23, 2023: `numba` is now fully isolated, and `sktime` release 0.16.1 has been released with experimental 3.11 support.
Issues that remain to fix before full support in 0.17.0:

* soft dependencies need to be checked with 3.11, and restrictions removed where appropriate https://github.com/sktime/sktime/pull/4269
* conda issues with 3.11 need to be fixed https://github.com/conda-forge/sktime-feedstock/issues/66
  this is waiting for migration, and is not necessarily blocking 0.17.0

---

Python 3.11!

* extends GHA CI tests and release tests to include python 3.11
* updates `pyproject.toml`

todo:

* wait until core deps support 3.11 (or turn them into soft deps, e.g., `statsmodels` and `numba`)
* check if anything fails, e.g., estimators dependent on soft dependencies not compatible with python 3.11
* fix any bugs or add version limiters in estimators
* once all is fixed, update documentation to include 3.11 support

### CODE REVIEW

**Comment by fkiraly** [comment]
image
😢

**Comment by fkiraly** [comment]
I suppose this was too early since it's getting the rc only?

**Comment by aiwalter** [comment]
3.11 was released yesterday

**Comment by fkiraly** [comment]
I know, but it's not seeing the 3.11 release, only release candidates if I am interpreting the log right?

**Comment by fkiraly** [comment]
restarted, now it's a different problem.

`numba` does not support python 3.11.

Another reason to turn it into a soft dep, I suppose.

**Comment by patrickzib** [comment]
1. Python 3.11 was published on October 24, 2022!
2. neither scipy nor numpy fully support it, yet. Let us turn them into a soft-dependency!

> BUG: SciPy test failures due to changes in NumPy main or Python 3.11 #22006
See: https://github.com/numpy/numpy/issues/22006

**Comment by fkiraly** [comment]
@patrickzib, bug reports are different from version compatibility.
scipy has 311 wheels:

image

**Comment by fkiraly** [comment]
numba does not have 311 wheels at current:
image

**Comment by fkiraly** [comment]
> Python 3.11 was published on October 24, 2022!

@patrickzib, there are things called "release candidates" and "pre-releases". So, people can develop against those release candidates, which in the best case enables compatibility on release day.

**Comment by fkiraly** [comment]
> Their bug report was opened: 17 Jul - this qualifies for way too long.

If you define "has bugs under python version X" as "is not compatible with python version X", then probably none of the python packages you know is compatible with any python version.

**Comment by EwoutH** [comment]
Statsmodels [0.13.3](https://github.com/statsmodels/statsmodels/releases/tag/v0.13.3) is released, with Python 3.11 wheels!

**Comment by fkiraly** [comment]
nice, @ewouth! Let's try this again...

**Comment by EwoutH** [comment]
Looks like the CI is currently blocked by Numba not being available for Python 3.11.

See https://github.com/numba/numba/issues/8304.

**Comment by fkiraly** [comment]
> Looks like the CI is currently blocked by Numba not being available for Python 3.11.

I think it's blocked by the monthly CI limit?
`numba` not being available would lead to CI failure instead, I think.

Either way, I think I have just the remedy here 😁 
https://github.com/sktime/sktime/pull/3856

**Comment by fkiraly** [comment]
@EwoutH, since you are watching this: any good idea why https://github.com/sktime/sktime/pull/3856 is installing `numpy 1.19` (old version) on `3.11`, or what is an easy way to track down the cause?

**Comment by EwoutH** [comment]
Where is it doing that exactly?

**Comment by fkiraly** [comment]
3.11 CI when installing the env

**Comment by EwoutH** [comment]
Sorry but I really can't find where it's happening. Can you link to exactly where? Click the line number in the CI log and copy the URL.

**Comment by fkiraly** [comment]
update, Feb 23, 2023: `numba` is now fully isolated, and `sktime` release 0.16.1 has been released with experimental 3.11 support.
Issues that remain to fix before full support in 0.17.0:

* soft dependencies need to be checked with 3.11, and restrictions removed where appropriate https://github.com/sktime/sktime/pull/4269
* conda issues with 3.11 need to be fixed https://github.com/conda-forge/sktime-feedstock/issues/66
  this is waiting for migration, and is not necessarily blocking 0.17.0

**Comment by fkiraly** [comment]
this is duplicative with `main`

**Pull request closed without merging**
