### PR TITLE
[ENH] New PAA and SAX transformer implementations

### PR DESCRIPTION
**Pull request by steenrotsman**
#### Reference Issues/PRs

See also #5732.

#### What does this implement/fix? Explain your changes.

New implementations for PAA and SAX. The old ones are in transformations/panel/dictionary_based. The new code is more efficient and concise. If anything is unclear in the new code, I'm happy to add a comment/make it more clear!

#### Does your contribution introduce a new dependency? If yes, which one?

No.

#### What should a reviewer concentrate their feedback on?

This is my first time contributing. Though I did follow the template, some elements might be incompliant with the required format.

#### Did you add any tests for the change?

Yes.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, I've added myself and possibly others to the [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) file - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [x] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [x] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks, that was quick!

This is an almost-approval, all looks fine content-wise.

I have two questions, these can also be resolved by discussion in theory.

* the older transformers are in the API reference in the section of series-to-primitives, while yours are in the series-to-series section, but upon inspection this seems to be incorrect for the older transformers. At least this is inconsistent, and imo both pairs should be in the same section to avoid user confusion.
    * not blocking, but what should the taxonomy be here? The old taxonomy must be incorrect, because we are dealing with series-to-series transformers.
* due to how search and retrieval (e.g., via `all_estimators`) currently works, estimators need to have unique names. `PAA` and `SAX` already exist.
    * this does not mean we cannot rename them later, see the [algorithm inclusion guidelines](https://www.sktime.net/en/stable/get_involved/governance.html#algorithm-inclusion-guidelines) - but at least in the next MINOR release cycle the name must be sth else to avoid downstream code breaking, see [deprecation policy](https://www.sktime.net/en/stable/developer_guide/deprecation.html)
    * if it is meant to be an upgrade, we could call them `PAA2` or `PAAV2`. An alternative is `PAAYourBrandNameHere`, though we've used that pattern mostly for interfaced (not `sktime` native) algorithms.

Not blocking but would be great:

* the `_check_params` implicitly assume some bounds on the parameters. This would be good to summarize for the user already in the docstring, e.g., `int greater equal 2` or similar.
* References in docstrings should be in the `References` section and use `rst` reference syntax (see most other estimators), then they become clickable.

**Comment by fkiraly** [comment]
Failures are due to no blank after `>>>` in doctest, it should be `>>> line1 = stuff`.
Easy fix, I didn't do it because you might be moving the estimators around, to avoid merge conflicts.

**Comment by steenrotsman** [comment]
Fixed. I changed the names to `PAA2` and `SAX2`, but I'd vote for deprecating the old classes. As for the section they should go in, I'm not sure. The returned types look like other time series (though typically a time series is defined as a sequence of real numbers, while the sequences returned by SAX can only contain natural numbers, often represented as characters). However, their use might be closer to primitives, as they were originally used to give lower bounds to the Euclidean distance.
I'm fine with either.

**Comment by fkiraly** [comment]
> Fixed. I changed the names to `PAA2` and `SAX2`, but I'd vote for deprecating the old classes.

Ok - we need to do that step-wise though, and ensure we do not break code downstream. I suggest opening a separate issue to discuss this and track.
One could do it this way:

* at the end, we rename `PAA` to `PAAlegacy` and `PAA2` to `PAA`, same for `SAX`
* for this, we need to come up with a good deprecation mechanism
    * the first step would be a warnig message in the constructor of `PAA` / `SAX` in every case where we expect reakage, e.g., the output conversion. It also needs to include migration instuctions - "stay if" and "switch if".
    * the "stay" condition is probably for all the same parameters, the "switch" codition is when non-joint parameters are used?
* probably we should also comment in the current docstring - separate PR though.

>As for the section they should go in, I'm not sure. The returned types look like other time series. 

We cosider sequences as a sub-type of time series (index-less), so yes, it should be series-to-series.
The section you selected looks fine, I suggest to move the older `PAX` and `SAA` to here.

> However, their use might be closer to primitives, as they were originally used to give lower bounds to the Euclidean distance.

Yes, although that's a typing question.

You *could* make the transformer polymorphic, by doing a dynamic `set_tag` in the `__init__` depending on a parameter. This would however assume that the number of primitive features for all time series instances in a panel are the same, and I'm not sure whether that is the case.

**Comment by fkiraly** [comment]
Silly question, from me out of interest since you seem familiar with the literature: how is `PAA` different from `TimeBinner`? Is it through the additional logic which selects breakpoints?

I.e., would it be the same as a parameter estimator, say, `BreakPointSelector`, and then you pipeline it with `TimeBinner`?

**Comment by fkiraly** [comment]
doctests are now failing, since it expects an output print below. You can use doctest skip, as this would not reduce coverage, or an ellipsis statement like `np.array(...)` to make your life easier if you want.

**Comment by steenrotsman** [comment]
> assume that the number of primitive features for all time series instances in a panel are the same

This is the case when using the `frames` and `word_size` attributes, but not when using the `frame_size` attribute.

> how is `PAA` different from `TimeBinner`?

Using `frames`, which is the original definition, each frame is exactly the same size and time points can be part of multiple frames. The effects of using `frame_size` can be achieved with `TimeBinner` as well, but `TimeBinner` can set other `aggfunc`s and divide the series into an arbitrary number of frames of arbitrary sizes. With a proper `aggfunc`, `TimeBinner` can probably also emulate `SAX`. Implementation-wise, `TimeBinner` returns primitives, so always a `DataFrame`, while `PAA` returns the input type.

> doctests are now failing

Weird, I think I followed the same format as in NumPy's own docstring... I'll skip them as the same outputs are tested with pytest already.

**Comment by fkiraly** [comment]
>> assume that the number of primitive features for all time series instances in a panel are the same

> This is the case when using the `frames` and `word_size` attributes, but not when using the `frame_size` attribute.

Then it does not satisfy the "series-to-primitives" contract, which in `transform` must transform n time series (however represented) into a 2D array-like of size n times k, for some k.

> Implementation-wise, `TimeBinner` returns primitives, so always a `DataFrame`, while `PAA` returns the input type.

Ok, then it is probably closer to `TimeBinAggregate`?

**Review by fkiraly — CHANGES_REQUESTED** [review]
Almost done, all points addressed except:

* can you kindly make sure the API docs are consistent and up-to-date
* both old and new transformers should be in the same section.

**Comment by steenrotsman** [comment]
> can you kindly make sure the API docs are consistent and up-to-date

I'm not sure if I understand correctly. Should I edit the docstrings for the old classes to indicate that they might be deprecated in the future?

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks!

With the "API docs" comment, I meant `transformations.rst` which you have fixed, but in fact there the two pairs are named the same by accident now, while one should be named `PAA2` etc.

Non-blocking, would appreciate thoughts about the deprecation procedure. E.g., rename the old to `PAAlegacy` and test parameter equality?

**Review by fkiraly — APPROVED** [review]

**Pull request merged**
