### PR TITLE
[ENH] testing global forecasters: reduces number of obs in `_make_hierarchical` for test data generation to ensure shorter runtimes

### PR DESCRIPTION
**Pull request by julian-fong**
@Xinyu-Wu-0000 @fkiraly @benHeid 

This pr reduces the number of observations from 50,000 to 500 in `_multiindex_data` and `_multiindex_hier_data` in order to reduce the computation load for local testing and CI testing

Let me know if there are other refactors required

Thanks!

### CODE REVIEW

**Comment by fkiraly** [comment]
hm, the pytorch forecasters still fail - FYI @benHeid, @Xinyu-Wu-0000

**Comment by Xinyu-Wu-0000** [comment]
Try to restrict the torch version `torch<2.4.0` like @benHeid has done in [962f83d](https://github.com/sktime/sktime/pull/6943/commits/962f83dd726b10f2d71772fab452a7139c4b543d). I think @benHeid is still testing to comfirm it has to be restricted but when he restricted the version to `2.3.1`, it works: https://github.com/sktime/sktime/actions/runs/10338782352.

**Comment by fkiraly** [comment]
@julian-fong, do you understand the failures? They seem genuine.

**Comment by julian-fong** [comment]
@fkiraly Unfortunately I do not.. these errors seem unrelated to the changes I made in the pr I think? Not 100% sure

**Comment by Xinyu-Wu-0000** [comment]
One of the issues could be caused by data too short. Try to increase the length of time series. You can decrease the number of time series to reduce the data size.

[test-full (3.9, ubuntu-latest)](https://github.com/sktime/sktime/actions/runs/10344756897/job/28632322890?pr=6948#logs):
```
=========================== short test summary info ============================
FAILED sktime/forecasting/tests/test_all_forecasters.py::TestAllGlobalForecasters::test_global_forecasting_no_X[TinyTimeMixerForecaster-0] - ValueError: __len__() should return >= 0
FAILED sktime/forecasting/tests/test_all_forecasters.py::TestAllGlobalForecasters::test_global_forecasting_multiindex[TinyTimeMixerForecaster-0] - ValueError: __len__() should return >= 0
FAILED sktime/forecasting/tests/test_all_forecasters.py::TestAllGlobalForecasters::test_global_forecasting_different_timestamps[TinyTimeMixerForecaster-0] - ValueError: __len__() should return >= 0
FAILED sktime/forecasting/tests/test_all_forecasters.py::TestAllGlobalForecasters::test_global_forecasting_hier_series[TinyTimeMixerForecaster-0] - ValueError: __len__() should return >= 0
FAILED sktime/forecasting/tests/test_all_forecasters.py::TestAllGlobalForecasters::test_global_forecasting_multiindex_hier[TinyTimeMixerForecaster-0] - ValueError: __len__() should return >= 0
```

**Comment by julian-fong** [comment]
> One of the issues could be caused by data too short. Try to increase the length of time series. You can decrease the number of time series to reduce the data size.
> 
> [test-full (3.9, ubuntu-latest)](https://github.com/sktime/sktime/actions/runs/10344756897/job/28632322890?pr=6948#logs):
> 
> ```
> =========================== short test summary info ============================
> FAILED sktime/forecasting/tests/test_all_forecasters.py::TestAllGlobalForecasters::test_global_forecasting_no_X[TinyTimeMixerForecaster-0] - ValueError: __len__() should return >= 0
> FAILED sktime/forecasting/tests/test_all_forecasters.py::TestAllGlobalForecasters::test_global_forecasting_multiindex[TinyTimeMixerForecaster-0] - ValueError: __len__() should return >= 0
> FAILED sktime/forecasting/tests/test_all_forecasters.py::TestAllGlobalForecasters::test_global_forecasting_different_timestamps[TinyTimeMixerForecaster-0] - ValueError: __len__() should return >= 0
> FAILED sktime/forecasting/tests/test_all_forecasters.py::TestAllGlobalForecasters::test_global_forecasting_hier_series[TinyTimeMixerForecaster-0] - ValueError: __len__() should return >= 0
> FAILED sktime/forecasting/tests/test_all_forecasters.py::TestAllGlobalForecasters::test_global_forecasting_multiindex_hier[TinyTimeMixerForecaster-0] - ValueError: __len__() should return >= 0
> ```

Yes, by decreasing the sequence lenght this error can be fixed, but not exactly sure what is happening in the other failures.

**Comment by Xinyu-Wu-0000** [comment]
This is caused by `pmdarima` is not compatible with numpy2. We need to downgrade numpy to 1.26.4.

```
FAILED sktime/forecasting/tests/test_all_forecasters.py::TestAllForecasters::test_predict_time_index[ForecastX-1-y:2cols-fh=[-2 -5]-datetime-datetime-False] - ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
FAILED sktime/forecasting/tests/test_all_forecasters.py::TestAllForecasters::test_predict_interval[ForecastX-1-y:1cols-fh=[2 5]-alpha=[0.25, 0.75]-range] - ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

With numpy2, `import pmdarima` will fail:

```py
Python 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pmdarima
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xinyu/DATA1_1T/anaconda3/envs/sktime_310/lib/python3.10/site-packages/pmdarima/__init__.py", line 52, in <module>
    from .arima import auto_arima, ARIMA, AutoARIMA, StepwiseContext, decompose
  File "/home/xinyu/DATA1_1T/anaconda3/envs/sktime_310/lib/python3.10/site-packages/pmdarima/arima/__init__.py", line 5, in <module>
    from .approx import *
  File "/home/xinyu/DATA1_1T/anaconda3/envs/sktime_310/lib/python3.10/site-packages/pmdarima/arima/approx.py", line 9, in <module>
    from ..utils.array import c, check_endog
  File "/home/xinyu/DATA1_1T/anaconda3/envs/sktime_310/lib/python3.10/site-packages/pmdarima/utils/__init__.py", line 5, in <module>
    from .array import *
  File "/home/xinyu/DATA1_1T/anaconda3/envs/sktime_310/lib/python3.10/site-packages/pmdarima/utils/array.py", line 13, in <module>
    from ._array import C_intgrt_vec
  File "pmdarima/utils/_array.pyx", line 1, in init pmdarima.utils._array
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by Xinyu-Wu-0000** [comment]
Not sure why numpy2 is installed. [pyproject.toml](https://github.com/alkaline-ml/pmdarima/blob/master/pyproject.toml) from `pmdarima`:

```
[build-system]
requires = [
    "numpy==1.21.2; python_version < '3.10'",
    "numpy==1.21.6; python_version == '3.10' and platform_system != 'Windows'",
    "numpy==1.22.3; python_version == '3.10' and platform_system == 'Windows'",
    "numpy==1.23.2; python_version == '3.11'",
    "numpy==1.26.0; python_version == '3.12'",
    "scipy==1.3.2; python_version <= '3.8' and platform_machine != 'aarch64'",
    "scipy==1.5.3; python_version <= '3.8' and platform_machine == 'aarch64'",
    "scipy==1.5.4; python_version == '3.9'",
    "scipy==1.7.2; python_version == '3.10'",
    "scipy==1.9.3; python_version == '3.11'",
    "scipy==1.11.2; python_version == '3.12'",
    "statsmodels==0.13.2; python_version <= '3.10'",
    "statsmodels==0.13.3; python_version == '3.11'",
    "statsmodels==0.14.0; python_version == '3.12'",
    "cython>=0.29,!=0.29.18,!=0.29.31",
    "setuptools",
]
build-backend = "setuptools.build_meta:__legacy__" # TODO: Don't use legacy backend
```

**Comment by yarnabrina** [comment]
@julian-fong @Xinyu-Wu-0000 can you please share the job link which is failing with `pmdarima` error because of `numpy` v2?

**Comment by julian-fong** [comment]
> @julian-fong @Xinyu-Wu-0000 can you please share the job link which is failing with `pmdarima` error because of `numpy` v2?

Hi @yarnabrina, you can find them [here](https://github.com/sktime/sktime/actions/runs/10344756897/job/28633535024?pr=6948)

**Comment by yarnabrina** [comment]
@Xinyu-Wu-0000 the specifications you mentioned are build requirements. The package requirements are different, and specified in requirements.txt.

https://github.com/alkaline-ml/pmdarima/blob/v2.0.4/requirements.txt

These are then used in package specifications in setup.py.

https://github.com/alkaline-ml/pmdarima/blob/15919ef6de7778dfb0e74e9b47708f6ea1ec4ee2/setup.py#L253

If you create a new environment and install pmdarima, I think you'll find that it installs latest numpy and then fails, as there's no bound specification. I haven't tested it myself, so please let me know if that's not the case.

**Comment by julian-fong** [comment]
linking #6570

**Review by fkiraly — COMMENTED** [review]
in-principle this seems fine if we are certain no failures are introduced, but we should separate out the bound on the `torch` version in another PR. I do not think we should add that to a patch release.

**Pull request merged**
