### PR TITLE
[MNT] update the alphabet_size variable default and type_dict deprecated

### PR DESCRIPTION
**Pull request by xxl4tomxu98**
##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by xxl4tomxu98** [comment]
@fkiraly , Hi Franz, I have re-created this PR

**Comment by fkiraly** [comment]
still the same issue - probably you are using the wrong branch?
We can jump on discord to sort it out with screenshare if you aren´t sure how.

**Comment by xxl4tomxu98** [comment]
cool let us do it

**Comment by xxl4tomxu98** [comment]
create another one with out changes to the main branch

**Pull request closed without merging**
