### PR TITLE
[MNT] Split CI jobs per components with specific soft-dependencies

### PR DESCRIPTION
**Pull request by yarnabrina**
Part 2, 3 and 4 of #5101
Depends on #5375

1. new extra with just test dependencies
2. action to run tests in `sktime/base` with only core and test dependencies
3. action to run tests in `sktime/<component>` with only core, test and component specific dependencies
4. workflow to run base framework tests only when `sktime/base` gets modified
5. workflow to run component specific tests only when `sktime/<component>` gets modified
6. workflow to run all (base framework and all components) tests every SUnday 00:00 and manually if desired

### CODE REVIEW

**Comment by yarnabrina** [comment]
Ready for review. See checks to note that new tests were skipped becuase of no changes. See checks in the diagnostic PR's to see the effect for when there are changes.

Notes:

1. Failure in CI status is due to the fact I cancelled existing CI workflows to trigger new one quicker.
2. I'm unsure if this is respecting "differentia testing" (only test modules that are changed). Is it necessary to pass any environment variable or some CLI flag?

**Comment by yarnabrina** [comment]
(Tagging @fkiraly @benHeid @achieveordie as reminder to review request in case you've missed this by accident. Also requesting @hazrulakmal as I think (?) you proposed CRON jobs before.)

This is the goal of this PR, i.e. what all I expect to happen:

1. developer creates a PR.
2. CI checks if the change is in "base" or in any of the independent "component"'s.
3. If in "base", only `sktime` gets installed along with test dependencies and all tests are run.
4. If in components, only affected component jobs are run with test dependencies, `sktime` and only component specific dependencies using new extras introduced in #5136, and all tests are run.
5. Every Sunday 00:00, all tests run on base and individual components. This can also be triggered manually any time (for example before a release).

Now, here are the possible things missing for now that I'm aware/doubtful about:

- As of now, I think (not certain) all tests are being run instead of tests only in modified modules. This is good for overall test coverage, but will slow things. So, if there is a way that adding some environment variable will enable/disable that behaviour, I'd like to enable for (3) and (4) above, and disable for (5).
- Similarly, I think (not sure) all tests are being run in all matrix combinations instead of being pseudo-randomly allocated to python/os version combinations. An environmental variable based way to control this will be easier to integrate again I guess, but may be there are better ways.
- I am a bit uncertain if the CRON job runs only on `main` branch or on all branches that have this workflow code. Based on [documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule), it looks like it should run only on latest commit on default branch, but if there is a way to check/test this, I am not sure.

**Review by achieveordie — COMMENTED** [review]
Apologies for missing the first PR and missing out on the initial discussions, I've gone through all linked PRs, issues, etc. and here are my general observations and questions:

- First things first, excellent diagnosis and solution. I really liked your proposed solution!
- For #5314, why is the individual component (forecasting) taking longer than the current checks in `main`? I'm aware that there were some significant changes that improved the runtime of the checks. Still, since I haven't been very active recently, I'm having some difficulty understanding why the new component CI is taking longer. I could be entirely wrong though.

Regarding the specific points you mentioned:
> As of now, I think (not certain) all tests are being run instead of tests only in modified modules. This is good for overall test coverage, but will slow things. So, if there is a way that adding some environment variable will enable/disable that behaviour, I'd like to enable for (3) and (4) above, and disable for (5).

I was scouring the internet and I found [`testmon`](https://testmon.org/), I haven't looked much beyond the surface level but I think this might help us to resolve this behavior. It is a pytest plugin that uses `coverage.py` under the hood to identify all the tests to run.

> Similarly, I think (not sure) all tests are being run in all matrix combinations instead of being pseudo-randomly allocated to python/os version combinations. An environmental variable based way to control this will be easier to integrate again I guess, but may be there are better ways.

I suggest moving forward with the originally-implemented solution and perhaps taking this issue in a separate PR since we're already changing quite a lot of things.

There are also various [hopefully still active] [plugins](https://docs.pytest.org/en/7.1.x/reference/plugin_list.html) which are suitable for our use case. I'll try to find something tomorrow and get back.

**Comment by yarnabrina** [comment]
Thanks for reviewing.

> why is the individual component (forecasting) taking longer than the current checks in main?

In the new CI jobs introduced here, all tests in a component run in all of the matrix, e.g. all unit tests on every forecaster gets tested in each of the 3*4 cases arising from OS and python version combinations.

However, that is not the case in `main` branch. First, there is a filter that estimators present only in the modified modules get tested (ref. `is_class_changed` from `sktime/utils/git_diff.py`). Second, the filtered estimators are assigned randomly to the entire matrix combinations in a way that they run at least once in every single python version and every single OS, but not in all (ref. `subsample_by_version_os` in `sktime/tests/test_all_estimators.py`). I'm not sure if it's "at least once" or "exactly once", but hopefully @fkiraly can correct me on that distinction. These two helps in reducing the CI time a lot, at the cost of significantly reduced test coverage (unless a diagnostic PR is run to run all tests manually as a hacky trick).

Anyway, becuase of the above two filters, the new diagnostic PR ends up running way more tests (counting for all iterations) spread in way more workflows (including the ones in `main` which I hope to replace if this PR gets approved). If @fkiraly (or anyone) can suggest me a way to control these two behaviours just from CLI (I need to be able to pass both True/False cases), using either environment variables or flags, hopefully that should solve these two filter issues.

> I was scouring the internet and I found [testmon](https://testmon.org/), I haven't looked much beyond the surface level but I think this might help us to resolve this behavior.

I think that was already considered previously. I'm not aware about all the discussion details, but the summary is (I think) that it's not ready yet to handle the huge testing codebase of `sktime` yet. Again, @fkiraly can give more details on that.

**Comment by fkiraly** [comment]
sorry, this is quite voluminous. I will likely have time to review on Fri or WE.

**Comment by fkiraly** [comment]
> I'm not sure if it's "at least once" or "exactly once", but hopefully @fkiraly can correct me on that distinction. 

It is at least once - if the number of OS and python versions is unequal, in general there will not be an assignment that satisfies "exactly once" for both OS and python versions.

Proof: one run covers exactly one OS and python version. Wlog let's assume there are more python versions than OS (otherwise switch OS/python version), n python versions, m OS, n>m. So there must be at least n runs to cover all python versions. By the pigeonhole principle, at least one of the OS versions must be repeated in there.

**Comment by fkiraly** [comment]
> Anyway, becuase of the above two filters, the new diagnostic PR ends up running way more tests (counting for all iterations) spread in way more workflows (including the ones in main which I hope to replace if this PR gets approved).

Can you please explain this, @yarnabrina? What is the "because" here, i.e., premise and consequence? What is the problem exactly in terms of tests being run where?

Apologies, I cannot follow your context as I have not fully understood the desired target behaviour or the current behaviour of your proposed CI workflow modification.

**Comment by fkiraly** [comment]
> I think that was already considered previously. I'm not aware about all the discussion details, but the summary is (I think) that it's not ready yet to handle the huge testing codebase of sktime yet. Again, @fkiraly can give more details on that.

The main problem was the way the `TestAll...` classes collect tests, scenarios, etc. The subsetting in testmon uses coverage as a proxy, which does not cover collection via `all_estimators` (or other scraping utilities).

@tarpas is the creator of testmon so might have some further insight in the context of this discussion.

**Comment by yarnabrina** [comment]
> desired target behaviour or the current behaviour of your proposed CI workflow modification

These are my goals:

1. I wish to run the tests for forecasting independently of all other components. For that, all I need are forecasting soft dependencies along with testing dependencies. So, I want to install only those in an environment (across supported operating systems and python versions) and run th tests. And, I wish to do the same for all components, at least those for which I created specific extra.
2. I do not wish to run the forecasting tests if there are no changes in forecasting folder. Again, I wish similarly for all components.
3. I wish to run the tests for base framework with only basic package installed along with test dependencies, without installing any optional soft dependencies.
4. I wish to run all tests for base and all other components regularly on `main` branch in case those tests started failing over the time but not capture because of no PR in corresponding codebase.
5. I wish to run all tests for diagnostics or maintenance purposes or before release when I want, even if it does not fit the set schedule.

> What is the problem exactly in terms of tests being run where?

Based on my understanding and knowledge, all of the above wishes are implemented. However, it seemed to me that every single tests are being run in the two diagnostic PR's (based on their run duration and number of tests), instead of only a fraction of them per operating system - python version combination (your pseudo random allocation logic) and only the modified tests (your changed modules only logic).

> What is the "because" here

These were what I was refering to:

> First, there is a filter that estimators present only in the modified modules get tested (ref. is_class_changed from sktime/utils/git_diff.py). Second, the filtered estimators are assigned randomly to the entire matrix combinations in a way that they run at least once in every single python version and every single OS, but not in all (ref. subsample_by_version_os in sktime/tests/test_all_estimators.py).

This is honestly a guess, and if you can tell me these two are being respected even now in the two diagnostic PR's, then I'm done with all my changes unless there are review requests.

If not, I need to understand why are those not being respected. I prefer running all for more coverage, but it's too long. So, here are two more goals regarding control:

1. In a PR, I wish to test only the changes made by users at least once in each operating system and at least once in each python version.
2. In scheduled diagnostic testing or manual run, I wish to execute all tests on all possible supported environments.

There are other goals I can think of, but I'm not addressing these now in this PR:

3. I wish to run all tests on all supported environments only for a specific estimator (or a set of estimators derived from a specific base adapter).
4. I wish to test all estimators that depend on a specific soft dependency when that gets modified in `pyproject.toml` by means of change in bounds.

Let me know if it makes it any clear @fkiraly.

**Comment by fkiraly** [comment]
> However, it seemed to me that every single tests are being run in the two diagnostic PR's 

Can you point me to them, please?

**Comment by yarnabrina** [comment]
If you're asking about the two diagnostic PR's:

1. #5313 - I made few spelling corrections in `sktime/base`
2. #5314 - I made few spelling corrections in `sktime/forecasting`

If you're asking about specific tests, I do not have any specific examples. As I said, it was a guess seeing each forecasting job took >30 minutes and had >10k tests, and also from the fact it failed for `evaluate`+`quantile` issues.

**Comment by fkiraly** [comment]
> it seemed to me that every single tests are being run in the two diagnostic PR's

I have looked at this now:

* indeed it looks to me that you are right, all tests are run
* I also do not know why - I would expect that both filters (only changed, and matrix design) would apply

**Comment by yarnabrina** [comment]
@fkiraly @benHeid @achieveordie : Re-requesting review now that feature freeze is over.

I am done with all my changes in this PR (#5304), and in the two diagnostic ones (#5313, #5314). I added few modifications to handle subsample and differential filters, and I think it's working correctly.

**Review by fkiraly — DISMISSED** [review]
Thanks, reviewed and approved.

Number 2 in the sequence of merges.

**Pull request merged**
