### PR TITLE
[BUG] fix ForecastingHorizon `to_absolute` wiht multiple frequencies

### LINKED ISSUE #7170: [BUG] ForecastingHorizon.to_absolute() does not support freq is '2T'
**Describe the bug**

**To Reproduce**

```python

from sktime.forecasting.base import ForecastingHorizon
import numpy as np
import pandas as pd
from pandas import PeriodIndex
from pandas._libs.tslibs.period import Period

fh_range = np.arange(1, 4)

freq = '2T'
fh = ForecastingHorizon(fh_range, is_relative=True)
cutoff = PeriodIndex(['2024-09-26 17:24'], dtype='period[2T]', name='_time')
# cutoff = Period('2024-09-26 17:24', freq='2T')

fh = fh.to_absolute(cutoff)

print(fh)
# acutal: ForecastingHorizon(['2024-09-26 17:25', '2024-09-26 17:26', '2024-09-26 17:27'], dtype='period[2T]', is_relative=False)
# expected: ForecastingHorizon(['2024-09-26 17:26', '2024-09-26 17:28', '2024-09-26 17:30'], dtype='period[2T]', is_relative=False)

```

**Expected behavior**

expected: ForecastingHorizon(['2024-09-26 17:26', '2024-09-26 17:28', '2024-09-26 17:30'], dtype='period[2T]', is_relative=False)

**Additional context**

I suspect that due to `_coerce_cutoff_to_index` enforcing the use of PeriodIndex instead of Period, it is not able to handle intervals such as `2T`.

```python
    def _coerce_cutoff_to_index(self, cutoff):
        """Coerces cutoff to pandas index, and updates self.freq with cutoff."""
        self.freq = cutoff
        if not isinstance(cutoff, pd.Index):
            cutoff = pd.Index([cutoff])
        return cutoff

```

In earlier versions, such as sktime==0.13.4, the test case worked well. Is there any recommended way to do this now?

**Versions**

sktime==0.33.1

<details>

</details>

### PR DESCRIPTION
**Pull request by tianjiqx**
#### Reference Issues/PRs

Fixes #7170 

#### What does this implement/fix? Explain your changes.

Use `Period` instead of `PeriodIndex` for performing mathematical operations

#### Does your contribution introduce a new dependency? If yes, which one?

no

#### Did you add any tests for the change?

add a unit test 

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Hm, looks like it breaks one of the existing test cases?

**Comment by tianjiqx** [comment]
Failed root cause:
```
            if isinstance(cutoff, pd.Index):
                cutoff = cutoff[[0] * len(relative)]
                if isinstance(cutoff, pd.PeriodIndex):
                    cutoff = cutoff.to_list()
    
            absolute = cutoff + relative
    
            if is_timestamp:
                # coerce back to DatetimeIndex after operation
                try:
>                   absolute = absolute.to_timestamp(fh._freq)
E                   AttributeError: 'Index' object has no attribute 'to_timestamp'
```
Due to unfamiliarity with the sktime testing framework, I am unable to run sktime's test suite locally. I tried copying the sktime test cases and running them, but the results are confusing. It's Passed.
```
def test_bugfix():
    from sktime.forecasting.dummy import ForecastKnownValues
    from sktime.utils.estimator_checks import (
        _get_test_names_for_obj,
        check_estimator,
        parametrize_with_checks,
    )

    estimator_class = ForecastKnownValues
    estimator_instance = estimator_class.create_test_instance()

    check_estimator(estimator_class, raise_exceptions=True, verbose=False)

    check_estimator(estimator_instance, raise_exceptions=True, verbose=False)
```
Is the failing case really this one? sktime/utils/tests/test_check_estimator.py::test_check_estimator_does_not_raise[ForecastKnownValues]
I seem unable to reproduce the error.
Additionally, my change is conditioned on `isinstance(cutoff, pd.PeriodIndex)`, but is_timestamp = isinstance(cutoff, pd.DatetimeIndex) . If  is_timestamp is True, it should not have any impact.

**Comment by XinyuWuu** [comment]
> Additionally, my change is conditioned on `isinstance(cutoff, pd.PeriodIndex)`, but is_timestamp = isinstance(cutoff, pd.DatetimeIndex) . If is_timestamp is True, it should not have any impact.

You have changed the type of `cutoff` after `is_timestamp = isinstance(cutoff, pd.DatetimeIndex)`.

> Due to unfamiliarity with the sktime testing framework, I am unable to run sktime's test suite locally.

You can run the test by `pytest sktime/utils/tests/test_check_estimator.py::test_check_estimator_does_not_raise`.

**Comment by tianjiqx** [comment]
> pytest sktime/utils/tests/test_check_estimator.py::test_check_estimator_does_not_raise



> > Additionally, my change is conditioned on `isinstance(cutoff, pd.PeriodIndex)`, but is_timestamp = isinstance(cutoff, pd.DatetimeIndex) . If is_timestamp is True, it should not have any impact.
> 
> You have changed the type of `cutoff` after `is_timestamp = isinstance(cutoff, pd.DatetimeIndex)`.
> 
> > Due to unfamiliarity with the sktime testing framework, I am unable to run sktime's test suite locally.
> 
> You can run the test by `pytest sktime/utils/tests/test_check_estimator.py::test_check_estimator_does_not_raise`.

pytest will produce error：
```
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --timeout -n auto sktime/utils/tests/test_check_estimator.py::test_check_estimator_does_not_raise
  inifile: /home/tianjiqx/opensource/sktime/setup.cfg
  rootdir: /home/tianjiqx/opensource/sktime

```
I found that cutoff = _coerce_to_period(cutoff, freq=fh._freq) converts DatetimeIndex to PeriodIndex, which affects subsequent logic. 

Additionally, this might be related to the Python version; GitHub CI uses Python 3.9, while I have Python 3.10 locally. I will do more testing.

**Comment by XinyuWuu** [comment]
> pytest will produce error：

You need to install the dev and test dependency set.
`pip install -e .[dev,test]` might help.

**Comment by tianjiqx** [comment]
> > pytest will produce error：
> 
> You need to install the dev and test dependency set. `pip install -e .[dev,test]` might help.

thx, it work. 

The main reason is that I am using pandas version 1.4.3 locally, so the operation `cutoff + relative` results in a pd.PeriodIndex, which is normal. 

However, in the CI/CD environment, relative is a `pd.Index` instead of an `pd.Int64Index`, leading to the absolute calculation result being of type `pd.Index`. This ultimately caused the issue where the method absolute.to_timestamp does not exist. The issue has been fixed.

**Review by fkiraly — CHANGES_REQUESTED** [review]
Ok, this is brilliant!

I see that this is very similar to what happens in line 829, above.

Is there potential to move both occurrences out into a single utility, or are the cases too different? We are in essence abstracting application of a shift.

I would also like a review from @sktime/core-developers, as this is a central location.

**Comment by yarnabrina** [comment]
Question: we earlier had multiple issues with M, MS, ME, W, W-<day> etc. frequencies. Does this fix address those as well?

**Comment by tianjiqx** [comment]
> Ok, this is brilliant!
> 
> I see that this is very similar to what happens in line 829, above.
> 
> Is there potential to move both occurrences out into a single utility, or are the cases too different? We are in essence abstracting application of a shift.
> 
> I would also like a review from @sktime/core-developers, as this is a central location.

In fact, I referred to the code from 829. Now, I have made some minor modifications. Does this meet the expectations?

**Review by fkiraly — APPROVED** [review]
> Does this meet the expectations?

Yes, makes sense. Btw, I think there is a typo in the docstring you moved, it should be 1.5.0, not 0.15.0, right?

Further, I was wondering if we cannot move change it to a function such as

`_add_index(x, y)`, which we would use as `_add_index(absolute, "-", cutoff)`, or `_add_index(absolute, "+", relative)`, or similar

**Pull request merged**
