### PR TITLE
[ENH] in forecasting metrics, allow a callable to be passed as `sample_weight` for dynamic weight generation

### PR DESCRIPTION
**Pull request by MarkusSagen**
#### Reference Issues/PRs

Addresses partially https://github.com/sktime/sktime/issues/7279 by allowing users to specify callables for `sample_weight`.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Nice!

I assume this is still work in progress, some early feedback:

* the `sample_weight_generator` is still in the inits, I believe this change is not needed in the target design, so should be reverted.
* docstring should say what format `y_true` and `y_pred` is expected in. Is this expecting, for instance, numpy, or pandas based data?
* for consideration of the design should `check_sample_weight_generator` be called *after* input checks and conversions? That is, after the call to `_check_ys`. Then the `y_pred`, `y_true` type will be guaranteed to be one of the three `pandas` based types, i.e., `pd.DataFrame`. This would also make the contract for the callable simpler.

**Comment by MarkusSagen** [comment]
@fkiraly Thank you for the feedback
I've started to adress some of the feedback now and included some tests

> the sample_weight_generator is still in the inits, I believe this change is not needed in the target design, so should be reverted.

Regarding this, I've now changed it a bit so metrics can still specify a sample weight generator and made one shared method for it in the base class, while still being scikit-learn compatible

As discussed in the issue thread, the reason for including it in the init method, is that usage in other closed methods (s.a. `sktime/forecasting/model_evaluation/_functions:evaluate`)

**Review by fkiraly — CHANGES_REQUESTED** [review]
I see, this is the same point as with `coverage` and `alpha` here: https://github.com/sktime/sktime/issues/7276

What I then would suggest is we split the change in two steps, as otherwise we are making too large changes to the base API of metrics:

1. allow `sample_weight` to be a function/generator, but do *not* add it to the `__init__` anywhere
2. add `sample_weight` as a potential `__init__` argument to *all metrics*, and this can be anything that `sample_weight` can be in `evaluate` or `evaluate_index`

Does this make sense? We will also need to get a lot of reviews since we are working on central interface points. Change number 1 is probably easier to get agreement on, since it does not change the signatures, only extends them.

**Comment by MarkusSagen** [comment]
Great! I've reverted those changes and included it in another PR #7304

**Comment by MarkusSagen** [comment]
Seems some of the tests failed because some of the CI/CD jobs failed to start

**Comment by fkiraly** [comment]
This is odd, it seems to have hit macos runners in the last days. Perhaps the queue generated by the python 3.13 release was too long and it got reset, as the macos runners tend to be slower than the rest. I restarted.

**Review by fkiraly — CHANGES_REQUESTED** [review]
Looks good from my side!

For the docstring, could we ensure to say that the signature of the callable is `y_true : pd.DataFrame, y_pred : pd.DataFrame`?

**Comment by MarkusSagen** [comment]
I've updated the docstrings now :)

**Review by fkiraly — APPROVED** [review]
Thanks.

I clarified the docstring a little, could you kindly check if that is correct?

**Pull request merged**
