### PR TITLE
[ENH] New splitter switching from expanding window to sliding window at cutoff point

### LINKED ISSUE #7191: [ENH] set max window size for ExpandingWindowSplitter
**Problem description**
In certain cases for time series forecasting you would like to have as much data as possible for training, however, if you account for too much training data in certain models, it will overfit to historical values and not the most recent ones. An expanding window split works well in scenarios when one has little data and forecasting models weight historical values more than the most recent ones. 

**Describe the solution you'd like**
What I would want is a splitter that utilizes the the training data well when there is not a lot of data, but transitions to a sliding window splitter once a maximum size is reached.

My proposal is to include one additional argument in the BaseWindowSplitter called `max_sliding_window_size` and a new slitter called `ExpandingSlidingWindowSplitter`. It would include the same code and features of the sliding and expanding window splitter.

### PR DESCRIPTION
**Pull request by MarkusSagen**
#### Reference Issues/PRs

Fixes #7191 - Combining expanding and sliding window splitter in one

#### What does this implement/fix? Explain your changes.

This PR implements a combination of the sliding window splitter and expanding window splitter. It will by default behave as the expanding window splitter up to a point. After the maximum expanded window size is reached, the splitter continues as a sliding window splitter.

#### What should a reviewer concentrate their feedback on?

- Potential issues with this approach?
- Should we extend the existing splitters with this argument or have it as a new class?

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks! The splitter looks fine to me.

Requests:

* code formatting is failing, see here how to address this: https://www.sktime.net/en/stable/developer_guide/coding_standards.html
* would it be easy, or not, to implement the splitter separately? We were thinking of getting rid of the window splitter base class mid- to long-term.

For your contribution, please do not commit directly to `CONTRIBUTORS.md`, but to `.all-contributorsrc`, the md is auto-generated (and overwritten) from the json file.

**Comment by fkiraly** [comment]
one more change request, the splitter should be added to the docs - `docs/source/api_reference/split.rst`

**Comment by fkiraly** [comment]
@MarkusSagen, ping - did you mean this Wednesday or next Wednesday?

**Comment by MarkusSagen** [comment]
> @MarkusSagen, ping - did you mean this Wednesday or next Wednesday?

Sorry about that, had some blockers work-wise
Aiming to have these changes in during the day

**Comment by MarkusSagen** [comment]
> Thanks! The splitter looks fine to me.
> 
> Requests:
> 
> * code formatting is failing, see here how to address this: https://www.sktime.net/en/stable/developer_guide/coding_standards.html

Thanks! I've fixed those requested changes now

> * would it be easy, or not, to implement the splitter separately? We were thinking of getting rid of the window splitter base class mid- to long-term.
> 

At the moment, it seems to require quite a bit of restructuring unfortunately. If possible, I'd hope not to do the re-write at the moment

> For your contribution, please do not commit directly to `CONTRIBUTORS.md`, but to `.all-contributorsrc`, the md is auto-generated (and overwritten) from the json file.

Excellent! I made the changes in that file instead

**Comment by MarkusSagen** [comment]
@fkiraly ping

**Review by fkiraly — DISMISSED** [review]
pong

**Comment by MarkusSagen** [comment]
Just checking, is there anything in addition on my part for enabling the CI/CD jobs?

**Comment by fkiraly** [comment]
> Just checking, is there anything in addition on my part for enabling the CI/CD jobs?

No, should all be fine and scheduled for the next release.

**Comment by MarkusSagen** [comment]
From what I could see, it seems that other docstring tests are failing 🤔

**Review by fkiraly — APPROVED** [review]
Yes, known failure since doc builds takes too long, stochastically..

**Pull request merged**
