### PR TITLE
[ENH] add contract test for hierarchical forecasting

### PR DESCRIPTION
**Pull request by fkiraly**
This PR adds a new contract test to `TestAllForecasters` which tests forecasting with hierarchical endogeneous and exogeneous data, for that it works and returns a forecast of expected mtype and format.

This test should also cover the failure case in https://github.com/sktime/sktime/issues/3961.

Contains fixes for further bugs detected through this:

* https://github.com/sktime/sktime/pull/4001

### CODE REVIEW

**Comment by fkiraly** [comment]
@ciaran-g, the failures of the `ReconcilerForecaster` look genuine, do you have an idea what is going on?

**Comment by ciaran-g** [comment]
Hi @fkiraly, just got an email notification on this PR - is there a possible bug here in the `ReconcilerForecaster`?

**Comment by fkiraly** [comment]
Having thought of it, I think it's not a bug - the `ReconcilerForecaster` adds more indices after the forecast (if `__total` levels are not present), so the forecast contains more hierarchy levels than the training data.

The check in the test was just too strict.

What is your opinion, @ciaran-g?

**Comment by ciaran-g** [comment]
> Having thought of it, I think it's not a bug - the `ReconcilerForecaster` adds more indices after the forecast (if `__total` levels are not present), so the forecast contains more hierarchy levels than the training data.
> 
> The check in the test was just too strict.

I see what you mean, yep the index tests should be relaxed then for this case.

However, looking into the code last night I think there might be a related bug in the `ReconcilerForecaster`. When it isn't used in a pipeline with the `Aggregator` or the `X` and `y` values aren't aggregated before predict or update are called. Seems like the class is missing a pre-processing step in the `.predict` and `.update` functions

```py

if X is not None:
  if _check_index_no_total(X):
      X = self._add_totals(X)
```

About to make a PR

**Comment by ciaran-g** [comment]
#3980

**Comment by aiwalter** [comment]
this PR is violating the PR rules defined here: https://www.sktime.org/en/stable/get_involved/governance.html#decision-making.

**Comment by fkiraly** [comment]
@aiwalter, early merge is possible as per the rules and standing policy.

Do you want to vote it down and revert it?

**Pull request merged**
