### PR TITLE
[ENH] Added permutation param to pipelines

### LINKED ISSUE #3439: [ENH] Tuning order of transformers in pipelines as a hyper-parameter
**Is your feature request related to a problem? Please describe.**
We have currently three sequential pipeline classes `TransformedTragetForecaster`, `ForecastingPipeline` and `TransformerPipeline`. Having several transformers chained raises the question which is the best order (permutation) of the given transformers.
For example in the pipeline below, what is the best order of transformers?
```python
    >>> pipe = TransformedTargetForecaster(
        steps=[
    ...     ("outlier", HampelFilter()),
    ...     ("impute", Imputer()),
    ...     ("detrend", Detrender()),
    ...     ("deseason", Deseasonalizer()),
    ...     ("minmax", TabularToSeriesAdaptor(MinMaxScaler())),
    ...     ("difference", Differencer()),
    ...     ("forecast", NaiveForecaster(strategy="drift")),
    ... ])
```

**Describe the solution you'd like**

To tune the permutations of transformers, we would need another parameter that allow to give several sortings of the steps.
A solution could look as follows:
```python
    >>> pipe = TransformedTargetForecaster(
        steps=[
    ...     ("outlier", HampelFilter()),
    ...     ("impute", Imputer()),
    ...     ("detrend", Detrender()),
    ...     ("deseason", Deseasonalizer()),
    ...     ("minmax", TabularToSeriesAdaptor(MinMaxScaler())),
    ...     ("difference", Differencer()),
    ...     ("forecast", NaiveForecaster(strategy="drift")),
    ... ],
    ... permutation=["difference", "outlier", "deseason", "detrend", "impute", "minmax", "forecast"],
    ... )
```
This could be implemented as a `Mixin` class so all sequential pipeline classes could inherit and implement it. To be discussed if `"forecast"` step should be part of `permutation` list or if it should just stay at position where it is given. The param `permutation` could also accept `permutation="all"` to try all `n!` combinations with `n` as number of given transformers.

**Describe alternatives you've considered**
I thought first of having a separate transformer composition for this, but now I think its actually best to integrate this into the existing pipeline classes.

**Additional context**
Grid search, tuning

@miraep8  would be interested about your feedback as you wrote the `MultiplexTransformer` which solves the 1:n selection of transformers.
Also pinging @benHeid and @fkiraly

### PR DESCRIPTION
**Pull request by aiwalter**
#### Reference Issues/PRs
closes #3439

### CODE REVIEW

**Comment by fkiraly** [comment]
@aiwalter, I think the idea of a permutation transformer is great!

I do not agree design-wise to attach it to the heterogeneous meta-estimator, or to the pipelines themselves - I think it "has no business there" in the sense of separation of concerns, and would be opposed to overloading functionality in the pipeline classes.

I would suggest a wrapper design, se #3439.

**Comment by fkiraly** [comment]
I'd really go about it the following way:

* inherit from `_DelegatedForecaster`
* init args are `estimator`, `permute_param_name` and `permutation`
* the entire logic sits in `__init__`, it passes on the parameter permuted, and copies over tags
* there is no other method, i.e., only `__init__`

**Comment by aiwalter** [comment]
can I put it into `TransformerPipeline`? I dont want to create another pipeline just for this 🤔

**Comment by fkiraly** [comment]
I'd rather not, since I think (a) that's too much responsibility - keep estimators modular, and (b) we would have to duplicate this for both pipelines. Why not the delegator idea which can be applied to any heteoregenous estimator?

**Comment by aiwalter** [comment]
superseded by #3689

**Pull request closed without merging**
