### PR TITLE
[MNT] Auto format pyproject

### PR DESCRIPTION
**Pull request by yarnabrina**
1. Introduces two new `pre-commit` hooks to auto-format and validate `pyproject.toml`
2. Formats existing `pyproject.toml`

### CODE REVIEW

**Comment by yarnabrina** [comment]
> FAILED sktime/datasets/tests/test_single_problem_loaders.py::test_check_link_downloadable[kdd_cup_2018_dataset_with_missing_values] - urllib.error.HTTPError: HTTP Error 504: Gateway Time-out

This looks like a random failure, definitely not caused by this PR. Any suggestions on how to address this?

**Comment by fkiraly** [comment]
> Any suggestions on how to address this? Or, is it sporadic in nature?

My original suggestion was a separate CI element: https://github.com/sktime/sktime/pull/5004
possibly even move to CRON job,

but I was not able to get it to work. Problem: seems to deactivate incremental testing, no idea why.

**Comment by yarnabrina** [comment]
I think I've an idea how to have a job that tests just unit tests in datasets directory and nothing else. Other tests will be taken care of by #5304 respecting incremental testing (please review).

But even if I do that, the new one will still fail if timeout happens. Are you saying we ignore failures in dataset-loader workflow and can merge to main anyway? If not, I am a bit confused how will it help.

**Comment by fkiraly** [comment]
> Are you saying we ignore failures in dataset-loader workflow and can merge to main anyway? 

Yes - or separate it out entirely as a CRON.

**Review by fkiraly — APPROVED** [review]
I'm happy with this, seems simple

**Pull request merged**
